### ISSUE TITLE
Make a version of `grow build` that doesn't use GH tokens

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp.dev#1004]
This came out of the discussion at https://github.com/ampproject/docs/pull/1002#issuecomment-398517598. It's needed so that we can run `grow build` as part of PR checks for incoming PRs, and Travis doesn't make secure tokens available to PR builds.

Currently, it's only `scripts/import_docs.js` that uses the token. Since we don't really want to do a deploy duding PR builds, perhaps we can restrict them to just building the docs and making sure nothing broke?

https://github.com/ampproject/docs/blob/3670e95f11318d904c6a8ae5759faf88706007be/scripts/import_docs.js#L13-L16

@pbakaus @bpaduch Thoughts?

**Comment by pbakaus** [comment]
@rsimha this is tricky as I believe we currently don't check in the docs, as it would be quite annoying to have to commit them every time, and that would mean that the incoming PR would build without any docs at all, which makes testing docs section changes quite difficult.

Any other way you can think of? If not, we might just have to commit them.

**Comment by rsimha** [comment]
Can you give me some more context around the difference between checking in the docs and commiting them? (If this is already discussed somewhere, I'm happy to read it up myself.)

**Comment by pbakaus** [comment]
Sorry, I meant the same thing. The docs markdown files are generated every time you do a full build, but are never committed, which means that they never *pollute* a commit, e.g. you did some other  change, do a test build locally, and then have a lot of changed files. Another way might be to add them to the gitignore, but then I don't know how to actually commit changes when you need them (short of removing temporarily from the gitignore again..). Does that make sense?

**Comment by rsimha** [comment]
@pbakaus Thanks. I read about how the build works from [here](https://github.com/ampproject/docs/blob/master/contributing/ampproject-files-build-process.md) and [here](https://github.com/ampproject/docs), and noted the point about using the `.md` files from `ampproject/amphtml` as the source of truth while building `ampproject/docs`.

A couple things I noticed:
1. Running `grow build` seems to be calling `gulp build` internally, which in turn reports that it is done within ~5 seconds even though the full build takes much longer. Is this expected?
2. At the end of `grow build`, I'm still seeing some changes. Is this expected?
```
 content/includes/list-blog-ads.yaml                                                                           | 106 ++++++++++++++++++++++++++---------------------------
 content/includes/list-blog.yaml                                                                               | 123 ++++++++++++++++++++++++++++++++++----------------------------
 content/latest/blog-ads/ads-a-first-look-at-using-web-packaging-to-improve-amp-urls.md                        |   2 +-
 content/latest/blog-ads/ads-amp-and-advertising-conversions.md                                                |   2 +-
 content/latest/blog-ads/ads-amp-roadshow-more-cities-more-content.md                                          |   2 +-
 content/latest/blog-ads/ads-faster-ads-with-render-on-idle.md                                                 |   2 +-
 content/latest/blog-ads/ads-google-io-2018.md                                                                 |   2 +-
 content/latest/blog-ads/ads-jung-von-matts-road-to-the-worlds-fastest-automotive-content-marketing-website.md |   9 +++--
 content/latest/blog-ads/ads-new-functionality-to-help-manage-user-choice-in-amp-pages.md                      |   2 +-
 content/latest/blog-ads/ads-new-tools-for-building-user-controls-in-amp-pages.md                              |   2 +-
 10 files changed, 132 insertions(+), 120 deletions(-)
```

Re: your point about committing the docs markdown files, there is a way to ignore them via `.gitignore`, and yet occasionally add / modify them by using `git add --force` or `git add -f`. See [this](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-add.html) reference.

Would that help eliminate the need for a token? Let me know, and I could make the required changes.

**Comment by pbakaus** [comment]
@rsimha 
1. yes, `gulp build` doesn't actually build pages, just executes a variety of scripts to prepare grow. So it runs for much less time.
2. these changes are expected, since we only grab the latest blog entries from RSS. we grab the 10 latest, and if we wouldn't commit them regularly, they'd error out when somebody would try to click on a link on our site. Not an ideal solution that will go away as soon as we switch fully to Wordpress for the blog section.

I didn't know the `git add -f` trick, if that's the case we can certainly try going that route. Feel free to try it out.

**Comment by rsimha** [comment]
Assigning to @danielrozenberg 

/cc @CrystalOnScript @pbakaus

**Comment by matthiasrohmer** [comment]
@pbakaus how do we want to deal with this in the context of amp.dev? We already force comitted a version of the `amp-accordion` reference doc to have a component overview page. But all the `{{ g.doc(..` statements pointing to the other docs would still break the build.

Should we just force commit all of them as @rsimha also suggested earlier? Then a build would run flawlessly even without GitHub credentials.

**Comment by pbakaus** [comment]
@matthiasrohmer we should probably commit them going forward, yes. We need to because of translation needs anyway.

**Comment by sebastianbenz** [comment]
Closing this as we're now executing tests as part of PRs. The sample import problem is handled in other issues.
