### ISSUE TITLE
Add link to GitHub project from navigation

### ISSUE THREAD

**Issue by tobie** [ampproject/amp.dev#1012]
It would be nice if the documentation site provided a link to the open source project. This could be to both the GitHub org itself and to the `amphtml` repository (as it's not obvious at first that `amphtml` is where everything is happening).

It could be either in the form of a small logo in the footer, a dedicated "contributing" menu dropdown, or both (my suggestion).

**Comment by bpaduch** [comment]
The footer idea sounds best with the current design.  We are planning to redesign the site in coming months and we will definitely have a spot or spots for it.

**Comment by sebastianbenz** [comment]
Done with amp.dev
