### ISSUE TITLE
[Master Feature] Create public developer documentation for Actions

### ISSUE THREAD

**Issue by jasti** [ampproject/amp.dev#1020]
- [ ] Explain how Actions differs or is similar to non-Actions AMP documents
- [ ] Getting started tutorials 
- [ ] Code Samples
- [ ] FAQs & Gotchas

Let individual platform documentation live within the platform documentation. This work is specifically to help developers getting started quickly and avoid common design anti-patterns.

**Comment by CrystalOnScript** [comment]
@jasti - can you confirm if this is still needed?

**Comment by jasti** [comment]
Thanks for the ping. Not needed anymore.
