### ISSUE TITLE
Document IOS viewer fixed layer side effects behavior

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amp.dev#1283]
## Context

The webkit engine (which underlies all IOS browsers) exhibits poor scrolling behavior when fixed layer elements overlay scrollable parents.  This manifests as fixed elements jumping when the page is scrolled.   In the context of AMP this becomes an issue when an AMP document rendered in a viewer.

To mitigate this the AMP runtime moves the fixed layer elements outside their parent to a separate `<body>` tag.   Unfortunately there are side effects of this which can trip up developers. 

## Side effects.

Parents of the fixed layer may no longer be available once it's moved.  For example:

```html
<html>
  <head>
    <style>
     .myFixedLayer { position: fixed }
     header h2 { color: red; }
    </style>
  </head>
  <body>
    <header>
       <div class="myFixedLayer">
          <h2>Hello World</h2>
      </div>
   </header>
   <article>
      Lorem ipsum ...
   </article>
  </body>
</html>
```

Becomes this when rendered in a viewer on IOS

```html
<html>
  <head>
    <style>
     .myFixedLayer { position: fixed }
     header h2 { color: red; }
    </style>
  </head>
  <html>
    <body>
      <header></header>
     <article>
        Lorem ipsum ...
     </article>
    </body>
  <html>
  <body>
    <div class="myFixedLayer">
        <h2>Hello World</h2>
    </div>
  </body>
</html>
```

Because `header` is no longer a parent of `.myFixedLayer` the selector `h2` will no longer match and the CSS color won't be applied.

Similarly this contrstruct:

````html
<a href=" ... " >
  <div class="myFixedLayer">Hello World</div>
</a>
````

Will break when the fixed layer is moved but it's parent `<a>` tag isn't.

This needs to be documented somewhere obvious as it continues to trip up developers.

**Comment by sebastianbenz** [comment]
+1 we should also mention how devs can test this.

**Comment by matthiasrohmer** [comment]
@CrystalOnScript, @pbakaus, who could take care of putting this in a Guide?

**Comment by sebastianbenz** [comment]
@jpettitt @dvoytenko is this still relevant in iOS 13 (I remember darkly that some things get fixed with his release)?

**Comment by jpettitt** [comment]
I believe the basic problem is fixed for iOS 13,  however it's still going to apply to phones running older versions so the code will remain in AMP for a while, it just won't trigger on versions > 13.

**Comment by dvoytenko** [comment]
Yeah. Should be all fixed in iOS13, but let's wait for it to actually get launched without regressions.

**Comment by CrystalOnScript** [comment]
@jpettitt @dvoytenko Is there an update on this? Does it still require documentation? Thanks :)

**Comment by dvoytenko** [comment]
This has been launched successfully on iOS13. So we should be all good on that front now.

**Comment by CrystalOnScript** [comment]
Great, thanks
