### ISSUE TITLE
Add /metrics (new page showcasing AMP metrics)

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amp.dev#129]
It'd be useful to have a page that showcases average page speed metrics for AMP.

**Comment by pbakaus** [comment]
@rudygalfi @cramforce what's up with that? Is that page still wanted? Last time I had it up and running you asked me to take it down again :)

**Comment by cramforce** [comment]
Need to prioritize. We have a new data pipeline. Would love to externalize it

**Comment by pbakaus** [comment]
Cool. Need help getting the data, but can build the actual page.

**Comment by bpaduch** [comment]
@rudygalfi @cramforce - We'd like to possibly tackle this during our Fixit - can we still do it? Where's the data, etc.

**Comment by cramforce** [comment]
@lannka Is this in scope for your intern project?
@bpaduch We were looking at how to automate the data export.

**Comment by lannka** [comment]
@cramforce not really :-) we can talk offline more about it

**Comment by bpaduch** [comment]
@lannka  - Any changes on this since June?  Is there a viable option?

**Comment by lannka** [comment]
It didn't end up being an intern project due to policy reasons. We can re-prioritize the work if we have a clearer product requirement.

**Comment by sebastianbenz** [comment]
Is this still relevant?

**Comment by pbakaus** [comment]
I actually built this a long time ago, but then we hid it again for some reasons I don't remember. I think we can close.
