### ISSUE TITLE
`input-throttled` and `input-debounced` are more similar to `input` than `change`

### ISSUE THREAD

**Issue by andrewwatterson** [ampproject/amp.dev#1341]
https://github.com/ampproject/docs/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md

In the descriptions of the `input-throttled` and `input-debounced` events, I think it should read "This is similar to the standard `input` event" (instead of "the standard `change` event"). `change` and `input` have fairly different behavior for the most common input element (a text field), and all indications are that the two AMP events in question are based off of `input`. (Sanity checked this with @cathyxz , but I may be misunderstanding something here.)

Meta-question: is `future` the currently released branch? I couldn't find this file in `master`

Apology: I would have solved this in a PR, but Santa won't let me run `grow` without more upvotes. :(

**Comment by wassgha** [comment]
I think this should be "similar to the standard `change` event", I don't think there's an `input` event that we fire. However, it says "Elements that fire `input` event." and that should be changed to "Elements that fire a `change` event."

Is that what you meant here?



--

**Comment by andrewwatterson** [comment]
No, my comment still stands. :) The documentation compares AMP events to the standard browser `change` event, which on text input fields only fires when the change is committed (on blur, for example). See the text input example at https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event .

As the text currently reads, it says our `throttled` and `debounced` events are similar to an event (`change`) that only fires when the field is blurred, which doesn't make any sense for a throttled or debounced event. Our event is more accurately described as "similar to the standard `input` event" as I mentioned above.
