### ISSUE TITLE
Missing description of non-standard fields on event object

### ISSUE THREAD

**Issue by andrewwatterson** [ampproject/amp.dev#1342]
https://github.com/ampproject/docs/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md

In the description of the `change` event for input elements, what do the `min` and `max` fields represent? These don't appear to be standard event fields and I can't guess at what they might be.

**Comment by wassgha** [comment]
There are actually standard for numeric input elements (text/number) see https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#Properties
