### ISSUE TITLE
amp-ad network list links to github

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp.dev#135]
Would be nice to have those pages also in the main docs.

**Comment by bpaduch** [comment]
Work required:  Build some import script to import each of these markdown files and ensure formatting is correct (note that many of these files aren't consistent and vary from vendor to vendor).

**Comment by sebastianbenz** [comment]
Just be to sure I understand what's asked: so we want to render all the MD files linked from https://amp.dev/documentation/components/amp-ad/#supported-ad-networks on amp.dev?

**Comment by matthiasrohmer** [comment]
Please reopen if still relevant.
