### ISSUE TITLE
[AMP.dev] Localize new documents & Guides into Korea

### ISSUE THREAD

**Issue by techhtml** [ampproject/amp.dev#1396]
## Objective

Almost AMP contents are translated but some contents are not. So I translate again some documents into Korean.

**Comment by matthiasrohmer** [comment]
Did I get it right that this would actually be something you'd do by yourself, @techhtml? 🙂

**Comment by techhtml** [comment]
@matthiasrohmer Yes. This work will do myself. but if other Koreans interested in translation work, This issue can help them.

**Comment by matthiasrohmer** [comment]
Thanks for your help so far! 🙂 Feel free to create new issues for specific smaller parts you are thinking about to contribute translations for.
