### ISSUE TITLE
Migrate amp-recaptcha-input endpoint from Glitch to Here

### ISSUE THREAD

**Issue by torch2424** [ampproject/amp.dev#1601]
relates to #1414

Currently, the `amp-recaptcha-input` endpoint is on [my AMP glitch project](https://glitch.com/edit/#!/torch2424-amp-glitch-express).

I (please assign to me) need to migrate this over. And Add a link to the file so people can see how to handle the recaptcha form request.

cc @sebastianbenz However, this will require some secrets in a .env file. Do we have a way of handling this currently?

**Comment by torch2424** [comment]
We should also be sure to use: https://www.npmjs.com/package/amp-toolbox-cors for CORS

**Comment by lluerich** [comment]
Hey @torch2424, @matthiasrohmer added a credentials util back in #2252. This should work fine for the purposes of this example. Do you have access to the datastorage

**Comment by torch2424** [comment]
@lluerich I currently do not 😄 That being said, I ave yet to start this migration, and I'm sure @sebastianbenz could help me get access to the datastore if needed.

**Comment by lluerich** [comment]
Hey @torch2424, I just went ahead and migrated the sample. Could you provide the credentials to @sebastianbenz somehow? PR will follow as soon as the credentials are migrated.

**Comment by torch2424** [comment]
@lluerich So I no longer work at google unfortunately 😢 

So I'd suggest just using a different reCAPTCHA account. 😄 I haven't done anything with mine yet, but if you do need the credentials, feel free to email me at: aaron@aaronthedev.com

Thanks! 😄

**Comment by lluerich** [comment]
@torch2424 thanks for the update. 😃
@sebastianbenz could you provide another reCAPTCHA account?
