### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by mucahityilmaz** [ampproject/amp.dev#1648]
Hey there, I'd like to translate this file into Turkish: https://github.com/ampproject/docs/blob/master/translations/tr/LC_MESSAGES/messages.po

Is there anyone else working on it? Or are there any other files to translate? I can do all of them. 

Thanks.

**Comment by sebastianbenz** [comment]
//cc @CrystalOnScript

**Comment by pbakaus** [comment]
So sorry we didn't follow up earlier! If you're still interested, we would love your contribution (and AFAIK nobody is working on it). Since then, the file location has changed, and is now located here: https://github.com/ampproject/docs/blob/future/pages/translations/tr/LC_MESSAGES/messages.po

**Comment by mucahityilmaz** [comment]
Alright, I can do it, but not very quickly, fyi.

**Comment by pbakaus** [comment]
No problem, take the time you need! Thanks a lot!

**Comment by CrystalOnScript** [comment]
@mucahityilmaz, sorry for my delayed response, been OOO - thanks so much for your interest! Lets us know if you hit any roadblocks :)

**Comment by matthiasrohmer** [comment]
Closed due to inactivity. You're welcome to reopen if you want to pick this up again 🙂
