### ISSUE TITLE
Do not use g.json for example pages

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#1671]
While researching on Grows build performance it seems as the examples got the new bottleneck. My guess is that the `g.json` frontmatter constructor that Grow has is not really high-performance. Instead of using that we should add the needed fields directly to the documents frontmatter.

**Comment by sebastianbenz** [comment]
Sounds good and makes things either to understand as well.

**Comment by sebastianbenz** [comment]
@matthiasrohmer is this still relevant?

**Comment by matthiasrohmer** [comment]
I remember to have tested this a while back. The improvements in build speed are negligible. Hence closing.
