### ISSUE TITLE
Make the members of the governance bodies and Collaborators/Reviewers visible to non-org members

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amp.dev#1699]
Currently membership in the TSC/AC/WGs is maintained in public GitHub teams in the ampproject org.  We are also planning on keeping track of the [new Collaborator/Reviewer roles](https://github.com/ampproject/amphtml/pull/21280) in GitHub teams.

Unfortunately only members of the ampproject org can view the membership of these teams, and GitHub does not have an option to make the members of these teams visible to everyone.  We should have an automated way to make these membership lists visible to everyone, perhaps publishing them on amp.dev.

**Comment by mrjoro** [comment]
@pbakaus I transferred the issue to the docs repo instead. :)

@sebastianbenz the data would come from the GitHub API I think.  We'd want to include the TSC, AC, Reviewers (amphtml), Collaborators (amphtml) and all of the subteams under working-groups.

https://developer.github.com/v3/teams/

**Comment by sebastianbenz** [comment]
@mrjoro Perfect, that shouldn't be a problem to integrate. What are the details per contributor we should include on the page?

**Comment by mrjoro** [comment]
I'd say at least GitHub username and full name.  It could also be useful to add the company if they have one specified.

**Comment by matthiasrohmer** [comment]
@pbakaus, did you have time to draft out what should be on this page apart form the members? Then Longo can start on a design 🙂

**Comment by pbakaus** [comment]
@matthiasrohmer apologies for the delay! Here's my attempt:

- Grid of working groups and their members
- Explanation what the working group does, and what their responsibilities are
- How to join and/or help the group (link to great first issues maybe?)
- TL of working group visually highlighted
- how to get in touch with the working group (preferred: issue on Github, secondary: slack channel, tertiary: design reviews / weekly meetings, quaternary: email)
- show upcoming weekly meeting with hangout link to join (if the wg does weekly meetings)
- code / products / projects that the working group produces
- link to the contribute section
- link to governance section/doc

@sebastianbenz @mrjoro let me know if you have any more ideas!

**Comment by LongoOfficial** [comment]
hiii everyone..

I want to share a first mock we did to get the right direction:
https://invis.io/4DT67GDE928

The basic idea is to have all 14 group names visible at first glance which you could easily click trough. Underneath, there is a description element with all the information for a particular working group. We adjusted the style of the wg logos to fit the new AMP design.
For the switcher element I wanted it as simple as possible – adding icons and descriptions would be super overwhelming and busy. ;) For UX we also imagined to have the switcher element sticky once you scroll it out of the viewport to grant easy access to every working group at any time.

I think there are some more opportunities and options to include easy and more visual access to the communication channels (slack, github etc..) and dymanic elements (like github issues). I also think we can ad a visual to the stage which is related to the wg. But we're working on it..

WDYT?

**Comment by pbakaus** [comment]
Hi Longo,

thanks for this and sorry about the delay! This is a good direction. I left a bunch of comments in InVision.

I think in general, the page needs higher information density / usability, and should focus a little more on actionable stuff (how can I join the group? how can I help? Who do I get in touch? What projects is this group responsible for?). Right now, if you don't have any sense for what the groups do in advance, you have to click through each group to get the "lay of the land".

Hope this, and my comments on the invision make sense! @sebastianbenz @mrjoro please chime in if you have additional thoughts.

**Comment by LongoOfficial** [comment]
thanks for the feedback @pbakaus !

We did an updated mock respecting your comments here:
https://invis.io/ZYTESUN897X#/378527215_AMPWorkingGroups3

In general we tried to stage the WGs more interactive from a UI perspective and include Issues from GitHub. However, I'm still lost with "How can I join the group", "How can I help". Could not find any reasonable data from WG repositories.
Can some help with that?

also, regarding the WG logos: I still think we need to update them according to the new brand design, as the old blue seems a bit off. But let's discuss this :)

**Comment by matthiasrohmer** [comment]
Thanks, @LongoOfficial! Chiming in as I've been sort of Longo's technical consultant here and want to address something that feels off about the WGs and also hits one of the points @pbakaus  mentioned: actually none of the individual READMEs inside the working group repositories say something about how to join or at least contribute. 

The [general governance document](https://github.com/ampproject/meta/blob/master/GOVERNANCE.md#working-groups) also doesn't but leaves that fairly open to the individual groups:

>A Working Group may add or remove members and change the Facilitator by using the consensus-based approach.

At least for me that doesn't seem too inviting 😉But I think it should be with the goal to find more of actively contributing working group/organization members. 

In my experience that brings the following benefit: a named group of people is much more responsive in comparison to random, anonymous contributors who can never be hold liable for their work.

**Comment by pbakaus** [comment]
heya, this is very nice, getting there! I left one comment, but overall think this is a nice MVP that we should start to build out.

Re: questions: I understand that the data does not yet exist on many things, e.g. on how to join, but that means this is an excellent opportunity to encourage the creation of said data. If you find a nice way to visualize, then I'm 100% positive that I can encourage the WG facilitators to add the right metadata. Does that make sense?

**Comment by pbakaus** [comment]
ping!

**Comment by matthiasrohmer** [comment]
We've started on this last week. Current status: layout is implemented apart from a few glitches, currently @robinvanopstal is working on fetching the data from GitHub.

**Comment by pbakaus** [comment]
great, thanks for the update.

**Comment by LongoOfficial** [comment]
Who is the person of contact regarding the WG logos? Just wanted to make sure that we are in sync with the right resources. thx :)

**Comment by pbakaus** [comment]
@mrjoro, @danielcyoung and @nainar maybe?

**Comment by mrjoro** [comment]
I'm not sure who we'll have working on these logos now; @danielcyoung do you know of anyone who could own this for now?

**Comment by matthiasrohmer** [comment]
@pbakaus, there's one pitfall we're currently running into: fetching the working group members. That's an information that is not publicly available but only for org members via the [Teams API preview](https://developer.github.com/v3/teams/). Can you check if there's a way you could provide us with credentials to access those?

Alternatively parsing members from the README.md would also work given all repos have one with the information formatted in the same manner. Another solution could be a separate `MEMBERS.yaml` which would work best but also add a third place where members need to be maintained.

**Comment by matthiasrohmer** [comment]
Thinking further about it, something like `META.yaml` might not even be the worst idea as we'd also need information about the preferred communication channels. Again it could be somehow parsed from the README.md but having it as structured data would be a lot more robust.

**Comment by pbakaus** [comment]
META file or something seems reasonable to me..for now, I'd hardcode it. We can make it dynamic a little later.

**Comment by matthiasrohmer** [comment]
As of https://github.com/ampproject/wg-stories/pull/19#issuecomment-543255714: as soon as all open PRs are merged and the working group pages are available on amp.dev we plan to replace the contents of the WG's repositories' README.md with a link to the matching page on amp.dev. This way information about a WG only needs to be maintained on GitHub and the METADATA.yaml.

**Comment by matthiasrohmer** [comment]
@newmuis brought up the idea of having WG alumni also listed on the page: https://github.com/ampproject/wg-stories/pull/19#discussion_r336485997

What do @ampproject/wg-outreach members think?
