### ISSUE TITLE
blog post redirects from ampproject.org don't work

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amp.dev#1789]
## Description of the issue found on ampproject.org

A blog post link clicked from ampproject.org that would redirect to amp.dev goes to the main blog page instead of the specific blog post

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. - Google Search: [Standardizing lessons learned from AMP]
2. Click first link: https://www.ampproject.org/latest/blog/standardizing-lessons-learned-from-amp/
3. Goes to https://blog.amp.dev/

What browser are you using? Chrome
What O/S are you using?

**Comment by sebastianbenz** [comment]
You're quick, we've deployed the redirect 8 minutes ago :-)

**Comment by sebastianbenz** [comment]
Fix is live

**Comment by rudygalfi** [comment]
This still reproduces for me.

**Comment by sebastianbenz** [comment]
Might be the browser cache. Can you try again in an incognito window?

>

**Comment by rudygalfi** [comment]
That was it, thanks. All good now.

**Comment by morsssss** [comment]
I'm actually seeing this is still a problem!

[This post](https://blog.amp.dev/2018/11/05/streaming-in-the-shadow-reader/) contains this link:

`https://www.ampproject.org/latest/blog/ads-the-shadow-reader-improved/`

which ends up redirecting to `blog.amp.dev`.

**Comment by patrickkettner** [comment]
this is fixed

**Comment by sebastianbenz** [comment]
Thanks for fixing Patrick!
