### ISSUE TITLE
Fix validation and formatting errors in imported documents

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#1809]
Follow-up to #1802. Imported docs are sometimes badly formatted and break when imported to amp.dev. Good sample is the [`amp-selector` reference docs](https://amp.dev/documentation/components/amp-selector.html?format=websites). 

One problem is python-markdown not escaping the angle brackets in the term `<amp-selector>` and the dependency injector therefore wrongly injecting the `amp-sidebar` extension. 

Another one is that the documents have HTML with nested markdown syntax which is not parsed by python-markdown.

**Comment by matthiasrohmer** [comment]
#1795 is somehow related and should be taken care of when extending `MarkdownDocument`.

**Comment by westonruter** [comment]
I ran across what I believe to be an example of this today: https://amp.dev/documentation/components/amp-recaptcha-input.html?format=websites

![image](https://user-images.githubusercontent.com/134745/58989658-2f034400-8799-11e9-872a-6e913eecabd2.png)

**Comment by matthiasrohmer** [comment]
@dlemm , #2367 will fix some validation errors but the formatting errors would still exist. It'd be great if you could take care of `amp-selector` for example and probably take Miri & Timo along with you to help you fix them and then also look at the other components. Especially they've been using Markdown in tables again which need to be fixed.

**Comment by dlemm** [comment]
I'll take care of that.

**Comment by dlemm** [comment]
What puzzled me is that the code is exactly the same for ```amp-accordion``` (for example) in the "Events" and "Actions" table. In the amphtml files there is
```<td width="40%"><strong><code>expand</code></strong></td>```
```<td width="40%"><strong><code>expand</code></strong></td>```
which render in the doc to 
```<td width="40%"><strong>`expand`</strong></td>```
and
```<td width="40%"><strong>`expand`</strong></td>``` 
but only the latter in the Actions table got rendered out right. The first one becomes ``` éxpand` ``

**Comment by tharders** [comment]
It is a problem with Python-Markdown that sometimes the markdown inside an html table is evaluated and sometimes not. According to the documentation it should normally not be evaluated per default.
So I will enable the `markdown.extensions.extra` that will evaluate markdown in the table when the attribute `markdown="1"` is set for the table tag. I will also modify the page importer so that this attribute is set for all imported markdown documents. For documents inside the docs project we then have to add the attribute `markdown="1"` manually.

**Comment by tharders** [comment]
Problems are fixed with PR #2633
