### ISSUE TITLE
"Initializing state" - Section on amp-bind page make no sense

### ISSUE THREAD

**Issue by mattrn** [ampproject/amp.dev#1827]
The "Initialize state"- Section on the amp-bind page(https://github.com/ampproject/amp-by-example/blob/master/src/20_Components/amp-bind.html) is not very clear.

The example uses an amp-state component but it is not made clear what it is for.
Furthermore if you remove the amp-state component from the example, it works exactly the same.

To me it seemed like, using this component, I could set an initial state so it would get displayed instead of null, when I first refresh the state.

If this is not possible, then this should be made clear in the section.

**Comment by sebastianbenz** [comment]
Thanks for the feedback. Moved this issue over to the amp.dev repository in which samples are now maintained.

**Comment by sebastianbenz** [comment]
The sample has been rewritten.
