### ISSUE TITLE
The AMP Cache URL converter inside amp-iframe is missing.

### ISSUE THREAD

**Issue by xiaotong-kk9** [ampproject/amp.dev#1841]
## Description of the issue found on ampproject.org

- Link: https://amp.dev/documentation/examples/guides/using_the_google_amp_cache/
- Description: The AMP Cache URL converter inside amp-iframe is missing.

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:
1. Visit [link](https://amp.dev/documentation/examples/guides/using_the_google_amp_cache/)
2. Check the `AMP Cache URL Format` Part.
3. Below `Here is AMP Cache URL for https://ampbyexample.com/components/amp-img:`, the AMP Cache URL converter is missing. Please have a look at the content inside `<amp-iframe title="Google AMP Cache tool">`.

What browser are you using?
Chrome 73

What O/S are you using?
macOS Mojave

**Comment by sebastianbenz** [comment]
Thanks for reporting, the sample has been turned into a guide: https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls.html?format=websites

But seems like we forgot to remove it. We should also setup a redirect to the guide.

**Comment by xiaotong-kk9** [comment]
Thank you!
This is super helpful.

**Comment by MadisonMiner** [comment]
Is it possible to add the converter tool that was previously available at https://ampbyexample.com/advanced/using_the_google_amp_cache/ to amp.dev? 

The tool was very useful, I used it often. If not, is the code for the converter tool available? 

Thank you,

**Comment by sebastianbenz** [comment]
The tool is here: https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls.html?format=websites

There is also a node API available here: https://github.com/ampproject/amp-toolbox/tree/master/packages/cache-url

**Comment by MadisonMiner** [comment]
Awesome! Both links are helpful. Thank you.

<https://www.linkedin.com/in/madisonminer/>

Madison Miner | WompMobile

Founder

p: 360.329.2653 <3603292653> | w: wompmobile.com
<http://www.wompmobile.com/>

1117 Ellis Street | Bellingham, WA 98225



ᐧ
