### ISSUE TITLE
Broken code preview examples/news-publishing/liveblog

### ISSUE THREAD

**Issue by keevkeev** [ampproject/amp.dev#1850]
## The code preview for blog posts returns only bracket property accessors instead of the desired code. 

- Page link: https://amp.dev/documentation/examples/news-publishing/live_blog/?format=websites

What browser are you using? Chrome
What O/S are you using? macOS (High Sierra)

**Comment by keevkeev** [comment]
@matthiasrohmer @sebastianbenz as long as this isn't a really large priority I'd love to try to tackle this

**Comment by matthiasrohmer** [comment]
Works for me as soon as all P0s are done. Have a look at the `amp-live-list` sample for reference as soon as you start with this.

**Comment by sebastianbenz** [comment]
Just a warning: it's a bit tricky to set this up in a way that also works
on the AMP Cache. Ping me before you start working on it.

**Comment by sebastianbenz** [comment]
Fixed
