### ISSUE TITLE
Implement automatic import for blog posts

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp.dev#1883]
<img width="1200" alt="Screen Shot 2019-04-14 at 3 53 56 PM" src="https://user-images.githubusercontent.com/89679/56089430-8b4e9380-5ecd-11e9-81b8-0fa24d81eacb.png">

CC @sebastianbenz

**Comment by matthiasrohmer** [comment]
News have been updated.

**Comment by cramforce** [comment]
This isn't fixed. There are newer stories now, but they aren't the latest ones.

**Comment by matthiasrohmer** [comment]
Fixed by @pbakaus, thanks!

**Comment by cramforce** [comment]
The homepage is currently not updated.

**Comment by sebastianbenz** [comment]
Just started a deploy which will update the blog posts.

**Comment by pbakaus** [comment]
@sebastianbenz I think it's fair to keep this open until our daily build doesn't fail anymore.. thoughts?
