### ISSUE TITLE
Russian Language Translation for AMP Project amp.dev Landing Page

### ISSUE THREAD

**Issue by lanagulotta** [ampproject/amp.dev#2021]
## Description of the issue found on ampproject.org: 

No Russian language translation is currently available on ampproject.org website.
Ventura Digital Arts (VeDiArts), Svetlana Gulotta, is organizing Russian language translation for the site pages. Svetlana is also currently looking for interns and volunteers to contribute to this project. Ventura Digital Arts, a digital agency, is contributing its resources to get Russian translation done as soon as it possible. Svetlana Gulotta, the SEO and the founder of VeDiArts, is a bilingual web developer, a big fan of Sergey Brin, and an avid supporter of AMP project, who has published AMP websites.

Bilingual volunteers can email me at lana@vediarts.com

- Page link: https://amp.dev/
- Page has no option in Russian language

Work Plan:

1. Copy text content into a document using Google Docs labeling paragraphs to correspond to each page element. 
2. Translate document into Russian language.
3. Edit translated document for proper language usage.
4. Copy and paste translated content in text holders of the page using developers tools such as VSCode. 
5. Submit translated page to AMP team. 

What browser are you using? Chrome
What O/S are you using? multiple

**Comment by matthiasrohmer** [comment]
That sounds great! @CrystalOnScript might be able to give some further guidance 🙂

**Comment by CrystalOnScript** [comment]
Oh wow this is absolutely incredible! So excited to see this! 

One document that would be extremely helpful to add translations to is the [ru/LC_MESSAGES/messages.po](https://github.com/ampproject/docs/blob/future/pages/translations/ru/LC_MESSAGES/messages.po) file. This translates things such as drop downs and buttons, making the site more understandable and navigable. 

If you're translating any documentation, please append `@ru` at the end of the filename and upload it next to the original file. 

Really excited to see this! I would also like to invite all participants to the [AMP Slack](https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877) and encourage you to join the [#amp-translation](https://amphtml.slack.com/messages/CCVMH4ZMF/) room.

Please let me know if you have any questions! Looking forward to seeing these contributions!

**Comment by lanagulotta** [comment]
@CrystalOnScript I finally found volunteers who are ready to start tomorrow. They are professional editors. I am planning to finish translation of the landing page amp.dev within one week, and i plan to continue to translate all of the pages on the amp.dev website. If our team works well, we can continue with documentation. Do you need to deliver to you translation as a text file or deliver the entire AMP page with Russian text already implemented? I have already downloaded the source file and ready to implement translation. 

I suppose, we can do this:
1. Commit text files of translation per page
2. Let other volunteers to add or amend translation to deliver the best language practices and technical accuracy,  give it 2 months.
3. I can implement translation into source code and commit the source code ready to publish.

**Comment by CrystalOnScript** [comment]
Sorry for my delayed response - been on a plane! 

My expertise is limited to documentation at the moment, the best way to deliver that would be to commit it directly to the repository in markdown format (if possible!) :)

As for the landing page, I need to refer to @pbakaus and @matthiasrohmer for their preferences and if we are able to support translations on those pages at this time?

**Comment by lanagulotta** [comment]
@pbakaus @matthiasrohmer It seems that there is no problem with supporting Russian language page, since it will be the same content as the English pages have but in Russian. We plan to add Russian content directly to source file, so that our project managers can review, approve the content and have ready-to-publish source file.  I am adding a volunteer Dmitriy who will be helping with Russian Translation issue.

**Comment by CrystalOnScript** [comment]
Awesome! From what I've been told, we just need the Russian translated page next to the the english page, but with a `@ru` appended to the name: `index.html` then becomes `index@ru.html`.

@pbakaus and @matthiasrohmer - please confirm if this is correct!

**Comment by pbakaus** [comment]
@CrystalOnScript that's correct. Said index.html file is located here: https://github.com/ampproject/docs/blob/future/pages/content/amp-dev/index.html

Thanks in advance!

**Comment by BanDuk01** [comment]
Hello, my name is Dmitriy. I will be helping Svetlana with translation project.

**Comment by lanagulotta** [comment]
Hi Dmitriy, thank you for joining us.

**Comment by matthiasrohmer** [comment]
Closed due to inactivity. You are very welcome to reopen this issue or create a new one if you are still willing to contribute 🙂
