### ISSUE TITLE
Magazine article example issues

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#2039]
A few issues I/O attendees pointed out in the [Magazine article](https://amp-article.herokuapp.com) sample:

-   There's a horizontal scroll bar at the bottom on mobile, but the page can't be scrolled.

-   If you scroll down and then back up, the hamburger menu button stops working.

-   The search and user account buttons in the top right corner don't do anything. Same goes for the items in the menu.

**Comment by matthiasrohmer** [comment]
Thanks for reporting, @fstanis! @sebastianbenz, can you move this one over to ampproject/samples?

**Comment by matthiasrohmer** [comment]
@sebastianbenz, is there someone monitoring and maintaining the issues over at ampproject/samples or should we take care of the issues mentioned by Filip?

**Comment by sebastianbenz** [comment]
Let's leave this for now as they're not really featured on amp.dev.

**Comment by matthiasrohmer** [comment]
Funnily this one is 😁 on the Use Cases page. And we've been discussing to make a thing out of them all in https://github.com/ampproject/amp.dev/issues/1994
