### ISSUE TITLE
request for example/documentation: passing amp-geo values to amp-analytics

### ISSUE THREAD

**Issue by AnothrNmbr** [ampproject/amp.dev#2040]
the amp-geo doc at https://blog.amp.dev/2018/05/03/dynamic-geo-personalization/ mentions "you can integrate amp-geo with your analytics through variable substitution," but we were unable to implement this or find any examples to work from. Could we get more documentation or example code for this? thanks in advance.

**Comment by CrystalOnScript** [comment]
@zhouyx @lannka @calebcordry @micajuine-ho @jpettitt
Is someone able to provide an code sample/example for this?

**Comment by zhouyx** [comment]
It will be through variable substitution `AMP_GEO` or `${ampGeo}`. 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-geo/amp-geo.md#variable-substitution

**Comment by CrystalOnScript** [comment]
Thanks @zhouyx but I am still unsure where/how the substitution is used. I would really appreciate a basic code sample.

**Comment by zhouyx** [comment]
You're asking how variables are used in amp-analytics? Here's a quick example of how it can be used in amp-analytics. (I hand coded it, can be an invalid json)
```
<amp-analytics><script type="application/json">{
  "requests": {
    "example": "https://example.com?geo=AMP_GEO"
  } 
 "triggers": {
    "pageview": {
       "on": "visible",
       "request": "example"
     }
  }
}</script></amp-analytics>
```
