### ISSUE TITLE
Migrate inline doc samples to preview.amp.dev

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2053]
Documentation pages still use the old inline samples with preview, e.g. here: https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design

We should improve these by directly rendering the source code into the doc page and serve the preview from preview.amp.dev.

You can find the existing samples here: https://github.com/ampproject/docs/tree/master/examples/src

@matthiasrohmer @lluerich @tharders does anyone of you want to look into this?

**Comment by CrystalOnScript** [comment]
I'm unsure if this issue is related or not, but while sandboxing at I/O I noticed none of the inline examples are working with the component documentation either, such as the `amp-carousel`

https://amp.dev/documentation/components/amp-carousel?format=websites

**Comment by sebil** [comment]
I'm reopening this issue, because of an unfinished styling task.
