### ISSUE TITLE
Migrate all ampbyexample backends to amp.dev

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2054]
...and fix/improve any broken samples along the way

//cc @matthiasrohmer @lluerich @tharders

**Comment by CrystalOnScript** [comment]
The [amp-autocomplete](https://amp.dev/documentation/examples/components/amp-autocomplete/?format=websites#amp-autocomplete) are not working. @caroqliu pointed out the DOM is also not rending `<input type="text">` causing the examples to fail.

**Comment by lluerich** [comment]
@sebastianbenz I finished looking through all the examples. Most of them are hosted on ampbyexample.com, but there are also some hosted on glitch and herokuapp. Since the title of the ticket concerns only ambyexample backends, I suggest, that I start migrating them first.

**Comment by sebastianbenz** [comment]
SGTM. Can you start migrating the broken samples first?

>
