### ISSUE TITLE
Fix spelling errors in "/contribute/contribute@ko.md"

### ISSUE THREAD

**Issue by JaewooKim0** [ampproject/amp.dev#2122]
@CrystalFaith

*Korean

/contribute/contribute@ko.md

*Few terms

**Comment by techhtml** [comment]
Hi, This is Eun from Korea.

Where is that files?

**Comment by techhtml** [comment]
I didn't find that problem.
Does anybody find this problem?

**Comment by techhtml** [comment]
@lesseasyway 
Hi, Could you update this issue that where is the file exist?
I didn't find an file.

**Comment by techhtml** [comment]
@matthiasrohmer Could you close this issue? I don't find any issues and he doesn't answer.
