### ISSUE TITLE
amp.dev e-commerce screenshots refresh

### ISSUE THREAD

**Issue by alankent** [ampproject/amp.dev#2127]
See https://amp.dev/documentation/examples/e-commerce/amp_for_e-commerce_getting_started/?format=websites

The screenshots have been used for a long time and are due for a refresh. The text starts by saying how AMP can be used to create beautiful experiences, but the actual screenshots are not "beautiful". We should update the screenshots with more attractive images.

Not a high priority, but the current screenshots do not showcase what many merchants are achieving.

**Comment by alankent** [comment]
Quick note: It was identified that the CSS may be missing on amp.dev for the page I was looking at, so it may just be a bug on the site rather than needing a full refresh.

**Comment by matthiasrohmer** [comment]
Indeed the sample used ampbyexample.com styling before which is now missing.

**Comment by patrickkettner** [comment]
the bug mentioned has been fixed
