### ISSUE TITLE
AMP Playground renders invalid AMP

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#2153]
I think it may confuse people that playground.amp.dev will render pages even when the markup is invalid. This might give the wrong impression of importance of validity, especially for formats like AMP for Email, where the AMP email isn't displayed if invalid.

I propose we revisit this and make it more obvious that the rendered result is invalid. Perhaps display a more prominent warning above the preview or even a lightbox asking something like "It appears the markup is invalid - render anyway?"

**Comment by sebastianbenz** [comment]
I didn't add anything like this as experimental components are not valid AMP either (but should work in the playground).

I like the invalid markup warning prompt though!

**Comment by matthiasrohmer** [comment]
The updated playground UI will make the invalidity of pages more prominent.

![Bildschirmfoto 2020-05-08 um 15 38 01](https://user-images.githubusercontent.com/12857772/81411012-f951a280-9141-11ea-8158-77e674642115.png)
