### ISSUE TITLE
Lint and validate pages after build

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2164]
Before pages are deployed they need to be linted (also to ensure that potential optimization steps work flawlessly) and checked for AMP validity.

This should happen either as an PR check for the set of changed files to keep check times on a human level if somehow possible or at least nightly with a notification about eventual errors.

**Comment by DerekNonGeneric** [comment]
@matthiasrohmer, it would be great if you could enumerate all of the checks you are interested in having. I have a really sweet setup going for a local repo I have been working on and see the value of instrumenting this one. Ideally, I'd like to at least see Markdown linting and AMP validation conducted while the commit is staged as a pre-commit hook and possibly during CI as well. Thoughts?

**Comment by matthiasrohmer** [comment]
Sorry, your comment slipped my attention: our setup has become a lot more complex since I wrote this in May 😅The main problem is that there are multiple render steps involved until the final page is served to the user.

The markdown files get rendered by Grow. The maintainers of ampproject/amphtml have started linting the markdown files in their repository. The same should happen for our markdown files before they get rendered.

Grow doesn't necessarily render valid AMP pages but could also render SSR templates (basically valid pages but sprinkled with SSR tags like `[% if ... %]`). Therefore this product is not easy to validate.

Next step is the pages router that renders the SSR tags and passes the rendered (ideally valid AMP HTML) on to the amp-optimizer which *should* return valid optimized AMP. As this currently happens on request also not really easy to validate.

This isn't in any way an answer to your question but more like a collection of hooks where we *could* jump in and test/validate. But to be honest I need to think about it a little more 😉

**Comment by matthiasrohmer** [comment]
Not feasible anymore as our build process does not yield valid AMP pages in the first place but they only get valid through the use of an AMP optimizer.
