### ISSUE TITLE
Automatically add a lightbox to all images on a doc page

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2223]
To improve the UX, we should automatically add a lightbox via [amp-lightbox-gallery](https://amp.dev/documentation/components/amp-lightbox-gallery) to all images on doc pages. At least for all images above a certain size (700px?). 

//cc @CrystalOnScript @pbakaus for thoughts

**Comment by pbakaus** [comment]
Seems good to me! Not sure how to implement (as we would have to measure image size), but...go for it :)

**Comment by sebastianbenz** [comment]
I'd go with image size defined in `width` first. We just have to be sure to define the real image sizes there instead of aspect ratios.

**Comment by matthiasrohmer** [comment]
This should happen automatically by now: https://github.com/ampproject/amphtml/blob/master/spec/auto-lightbox.md

Please reopen if I am mistaken! 🙂
