### ISSUE TITLE
Create a shortcode for internal links

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2243]
Would be great to have a simple shortcode for internal links. Currently, I always have to copy paste the code from a different page. 

//cc @matthiasrohmer

**Comment by matthiasrohmer** [comment]
So basically a wrapper around `{{ g.doc('content/amp-dev/...', locale=doc.locale) }}`? 😉 Did you have a specific syntax in mind?

I could imagine `[link example="amp-accordion"]` and `[link component="amp-web-push"]` for example. Guides would be a bit more verbose though as you'd still need to know their bucket and file type: `[link guide="develop/interactivity/get-familiar.md"]`.

**Comment by sebastianbenz** [comment]
It's even worse: `{{g.doc('/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate.md', locale=doc.locale).url.path}}`. Or is `.url.path` not needed?

It'd be perfect if we could stay with the markdown link syntax and automatically rewrite relative links to the grow syntax.
