### ISSUE TITLE
component-sidebar – letters as shortcuts on the right-hand side

### ISSUE THREAD

**Issue by sebil** [ampproject/amp.dev#2269]
To improve the usability of the component-sidebar (the one with alphabetically ordered list of all components) @sebastianbenz suggested a new idea. See below:

> [...] How about showing letters as shortcuts on the right-hand side? Similar to the iOS
contacts app: [contacts-app-screenshot](https://img.gadgethacks.com/img/35/14/63541628772516/0/find-fix-missing-contacts-ios-7-1-2.w1456.jpg)

>

_Originally posted by @sebastianbenz in https://github.com/ampproject/docs/pull/2253#issuecomment-498697243_

**Comment by sebil** [comment]
I will discuss this with Longo because we probably need a layout for this.

**Comment by sebastianbenz** [comment]
SGTM. Thinking about this more, this also makes a lot of sense on desktop.

**Comment by matthiasrohmer** [comment]
@robinvanopstal, can you please discuss this with Ferdi when refactoring the sidebar for frontend21?
