### ISSUE TITLE
Markdown is not converted to HTML in table

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#2274]
On https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#html-tags

There is markdown not converted to HTML appearing in the page:

![image](https://user-images.githubusercontent.com/134745/58989754-5f4ae280-8799-11e9-931f-803fde65163f.png)

**Comment by matthiasrohmer** [comment]
Yes, that sadly happens from time to time. python-markdown stops parsing inside of HTML blocks as this one. That's the source document with the acutal table: https://raw.githubusercontent.com/ampproject/amphtml/master/spec/amp-html-format.md

All other links there are formatted as actual `<a>`s - this one should be as well.

**Comment by sebastianbenz** [comment]
@tharders is this still a problem?

**Comment by tharders** [comment]
This problem was already fixed
