### ISSUE TITLE
Migrate Support Section from ampproject.org to amp.dev

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2293]
This page and it's child-pages haven't been moved yet: 

* https://www.ampproject.org/support/faqs/overview -> migrate
* https://www.ampproject.org/support/developer/get_support -> migrate
* https://www.ampproject.org/static/img/brand-guidelines.pdf -> 404

@matthiasrohmer would be great if your team could migrate these as soon as possible. 

//cc @pbakaus

**Comment by matthiasrohmer** [comment]
Hah, you were quicker than me. That just occurred to me when I was showing Dennis how to fix the broken link this afternoon. We'll do them next week!

**Comment by sebil** [comment]
See PR: #2513 and #2459
