### ISSUE TITLE
Make it more obvious which development host to access

### ISSUE THREAD

**Issue by ianand** [ampproject/amp.dev#2354]
## Bug Report

Local version of amp.dev doesn't show any images

### Current Behavior
I must be doing something wrong.

I followed the instructions on getting started in the Readme without issue and was able to view amp.dev locally at `localhost:8081` in my browser. The only problem is that while the content is all there are no images (they all are getting 404s in DevTools). Looking at my console I find error messages like:

```
404: /static/img/tools/amp-story-tick.jpg
Traceback (most recent call last):
  File "grow/server/main.py", line 118, in __call__
  File "grow/server/main.py", line 227, in wsgi_app
  File "grow/server/main.py", line 165, in dispatch_request
RouteNotFoundError: '/static/img/tools/amp-story-tick.jpg was not found in routes.'
```

After reading the grow documentation, I've been able to workaround the issue but manually changing the `podspec.yaml` to include a `static_dirs` reference to the `static` folder, fixing some python errors, and then running `grow run` manually in the `pages` directory. This works, but based on the changes I needed to do to get it to work I'm pretty sure that's not the normal workflow. My sense is that something is wrong in my setup or static images are normally served some other way.

### Expected behavior/code

When I visit `localhost:8081` in my browser it shows both the content and images.

### How do we reproduce the issue?

Not sure. I simply followed the instructions in the readme, i.e. 

1.  `nvm install --lts`
2.  `curl https://install.grow.io | bash`
3.  `npm install` 
4.  Creating and `export`ing an `AMP_DOC_TOKEN`
5.  `gulp bootstrap`
6.  `gulp develop`

Even tried recloning the repo and starting over and got the same result.

What browser are you using? Chrome 75
What O/S are you using? macOS 10.14.5

**Comment by matthiasrohmer** [comment]
The most important bit comes after step 6. in the README 😉 

>This command prints a lot to the shell and will most probably end on `Server ready. Press ctrl-c to quit.`. This means everything went fine so far but other than stated in the logs the site is then available at [http://localhost:8080/](http://localhost:8080/). The service running on 8081 is only Grow rendering the pages.

**Comment by ianand** [comment]
doh. thanks @matthiasrohmer. how embarrassing.  

Two proposals:

1. Make sure that line in the readme is in bold. 
2. Have gulp output something after grow, telling folks the correct port. That way the last message on the console will be point the user to correct port.

I could submit a PR for either or both.

**Comment by ianand** [comment]
Understand it better now that I went through the gulp files (it starts grow *and* a node server in `platform.js`) which is what I should've done earlier. Doh.

**Comment by matthiasrohmer** [comment]
Yes, but not your fault at all 🙂But maybe your research also made the problem more obvious: the Grow server does it's async business without an easy solution (despite sniffing on the stdout of the child process) for the JavaScript part of the application to tell the user which host to access - that's my dilemma 😅
