### ISSUE TITLE
Add a page for the AMP Contributor Summit 2019

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amp.dev#2360]
We'd like to have a page with information on the AMP Contributor Summit 2019 (#ampcs2019).

As a starting point we can copy what we did for AMP Conf 2019 here:  https://github.com/ampproject/docs/tree/future/pages/content/amp-dev/events

The content on the page should include:

- Dates (October 8-10, 2019)
- Location (currently just NYC while we finalize where in NYC it will be)
- Basic description of the conference, including some of the [conference goals](https://docs.google.com/document/d/10Aqe8uMCDZctCCK993JBS6DRNTxlHgenCVydBRxhv70/edit?userstoinvite=jacelegan@gmail.com&ts=5d079df6&actionButton=1#heading=h.9bctlxtw7svo).  This should emphasize this is a technical conference and for contributors to AMP.
- High-level daily agenda (pending finalization from the Content organizers, e.g. "Tuesday, Optional New Contributor Day or Hackathon; Wednesday & Thursday, Core Conference Days with Talks & Breakout Sessions"
- A prominent link to the application when it is ready; "coming soon" in the meantime

This can potentially copy some wording/ideas from the [announcement blog post for 2018](https://blog.amp.dev/2018/06/28/announcing-the-amp-contributor-summit/) and the [takeaways post for 2018](https://blog.amp.dev/2018/10/15/amp-contributor-summit-learnings-takeaways/).

@vishaldodiya has volunteered to work on this!  Thanks Vishal. :)

@cathibosco and @mattludwig were working on gathering some assets, which seems like it would be useful here as well.

**Comment by vishaldodiya** [comment]
@mrjoro 

Just to keep a note. We will need to update the `Code of Conduct`, `Accessibility` and `Contact` details.

**Comment by amanintech** [comment]
Can be Closed now
