### ISSUE TITLE
Bookmarked links in docs are incorrect

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2370]
### Current Behavior
Some links intended to jump to sections on page do not work, such as the "deep-merge" link on [amp-bind](https://amp.dev/documentation/components/amp-bind?format=websites#updating-state-with-amp.setstate()) documentation.

Currently the link looks like this:
`<a href="#deep-merge-with-ampsetstate">deep-merge</a>`

Not sure if theres a way to fix this other than updating the links manually? However, that would impact devs who prefer to read documentation on GH. 

What browser are you using?
Chrome, current
What O/S are you using?
Mac

**Comment by sebastianbenz** [comment]
@tharders @matthiasrohmer do you see a way how we can unify the id generation of grow and github?

**Comment by tharders** [comment]
We should really use explicit defined anchors for such references.
This will also solve the problems with anchors in translations: https://github.com/ampproject/amp.dev/issues/2647

When we use HTML code like `<a name="target"></a>` to define an anchor this would work for our site and for github.

**Comment by tharders** [comment]
# Proposed Solution

## Anchor definition

All files in the amp.dev repository will use explicit anchors.
Only those sections that are the target of a link will get an explicit anchor in the headline after the text: 
```md
## Layout guidelines <a name="layout"></a>

Copytext for this section...

[link to anchor](#layout)
```

The anchor name should be a short, meaningful name that represents the paragraph and is unique in the document. 
The name is always in english and must remain untouched on translation of a document. This will guarantee that a link from an untranslated file will always be valid, regardless of whether the target document is translated or nor.

On import of the component documentation explicit anchors are added to all headlines based on the headline text like it is done by github. This will ensure that anchors work in github and that a translation based on an imported document will keep the english anchors.
(The explicit anchor will not be added if an explicit anchor is already present.)


## Validation

We can extend the link checker job to validate anchors of internal links.
* The link must point to an explicit anchor in the target document
* The anchor must be present in all translations


## Feedback?
@CrystalOnScript @pbakaus @sebastianbenz If this is fine for you, we will change all documents and extend the link checker accordingly.

**Comment by pbakaus** [comment]
Actually there's a nicer solution for this: A while back I started working on a solution, found a good approach but Grow failed on me, and then had the Grow team fix the blocking issue for me: https://github.com/grow/grow/issues/850#event-1912745179

All you should have to do is this:

1. Load the [`attr-list`](https://python-markdown.github.io/extensions/attr_list/) extension with the following code in `podspec.yaml`:

```
markdown:
  extensions:
  - kind: markdown.extensions.attr_list
```

2. then add explicit ids to the markdown with a variation of [extended markdown syntax](https://www.markdownguide.org/extended-syntax/#heading-ids), like so :

```
## A settext style header {: #someid }
```

Enjoy this free gift! :)

**Comment by tharders** [comment]
Thanks @pbakaus, I didn't think about this markdown extension.
The short syntax is quite nice, but the attr-list extension caused some problems when I was playing with the markdown extensions, since we have a few places where we have curly braces in the markdown.
Maybe the shorter syntax is not worth dealing with those problems since editors would also have to learn this special syntax.

The general idea with those explicit anchors in english is fine for you?

**Comment by pbakaus** [comment]
General idea seems fine/inevitable to me, unless we go really fancy and automate it with SSR (which would be neat). If we don't do SSR, then I'll let you decide on the best path here.

**Comment by tharders** [comment]
@pbakaus Can you explain your idea how SSR would help with the anchor problems?

Of course we could do some magic to have the same anchors on the amp.dev like they are generated by github. But the problem with the translations would still remain.

**Comment by pbakaus** [comment]
@tharders right, it doesn't solve the "go from untranslated file to translated file" case. For that, the SSR would need to be smart enough to match english headers to translated headers, which sounds like a stupidly hard problem :)

**Comment by matthiasrohmer** [comment]
@pbakaus, alright that was the idea we've guessed. But: how would SSR ever know about the anchor as fragments are not sent to the server 😉

**Comment by pbakaus** [comment]
@matthiasrohmer heh, not sure if joking or not, but I meant SSR for the whole doc, then dynamically attach static english anchors to links (the anchor in URL is irrelevant for that). One idea: We could do a system that isn't semantic, and uses absolute numbers (e.g. third header in doc is #3), that would work for translated docs as well..
