### ISSUE TITLE
Change "AMP Cache" -> "AMP Caches"

### ISSUE THREAD

**Issue by raisaveuc** [ampproject/amp.dev#2382]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
https://amp.dev/about/websites
"AMP Cache" header should be "AMP Caches" as per style guide and the fact that there are multiple AMP Caches.

**Which part of the site would that content live at?**
amp.dev > about >websites

**What's the type of content?**
One of the last headers on the page https://amp.dev/about/websites

**Comment by karansapolia** [comment]
@raisaveuc I think this issue can be closed as https://github.com/ampproject/amp.dev/pull/3134 has been merged.
