### ISSUE TITLE
Menu items on mobile inaccessible by keyboard

### ISSUE THREAD

**Issue by raisaveuc** [ampproject/amp.dev#2385]
### Current Behavior
When tabbing through amp.dev, user focus goes to logo, then becomes invisible for 7 items, then highlights "Get Started" CTA. The first invisible item seems to be the language selector, but when you hit "Enter" to access it, there is no way to select from the languages. The invisible focused elements after that seems to be for the dropdown arrows of the submenus, but these can't be toggled open/closed with the keyboard. The only menu item you can access by tab (with invisible focus) is the "Blog" link (6th tab), since it's not nested like the others in the menu.

Please also provide:
- Page link: https://amp.dev/
(See screenshot at end of bug with tab order traced from ChromeLens extension)

### Expected behavior/code
The menu icon should have a clear focus state and be possible to open/close/navigate via keyboard. Similar to AMP Start ecommerce template, but user should also be able to loop through menu items once they reach the end of the menu: https://www.ampstart.com/templates/e-commerce/landing.amp

### How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Open amp.dev on mobile emulator
2. Tab through page and try to reach hamburger menu and/or language selector
3. Notice invisible focus states and inability to open or see menu items

What browser are you using?
Chrome 75 mobile emulator Nexus 5X

What O/S are you using?
MacOS  #10.13.6

Screenshot:
![amp dev_(Nexus 5X) (1)](https://user-images.githubusercontent.com/17463384/60184971-5a71cf80-9829-11e9-8a7c-ad22946849c3.png)

**Comment by sebastianbenz** [comment]
We should fix this soon. @sebil can you please take a look?
