### ISSUE TITLE
External links in courses should go to new tab

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#2387]
Links to the likes of glitch should indeed go to a new tab, not replace the current page!

Does our markdown have an option for this?

**Comment by matthiasrohmer** [comment]
Sadly no 🙁You need to resort to `<a href="{{ g.doc('...', locale=doc.locale) }}" target="_blank>`.

**Comment by morsssss** [comment]
Ok, got it!

Reopening so that I will actually do this work... that is, not creating an extension in our markdown, but fixing these links 😄
