### ISSUE TITLE
Implement a site search

### ISSUE THREAD

**Issue by virgiltu** [ampproject/amp.dev#2412]
For the love of god, can we please get a from or maybe a link to the google forum that matches amp. Also would be nice to have something like codepen where people can put their work. If i build a nice amp module, i can showcase it so other can use it. And also a god dam search on the documentation. I know this was requested before. 

These have to be the top must have to get this more popular. I know so many people that got frustrated and just gave up on amp because it was to hard to find help or took hours to find something.

**Comment by pbakaus** [comment]
Hi there, we definitely hear you, and understand your frustration.

We've recently redesigned/relaunched our site, and the Search feature has not been ported over yet. It's obviously critical as you pointed out, and it's the next high priority item for our devs. Looping in @matthiasrohmer, who is I believe starting work on it in the next days.

As for the others:

1. Codepen works with AMP! There's also https://playground.amp.dev/, but the Playground doesn't have save functionality. You make a good point, it'd be awesome to make it easier to contribute to our examples, and offer more CodePen like functionality..
2. For AMP on Google, consider the webmasters forum: https://support.google.com/webmasters/community?hl=en. We have nothing to do with it though.

Stay tuned for more updates, thanks for the report!

**Comment by virgiltu** [comment]
This is amazing news. No worries with all the frustration I keep my spirits up to deliver amazing content.

**Comment by matthiasrohmer** [comment]
Thanks for your feedback, @virgiltu! I can only second what Paul already said. We are working everyday to make AMP more accessible to developers - especially by improving amp.dev

As search is indeed one of the next top priority features and there's no publicly tracked issue for it yet, I am going to rephrase the title of this one here. Hope that's fine for you!

**Comment by tharders** [comment]
I will close this, since the search is live now.
Problems and improvements for the search should be addressed in a new issue.
