### ISSUE TITLE
Add AWeber to the AMP Tools Listing

### ISSUE THREAD

**Issue by cvasquez** [ampproject/amp.dev#2424]
## Request to add third-party tool/service/platform/vendor

**1. What's the name?**
AWeber

**2. For which format?**
Email

**3. What type is it?**
Service Provider

When we add the ability to create AMP components directly in our editor, should we also list as a Creation & Design tool?

**4. What page should it appear on?**
2. [amp.dev/documentation/tools](https://amp.dev/documentation/tools)

**5. If you choose 2 in Step 4:**
* [AWeber Homepage](https://www.aweber.com/index.htm)
* [AMP for Email Knowledge Base Article](https://help.aweber.com/hc/en-us/articles/360025741194--DRAFT-Getting-Started-with-AMP-for-Email-with-AWeber?flash_digest=bbb7857d402a0c9ea2bf4c791ecb1d773648fff0)

**Comment by matthiasrohmer** [comment]
@fstanis, please triage or forward to someone else from the wg-amp4email. Thank you!

**Comment by fstanis** [comment]
Hey @cvasquez, could you provide a logo we can add to the website?

Beyond that, no objections.

**Comment by cvasquez** [comment]
@fstanis does this work alright? https://www.aweber.com/assets/img/aw-logo.png

We're super stoked to help more folks start using AMP for Email!
