### ISSUE TITLE
Tip and inline filtering doesn't work on local build 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2441]
### Current Behavior
Local builds shows the short codes for tips and inline filtering, but does not render the actual tip or inline filters 

Please also provide:
- [Create responsive AMP pages demonstrates both issues on local machine](http://localhost:8080/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design?format=email)
https://snag.gy/iZsc3V.jpg
https://snag.gy/DIwfOr.jpg

### Expected behavior/code
Would love to see the actual tips and filtering work on local machines before pushing code to production.

**Comment by matthiasrohmer** [comment]
Interesting to see this happening again. Will look into this.

**Comment by CrystalOnScript** [comment]
Thanks! ^__^

**Comment by matthiasrohmer** [comment]
@CrystalOnScript, can you do me a favor and check your Grow version with `grow --version` so I can try to reproduce? 🙂

**Comment by CrystalOnScript** [comment]
Sure thing! `0.7.6`

**Comment by patrickkettner** [comment]
no longer an issue
