### ISSUE TITLE
Document how to contribute to amp.dev

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2456]
If someone wants to set up new content for amp.dev there are a few features built-in to the platform that make it easy creating new content experiences but on the other hand there are also some quirks that need to be documented so no one stumbles over them.

A list of specialties of amp.dev that I'd like to see documented:

- Content structure and hierarchy (`pages/content/amp-dev/...`, HTML vs YMAL vs Markdown)
- Various shortcodes: `[tip]`, `[filter]`, `[video]`, `{{ image() }}`, `[example]`
- Special frontmatter keys (`bucket`, `formats`, `$titles`, ...)
- Imported documents and how to handle them
- Example authoring
- CSS styleguide
- Success story authoring (TBD, as the audience for this one is limited)

Please feel free to extend the lists with items I haven't thought of. 

Some of this content already exists in the contributing directory and only needs to be migrated to proper pages living in `pages/content/amp-dev/documentation/guides-and-tutorials/contribute`.

/cc @pbakaus, @sebastianbenz, @CrystalOnScript

**Comment by patrickkettner** [comment]
@sebastianbenz @matthiasrohmer is this something that JVM folks should be doing

**Comment by sebastianbenz** [comment]
I think @CrystalOnScript already documented most of the things.
