### ISSUE TITLE
Embedded component samples don't show

### ISSUE THREAD

**Issue by alabiaga** [ampproject/amp.dev#2469]
Page link:  https://amp.dev/documentation/components/amp-ad?format=websites#example:-displaying-a-few-ads

Scroll to "Example: Displaying a few ads" section.

Expected: Ads?
Actual: Empty. The tag 'amp-iframe' requires including the 'amp-iframe' extension JavaScript. 

Browser:
  Chrome

**Comment by matthiasrohmer** [comment]
Will be fixed by ampproject/amphtml#22974.
