### ISSUE TITLE
Make various pages format- or category filterable server- and client-side

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2475]
Successor to #1694 and #2341. #2325 will allow SSR for pages based on one of the context variables `format = 'websites' || 'stories' || 'ads' || 'email'` and `category`.

We should use this to make the following pages filterable per either deep-link or via the client side:

- Success story overview
- Templates overview
- Tools
- Roadmap

**Comment by dlemm** [comment]
The template overview, the Roadmap and the success story overview page are still open, right?

**Comment by sebastianbenz** [comment]
Does Tools already support SSR?

>

**Comment by fstanis** [comment]
Friendly ping - is this still on the roadmap? It would really help with the tools page.

**Comment by matthiasrohmer** [comment]
I need to double check: AFAIK the tools page was one of the first pages we've implemented SSR on but needed to revert multiple times due to errors with our minifying pipeline. 

A quick check on https://amp.dev/documentation/tools/?format=stories does nothing so I guess we never merged it again after fixing the related bugs. See #2509 and #2508 and finally #2614 for more history.

If I didn't miss anything in this quick research we are good to reopen a PR to finally add SSR for the tools page. Given the branch with this work still exists somewhere.

**Comment by fstanis** [comment]
Another friendly ping on this.

**Comment by sebastianbenz** [comment]
It's live on staging for success-stories and tools:
https://amp-dev-staging.appspot.com/documentation/tools/?format=email

>
