### ISSUE TITLE
Refine new overview pages

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2476]
Some small points I oversaw when reviewing the new overview pages last.

- This padding here seems off:
<img width="177" alt="Bildschirmfoto 2019-07-12 um 15 13 05" src="https://user-images.githubusercontent.com/12857772/61130708-a07c9380-a4b7-11e9-8357-6fdb4aa6d69b.png">

- The *Toggle sidebar* button seems off in comparison to the detail pages:
<img width="241" alt="Bildschirmfoto 2019-07-12 um 15 14 20" src="https://user-images.githubusercontent.com/12857772/61130812-da4d9a00-a4b7-11e9-8c9e-3b673a26d70f.png">

- The images here are distorted and don't convey any message, remove them:
![Bildschirmfoto 2019-07-12 um 15 15 36](https://user-images.githubusercontent.com/12857772/61130847-f0f3f100-a4b7-11e9-9499-fad05b3eaba0.png)

- The table sometimes breaks:
<img width="1011" alt="Screen Shot 2019-07-12 at 15 14 20" src="https://user-images.githubusercontent.com/12857772/61130930-2567ad00-a4b8-11e9-9374-3725cc969203.png">

- Overview pages for components, examples and guides are not filterable anymore

**Comment by matthiasrohmer** [comment]
- Four format dots in a row don't work out

![Bildschirmfoto 2019-07-12 um 15 23 49](https://user-images.githubusercontent.com/12857772/61131333-44b30a00-a4b9-11e9-8636-274ca5853021.png)

**Comment by matthiasrohmer** [comment]
- This needs to be "AMP Email"
![Bildschirmfoto 2019-07-12 um 15 31 26](https://user-images.githubusercontent.com/12857772/61131693-2699d980-a4ba-11e9-99ec-e7977dc72ae1.png)

**Comment by sebastianbenz** [comment]
We need a different way to filter categories on mobile:

1. slider requires way too much scrolling
2. super confusing: jumping to one of the last categories, requires me to
scroll across all components before I can to the top of the page again.

=> amp-bind would be better for filtering

>

**Comment by LongoOfficial** [comment]
Get Started Page:
- can we somehow fix that cropped shadow in the video carousel?
![image](https://user-images.githubusercontent.com/41894292/61134561-27356e80-a4c0-11e9-8440-a7838da3893b.png)

Guides & Tutorials:
- we waste space with the cards. can we get rid of the margin underneath the category tag?
![image](https://user-images.githubusercontent.com/41894292/61134613-492ef100-a4c0-11e9-8e8b-a61f7f628359.png)

Components:
- in the cards the headline of the component looks a bit too big. we should make them slightly smaller (1em) and increase the margin to the top (10px)
![image](https://user-images.githubusercontent.com/41894292/61134656-5b109400-a4c0-11e9-93c3-f5e5661f8b8b.png)

Components/Examples:
- the categories filter looks alien. Can we make the shadow only appear on the bottom and not on the top? the categories clearly need to relate to the following section. also it should not overlap previous elements
![image](https://user-images.githubusercontent.com/41894292/61134846-c6f2fc80-a4c0-11e9-9f45-52818de23930.png)
![image](https://user-images.githubusercontent.com/41894292/61135028-1fc29500-a4c1-11e9-8b2a-951d8906531f.png)

Examples:
- can we make the list for only the the component examples two-columned? to show the used components is a bit irritating here.
![image](https://user-images.githubusercontent.com/41894292/61135221-85168600-a4c1-11e9-8c63-4a5138a744d4.png)


Mobile category filter:
- can we make the scrollbar less prominent? For example: Let's make it smaller in height (2px), less dark (#cecece) and increase the padding bottom (8px)..
