### ISSUE TITLE
Roadshow map: handle duplicate locations

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2485]
Only show old event location on the map if there is no upcoming one in the same city. See https://github.com/ampproject/docs/pull/2472

//cc @matthiasrohmer @morsssss

**Comment by morsssss** [comment]
Thanks! Sorry I didn't just do this myself; I assume I couldn't just do it with jinja, and so I thought I'd be wisest to leave this to those who'd know.

**Comment by sebil** [comment]
Created a PR that fixes the issue #2516

**Comment by morsssss** [comment]
Woo! Thanks so much!

Glad to see it was not complex after all :)

**Comment by sebil** [comment]
You're welcome!
