### ISSUE TITLE
Code snippet formatting feels claustrophobic 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2499]
### Current Behavior
Code snippets that require side scrolling don't have much room between the end of the snippet and the side of the snippet box. It makes it difficult to copy just the code snippet and not other elements on the page. 

Please also provide:
- Page link: [link](https://amp.dev/documentation/guides-and-tutorials/develop/interactivity/advanced-interactivity/?format=websites)
- [Screenshots](https://snag.gy/Za9he3.jpg)

**Comment by matthiasrohmer** [comment]
@sebil, can you please investigate with Longo?
