### ISSUE TITLE
SSR template tags clash with code examples in amp-analytics documentation

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2504]

**Comment by sebastianbenz** [comment]
The amp-analytics readme broke Nunjucks template rendering because of it's JSON code block:

```
...
[[30, 40], [40, 50]]
...
```

We should find a way to avoid these kinds of conflicts.

**Comment by matthiasrohmer** [comment]
Temporarily fixed by sort of escaping `[[` and `]]` in a ugly manner, will be permanently fixed by using a different set of template tags for SSR. Therefore prioritizing down to high.

**Comment by matthiasrohmer** [comment]
I'll take care of updating the template tags.
