### ISSUE TITLE
Verify health of commit on staging before deploying to production

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2510]
It would already saved us multiple times if the production build checks some pages (or all different templates) to render successfully on staging before starting a production build.

**Comment by sebastianbenz** [comment]
+1000

I started working on this here
<https://github.com/ampproject/docs/blob/future/integration-tests/Platform.spec.js>,
but haven't had time to finish it yet...

>

**Comment by matthiasrohmer** [comment]
Sebastian added smoke-tests by now 🙂
