### ISSUE TITLE
Make it possible to preview templates preview and browse them on Github

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2542]
With #2530 it's now possible to preview templates, e.g.: https://amp-dev-staging.appspot.com/documentation/templates/preview/websites/gallery/templates/gallery.amp.html

... and browser them on Github: https://github.com/ampproject/amp.dev/tree/future/templates.

We should integrate this into the template UI. @alankent has already started looking into this.

**Comment by CrystalOnScript** [comment]
@sebastianbenz @alankent Looks like this has been resolved. Okay to close?
