### ISSUE TITLE
Filtering doesn't prevent pages from being shown for other formats

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#2553]
Examples:

*   https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts/?format=email
*   https://amp.dev/documentation/guides-and-tutorials/learn/experimental/?format=ads

These pages are invisible in the menu on the left, which is good, but they can still be opened when another format is selected. This seems confusing, as it e.g. implies custom fonts are supported in emails, which is not the case.

**Comment by sebastianbenz** [comment]
Good point. Ideally, we should show a message saying that this component is not supported by email.

**Comment by matthiasrohmer** [comment]
... @sebastianbenz, was quicker. Was about to suggest the same thing, adding an *Important* callout that the document the user is looking at is not valid for the selected format.

Given that one could only come to this state by guessing links, I'd not prioritize this very high if that's okay for you.

**Comment by fstanis** [comment]
> Given that one could only come to this state by guessing links

I don't think this is entirely correct, it could be linked to from other pages. For example, the fonts one is linked to [from the Supported CSS page](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages/?format=email). In an ideal world, we'd remove those links with `[filter ...]`, but this is a difficult task, especially since they're valid technically.

**Comment by matthiasrohmer** [comment]
Oh you're right! Haven't thought of that - at least they are now not 404ing anymore.
