### ISSUE TITLE
Ugly TOC layout

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2556]
<img width="575" alt="Screen Shot 2019-07-18 at 18 24 03" src="https://user-images.githubusercontent.com/380472/61474624-526d0180-a989-11e9-9ce7-dce312b491b3.png">

https://amp.dev/documentation/components/amp-ad/?format=websites

**Comment by matthiasrohmer** [comment]
@tharders, all component reference documents have an inline h1 formatted as code, which breaks the TOC building and therefore should actually be stripped out during the import. At least that's my guess... 😉
