### ISSUE TITLE
Create an ecommerce landing page

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2565]
The first amp.dev search result for "amp ecommerce" Is https://amp.dev/documentation/examples/e-commerce/amp_for_e-commerce_getting_started. , which is a sample I quickly hacked together before AMPConf 2018. We definitely should have a better landing page for that topic!

Once we have it, we should delete the same page.

//cc @alankent @nainar @CrystalOnScript

**Comment by patrickkettner** [comment]
@sebastianbenz should this still be open?

**Comment by sebastianbenz** [comment]
No :-)
