### ISSUE TITLE
New translation: AMP Boilerplate Code

### ISSUE THREAD

**Issue by silverskyvicto** [ampproject/amp.dev#2569]
@CrystalOnScript 

I am thinking of translating this page.
Details are as follows.

- Language: ja
- File to translate: amp-boilerplate.md
- Full File
- Estimated travel time: 1 hours

**Comment by CrystalOnScript** [comment]
@silverskyvicto thanks for translating this page! While the original is imported from [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md), the translated file should still be placed [here](https://github.com/ampproject/amp.dev/tree/future/pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec).

@pbakaus can you confirm?

**Comment by pbakaus** [comment]
@CrystalOnScript correct, thank you!
