### ISSUE TITLE
Update to and pin latest Grow version for all environments

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2572]
Currently we don't enforce a specific Grow version via the Podspec which might cause problems as mentioned in #2512 and #2215 

Additionally we'll benefit from better build performance and the possibility to build a specific page by pod path which is nice for testing changed pages.

**Comment by patrickkettner** [comment]
@matthiasrohmer @sebastianbenz is this fixed with v1 grow being live now?
