### ISSUE TITLE
Empty whitespace on sample cards on mobile

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2574]
<img width="416" alt="Screen Shot 2019-07-22 at 09 30 55" src="https://user-images.githubusercontent.com/380472/61614232-7ec39f00-ac63-11e9-803c-53e930961d89.png">

https://amp.dev/documentation/examples/?format=websites

It's caused by `height: 100%` on `.ap-m-teaser-example .ap-m-teaser-card` which hides the nr of used components.

**Comment by matthiasrohmer** [comment]
@dlemm, please check if that still occurs with the updated example teasers.

**Comment by dlemm** [comment]
It's there too. I'll change it there.

**Comment by patrickkettner** [comment]
@sebastianbenz this seems to be fixed - can you confirm?
