### ISSUE TITLE
Broken JSON: /tr/documentation/components/amp-animation/

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2577]
https://amp.dev/tr/documentation/components/amp-animation/#development=1

**Comment by patrickkettner** [comment]
@sebastianbenz could you elaborate?

**Comment by sebastianbenz** [comment]
<img width="1105" alt="Screen Shot 2020-07-28 at 08 08 12" src="https://user-images.githubusercontent.com/380472/88625696-8ce3a100-d0a9-11ea-9a9e-28581355082e.png">

**Comment by patrickkettner** [comment]
fixed by #4239
