### ISSUE TITLE
Document `amp-video-docking` incompatible with iOS amp viewer

### ISSUE THREAD

**Issue by wassgha** [ampproject/amp.dev#2582]
Concerning the `amp-video-docking` experiment @alanorozco it seems like the feature is not supported on iOS when the page is served from the amp viewer.

See code below
https://github.com/ampproject/amphtml/blob/3e0c105bb4c3a29fdee079334d1d6f6868f02227/extensions/amp-video-docking/0.1/amp-video-docking.js#L404-L417

Referencing stackoverflow question:
https://stackoverflow.com/questions/56954113/amp-video-docking-doesnt-work-on-ios-when-served-from-google-amp-cache-url

**Comment by lucamago** [comment]
Hi, any update for this issue?

**Comment by patrickkettner** [comment]
this should have been closed by ampproject/amphtml#26064
