### ISSUE TITLE
Support small devices with 240px width

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2602]
The site should be usable for very small devices (240x320px). 

* content is wider than 240px on all pages
* blog post margins are way too big (that's even a problem on larger devices) //cc @westonruter @felixarntz 
* cards are too big

For testing: create a new custom device in devtools with: 

Width =240
Height = 320 
DPR = 1

**Comment by sebastianbenz** [comment]
Two other things: 

1. lang selector is over hamburger
2. menu content does not cover the whole height

<img width="247" alt="Screen Shot 2019-07-24 at 12 51 49" src="https://user-images.githubusercontent.com/380472/61788206-d869cc00-ae11-11e9-8c7d-3f11c889b285.png">

**Comment by tharders** [comment]
@sebastianbenz My feeling is that amp.dev is never visited by users with a device with below 320 pixel.
Is there anything that supports the request for such a small device size?
(Like analytics data, user complaints or lists of device sizes with current utilization rate)

**Comment by sebastianbenz** [comment]
@tharders in that case it's about amp.dev being a good web citizen and setting an example for inclusive design.

**Comment by LongoOfficial** [comment]
I would agree with @sebastianbenz that the site never should look broken at anytime. But we should not optimize for devices narrower than 320px.

**Comment by sebil** [comment]
See PR #2670

**Comment by westonruter** [comment]
I've improved the margins on https://blog.amp.dev/ by adding:

```css
@media (max-width:300px) {
    .ap-t-custom-content .ap--content {
        padding: 0;
    }
}
```

**Comment by sebastianbenz** [comment]
Thanks Weston!
