### ISSUE TITLE
Adjust roadmap import to new organisation scheme

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2604]
Something in the organisation of the ampproject/amphtml issues seems to have changed as a fresh import of the roadmap makes it look kinda sad.

![Bildschirmfoto 2019-07-24 um 15 11 41](https://user-images.githubusercontent.com/12857772/61796355-80d55b80-ae25-11e9-9bbd-5a9c48820ec7.png)
![Bildschirmfoto 2019-07-24 um 15 12 16](https://user-images.githubusercontent.com/12857772/61796361-85017900-ae25-11e9-90c5-9afc6c627159.png)

**Comment by sebastianbenz** [comment]
Closed in favor of #3594
