### ISSUE TITLE
Explicitly explain used components in examples

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#2621]
via @tharders: a lot of samples start with explaining what components are needed to get it running. For example Custom_Loading_Indicators.html is authored as following:

```html
  <!-- ## Setup -->
  <!-- Import the `amp-list` and `amp-mustache` components in the header -->
  <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
  <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
```

The problem is although the comment mentions both `amp-list` and `amp-mustache` only `amp-list` will end up on the sample documentation page 

![Bildschirmfoto 2019-07-26 um 10 56 08](https://user-images.githubusercontent.com/12857772/61939649-02e39280-af94-11e9-8aaa-a5c7607159e2.png)

That's because the parser is building sections from comments and and their directly following element.

This could either be fixed by introducing something that allows multiple elements to be shown with one comment or handle during authoring by rewriting the mentioned example to

```html
  <!-- ## Setup -->
  <!-- Import the `amp-list` ... -->
  <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
<!-- ... and `amp-mustache` components in the header -->
  <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
```

**Comment by matthiasrohmer** [comment]
@sebastianbenz, I guess that's known but we still wanted to somehow track this. Let us know what you think 🙂

**Comment by tharders** [comment]
Another option would be to simply add all tags to the next section until the next comment.
You could then use an empty comment to stop including tags.
But of course this change would change the output of lots of examples without changing the code in them.

The solution proposed by @matthiasrohmer  would maybe be a bit easier to implement if we only have a simple "join" comment between the tags

```html
  <!-- ## Setup -->
  <!-- Import the `amp-list` and `amp-mustache` components in the header -->
  <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
  <!-- ... -->
  <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
```

**Comment by sebastianbenz** [comment]
Yup. That bugged me as well in the past. Over time we ended up describing for each component what it's used for:

```
<!--
  We use a few AMP extensions to dynamically render a list of rooms. We use `amp-form` to send a filter request to the server.
-->
<script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
<!--
  We use `amp-mustache` as a template rendering engine for `amp-list`.
-->
<script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
<!--
  We use `amp-list` to dynamically show a list of rooms.
-->
<script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
```

I think that's actually a better approach than randomly importing a bunch of components. However, as you've noticed, not all examples have been migrated to this style...

**Comment by tharders** [comment]
I would prefer a smaller setup block with one text and then all imports in one code block.
On pages like https://amp.dev/documentation/examples/interactivity-dynamic-content/seatmap/?format=websites the setup block takes too much space without being really helpful at the early stage of the document. What the components do is better explained where they are used and not where they are imported. 
The idea from @matthiasrohmer was to explicitly include multiple tags in one section. That is not random and would not change anything without explicit usage. So no randomness.

**Comment by sebastianbenz** [comment]
By random I meant: people just added a bunch of extensions without explanation. Having to explicitly explain each dependency forces authors to explain why they import something. 

I agree with the setup block taking too much space though. It definitely would be nice to have a better solution here, but it's a low priority for me.

**Comment by matthiasrohmer** [comment]
@dlemm will have a look at problems like this when he tests Leo's work.
