### ISSUE TITLE
Inline sample previews: linebreaks get lost

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2624]
<img width="815" alt="Screen Shot 2019-07-26 at 16 17 07" src="https://user-images.githubusercontent.com/380472/61958028-d85bfe80-afc0-11e9-93c6-10a91b22e1ca.png">

https://amp-dev-staging.appspot.com/documentation/components/amp-accordion/?format=websites

**Comment by matthiasrohmer** [comment]
🙁 That's been me with

https://github.com/ampproject/amp.dev/blob/65f5347e9e179e40bb6e65c1b9863a5df1a5ad37/gulpfile.js/build.js#L381-L382
