### ISSUE TITLE
Desktop Safari: tool screenshots cover header

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2626]
https://amp.dev/documentation/tools/

<img width="839" alt="Screen Shot 2019-07-26 at 16 27 18" src="https://user-images.githubusercontent.com/380472/61958794-510f8a80-afc2-11e9-960e-74728748ea60.png">

**Comment by sebil** [comment]
Hey @sebastianbenz , I can't reproduce this issue on my machine
- MacOS 10.14.1
- Safari 12.0.1 

Can you please tell me on which MacOS + Safari versions the screenshot was taken?

**Comment by sebastianbenz** [comment]
OSX 10.14.5 (18F203)
Safari Version 12.1.1 (14607.2.6.1.1)

Sorry, should've added these earlier.

>

**Comment by sebil** [comment]
Thanks. Unfortunately I still can't reproduce the issue with exact the same MacOS and Safari versions (see screenshot)
Can you tell me the exact screen resolution or browser size with the screenshot was taken?

![Screenshot](https://user-images.githubusercontent.com/22053023/61972361-af983100-afe1-11e9-9d76-ea6e00103bfb.png)

**Comment by sebastianbenz** [comment]
@sebil can you try scrolling up.

**Comment by sebil** [comment]
Okay thanks, now I understand what you meant. First I thought it's initially overlaying.
Seems like a `z-index` issue. I'll fix it asap.

**Comment by sebil** [comment]
@sebastianbenz  see the commit above, that fixes the issue.
Likewise I could've set `translateZ(-200px)` to fix it, but that seemed not safe enough for me.
With `skew` and `scale` I tried to come as close as possible to the actual look.
PR is on the way...
