### ISSUE TITLE
AMP HTML Specification Japanese translation Proposal

### ISSUE THREAD

**Issue by silverskyvicto** [ampproject/amp.dev#2628]
@CrystalOnScript 

I am thinking of translating this page.
Details are as follows.

- Language: ja
- File to translate: amphtml.md
- Full File
- Estimated travel time: 4 hours

A short description of your contribution:

Type of contribution:
[ ] Guide
[ ] Tutorial
[ ] Example
[x] Translation 
[ ] Other (please specify)

Process
Read the contributing guide, then create a copy of [this template](https://docs.google.com/document/d/18i_lbQ-h-auYW2SwbWRuuu2_xhtU5XrjXlcCtj0sNeY/edit?usp=sharing) and fill in the proposal and outline sections. When you’ve finished, add the link to this issue and check the box for step one. A member of the AMP team will assign the ticket to themselves and work as your reviewer through the remaining steps. Thanks for contributing to AMP! 

[x] 1. Proposal created `link to proposal` 
[x] 2. Proposal approved.
[ ] 3. Draft complete.
[ ] 4. Draft approved.
[ ] 5. Pull request submitted.
[ ] 6. Pull request approved!

**Comment by CrystalOnScript** [comment]
This would be awesome! No need to add the translation into a google doc for this one if you're able to submit it as a PR. Thanks :)
