### ISSUE TITLE
amp-state is not a component 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2629]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
`amp-state` is a defined element used with the `amp-bind` component. However, much documentation calls `amp-state` a component. No instance of `amp-state` should be referred to as a component. 

**Which part of the site would that content live at?**
All references to amp-state 

**What's the type of content?**
Terminology update 

**Optional: Proposed information architecture**
existing is fine

**Comment by ChrisThorn10** [comment]
Hey! I'd like to take a stab at this one, please!
