### ISSUE TITLE
Reference metadata requirements

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp.dev#2632]
## 📖 Missing or out-of-date documentation

The AMP Story best practices guide (https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices/) should mention that aggregators such Google Search are likely to have metadata requirements for optimal placement (see https://developers.google.com/search/docs/guides/about-amp). (This doc will be updated shortly to call out the AMP Story requirements more strongly.)

**Comment by patrickkettner** [comment]
@sebastianbenz @CrystalOnScript is this still true?
