### ISSUE TITLE
Component reference docs do not specify used components

### ISSUE THREAD

**Issue by tharders** [ampproject/amp.dev#2644]
The pages imported from amphtml will not explicitly add required imports.
Since the automatic import does no longer work youtube videos, animated gifs or embedded iframes do no longer work.

For example the video on the following page is not shown:
https://amp.dev/documentation/components/amp-bind/?format=websites

I see different options how to handle this:
* Add the import expressions to the documents like `{% do doc.amp_dependencies.add('amp-iframe', '0.1') %}`
  (Not very nice syntax for a normal code editor)
* Add the imported components to the documents in a new `imports` prroperty in the frontmatter section (Better syntax for editors, but still easy to forget)
* We look for used components when importing the files and add the imports automatically
* We add automatic component import again for all pages (But then we maybe should only support those few standard components like `amp-youtube`, `amp-iframe`, `amp-anim`

@sebastianbenz , @matthiasrohmer What do you think?

**Comment by sebastianbenz** [comment]
I'm in favor of: 

> We add automatic component import again for all pages (But then we maybe should only support those few standard components like amp-youtube, amp-iframe, amp-anim

Otherwise it gets more complicated for translations which are stored on amp.dev.
