### ISSUE TITLE
Change amp-accordion component doc to clarify that disable-session-states is not valid for emails

### ISSUE THREAD

**Issue by tharders** [ampproject/amp.dev#2646]
At least when the documentation is viewed for format `email` it should be clear that the attribute `disable-session-states` is not valid for emails.
https://amp.dev/documentation/components/amp-accordion/?format=websites

There's a [filter syntax](https://github.com/ampproject/amp.dev/blob/future/contributing/documentation.md#format-filtered-paragraphs) on markdown level we can use to filter code sample and explanation.

This should be done for the english document in the amphtml repo and for the translations in this repo.

**Comment by sebastianbenz** [comment]
//cc @fstanis can you take a look?

**Comment by patrickkettner** [comment]
this was added
