### ISSUE TITLE
Invalid anchors in translations

### ISSUE THREAD

**Issue by tharders** [ampproject/amp.dev#2647]
Translations often do not have translated anchor ids.
But since the anchors point to the headlines in the documents they will not work without translation

For example on this page https://amp.dev/fr/documentation/components/amp-bind/?format=websites#white-listed-functions see the internal links "fonctions sur liste blanche"

Since links with anchors can also point to other files that are not translated, the links would have to change once the translation is ready.
It would be better to explicitly define anchor ids, so that they can be the same in all translations.

**Comment by sebastianbenz** [comment]
+1 to explicitly defining anchor ids. That's something we have to watch out for during code reviews. Theoretically, we could turn this into an automated check.
