### ISSUE TITLE
Figure out why images are missing from amp-story doc

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2652]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
Images are missing from the doc, we should figure out why. 

**Which part of the site would that content live at?**
https://amp.dev/documentation/components/amp-story/?format=websites

**Comment by tharders** [comment]
The reason is this ticket: https://github.com/ampproject/amp.dev/issues/2644
