### ISSUE TITLE
AMP Poll example not working

### ISSUE THREAD

**Issue by wassgha** [ampproject/amp.dev#2671]
The AMP Poll example ([here](https://amp.dev/documentation/examples/interactivity-dynamic-content/poll/?format=websites#asd)) is broken (form submission fails and can't connect to the server).

/cc @lluerich @sebastianbenz

**Comment by wassgha** [comment]
Fixed by #2676

**Comment by sebastianbenz** [comment]
Unfortunately, it's still broken.

**Comment by lluerich** [comment]
Datastore integration fixed by #2738
