### ISSUE TITLE
Update CSS Limits 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2681]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
[Defining CSS and Keyframes section in Triggering CSS animations](https://amp.dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations/?format=websites) specifies that inline styles have a 25,000 byte limit that is separate from the overall 50,000 byte style limit. 

What it should specify:
- Each use of inline style has a 1,000 bye limit
- Inline styles contribute to the same 50,000 byte limit used in the `<style>` tag. 

**Which part of the site would that content live at?**
https://amp.dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations/?format=websites

It should maybe be defined here as well:
https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages/?format=websites

**What's the type of content?**
Guie

**Optional: Proposed information architecture**
n/a

**Comment by sebastianbenz** [comment]
@CrystalOnScript is this still relevant?

**Comment by CrystalOnScript** [comment]
No longer needed. Closed.

**Comment by honeybadgerdontcare** [comment]
Resurrecting this as I can't find in documentation on amp.dev that there is a 50k limit for CSS and that it includes both `<style amp-custom>` and inline styles.

**Comment by CrystalOnScript** [comment]
This information is [here](https://amp.dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations/?format=websites#defining-css-and-keyframes)

But it should probably be [here as well](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/?format=websites#add-styles-to-a-page)

**Comment by honeybadgerdontcare** [comment]
Could we also explicitly mention that `Each use of inline style has a 1,000 bye limit`?

Perhaps `Inline styles. Inline styles count towards the 50,000 byte <style amp-custom> limit and have a 1,000 byte limit each.`. Though I'm sure you know a better way to phrase it.

**Comment by patrickkettner** [comment]
resolved via 9e043f7bff68e731b46278461f6eaa809925d53d
