### ISSUE TITLE
Hide translation warning on mobile

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2683]
It's not really actionable on mobile and takes away important screen space.

**Comment by sebastianbenz** [comment]
<img width="439" alt="Screen Shot 2019-08-01 at 21 35 04" src="https://user-images.githubusercontent.com/380472/62321985-44989f80-b4a4-11e9-91be-516fc2d35d07.png">

**Comment by tharders** [comment]
Fixed with #2957
