### ISSUE TITLE
The PWA is not full screen when installed

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#2691]
### Current Behavior

If you install the PWA, it's currently not full screen.

![Screenshot_20190802-153901](https://user-images.githubusercontent.com/250887/62378263-59287680-b53c-11e9-966d-df261fcfdceb.png)

Notice the blue header on top.

### Expected behavior/code

A full-screen, app-like experience.

### How do we reproduce the issue?

1. Open amp.dev on Chrome for Android.
2. Wait for ***Add amp.dev to Home screen*** to appear and then tap it.
3. Press "Add".
4. Close Chrome and open amp.dev from the home screen.

What browser are you using?
Chrome M76

What O/S are you using?
Android 9

**Comment by sebastianbenz** [comment]
Splendid timing #2684
