### ISSUE TITLE
amp.dev pages not AMP valid due to table markdown="span"

### ISSUE THREAD

**Issue by mcmd** [ampproject/amp.dev#2692]
### Current Behavior
Some pages in amp.dev are invalid due to an unexpected attribute in tables:

> `The attribute 'markdown' may not appear in tag 'table'. DISALLOWED_HTML`

- Page link: (two examples)
https://amp.dev/documentation/components/amp-audio/?format=websites
https://amp.dev/documentation/components/amp-ad/

### Expected behavior/code
Pages should be AMP valid

### How do we reproduce the issue?
Validate pages in current state, for instance, [this](https://validator.ampproject.org/#url=https%3A%2F%2Famp.dev%2Fdocumentation%2Fcomponents%2Famp-audio%2F%3Fformat).

**Comment by sebastianbenz** [comment]
@tharders is this caused by the table processor?

**Comment by matthiasrohmer** [comment]
It is. ☹ `markdown="1"` gets stripped out but with a value of `span` it doesn't seem to be.
