### ISSUE TITLE
New translation: CORS in AMP

### ISSUE THREAD

**Issue by Tom-Zhong** [ampproject/amp.dev#2707]
@CrystalOnScript 

Hi, I am thinking of translating this page.
Details are as follows.

- Language: @zh_CN
- File to translate: amp-cors-requests.md
- Full File
- Estimated travel time: 1 day

**Comment by CrystalOnScript** [comment]
This would be very much appreciated! :)

**Comment by patrickkettner** [comment]
closing as completed
