### ISSUE TITLE
Vietnamese Translation

### ISSUE THREAD

**Issue by duythanhvn** [ampproject/amp.dev#2717]
Hi @CrystalOnScript,

I'm insteresting this project. I want to translate this project into Vietnamese, please guide me how to start.

- Language: Vietnamese (vi_VN).
- Full files.
- Estimated time: 2,5 months.

Kindly regards,
Thanh Doan, Steve

**Comment by CrystalOnScript** [comment]
Hello @duythanhvn, thanks for taking an interest, this is so fantastic!!! I'd love to expand our support Vietnamese!! 

@sebastianbenz, @matthiasrohmer, and @pbakaus to weigh in on if we need to implement any site structural support.

**Comment by duythanhvn** [comment]
Hi team,

This is very exciting. I remember I met you at the AMP Roadshow Conference, December 2018 in Ho Chi Minh. Please tell me if I can support the project after your discussion.

Kindly regards,
Thanh Doan, Steve

**Comment by CrystalOnScript** [comment]
@duythanhvn - very excited to have this contribution, it should be no problem to support Vietnamese on amp.dev!!!

**Comment by patrickkettner** [comment]
closing as completed
