### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by GladysMaria** [ampproject/amp.dev#2744]
Hi team,

This is very exciting. I remember I met you at the AMP Conf, April  2019 in Tokyo. 
I want to translate this project into Spanish, please guide me how to get started.

Language: Spanish (@es).
Files: Courses.
Estimated time: 2 months.
Kindly regards,
@CrystalOnScript
Gladys García

**Comment by CrystalOnScript** [comment]
Hi @GladysMaria! I'm so excited you're interested in translating our courses!

The course files are located [here](https://github.com/ampproject/amp.dev/tree/future/pages/content/amp-dev/documentation/courses): once the file has been translated it should be placed next to the english file with `@es` appended to the name. These can be submitted in single files, batches, or all at once! Whatever works for you! 

If there's any confusion about the process or if you hit any roadblocks please reach out and we'll figure out how to move forward. 

Thanks so much for your contribution! Welcome to the team!! 

cc/ @morsssss

**Comment by morsssss** [comment]
Woooooooooooooooooo!

Let me know how this progresses :)

Also note that there's a PR right now to include compressed versions of all
three courses. The compressed versions don't contain much new language -
they're mostly about removing content for beginners. But they'll need
translating too...

**Comment by GladysMaria** [comment]
Hi you guys, I'm very excited to do this job. I will start on Sunday (2019-08-18). I let you know the progress!!
Thank you very much for letting me be part of the team!

**Comment by CrystalOnScript** [comment]
Hey @GladysMaria just wanted to check in to see how things were going and if we could help! :)

**Comment by morsssss** [comment]
@GladysMaria, I wanted to check in too!

**Comment by patrickkettner** [comment]
closing due to time, please do reach out if you have anything to share!
