### ISSUE TITLE
Align component documentation with AMP for Email spec

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#2745]
It seems the component documentation generally doesn't take into account AMP for Email restrictions, e.g. `[src]` not allowed in `amp-img` (ampproject/amphtml#23165) or `src` not allowed in `<amp-state>` ([SO question](https://stackoverflow.com/questions/57094275/is-src-attribute-allowed-in-amp-state/57096427)) which is causing confusion for users.

Would be good to review [the supported components](https://amp.dev/documentation/components/?format=email) and check if they match the [restrictions outlined in the spec](https://github.com/ampproject/amphtml/blob/master/spec/email/amp-email-components.md).

**Comment by TorbenTigges** [comment]
>causing confusion for users.
5 months later, still impossible to trust the documentation which is specifically for email (https://amp.dev/documentation/components/amp-bind/?format=email).
Client demands to use this function, as they've seen it in the documentary and articles with examples all over the web.
