### ISSUE TITLE
Improve new overview pages

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2756]
# Desktop

1. I don't understand the color coding on the card. What does the white space mean?

<img width="1141" alt="Screen Shot 2019-08-13 at 15 31 29" src="https://user-images.githubusercontent.com/380472/62945762-ad0a4980-bddf-11e9-9281-b58e75e77459.png">

2. Too much space between yellow dot and title

<img width="1078" alt="Screen Shot 2019-08-13 at 15 29 16" src="https://user-images.githubusercontent.com/380472/62945770-aed40d00-bddf-11e9-8219-58510920a177.png">

3. Open in playground should open the playground in the currently active format 

<img width="860" alt="Screen Shot 2019-08-13 at 15 29 05" src="https://user-images.githubusercontent.com/380472/62945771-af6ca380-bddf-11e9-969c-ccd3dbf5c43a.png">

4. "None" example listed below
5. It's not clear that these are sample highlights. My first impression would be that these are all samples on the page. Change to: "Featured examples"
6. There's a lot of space below "Learn AMP by Example". 

<img width="1532" alt="Screen Shot 2019-08-13 at 15 28 33" src="https://user-images.githubusercontent.com/380472/62945774-af6ca380-bddf-11e9-90ca-9356407fe61c.png">

7. Same feedback as before. Mixing cards and simple sample listing looks super weird. We should get rid of the cards.

<img width="352" alt="Screen Shot 2019-08-13 at 15 28 15" src="https://user-images.githubusercontent.com/380472/62945775-af6ca380-bddf-11e9-9200-eae0792d4888.png">

8. I find the heading "Categories" a bit confusing here. Either "Example categories" or something like: "Filter by category". It's also not clear that these are filters for the samples below (same is true for components and guides pages).  

<img width="420" alt="Screen Shot 2019-08-13 at 15 27 56" src="https://user-images.githubusercontent.com/380472/62945776-b0053a00-bddf-11e9-9c66-ff8f01198f72.png">

9. The last item should be "show more" that jumps to the matching category below.

<img width="565" alt="Screen Shot 2019-08-13 at 15 27 44" src="https://user-images.githubusercontent.com/380472/62945779-b1366700-bddf-11e9-819a-35ee6668c317.png">

10. Typography looks. bad of Categories heading vs sub headings. //cc longo

<img width="1105" alt="Screen Shot 2019-08-13 at 15 27 25" src="https://user-images.githubusercontent.com/380472/62945780-b1366700-bddf-11e9-9cee-a0d8cc6ee0a3.png">

# Mobile

11. Guides / Tutorial content is hidden in sidebar. All guides should be listed on the main page.
12. Guides / Tutorial content is hidden in sidebar. Highlighted and recent guide cards take up way too much space. They should be very condensed so that it's possible to quickly get to the main content.

13. Components: cards are way too big.
14. Components: amp-story should not be a highlighted component for websites.

**Comment by sebastianbenz** [comment]
Some quick feedback to the new overview pages. 

//cc @CrystalOnScript PTAL as well https://amp-dev-staging.appspot.com/documentation/guides-and-tutorials/

**Comment by sebastianbenz** [comment]
15. The page title should reflect the format: `AMP Website Examples` instead of `Examples`. It's already working for the Guides overview page.

**Comment by matthiasrohmer** [comment]
Thanks for your comments! I implemented the ones there's no discussion about in #2776. I'll leave 6., 7., 11. - 13. to @LongoOfficial.

14. is actually just unfortunate as it is made available for websites as well as stories: https://github.com/ampproject/amphtml/blame/master/extensions/amp-story/amp-story.md
