### ISSUE TITLE
Optimized AMP Diff 404's

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#2765]
I think this worked when I first tried it... but it doesn't for me now.

On [this page](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/server-side-rendering/?format=websites), try the ["click for a large version" link](https://amp.dev/optimized-amp-diff/). It's a broken link.

**Comment by CrystalOnScript** [comment]
Sorry for the accidental close: @sebastianbenz @matthiasrohmer any updates on this? Link womm

**Comment by sebastianbenz** [comment]
Still works for me.

>
