### ISSUE TITLE
SXG: Add alternate service providers

### ISSUE THREAD

**Issue by twifkak** [ampproject/amp.dev#2769]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
Should include a section with references to SXG service providers, as alternatives to the DIY method.

**Which part of the site would that content live at?**
 - https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/signed-exchange/
 - https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/publishing_checklist/

**What's the type of content?**
Presumably a bulleted list of links with short descriptions? I'll leave that up to you.

**Comment by rudygalfi** [comment]
Any generator services should suggest themselves for this list, as we may not be aware of them all. One I am aware of is [Cloudflare](https://blog.cloudflare.com/announcing-amp-real-url/).
