### ISSUE TITLE
🔱 Build fails on Windows

### ISSUE THREAD

**Issue by DerekNonGeneric** [ampproject/amp.dev#2790]
### Current Behavior

Currently, the README claims that this repository is able to be built with Windows as can be seen in the requirements section.

https://github.com/ampproject/amp.dev/blob/16994c3e6ec66739657307b1ded51df9f0d9e4cd/README.md#L21-L23

This, however, does not seem to be the case.

```
C:\Users\Derek\source\repos\amp.dev\examples\source\1.components\amp-web-push\static\sw.js:17
importScripts('/sw-toolbox/sw-toolbox.js');
^

ReferenceError: importScripts is not defined
    at Object.<anonymous> (C:\Users\Derek\source\repos\amp.dev\examples\source\1.components\amp-web-push\static\sw.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at routers.filter.forEach (C:\Users\Derek\source\repos\amp.dev\examples\index.js:39:57)
    at Array.forEach (<anonymous>)
    at loadRouters (C:\Users\Derek\source\repos\amp.dev\examples\index.js:37:8)
    at Object.<anonymous> (C:\Users\Derek\source\repos\amp.dev\examples\index.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

### Expected behavior/code

I expect to be able to build the amp.dev site locally and launch the dev server.
After running `npm install` and executing the `gulp bootrap` task, the build crashes.

### How do we reproduce the issue?

Please provide the steps to reproduce the issue:

0.  If necessary, spin up a Windows VM (10 or Server 2016)
0. Open an elevated PowerShell prompt
0. Install Grow
0. Install Node LTS
0. Globally install Gulp
0. Clone this repo (`future` branch)
0. Add the doc token environment variable
0. `npm install`
0. `gulp bootstrap`

What browser/terminal are you using? Windows PowerShell
What OS are you using? Windows 10

**Comment by sebastianbenz** [comment]
Thanks for reporting! I haven't got a windows vm ready for testing, but #2791 should fix it for now. However, there might be other hidden issues. Please report back if you encounter more!

**Comment by derekcecillewis** [comment]
Quite a few more paths required the `sep` treatment before I was able to get out of the woods on the above error, but one of the corrections necessary is featured in your PR. Merging would be an improvement over what you currently have, but I wouldn't close this issue if you do. There are indeed other hidden issues, as you mentioned. I haven't been able to resolve them yet, but I have a clever solution in mind. As far as I can tell, this doesn't seem like a small task. It seems like Windows hadn't been considered for a while.

**Comment by sebastianbenz** [comment]
>  It seems like Windows hadn't been considered for a while.

TBH, we never considered it as the static site generator we use ([Grow](https://grow.io)) doesn't support  window (this might have changed). Did you manage to get grow working on windows?

Sorry, for not mentioning that earlier, I wasn't aware either.

**Comment by derekcecillewis** [comment]
Wow, I hadn't even considered that! But believe it or not, I did manage to get it working well enough to not suspect that it might be the problem. 🤔

![grow-develop](https://user-images.githubusercontent.com/17770407/63351593-868f6580-c32d-11e9-85ba-2fad9f981dd3.png)
![Screenshot 2019-08-20 09 31 00](https://user-images.githubusercontent.com/17770407/63351615-8f803700-c32d-11e9-8359-ec9a5b47be39.png)
![Screenshot 2019-08-20 09 32 14](https://user-images.githubusercontent.com/17770407/63351614-8f803700-c32d-11e9-817d-1c77e412ce4e.png)

**Comment by derekcecillewis** [comment]
@sebastianbenz would you like me to submit a PR that (hopefully temporarily) updates the README to clarify that Windows is not a currently supported OS for those intending to conduct development on this repository?

**Comment by sebastianbenz** [comment]
@derekcecillewis yes please. Thanks a lot for looking into this!

**Comment by tharders** [comment]
Closing this issue since the readme now indicates that windows is not supported and there is currently no plan to support windows in the near future.
