### ISSUE TITLE
Redirect for ampproject.org faqs missing

### ISSUE THREAD

**Issue by tharders** [ampproject/amp.dev#2796]
There are still pages on the old website that do not redirect to amp.dev. For example https://www.ampproject.org/support/faqs

I would think that all requests to ampproject.org should result in a redirect to amp.dev.

Is there some kind of log or tracking to find out which pages are still reachable?
We could create specific redirects for those pages then.

We can also add a default redirect to the amp.dev homepage for everything that has no special redirect.

**Comment by matthiasrohmer** [comment]
I fixed this with #2718, just never merged to production.

**Comment by sebastianbenz** [comment]
Here's a list of pages not yet redirected: https://gist.github.com/sebastianbenz/d72e5144a4642ac2b6ff87ccc7204a70

Got this from search console by checking the latest 1000 pages in search for redirects.

**Comment by sebastianbenz** [comment]
Seems like the blog is not yet redirecting (//cc @westonruter / @amedina) + FAQs (which has been fixed already) + this page: https://www.ampproject.org/docs/troubleshooting/amp-cache-debugging

**Comment by westonruter** [comment]
How are the FAQs related to `blog.amp.dev`? I mean, is there anything needed on the `blog.amp.dev` side of things?

**Comment by sebastianbenz** [comment]
@westonruter the old blog doesn't redirect to amp.dev. See links here: https://gist.github.com/sebastianbenz/d72e5144a4642ac2b6ff87ccc7204a70

**Comment by westonruter** [comment]
Closing the loop on this… the blog was on two domains, and the URLs here are not involved in what was migrated from amphtml.wordpress.com to blog.amp.dev (AFAIK).

**Comment by patrickkettner** [comment]
fixed in #4226
