### ISSUE TITLE
🐛 amp-img Example: Specifying a fallback image

### ISSUE THREAD

**Issue by derekcecillewis** [ampproject/amp.dev#2800]
### Current Behavior
The image doesn't fit or fill its container.

Please also provide:
- Page link: https://amp.dev/documentation/components/amp-img/#example:-specifying-a-fallback-image
- (Optional) Screenshots / videos

![Screenshot 2019-08-20 18 37 19](https://user-images.githubusercontent.com/17770407/63389821-f5df7680-c37a-11e9-8ba5-ed0c91586b63.png)

### Expected behavior/code
Fit and fill the container.

### How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Visit the link provided
2. Adjust browser width as necessary

What browser are you using? Chromium
What O/S are you using? Windows 10

**Comment by sebastianbenz** [comment]
This is working as intended as the image doesn't specify a responsive layout.

**Comment by derekcecillewis** [comment]
I understand that the goal of this example is to demonstrate the use of fallback images and not necessarily responsive layouts. However, [responsive layouts and fallback images are not mutually exclusive](https://jsbin.com/dovecej/edit?html,output), so having the example look ugly seems unnecessary. I could be missing something, though. Are integration tests done with these examples that require the behavior being demonstrated to be isolation?
