### ISSUE TITLE
The prod sitemap_grow.xml contains the test pages

### ISSUE THREAD

**Issue by tharders** [ampproject/amp.dev#2802]
The [grow sitemap](https://amp.dev/sitemap_grow.xml) contains the test pages like https://amp.dev/tests/examples/default_settings/ although they are not deployed on prod.

We use a filter to exclude those pages, but this does not exclude those pages from the sitemap. Pleas note that the build also uses a filter to generate only a specific locale, where we need to have a sitemap for "all" pages.

**Comment by sebastianbenz** [comment]
This happens here: https://github.com/ampproject/amp.dev/blob/future/frontend/templates/layouts/sitemap.xml#L3

Do we have a generic way to iterate over all prod pages?
