### ISSUE TITLE
Error pages do not support SSR

### ISSUE THREAD

**Issue by tharders** [ampproject/amp.dev#2803]
The navigation contains a server side rendering command for the "documentation" -> "examples": 
`AMP [= format|capitalize =] Examples`
This is not evaluated for the error pages like [404](https://amp.dev/notfound/)

![image](https://user-images.githubusercontent.com/6458408/63427210-e90f6100-c414-11e9-8966-955c2edcfe4d.png)

**Comment by sebastianbenz** [comment]
We don't use the format in the examples any more, so it's not an issue for now.
