### ISSUE TITLE
amp-script documentation for inline scripts needs updating

### ISSUE THREAD

**Issue by alankent** [ampproject/amp.dev#2807]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
The page https://amp.dev/documentation/components/amp-script/?format=websites contains an example of `amp-script` where the script is inlined. The example needs updating to match the final released version of `amp-script`.

@fstanis said "You need a CSP with the hash to use amp-script inline."

Also the version where the script is in an external file works, but using `textContent += ...` has a side effect of destroying the `<button>` element so you can only click on it once. Keeps the example short though, so not end of the world.

**Which part of the site would that content live at?**
URL given above.

**What's the type of content?**
Referenced docs out of date due to changes made to `amp-script` before release.

**Comment by fstanis** [comment]
To clarify on CSP: this requirement was introduced in ampproject/amphtml#23691.

When using `<amp-script>` with either:

*   An inline script via `script="some-id"`
*   `src` attribute set to a cross-origin URL

...then your document must contain a CSP-line `<meta name="amp-script-src" content="...">` entry in `<head>`. The `content` attribute works in a similar way to [script-src CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src), specifically the `'<hash-algorithm>-<base64-value>'` type (the only algorithm supported is `sha384`). It can contain multiple space-separated hashes (one for each script).

For example, if you have `<script id="hello" type="text/plain" target="amp-script">console.log('hello')</script>`, you would:

1.  Extract the script content: `console.log('hello')`
2.  Calculate the SHA384 sum for it: `2449d3149fb10f687794aeb1f9794d9b07dc9f585743439ca7d2339ef2bf75a419e8e887a5862efabe724746c29ae83c`
3.  Use `base64url` encoding: `JEnTFJ-xD2h3lK6x-XlNmwfcn1hXQ0Ocp9IznvK_daQZ6OiHpYYu-r5yR0bCmug8`
4.  Add `sha384-` prefix: `sha384-JEnTFJ-xD2h3lK6x-XlNmwfcn1hXQ0Ocp9IznvK_daQZ6OiHpYYu-r5yR0bCmug8`
5.  Put it in a `<meta>` tag: `<meta name="amp-script-src" content="sha384-JEnTFJ-xD2h3lK6x-XlNmwfcn1hXQ0Ocp9IznvK_daQZ6OiHpYYu-r5yR0bCmug8">`
6.  Add this `<meta>` tag to head.

**Comment by fstanis** [comment]
If using node.js, this function will perform steps 2-4 for you:

```js
const crypto = require('crypto');

function generateCSPHash(script) {
  const hash = crypto.createHash('sha384');
  const data = hash.update(script, 'utf-8');
  return 'sha384-' + data.digest('base64')
    .replace(/=/g, '')
    .replace(/\+/g, '-')
    .replace(/\//g, '_');
}

generateCSPHash("console.log('hello')");
```

**Comment by fstanis** [comment]
You need to base64 encode the raw bytes, not the hex string - sorry that I wasn't clear.

So you need to do hex -> binary -> base64 instead of hex -> base64. In a terminal, you can use `xxd` to decode the hex:

```bash
echo "2449d3149fb10f687794aeb1f9794d9b07dc9f585743439ca7d2339ef2bf75a419e8e887a5862efabe724746c29ae83c" | xxd -r -p - | base64
```

This will give you `JEnTFJ+xD2h3lK6x+XlNmwfcn1hXQ0Ocp9IznvK/daQZ6OiHpYYu+r5yR0bCmug8` so you'd still need to replace `+` with `-` and `/` with `_` to turn it into URL format.

(of course, ideally you can use something that just goes directly to base64 instead of hex, like the node.js snippet I posted)

**Comment by fstanis** [comment]
ampproject/amp-toolbox#465 adds support for generating this automatically by the amp-optimizer.

**Comment by choumx** [comment]
https://github.com/ampproject/amphtml/pull/24242 makes amp-script documentation a bit clearer.

**Comment by choumx** [comment]
@webdevmike Yea, copy/pasting can inadvertently include three zero-width spaces that we use to identify "user errors" at runtime. The fixed string substitutions in the above PR should avoid this now. Thanks for your patience!

**Comment by webdevmike** [comment]
@choumx That makes sense, Thanks for the explanation!

**Comment by vishnu323** [comment]
> If using node.js, this function will perform steps 2-4 for you:
> 
> ```js
> const crypto = require('crypto');
> 
> function generateCSPHash(script) {
>   const hash = crypto.createHash('sha384');
>   const data = hash.update(script, 'utf-8');
>   return 'sha384-' + data.digest('base64')
>     .replace(/=/g, '')
>     .replace(/\+/g, '-')
>     .replace(/\//g, '_');
> }
> 
> generateCSPHash("console.log('hello')");
> ```

**Comment by vishnu323** [comment]
what about when script is more than online.its works when the script is online.but more than online.the generated sha384 is not correct.may i know on more example is the script is more than online
