### ISSUE TITLE
Broken link to amp-carousel docs from amp-carousel example

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#2816]
## Bug Report

On https://amp.dev/documentation/examples/components/amp-carousel/

![image](https://user-images.githubusercontent.com/134745/63610822-37486f80-c58f-11e9-8664-129fcf1327bd.png)

The link to `amp-carousel` is https://amp.dev/documentation/components/reference/amp-carousel.md?format=websites

But this is a 404.

It should actually be https://amp.dev/documentation/components/amp-carousel/?format=websites

**Comment by sebastianbenz** [comment]
This applies to all internal links defined in samples. This is most likely caused by the recent change to the way grow processes links.

@tharders does the link checker apply to examples?

**Comment by sebastianbenz** [comment]
Correction: all links to component reference docs are broken from samples as well as guides.

**Comment by sebastianbenz** [comment]
Versioning the reference doc files caused this. All component doc links need to add the version `amp-bind.md` -> `amp-bind-v0.md`. //cc @pbakaus

**Comment by pbakaus** [comment]
My bad, apologies, and thanks to @sebastianbenz for fixing it quickly!
