### ISSUE TITLE
Search promoted JSON files are not generated during build

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2819]
See temporary fix: https://github.com/ampproject/amp.dev/commit/8f272c26edd58b5255d7a0c197d0636e4e62db08

**Comment by tharders** [comment]
The file is generated together with the grow pages.
But the buildPages job only adds dist/pages to the tar.
The buildPrepare job adds all dist/ objects, but at this stage the json is not generated.
@sebastianbenz Not sure what is the best approach here. It's not really nice to add only this specific path to the tar command for buildPages, but it should do the trick.
Do you have any other idea?

**Comment by sebastianbenz** [comment]
Yeah, I don't see a good way either. We do something similar already for the sitemap so we can maybe handle these together.
