### ISSUE TITLE
Enable the Chrome Origin Trial for dynamic autoplay delegation

### ISSUE THREAD

**Issue by wassgha** [ampproject/amp.dev#2825]
Need to add a token as a `meta` to enable the Chrome Origin Trial for Dynamic Autoplay Delegation on the `amp.dev` domain (fixes broken autoplay on a lot of iframe based video components)

**Comment by sebastianbenz** [comment]
@wassgha can we close this issue now?

**Comment by wassgha** [comment]
Nope, there's an issue with the Chrome Origin Trial and this hasn't been
resolved yet

**Comment by patrickkettner** [comment]
closing as this feature is [no longer being pursued](https://www.chromestatus.com/feature/4588736224428032)
