### ISSUE TITLE
Search: empty search window if no result is found

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2829]
Steps to reproduce: 

1. enter `amp-scri` as search query 
2. wait 
=> no result is shown, only an empty screen

<img width="1193" alt="Screen Shot 2019-08-24 at 20 51 58" src="https://user-images.githubusercontent.com/380472/63641616-7c64c280-c6b1-11e9-9cec-0cf7310e6210.png">

//cc @sebil @tharders

**Comment by tharders** [comment]
I cannot reproduce this issue.
When no results are found I get the appropriate message.
Maybe it is a duplicate of https://github.com/ampproject/amp.dev/issues/2817
Feel free to reopen this issue with more details if you are able to reproduce.

**Comment by sebastianbenz** [comment]
Investigated a bit further. It's not a duplicate of #2817 (the request does not fail). What I've noticed  is that after 10s the "no results found message" appears.

**Comment by tharders** [comment]
Problem is, that the autocomplete suggestions are over the error message.

**Comment by sebastianbenz** [comment]
Good catch!
