### ISSUE TITLE
Search: keyboard navigation broken on safari

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2834]
Steps to reproduce:

1. a search query
2. press tab
=> focus leaves input but does not move to search results

Safari: Version 12.1.2 (14607.3.9)

**Comment by sebil** [comment]
I've found this: https://stackoverflow.com/a/1914496/11983004

> By default tab-access is disabled in safari(!). To enable it, check "Preferences > Advanced > Press tab to highlight each item on a page".

I think everybody who's a keyboard user on safari should know this, therefore I wouldn't dive deeper in this.

**Comment by sebastianbenz** [comment]
interesting! thanks for figuring this out.
