### ISSUE TITLE
amp-script password tutorial: minor tweaks for clarity

### ISSUE THREAD

**Issue by philkrie** [ampproject/amp.dev#2837]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
[Add custom JavaScript to AMP pages with amp-script](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial/?format=websites) (password tutorial)

With the general release of amp-script, we'd like to train our vendor team up on it. I went through the two tutorials for amp-script on amp.dev and noticed some minor issues that could confuse newcomers.

 **1. Title Similarity** 
This page has a very similar title to [Include custom JavaScript in AMP pages
](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/?format=websites) which is confusing when viewing them in the Guides and Tutorials [page](https://amp.dev/documentation/guides-and-tutorials/?format=websites). Which one should I start with? One is an interactive tutorial, and the other a technical guide.

**2. git clone snippet not working**
git clone git@github.com:CrystalOnScript/vanilla-js-amp-script.git resulted in permission denied for me. I just used git clone https://github.com/CrystalOnScript/vanilla-js-amp-script.git

**3. src attribute must point to an absolute URL info note**
This isn't mentioned in the amp-script official doc, and this also fails to mention the "script" attribute as a possibility

**4. amp-script experimental warning still present**
Should be updated or removed

**5. initCheckPassword(passwordBox); placement**
This is noted at very bottom, after telling the user to refresh the page and that everything should work, and after the animated GIF. If you don't scroll all the way down you might miss it and get confused.

**6. Consider removing npm/node dependency**
The form endpoint requires this to be served from localhost. It isn't relevant for the purposes of teaching amp-script, since the JS could just be written in the HTML file. Instead of submitting the form to an actual endpoint, you could just have inputs and then mock a success message using amp-script or even just an action. The additional potential setup time (installing packages, installing node) is all to accommodate amp-form, instead of amp-script which is the point of the tutorial. node isn't required to teach this lesson (using amp-script to manipulate the DOM based on user input)

Minor Issues
**Create a directory titled js at the root of your repositior and add the script.js file.**
"Root of your repository" is ambiguous, given that the user is deploying the application from a sub directory within the git repo, and it needs to be placed within that sub directory.

**7. The first initCheckPassword(element) snippet is missing a closing bracket**

**Comment by fstanis** [comment]
FWIW, when that guide was written, inline scripts weren't supported. I agree that inline script allows us to simplify it.

**Comment by CrystalOnScript** [comment]
@philkrie - thanks for your suggestions and catches on the tutorial! I've updated most things, minus the node dependency. While Web Server for Chrome may be easier, we do not want to force readers to use a specific browser to follow the tutorial. Inline amp-script is still up in the air, but I will consider revising the tutorial when it becomes more clear. Thanks again!
