### ISSUE TITLE
amp-script documentation incomplete, content is split across articles

### ISSUE THREAD

**Issue by philkrie** [ampproject/amp.dev#2838]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**

[amp-script docs
](https://amp.dev/documentation/components/amp-script/)
[Include custom JavaScript in AMP pages
](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/?format=websites)
[Include custom JavaScript in AMP pages
](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/?format=websites)

The amp-script documentation is very short and misses a lot of the important details and limitations that will likely frustrate developers when they encounter them while developing.

The [Include custom JavaScript in AMP pages
](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/?format=websites) article contains **critical** information about amp-script (5 second fetch limit, 1 second manipulation limit, initialization limitations). The [password amp-script tutorial](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial/?format=websites) has information that is absolutely critical as well, such as the necessity for absolute URL paths for amp-script src, something not mentioned in the amp-script documentation.

These three pages each contain a part of the spec, when the amp-script docs should have all of it.

### Suggested organization:
[amp-script docs](https://amp.dev/documentation/components/amp-script/) needs to have the full technical spec to avoid confusion. As mentioned in #2837 , [Include custom JavaScript in AMP pages
](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/?format=websites) and [Add custom JavaScript to AMP pages with amp-script](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial/?format=websites) have confusing, similar titles. Since [Include custom JavaScript in AMP pages
](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/?format=websites) contains a lot of amp-script technical info not present in the amp-script doc, I think it should be deleted all together and its content added to the amp-script doc. 

The tutorial should be renamed and updated per my suggestion in #2837 

### amp-script docs minor tweaks
Specifically for what is already in the amp-script doc, I have some suggestions:

1. 

> Maximum of 10,000 bytes per amp-script element that uses a local script via script[type=text/plain][target=amp-script].
> Maximum total of 150,000 bytes for all amp-script elements on the page.

Compared to the rest of the AMP documentation, using bytes instead of kB seems odd. Also something something I've forgotten how to count that low.

2. 

> Same-origin src must have Content-Type: application/json.
> Cross-origin src and local scripts must have matching script hashes in a meta[name=amp-script-src] element in the document head. A console error will be emitted with the expected hash string. For example:

This is not clear. The first point isn't even true for localhost as far I'm aware (in the tutorial, the app is deployed to localhost and it worked with Content-Type:application/javascript). The same goes for the hash, which is NOT mentioned in the tutorial. I'm aware that localhost could be an exception for this, but the tutorial should at least mention it.

3.

What are "script hashes"? Is that a hash of the script's content, or the script name? In the example it appears to be the name:
```javascript
 <!-- Cross-origin src requires hash: sha384(example.js) == abc123 -->
 <!-- Local script requires hash: sha384(#myScript) == def456 --> 
```
The documentation should be more clear, because realistically, names like "example.js" wouldn't seem to form a great hash if we are concerned with security, given that many js files share the same name (like app.js, or core.js).

**Comment by CrystalOnScript** [comment]
@philkrie - thanks again for the suggestions! A lot of these issues are related to the reference documentation, which is located in the AMPHTML repository. I've opened an [issue there](https://github.com/ampproject/amphtml/issues/24378) and addressed what I could in the guide and tutorial. Closing this issue.
