### ISSUE TITLE
amp.dev - add voting for feature requests and 3P vendor support

### ISSUE THREAD

**Issue by rmwfranchise** [ampproject/amp.dev#2844]
## Feature Request

Add a voting forum on amp.dev. This should be a voting / reddit styled UX where users can upvote 3P solutions or feature requests. Voting would happen via Github's reactions API (on an amp.dev page). User's could use their Github account for voting.

**Comment by sebastianbenz** [comment]
To add a few more details:

* voting can be enabled for ampproject/amphtml issues via tag, e.g.: `feature-request`. 
* users can vote via 👍 (these would be mirrored to Github reactions on issues). It probably makes sense to only allow up-voting. 
* current voting can be seen on either a dedicated page or a new column in the [amp.dev roadmap](https://amp.dev/community/roadmap/).

Adding @nainar @ampproject/wg-outreach for feedback.

**Comment by sebastianbenz** [comment]
We decided to not target this right now (unless there are volunteers) as this functionality is already covered by github issues.
