### ISSUE TITLE
Add documentation for the new amp-megaphone component

### ISSUE THREAD

**Issue by wassgha** [ampproject/amp.dev#2845]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
Documentation and example usage of the newly implemented `amp-megaphone` extension

**Which part of the site would that content live at?**
Reference docs and examples

**What's the type of content?**
API docs

**Comment by sebastianbenz** [comment]
The documentation will be pulled in from the md file once the component has been released. I don't think that we need a separate sample for this. Instead turn the samples in the md file into a executable ones using the [inline preview mode](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting/?format=websites#preview-code-samples).

**Comment by wassgha** [comment]
Sounds good, closing then.
