### ISSUE TITLE
Broken example for `amp-base-carousel`

### ISSUE THREAD

**Issue by wassgha** [ampproject/amp.dev#2850]
## 📖 Missing or out-of-date documentation

The example link [here](https://amp.dev/documentation/components/amp-base-carousel/) leads to a 404 page.

**Comment by matthiasrohmer** [comment]
There is no dedicated example for `amp-base-carousel` yet but only the one for `amp-carousel`: https://amp.dev/documentation/examples/components/amp-carousel/?format=websites

One for `amp-base-carousel` would need to be created while documenting all the new features it brings.

**Comment by patrickkettner** [comment]
closing as the link was removed
