### ISSUE TITLE
Versioned docs lead to GitHub 404

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2857]
Click on v1: https://amp-dev-staging.appspot.com/documentation/components/amp-carousel/?format=websites

Not sure what caused this, might be #2853.

//cc @tharders @pbakaus

**Comment by tharders** [comment]
@sebastianbenz Before yesterday we had no components with multiple version docs. So this is the first time we see this toggle at all. I suspect that the problem exists a little longer.
But currently I have no idea why a relative link would be converted to a github link.
