### ISSUE TITLE
Autocomplete should offer link to article

### ISSUE THREAD

**Issue by tewdin** [ampproject/amp.dev#2864]
I don't know what is the point of having autocomplete search if there is no way to use results as links instead of filling input field. If I already found what I was looking for then why I want to go to result page? Normally, top three results are all what visitor needs (and of course visitor can press submit button if (s)he really wants to go result page).

I would greatly appreciate it if it were possible to create a link from the search results as you type. The visitor could immediately continue to go wherever they wanted to go.

**Comment by matthiasrohmer** [comment]
Thanks a lot for your feedback, makes sense 🙂
