### ISSUE TITLE
Document imports: escape nunjucks delimiters

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2865]
The following delimiters need to be escaped after importing:

```
        blockStart: '[%',
        blockEnd: '%]',
        variableStart: '[=',
        variableEnd: '=]',
        commentStart: '[#',
        commentEnd: '#]',
```

Example where it's currently breaking: http://localhost:8080/documentation/guides-and-tutorials/optimize-and-measure/amp-managing-user-state/?format=websites

**Comment by sebastianbenz** [comment]
We also have to manually fix all already imported and translated versions of `amp-managing-user-state`.

**Comment by matthiasrohmer** [comment]
Filed mozilla/nunjucks#1240 as nunjucks currently has a strange behaviour around custom tags with raw blocks.

**Comment by sebastianbenz** [comment]
Are there any workarounds possible?

**Comment by matthiasrohmer** [comment]
Jep, the one we've talked about will work for now:

```
{{ '[% raw %]' }}
[= 'Escaped.' =]
{{ '{% endraw %}' }}
```

I am working on a PR for this.
