### ISSUE TITLE
Managing User State Article is broken (500 error)

### ISSUE THREAD

**Issue by caiotomazelli** [ampproject/amp.dev#2883]
### Current Behavior
This [link](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-managing-user-state/?format=websites) is returning a 500 error

Please also provide:
- [Page link](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-managing-user-state/?format=websites)
- (Optional) Screenshots / videos
![image](https://user-images.githubusercontent.com/9386901/64212768-cd7a7080-ce80-11e9-82f4-51b979e51dc9.png)

### Expected behavior/code
I expected a response with 200 status code

### How do we reproduce the issue?
Visit the link provided above 

Please provide the steps to reproduce the issue:

1. Visit amp.dev
2. In the "Guides and tutorials" section, under "Optimize & Measure", click on "Manage non-authenticated user state with AMP"
3. The 500 error page will show up

What browser are you using? Chrome
What O/S are you using? Debian Linux / Chrome OS

**Comment by sebastianbenz** [comment]
Fixed
