### ISSUE TITLE
Favorite Button Example is not working

### ISSUE THREAD

**Issue by taytus** [ampproject/amp.dev#2886]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be updated**

Playgroundd example of this tutorial: https://amp.dev/documentation/examples/interactivity-dynamic-content/favorite_button

The example works on the docs but not in the playground

**Which part of the site would that content live at?**

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Finteractivity-dynamic-content%2Ffavorite_button

**What's the type of content?**
Example

**Comment by sebastianbenz** [comment]
Thanks for reporting. Looks like a CORS issue:

```
Access to fetch at '
https://amp.dev/favorite-with-count?__amp_source_origin=https%3A%2F%2Fplayground.amp.dev'
(redirected from '
https://playground.amp.dev/favorite-with-count?__amp_source_origin=https%3A%2F%2Fplayground.amp.dev')
from origin 'https://playground.amp.dev' has been blocked by CORS policy:
Response to preflight request doesn't pass access control check: The value
of the 'Access-Control-Allow-Origin' header in the response must not be the
wildcard '*' when the request's credentials mode is 'include'.
```

>
