### ISSUE TITLE
[translation-Korean] on 'Add translations' page

### ISSUE THREAD

**Issue by biyott** [ampproject/amp.dev#2891]
original:
- \documentation\guides-and-tutorials\contribute\translations.md

I'll add below:
- \documentation\guides-and-tutorials\contribute\translations@ko.md
- Korean
- Full File
- Within 2 days.

 @CrystalOnScript

**Comment by biyott** [comment]
#2892 I completed translate and made pull requests.
@CrystalOnScript

**Comment by patrickkettner** [comment]
thanks for the work!
