### ISSUE TITLE
Component amp-live-list When insert amp-playbuzz

### ISSUE THREAD

**Issue by gian88** [ampproject/amp.dev#2894]
I Have the following problem: When the amp-live-list detect a new item and show me the button of the updated when make click the button and insert the component the amp-playbuzz the component not show me anything because I need insert on the head of the page a custom scripts  **script async custom-element="amp-playbuzz" src="https://cdn.ampproject.org/v0/amp-playbuzz-0.1.js"></script>** but I have a problem the amp system no permitted manipulate DOM to insert these script, and cant insert the script when load the page because if no exist the component amp no validate because I am importing a script by not used. I Need some help how insert the library in the amp-live-list. The problem is same when add in live the component facebook, twitter etc.

**Comment by sebastianbenz** [comment]
Please answer these questions on [stackoverflow using the amp-html tag](https://stackoverflow.com/search?q=user:967+[amp-html]). 

When using amp-live-list you have to import all required components in advance.
