### ISSUE TITLE
Versioned component documentation - support for different versions per format

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#2895]
## Bug Report

Related to: #2770

Some component versions may not be available for all formats, e.g. `amp-carousel` 0.2 is not currently supported for emails.

I made ampproject/amphtml#24340 to correct this in the docs, so `extensions/amp-carousel/amp-carousel.md` (0.2 docs) now doesn't list email in formats, but `extensions/amp-carousel/0.1/amp-carousel.md` (0.1 docs) does. This follows the *New version, doc still in top level folder, old docs in version sub-folders* variation described in #2770.

### Current Behavior

Based on testing locally, this change makes amp-carousel docs hidden all together for emails.

![image](https://user-images.githubusercontent.com/250887/64353562-de98be00-cff5-11e9-8d78-01eeac09053f.png)

### Expected behavior/code

When email is selected as format, the docs for amp-carousel should display 0.1 docs and hide the version selector. Alternatively, the docs should default to 0.1 version docs.

**Comment by pbakaus** [comment]
This is actually going to be quite difficult to achieve (but I agree with your proposal).

@sebastianbenz @matthiasrohmer I spent half an hour investigating this, and it's non-trivial, so will have to delegate to one of you. This will likely need to be done through `component-sidebar.j2` and the actual importer, and it's complicated by the fact that you will have to combine SSR templating (Nunjucks) and Jinja2.

Basically, there's a loop right now that looks like this:

```
{% for component in components if component.is_current %}
...
  [% if format in {{ formats|tojson }} %]
    <li {% if activeDocument %}autoscroll {% endif %} class="nav-item {% if activeDocument %}active {% endif %} level-2">
      <a class="nav-link" href="{{ component.url.path }}">{{ component.title }}</a>
    </li>
  [% endif %]
...
{% endfor %}
```

Currently this loop skips component md files that don't have `is_current: true` in the front matter, but this logic is too naive as it does not respect formats. What one of you will need to do:

1. Something like `is_current_for: ['email', 'ads']`, which needs to be generated in the importer
2. Remove the conditional check in the Jinja2 for loop
3. inside the loop, wrap everything with a Nunjucks if statement, checking whether the current format is in the `is_current_for` set.

Can one of you take a look? If not, I'll get to this when I'm done with performance reviews :)

**Comment by sebastianbenz** [comment]
This really is getting complicated. I can take a look next week. I'm already familiar with the code.

**Comment by pbakaus** [comment]
@sebastianbenz thanks much!
