### ISSUE TITLE
All sample styles are broken

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2901]
For example: https://amp.dev/documentation/examples/interactivity-dynamic-content/favorite_button/

The `.favorite-button` selector is no longer present in the CSS.

**Comment by sebastianbenz** [comment]
This has been caused by: https://github.com/ampproject/amp.dev/pull/2411 

Seems like transformation accidentally removes the styles.

//cc @fstanis

**Comment by fstanis** [comment]
Potentially related issue: cheerio replaces `<` and `>` with `&lt;` and `&gt;` too aggressively, so we get things like `<link rel="canonical" href="&lt;% canonical %&gt;">`.
