### ISSUE TITLE
Link icons in search are not reusing symbol

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2911]
### Current Behavior
We are requesting the same SVG 5 times instead of using a symbol on the homepage. 

```
<svg id="internal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><path d="M43.16 10.18c-0.881-0.881-2.322-0.881-3.203 0s-0.881 2.322 0 3.203l16.335 16.335h-54.051c-1.281 0-2.242 1.041-2.242 2.242 0 1.281 0.961 2.322 2.242 2.322h54.051l-16.415 16.335c-0.881 0.881-0.881 2.322 0 3.203s2.322 0.881 3.203 0l20.259-20.259c0.881-0.881 0.881-2.322 0-3.203l-20.179-20.179z"></path></svg>
```

**Comment by matthiasrohmer** [comment]
Not quite sure but I guess `symbol`/`use` might have caused problems when used inside the `amp-mustache` template.

**Comment by matthiasrohmer** [comment]
That's indeed the reason:

https://github.com/ampproject/amp.dev/blob/3f225a2975548789ea9f1b436b072ba62ae191df/frontend/templates/views/partials/search.j2#L7-L10

**Comment by sebastianbenz** [comment]
Excellent, the fix should be live now.

>
