### ISSUE TITLE
Small sized images are getting stretched in the amp lightbox

### ISSUE THREAD

**Issue by Zabi09** [ampproject/amp.dev#2913]
When I am adding the small images like 150*150 then those images are getting stretched and not looking good in desktop and even on mobile devices and I have added some CSS to override it but it is not working - https://monosnap.com/file/N2jet7nu7WFfnYF6zprycJq9RCFDlV

Will you please tell me how to change "i-amphtml-image-lightbox-viewer-image" class because the inline CSS of this class only creating the problem.

**Comment by sebastianbenz** [comment]
Please ask questions on Stackoverflow using the `amp-html` tag. This repository is only for issues related to the amp.dev website.
