### ISSUE TITLE
Add search to blog

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2924]
We should integrate the current search implementation into the blog as well. 

@matthiasrohmer do you know a good way to share the search markup as a snippet?

**Comment by matthiasrohmer** [comment]
I'd go for the same approach as with header and footer: https://github.com/ampproject/amp.dev/tree/future/pages/content/shared. See #1800 for history 🙂

**Comment by matthiasrohmer** [comment]
Now part of #3152.
