### ISSUE TITLE
Examples: wrapper divs are not removed

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2928]
Examples should remove surrounding `div` elements if they have no further attributes, e.g. here:

```
<div>
  <amp-lightbox id="my-bindable-lightbox"
    [open]="showLightbox"
    layout="nodisplay"
    on="lightboxClose:AMP.setState({showLightbox: false})">
    <div class="lightbox"
      role="button"
      tabindex="0"
      on="tap:my-bindable-lightbox.close">
      <h1>Hello World!</h1>
    </div>
  </amp-lightbox>
  <button on="tap:AMP.setState({showLightbox: true})">
    Open lightbox
  </button>
</div>
```

http://localhost:8080/documentation/examples/components/amp-lightbox/?format=websites#development=1

This used to work on AMP by Example and I thought that the sample parser already takes care of this. 

//cc @matthiasrohmer @tharders

**Comment by matthiasrohmer** [comment]
You've got a preference where to put the logic for this? From best to worst:

1. In the abe.com parser
2. Somewhere in the SamplesBuilder/Transformer context, where the latter already uses a DOM which would be suitable for the task
3. `if section.startswith('<div>') and section.endswith('</div>'):` 😉

**Comment by sebastianbenz** [comment]
It's already implemented here: https://github.com/ampproject/amp-by-example/blob/master/lib/CodeSection.js#L124

We might simply be calling the wrong API to get the code section.

**Comment by matthiasrohmer** [comment]
Huh, the more you know. Thanks! I'll check...
