### ISSUE TITLE
Compress courses images

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2931]
Some of them are up to 712kb.

**Comment by DerekNonGeneric** [comment]
For your consideration:
- [pngcrush](https://www.npmjs.com/package/pngcrush)
- [rollup-plugin-imagemin](https://www.npmjs.com/package/rollup-plugin-imagemin)
- [imagemin-webpack-plugin](https://www.npmjs.com/package/imagemin-webpack-plugin)
- [Kraken.io](https://kraken.io/web-interface)

**Comment by morsssss** [comment]
(shame)

@robocel had kindly offered to do this earlier this year. Rob, whaddya say?

**Comment by morsssss** [comment]
This has been fixed via #3322 . We could probably compress some images more aggressively, but it's so much improved!
