### ISSUE TITLE
Documentation Wanted: Testing AMP emails on supported clients

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2936]
A short description of your contribution proposal:
A guide, or maybe tutorial, that walks developers through testing their AMP email on supported clients. 

We need:
- A list of supported clients and their testing documentation 
- Common gotchas 
- Example email to test 

Type of contribution:
[x] Guide
[x] Tutorial
[ ] Example
[ ] Translation 
[ ] Other (please specify)

Note: This content proposal is free to claim by interested parties until assigned. 

Related to [#2921](https://github.com/ampproject/amp.dev/issues/2921)

**Comment by sebastianbenz** [comment]
Fixed by #2948
