### ISSUE TITLE
Adding new email service provider at https://amp.dev/documentation/tools/

### ISSUE THREAD

**Issue by RussianTranslator** [ampproject/amp.dev#2937]
One more email service provider, SendPulse, added support for AMP email. 
Whom can I contact about listing it at https://amp.dev/documentation/tools/?

P.S. Not sure this is the right place to ask, will appreciate any help. Here's link to the [docs ](https://sendpulse.com/knowledge-base/email-service/email-sending/how-send-amp-emails). 

![amp1](https://user-images.githubusercontent.com/11932351/64433351-f7bd6f80-d0c6-11e9-8d5d-e98ffc5420ae.png)
![amp2](https://user-images.githubusercontent.com/11932351/64433352-f7bd6f80-d0c6-11e9-904c-9ba1fa3e173f.png)

**Comment by fstanis** [comment]
Hi, you can make a PR to add this tool. Example is: #2439

**Comment by patrickkettner** [comment]
ping @RussianTranslator
