### ISSUE TITLE
Inline code samples not working in playground 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2966]
### Current Behavior
Some code samples don't work when you click the "open in playground" button, such as [carousel](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fcomponents%2Famp-carousel.example.1.html%3Fformat%3Dwebsites&format=websites&_gl=1*1yhebuz*_ga*MzM1MjQ0ODE5LjE1NjUwMzU1MTg.)

**Comment by tharders** [comment]
The example has a fixed with of 450 pixel, but the mobile phone previews have less.
So the right arrow is not shown.
When you switch to responsive or custom size with at least 450 pixel width it works.

**Comment by tharders** [comment]
Adding `layout="responsive"` to the carousel would fix this problem.

**Comment by CrystalOnScript** [comment]
Thanks @tharders - I'll update the sample code!
