### ISSUE TITLE
Link to samples from component docs

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2971]
We should more strongly combine component docs and samples:

- [ ] a component doc should list all samples using the component
- [ ] if available, a component doc should show the sample width (https://github.com/ampproject/amp.dev/issues/1326)
- [ ] remove examples row from component table in amphtml repo

**Comment by matthiasrohmer** [comment]
This will be fixed by #3344.

**Comment by sebastianbenz** [comment]
Done as part of new component intro tables.
