### ISSUE TITLE
Invisible text in amp-autocomplete documentation

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amp.dev#3004]
### Current Behavior

There are some invisible text in the amp-autocomplete documentation:

Please also provide:
- Page link: https://amp.dev/documentation/components/amp-autocomplete/#attributes

### Expected behavior/code

Text should be visible.

### How do we reproduce the issue?

1. Go to the link above
2. Find this text: `If fetching the data at the src URL fails, the triggers a fallback.`
3. Note that the "triggers a fallback" part is invisible. You can make it visible by highlighting the text.

What browser are you using?

Chrome

What O/S are you using?

Linux

**Comment by sebastianbenz** [comment]
This is WAI. The doc import is synced with the current AMP release. You can add exceptions [here](https://github.com/ampproject/amp.dev/blob/future/platform/lib/pipeline/componentReferenceImporter.js#L22) in case of important doc fixes.

**Comment by zhangsu** [comment]
I don't understand. This is about some text in the documentation not styled correctly and therefore hidden (until you highlight the text). How is this WAI and related to fetching from AMP releases vs master?

**Comment by caroqliu** [comment]
Addressing this in the new issue linked above, this time in the relevant repo @zhangsu

**Comment by sebastianbenz** [comment]
@zhangsu sorry for closing this prematurely, I've mixed this up with a different issue.
