### ISSUE TITLE
Component docs: show latest prod version by default

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3023]
For example, the new amp-sidebar v1.0 docs should not be shown by default while the new version is still experimental. 

However, the should be linked from the older doc versions.

//cc @nainar in case we'd prefer to show the experimental version by default.
//cc @tharders

**Comment by nainar** [comment]
I agree with you - experimental docs can be found via github.

**Comment by patrickkettner** [comment]
@sebastianbenz is this still valid? Unless I am misunderstanding, the bento changes earlier this year sorted this?

**Comment by sebastianbenz** [comment]
Correct. Thanks for checking in.

>
