### ISSUE TITLE
Gulp command in Develop section of README

### ISSUE THREAD

**Issue by DerekNonGeneric** [ampproject/amp.dev#3030]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
The Develop section of the README includes instructions that assume the user already has a global installation of Gulp, yet never specifies to run `npm i -g gulp`.

**Which part of the site would that content live at?**
The amp.dev README file.

**What's the type of content?**
Local development instructions.

**Optional: Proposed information architecture**
Rather than including instructions to globally install Gulp, I propose to include these Gulp commands in the `package.json` `"scripts"` field and run them as `npm run _____`.

This approach has two main advantages:

- Guarantees that the intended version of Gulp is being used
- Avoids ending up with two Gulp installations (global and local)

For those who already have Gulp installed globally, they would no longer need to assure that their globally installed version matches the one being used by this project.

**Comment by matthiasrohmer** [comment]
Thanks for your feedback! Indeed it's a little unfortunate that we're currently relying on a globally installed version of gulp what might cause version conflicts.

Anyhow I am not a fan of the proposed solution. Making all (or even some) of our gulp tasks available as NPM scripts would immensely bloat up the package.json, which already holds a lot of scripts that are independent of gulp.

Instead I'd propose to hint using `npx gulp <taskname>` in the readme. What do you think?

**Comment by DerekNonGeneric** [comment]
That works too!

**Comment by DerekNonGeneric** [comment]
Believe it or not, running `npx gulp bootstrap` results in an error, but running `gulp bootstrap` with it installed globally, completes without error. Here's that error.

```
[15:23:39] 'importAll' errored after 3.2 min
[15:23:39] Error: connect ECONNREFUSED 192.30.253.117:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[15:23:39] 'bootstrap' errored after 3.2 min
```

**Comment by cathyxz** [comment]
My bad, I was literally looking at the wrong repository (comment cc to wg-infra deleted).

**Comment by rsimha** [comment]
For the `amphtml` repo, we’ve fixed the version mismatch by recommending `gulp-cli` over a global install of `gulp`

**Comment by DerekNonGeneric** [comment]
That error above appears to have been a *Github API hickup* (unrelated to local Gulp usage). Pull request for the proposed solution incoming momentarily.
