### ISSUE TITLE
Grow installation instructions in README seem wrong

### ISSUE THREAD

**Issue by DerekNonGeneric** [ampproject/amp.dev#3031]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
The Requirements section of the README says to use `pip` instead of its installer when installing Grow. Simply running `pip install grow` seems to only install the module to `~/.local/lib/python2.7/site-packages`. At least this is what I experienced on Debian 10. I think it might be necessary to run Grow's install script, which adds `bin/grow` to the user's home directory and then adds that to the user's `PATH`.

**Which part of the site would that content live at?**
The amp.dev README file.

**What's the type of content?**
Local development instructions.

**Optional: Proposed information architecture**
I don't know why the instructions specify to not use the installer. I was only able to install it on my system with this procedure:

1. `pip install grow`
1. `curl https://install.grow.io | bash`

I would probably include both steps in the README unless someone knows why not.

**Comment by DerekNonGeneric** [comment]
@matthiasrohmer what should `which grow` be outputting?

**Comment by DerekNonGeneric** [comment]
I have discovered that there is a step that is missing! It is explained [Installing to the User Site](https://packaging.python.org/tutorials/installing-packages/#id6) from the pip docs. Following those instructions, I was able to convert what we currently had to these three commands. The first command is for local user installation of Grow. The second command can be omitted if that directory is already in the user's `$PATH`, but the _user base binary directory_ **does need** to be added to `$PATH` on a fresh install of Debian 10. The third command avoids having to log in and out for the changes to take effect.

```sh
$ pip install --user grow
$ echo "export PATH=\"$(python -m site --user-base)/bin\":\$PATH" >> ~/.bashrc
$ source ~/.bashrc
```

**Comment by DerekNonGeneric** [comment]
Now using the raw Python module, running `grow --version` produces a warning:

```
Warning: libyaml missing, using slower yaml parser.
```

I was able to remedy this warning by doing the following.

**Debian-based (tested)**
```bash
sudo apt install -y python-yaml
```
**macOS (untested)**
```bash
brew install libyaml
```
---
Simply installing the pip package did not resolve the warning on Debian.

```bash
pip install --user pyyaml
```
^ This might be slower parser mentioned in the warning.

**Comment by matthiasrohmer** [comment]
Sorry for not catching up on this. What you described in https://github.com/ampproject/amp.dev/issues/3031#issuecomment-535901317 is indeed the correct "fix" for this i.e. what I meant earlier with setting up pip correctly.

The warning you mentioned is either fine to ignore or fixable with your proposed commands.

Anyway I am a bit unsure which of those steps should end up in our own README.md.

**Comment by DerekNonGeneric** [comment]
I just tested the Grow installation instructions on my old Mac and they did not work. Simply running `pip install grow` did not add it to the path (even after opening and closing Terminal). I also discovered that the Terminal app uses `.bash_profile` instead of `.bashrc`. I was not able to resolve that warning with `brew install libyaml` on macOS.
