### ISSUE TITLE
Select correct default format

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3057]
https://amp.dev/documentation/guides-and-tutorials/start/visual_story is only relevant for stories. However, the canonical link will go to the websites version of the page.

We should update the default format selection to be aware of the actually supported formats.

//cc @tharders @matthiasrohmer

**Comment by tharders** [comment]
This is related to #2588
The discussion there provides the solution to this problem.

**Comment by sebastianbenz** [comment]
Good point. Closing as duplicate.
