### ISSUE TITLE
geolocation-based_consent_flow Example is blank for users not from EEA

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amp.dev#3063]
## Bug Report

Please refer to https://github.com/ampproject/amphtml/issues/24755

### Current Behavior
If the user is not from the region that requires consent, they get a black page. 

A clear and concise description of the bug you found on amp.dev.

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fuser-consent%2Fgeolocation-based_consent_flow&format=websites&mode=Galaxy+S5

### Expected behavior/code
Add content to the page to communicate well that the consent is not required so no prompt

### How do we reproduce the issue?
Visit the page not from EEA

**Comment by zhouyx** [comment]
@micajuine-ho Good time to fix this while we are making changes to the examples. Thanks

**Comment by micajuine-ho** [comment]
Ok, sg. I will get to it in the next few days
