### ISSUE TITLE
Migrate https://status.ampproject.org to amp.dev

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amp.dev#3075]
Malte and I found out that this micro-site isn't on amp.dev yet. Can you two figure out how to move it? Probably just requires some DNS config changes?

Thanks in advance!

**Comment by matthiasrohmer** [comment]
Maybe I should cancel my subscription to this repo 😅Anyway my thoughts on this: doesn't it actually make sense to have the status page on this domain as its cdn.*ampproject.org* where the files are coming from? Or ist that also subject to change?

**Comment by pbakaus** [comment]
mhh fair point. @cramforce wdyt?

**Comment by cramforce** [comment]
The domain doesn't matter. The thing that matters is that it must not be hosted on the same infra as cdn.amproject.org and ideally also not the same infra as amp.dev

**Comment by sebastianbenz** [comment]
Where is status.ampproject.org currently hosted?

>

**Comment by danielrozenberg** [comment]
It's a GitHub Site, CDN'd by CloudFlare

I don't feel strongly about which domain to serve this from, but do note that switching domains involves a lot of grunt work, e.g., changing DNS records requires a Google security review, getting a new SSL cert means working with CloudFlare to produce a new one, etc... lmk if you think it's worth the transition :)
