### ISSUE TITLE
playground.amp.dev SSL cert expired; unreachable

### ISSUE THREAD

**Issue by runofthemill** [ampproject/amp.dev#3093]
### Current Behavior
Cert is expired :(

Cannot reach any pages on the playground.amp.dev subdomain.

![Screen Shot 2019-10-10 at 4 33 00 PM](https://user-images.githubusercontent.com/8418440/66613904-dfd08400-eb7b-11e9-8ad8-2901ae1fe93d.png)

**Comment by sebastianbenz** [comment]
Thanks for reporting. Fixed
