### ISSUE TITLE
Imported spec docs don't link to each other correctly

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#3107]
## Bug Report

Spec pages (those in [ampproject/amphtml/spec](https://github.com/ampproject/amphtml/tree/master/spec) that link to other spec pages in the same folder are not converted to amp.dev links.

Example: [AMP HTML Specification](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/?format=websites) has a link "AMP boilerplate code". This link should link to [AMP boilerplate code on amp.dev](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate/?format=websites) but instead takes you to the [amp-boilerplate.md on GitHub](https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md).

Same goes with the email spec docs that are interlinked.

**Comment by patrickkettner** [comment]
fixed in #3107
