### ISSUE TITLE
Google search doesn't know about ?format=

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#3115]
### Current Behavior

If you find a page using Google search, it will always take you to the web version, even if that particular page is not applicable for websites (e.g. email only).

### Expected behavior/code

The current behavior causes confusion for two reasons:

- #2960 added a warning when a page is not applicable for the current format. This means all search results that link to pages not applicable to websites always have a warning.
- When a page is clearly related only to one format, as with "Create your first AMP Email", it may not be clear to the user they have the wrong filtering and they may click on another page on the left, thinking it applies to email.

### How do we reproduce the issue?

1. Try this search: https://www.google.com/search?q=%22Create+your+first+AMP+Email%22+site%3Aamp.dev
2. Click on first result
3. Notice "websites" is selected in the top left corner

**Comment by fstanis** [comment]
One simple solution that comes to mind:

1. Create new metadata property, `default_format`
2. When a user lands on a page that has a `default_format` and no `?format=` is present, redirect them to `?format=${default_format}`
3. If no `default_format` is specified for a page and there's only one entry in `formats`, then that format is the default format.

**Comment by tharders** [comment]
The problem with the default format is described here: #2588 
Will close this issue as a duplicate.
