### ISSUE TITLE
Nested list items don't show up as nested in the WG section of governance document

### ISSUE THREAD

**Issue by tobie** [ampproject/amp.dev#3130]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**

Nested list items don't show up as nested in https://amp.dev/community/governance/#working-groups. See for contrast the canonical document at https://github.com/ampproject/meta/blob/master/GOVERNANCE.md#working-groups.

**Which part of the site would that content live at?**
Not relevant

**What's the type of content?**
Governance documentation

**Comment by matthiasrohmer** [comment]
@robinvanopstal, it works for the [Decision making policy](https://github.com/ampproject/meta/blob/master/GOVERNANCE.md#decision-making-policy) section so that's probably just a formatting error.
