### ISSUE TITLE
Investigate application start up times

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3145]
@sebastianbenz and I already encountered fairly early that the concept of shipping the built pages with our VM instance image could cause problems, especially regarding the VM's startup time.

It seems as if this problem is becoming more current now again. Signs are:
- Failing deployments because application takes too long to start after deploying it: https://travis-ci.org/ampproject/amp.dev/jobs/602714785#L767
- Failing uptime checks (Stackdriver) for starting VMs that are already receiving traffic

We need to investigate if the cause that we identified in spring is still the reason or if its something else and then should try to improve it.

/cc @tharders

**Comment by sebastianbenz** [comment]
We should also check the logs for any application crashes.

**Comment by matthiasrohmer** [comment]
Here is what I'd do:

1. Instead of storing the built pages as archives and downloading them at the end of the build process to then add them to the Docker image like so:

https://github.com/ampproject/amp.dev/blob/43ab82890b961774f354b742cbf261c7467a1ab6/gulpfile.js/build.js#L349-L359

We extract them to the Google Cloud Storage and then don't use `fs` calls here

https://github.com/ampproject/amp.dev/blob/43ab82890b961774f354b742cbf261c7467a1ab6/platform/lib/common/growPageLoader.js#L32-L43

to load them but use [@google-cloud/storage](https://www.npmjs.com/package/@google-cloud/storage) to read them from the GCS. This should decrease the time needed to create a new VM as well as uploading the image during deployment.

2. Add a caching layer to the growPages.js router caching *after* rendering and optimizing

https://github.com/ampproject/amp.dev/blob/43ab82890b961774f354b742cbf261c7467a1ab6/platform/lib/routers/growPages.js#L288-L294

This cache should be shared across instances using [@google-cloud/redis](https://www.npmjs.com/package/@google-cloud/redis). To discuss: what to use as a cache key? The request path for sure, but do we want to use the [who-am-i](https://amp.dev/who-am-i) information in the key as well or rather wait til a cached item gets stale?

@sebastianbenz, @tharders: can you please have a look at the proposal and hint me at any spots I might have missed? Thanks!

**Comment by sebastianbenz** [comment]
Thanks for looking into this. Comments:

re 1.: does this mean you want to store all files in cloud storage? Static files as well? 
re 2.: using redis here makes sense. Have you got an idea how to best update caches on deploy?

**Comment by matthiasrohmer** [comment]
1. Didn't even thought about static files, but yes that would definitely make sense and even further decrease image size. @tharders mentioned it would be nice if we are somehow able to mount the GCS in a way it's usable by `fs` calls. That would avoid creating a special case which is not easily testable. I'll look into this.

2. If we use the build number combined with the request URL as a cache key old entries would automatically expire, which would make cache busting on deploy not necessary - despite costs. Is that enough or do we need to look for a solution to force empty the cache?

**Comment by sebastianbenz** [comment]
re 1: sgtm
re 2.: didn't know that redis supports auto-expiring keys. That's perfect then!

**Comment by sebastianbenz** [comment]
one thing about 1) how would rollback and cleanup work in this scenario?

**Comment by matthiasrohmer** [comment]
>Add a caching layer to the growPages.js router caching after rendering and optimizing

Done.
