### ISSUE TITLE
Please bring back the template Demos

### ISSUE THREAD

**Issue by virgiltu** [ampproject/amp.dev#3147]
We use to be able to see the demos of these site before download. 
https://amp.dev/documentation/templates/

Now they dont work. As an example ecommere travel does not work because the dataset uses an api. 

Please bring back the demos.

**Comment by sebastianbenz** [comment]
We hear you! That's on our todo list and should be back soon.

**Comment by sebastianbenz** [comment]
It has been fixed with #2530
