### ISSUE TITLE
Import information about AMP's release schedule

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3161]
We should import https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md into amp.dev

**Comment by CrystalOnScript** [comment]
Agreed! But I don't think it fits into guides/tutorials... Maybe a standalone page we can link to on [the roadmap](https://amp.dev/community/roadmap/)? 

CC @sebastianbenz @pbakaus

**Comment by matthiasrohmer** [comment]
This has made it to https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/ 👌
