### ISSUE TITLE
Add an "events" and "actions" section to every component

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#3167]
[Actions and events](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/) lists the allowed actions and events for each component.

However, it would be good if each component also listed actions and events it supported, e.g. [amp-sidebar](https://amp.dev/documentation/components/amp-sidebar/) doesn't mention anywhere what it supports.

Perhaps we could add it to the table on the top, similar to *Supported Layouts*.

(cc @CrystalOnScript who originally pointed this out)

**Comment by matthiasrohmer** [comment]
The introduction table might not be the most ideal place to put this information as it's sort of deprecated 😅At last that's what we planned in the last weeks, sorry that I never documented that. Just created #3168.

**Comment by fstanis** [comment]
Ah, so we could potentially move it to frontmatter then?

**Comment by matthiasrohmer** [comment]
@sebastianbenz doubted that actions and events are describable in the condensed frontmatter. @sebastianbenz, can you elaborate?

**Comment by matthiasrohmer** [comment]
Continued in #3295 and amphtml#26051.

**Comment by fstanis** [comment]
Whoops, I forgot I'd already had an issue on this! 😄
