### ISSUE TITLE
Access Denied Google Doc behind documentation formatting link

### ISSUE THREAD

**Issue by DerekNonGeneric** [ampproject/amp.dev#3172]
### Current Behavior
In the [Writing Documentation section](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/#writing-documentation) of the [Contribute Documentation](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/) page, the `documentation formatting` link sends users to an Access Denied Google Doc requiring users to request access to the document. 

Please also provide:
- Page link: https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/
- (Optional) Screenshots / videos

![amp-docs-bug](https://user-images.githubusercontent.com/17770407/67942958-6e4e8900-fbaf-11e9-9d0f-cae0ad6f9eda.png)

### Expected behavior/code
Link to either a public Google Doc or an AMP document part of the amp.dev site.

### How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Visit the [Writing Documentation section](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/#writing-documentation) of the [Contribute Documentation](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/) page.
2. Click the `documentation formatting` link.
3. Observe.

What browser are you using? Chrome
What O/S are you using? Windows Server 2019

**Comment by CrystalOnScript** [comment]
Thanks for flagging! Resolved today with [this commit](https://github.com/ampproject/amp.dev/commit/cdbc3ce4a9c7c565955f5605355f6bd7fe324b64)

**Comment by DerekNonGeneric** [comment]
@CrystalOnScript, is it going to be linking to a Markdown document on GitHub?

**Comment by CrystalOnScript** [comment]
Yeppers! It will link to an existing markdown file on amp.dev.

**Comment by DerekNonGeneric** [comment]
Are you sure the value provided to `href` will resolve in a browser? The other that is intended to viewed on GitHub includes the entire URL. Wouldn't it need to be the following?

```
https://github.com/ampproject/amp.dev/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/documentation-types.md
```
