### ISSUE TITLE
Please link in sidebar documentation of AMP Stories under "Develop"

### ISSUE THREAD

**Issue by jasti** [ampproject/amp.dev#3177]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
This is a pretty important document that should be more visible on the sidebar hierarchy: https://amp.dev/documentation/guides-and-tutorials/develop/story_ads_best_practices/?format=stories#sample-story-ad

**Which part of the site would that content live at?**
AMP Stories > Develop

**What's the type of content?**
Documentation

**Optional: Proposed information architecture**
If you have ideas on how we should structure the content, tell us!

**Comment by CrystalOnScript** [comment]
This will be resolved in the next deployment of amp.dev!
