### ISSUE TITLE
What is AMP_DEV_CREDENTIAL_GOOGLE_CSE_API_KEY?

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#3202]
I just got this when I ran `gulp develop --clean-samples`:

```
ERROR: Google site search will not be available! Environment variable AMP_DEV_CREDENTIAL_GOOGLE_CSE_API_KEY is not set.
```

What is `AMP_DEV_CREDENTIAL_GOOGLE_CSE_API_KEY`? I searched the repo, but couldn't find any reference to it.

**Comment by sebastianbenz** [comment]
it's used for the Google Custom site search integration. It's save to ignore unless you want to test search. We probably should make this a warning instead.

**Comment by fstanis** [comment]
Sure, might also be worth documenting similar to how we do with `AMP_DOC_TOKEN`.
