### ISSUE TITLE
amp-ad should mention how to create responsive ads

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3207]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
Just spoke to someone from UnoTV, who have a new and nice AMP-first implementation. They had struggled with creating a responsive ad. Turns out there's a simple way: create two `<amp-ad>`s with an appropriate media query for each. AMP will intelligently only make an ad call for the `<amp-ad>` that's visible. Which, as I think about it, makes sense... because AMP does in-viewport prioritization! But this technique isn't mentioned anywhere on amp.dev, or, it turns out, the Internet.

A simple paragraph and a code sample from us could fix this common use case.

**Which part of the site would that content live at?**
This should go in the main reference docs... or, ok, perhaps we need a sample.

**What's the type of content?**
A paragraph and a code sample would do it

**Comment by CrystalOnScript** [comment]
@morsssss @ lannka @calebcordry 
Is someone able to provide a code sample for this?

**Comment by powerivq** [comment]
Clean up old issues.
