### ISSUE TITLE
"Previous" and "Next" Link texts in blog need guaranteed separation

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3208]
## Bug Report
The text next to the "previous" and "next" arrows, if sufficiently long, can lack any spacing... so the two bits of text merge into one.

This happens, for example, at [https://blog.amp.dev/2018/10/08/how-to-make-amp-even-faster/](https://blog.amp.dev/2018/10/08/how-to-make-amp-even-faster/) .

See screenshot:

<img width="755" alt="Screen Shot 2019-11-13 at 10 05 30 AM" src="https://user-images.githubusercontent.com/29419498/68791140-8b4a7980-05fd-11ea-9ba2-d4e6a161e775.png">

**Comment by matthiasrohmer** [comment]
@westonruter, same as with other blog issues: let us know if we could help or reassign to someone in your team. 🙂

Looking at the CSS selectors it seems that those are blog specific stylings.

**Comment by westonruter** [comment]
Thanks. We're currently stretched pretty thin but I'll add it to the list.

**Comment by westonruter** [comment]
This is now fixed:

![image](https://user-images.githubusercontent.com/134745/71299969-cf8c1080-2345-11ea-8e8e-9f8e6ef2ba62.png)

**Comment by morsssss** [comment]
Beautiful!
