### ISSUE TITLE
[Translate-ko] Add signed-exchange page, publishing checklist page

### ISSUE THREAD

**Issue by biyott** [ampproject/amp.dev#3235]
A short description of your contribution:

Type of contribution:
[ O ] Translation 

Process
https://docs.google.com/document/d/19DEZWu1hjfDU1i0H-olbscVxjuGfJXyHUhI2IAMPZIA/edit#

I'm sorry.
Proposal Guide article already submitted by mistake without reading.

[ ] 1. Proposal created `link to proposal`
[ ] 2. Proposal approved.
[ ] 3. Draft complete.
[ ] 4. Draft approved.
[ O ] 5. Pull request submitted.
[ ] 6. Pull request approved!

**Comment by techhtml** [comment]
Hello new translator!

Thank you for your contribution,
When will you complete your translation, feel free to request to reviewing me :)

I always in here.
THx!

**Comment by biyott** [comment]
@techhtml I already complete translation.
[This pull request](https://github.com/ampproject/amp.dev/pull/3220)

**Comment by biyott** [comment]
용어에서 고민하고 있는 부분이 있는데,

- 예를 들면 `signed exchanges` 라든가 'Response', 'Request', 'Accept', 'header', 'binary', 'Deploy', 'production', 'staging', 'provider', 'canonicals', 같은 경우 영어나 발음 그대로 표기한 것이 더 직관적이고 이해가 잘 되는 것 같습니다. 그렇다고 '스테이징', '프로바이더'와 같은 단어로 채우기엔 너무 외래어를 남발하는 느낌이 들고요.
- 'non-cache' 같은 것도 '비 캐시'와 같이 번역하기에 좀 억지스러운 느낌입니다. 차라리 'non-캐시'가 더 이해가 잘 됩니다.
- 개발문서의 경우 서술형 문장 문맥만을 번역하는 것이 더 이해가 쉽다고 생각하는데, 다른 분들은 어떤지 궁금했습니다. 더불어 해당 주제에 대해 처음 접하는 개발자 분들이 문서를 보는데 어느 것이 더 쉬울지도 중요할 것 같고요.
(가령 START/LEARN/DEVELOP/INTEGRATE/OPTIMIZE & MEASURE/CONTRIBUTE 과 같은 메뉴의 경우 번역하지 않는 것이 더 자연스럽고 이해가 쉽다고 생각하고 있습니다.)

**Comment by techhtml** [comment]
`signed exchanges` 는 원문 그대로 가져가는 게 좋다고 생각하고,
각각 순서대로 응답, 요청, 허용, 헤더, 바이너리, 배포, 제품, 스테이징, 프로바이더 (얘는 기술 용어라), 대체 링크
등으로 번역하고 있습니다.

`non-cache` 는 `캐시가 아닌` 같은 식으로 풀어서 쓰셔도 좋을 듯 합니다.

**Comment by techhtml** [comment]
제가 정신이 없어서 리뷰 중간에 몇가지 어색한 표현은 추가 자정작용 등을 통해 개선될 거라 판단하며 리뷰를 진행하고 있는데요. 용어집은 별도로 마련해두는 방향이 좋아보이네요 :)

**Comment by biyott** [comment]
답변 감사합니다. 👍
기존에 번역한 단어도 고치는 방향을 생각해봐야겠네요.
진행할 번역에 대해 이슈에 남기겠습니다.

**Comment by patrickkettner** [comment]
나는 그것이 얼마나 오래되었는지 때문에 이것을 닫고 있습니다. 귀하의 공헌에 감사드립니다!
