### ISSUE TITLE
Bug: amp-story component page is invalid AMP, and has broken samples

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amp.dev#3242]
See https://amp.dev/documentation/components/amp-story/#data-text-background-color

![image](https://user-images.githubusercontent.com/43004/69684861-020c5b80-106f-11ea-8266-96b03f743b21.png)

**Comment by nutcha1** [comment]
https://github.com/ampproject/amp.dev/issues/3242#issue-529054677

**Comment by matthiasrohmer** [comment]
Hm.. the examples seem fine to me, that's rather an issue with rewriting the relative GitHub paths to absolute URLs. But in this case there just seem to be hidden characters somewhere: `https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/img/text-background-color-ex-2.png%E2%80%8B%E2%80%8B%E2%80%8B`. That's the image's src.
