### ISSUE TITLE
Can we get rid of confusing warning on pages about stories?

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3243]
Let's say you visit [the guide on best practices for Stories](https://amp.dev/documentation/guides-and-tutorials/develop/amp_story_best_practices/), with nothing in the URL parameter.

You then see at the top of the page, this warning:

<img width="655" alt="Screen Shot 2019-11-27 at 12 30 34 PM" src="https://user-images.githubusercontent.com/29419498/69746251-db533100-1111-11ea-871d-ac08559a62cf.png">

Of course, you haven't ever selected the "websites" format, so you don't know why you're getting this message.

It would make sense to me if the desired format could simply be autoselected in such cases, with the proper query string silently appended.

Or, as a much larger fix, I personally have found the query strings which select formats confusing since the redesign, and I'd love if they weren't necessary at all.

**Comment by sebastianbenz** [comment]
This will be fixed by #2588 and with the new format selector.

**Comment by morsssss** [comment]
excellent... thanks!
