### ISSUE TITLE
amp-img documentation for amp4email includes srcset attribute

### ISSUE THREAD

**Issue by HaraldWalker** [ampproject/amp.dev#3252]
## What's the issue?

The amp for email documentation of amp-img includes the srcset attribute but in the amp validator the srcset attribute is not allowed in amp4email.  

Seen on following pages:  
https://amp.dev/documentation/components/amp-img/?format=email
https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction/?format=email

## How do we reproduce the issue?

1. go to https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction/?format=email
2. click on 'Open this snippet in playground' below first example. 
3. notice validation error in playground.

**Comment by choumx** [comment]
@sebastianbenz Is it possible to conditionally change copy based on format? Or would we need a separate `amp-img-email.md` file?

**Comment by sebastianbenz** [comment]
Yes, [that's possible](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting/?format=websites#filtering-sections). We need to systematically go through all the component ref docs. I'l create a separate issue for this.

**Comment by fstanis** [comment]
#2745 is the existing issue about this.

**Comment by zhangsu** [comment]
@CrystalOnScript another minor correction we need that wasn't included in the fix for #2745 ...

**Comment by CrystalOnScript** [comment]
I believe this was addressed in this fix here:
https://github.com/ampproject/amphtml/pull/26107/files#diff-a27c8fa1a992f7479e7a77d13cde7149R131

But it looks like it hasn't gone live yet... @matthiasrohmer, do we know when the next deploy is?

**Comment by matthiasrohmer** [comment]
This went to prod in the meantime.
