### ISSUE TITLE
Video components page mentions amp-iframe instead of amp-video-iframe

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3255]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
[This guide on components for video players](https://amp.dev/documentation/examples/multimedia-animations/integrating_videos_in_amp_an_overview/) is quite helpful! At the end, though, it says that for nonsupported players, it's best to simply use an `<amp-iframe>`. I imagine that we actually want to direct people instead to `<amp-video-iframe>`.

Also, while I'm at it, the title is "Integrating Videos in AMP an Overview". I'd suggest inserting a colon before "an Overview", or simply shortening this to "Integrating Videos in AMP".

**Comment by CrystalOnScript** [comment]
I think that the use of `<amp-iframe>` may be correct here. As:
`Use amp-iframe for videos not supported in AMP` 
vs
`With amp-video-iframe you can include a custom-built video player` 
Which are two different use cases. 

But cc @sebastianbenz to weigh in. If we keep it as `<amp-iframe>`, we should probably update the link.

**Comment by sebastianbenz** [comment]
+1 to Ben. We should only mention amp-video-iframe: `... for nonsupported players, it's best to embed these via iframe using the <amp-video-iframe> component.

**Comment by CrystalOnScript** [comment]
Ah, got it! Looks like a larger update overall - I'll spend some time with it.

**Comment by manisaiprasad** [comment]
if amp team can give me a working link I think I can  fix this issue by a PR
@CrystalOnScript @matthiasrohmer  @sebastianbenz @twifkak

**Comment by sebastianbenz** [comment]
That's great! You can find a few videos [here](https://github.com/ampproject/amp.dev/tree/future/examples/static/samples/video).  The are available via: `https://amp.dev/static/samples/video/filename.mp4`
