### ISSUE TITLE
Add RebelMouse to the Platform & Vendor Partners page as a CMS

### ISSUE THREAD

**Issue by charset-and-forget** [ampproject/amp.dev#3260]
As suggested by @mattludwig ; would be happy to provide any info necessary in order to add our CMS to relevant places on amp.dev.
Developers are able to easily implement AMP and provide content creators with great tools for creating AMP posts and AMP-compatible monetization.
[https://amp.dev/support/faq/platform-and-vendor-partners/](url)
[https://amp.dev/documentation/tools/](https://amp.dev/documentation/tools/)

**Comment by mattludwig** [comment]
@CrystalOnScript @sebastianbenz -- Could we add RebelMouse to the Platform & Vendor Partners page as a CMS?

Also open to putting them on the site in other places where makes sense -- their AMP product within the RebelMouse CMS is fairly robust

**Comment by CrystalOnScript** [comment]
Hi @charset-and-forget - sorry for the delayed response! To get your CMS featured, could you please fill out the following template with the requested assets/information?
```
<!--
Thank you for wanting to add a community resource to amp.dev.

Please fill in as much of the below template as you're able.
-->

## 🛠️ Request to Add Third-Party Tool/Service/Platform/Vendor

### 1. Resource name
Insert name here

### 2. Relevant format(s)

<!-- Use [x] to mark a selection. -->

- [ ] websites
- [ ] stories
- [ ] ads
- [ ] email


### 3. Resource type

<!-- Use [x] to mark a selection. -->

- [ ] editor
- [ ] service provider
- [ ] developer tool
- [ ] content platform
- [ ] CMS
- [ ] ads
- [ ] audio/video
- [ ] analytics vendor

### 4. Destination
1. [amp.dev/support/faq/platform-and-vendor-partners](https://amp.dev/support/faq/platform-and-vendor-partners)
2. [amp.dev/documentation/tools](https://amp.dev/documentation/tools)

#### 4.1 If you chose 1 in Step 4:
Please provide an image (min. 800x400 pixels) to appear on the [Tools](https://amp.dev/documentation/tools) page, as well as a short description (max. 100 characters).

#### 4.2 If you chose 2 in Step 4:
Please provide link(s) to your documentation page(s) on your domain and for ads, the configuration page in the [ads/](https://github.com/ampproject/amphtml/tree/master/ads) folder of the `amphtml` repository.
```

**Comment by charset-and-forget** [comment]
>Hi @charset-and-forget - sorry for the delayed response! To get your CMS featured, could you please fill out the following template with the requested assets/information?

No problem, @CrystalOnScript the holiday season is always hectic. Happy to move forward with this and create awareness about RebelMouse's awesome AMP support!

 ## 🛠️ Request to Add Third-Party Tool/Service/Platform/Vendor

### 1. Resource name and link

RebelMouse
https://www.rebelmouse.com/amp/

### 2. Relevant format(s)


 
 - [x] websites
 - [x] stories
 - [ ] ads
 - [ ] email
 
 
 ### 3. Resource type
 
 
 
 - [ ] editor
 - [ ] service provider
 - [ ] developer tool
 - [ ] content platform
 - [x] CMS
 - [ ] ads
 - [ ] audio/video
 - [ ] analytics vendor
 
 ### 4. Destination
 - [x] 1. [amp.dev/support/faq/platform-and-vendor-partners](https://amp.dev/support/faq/platform-and-vendor-partners)

 - [x] 2. [amp.dev/documentation/tools](https://amp.dev/documentation/tools)
 
 #### 4.1 If you chose 1 in Step 4:
 Please provide an image (min. 800x400 pixels) to appear on the [Tools](https://amp.dev/documentation/tools) page, as well as a short description (max. 100 characters).
![RM_AMP_Header](https://user-images.githubusercontent.com/45695026/72739172-2701e400-3b71-11ea-8a61-1738bbad8a38.png)
Build AMP sites, posts, and stories. Win search, social, and email. Fast. Flexible. Secure. Modern.
 
 #### 4.2 If you chose 2 in Step 4:
 Please provide link(s) to your documentation page(s) on your domain, <s>and for ads, the configuration page in the [ads/](https://github.com/ampproject/amphtml/tree/master/ads) folder of the `amphtml` repository.</s>
[https://www.rebelmouse.com/amp-stories-2644865309.html](url)
[https://www.rebelmouse.com/amp-2644865462.html](url)

**Comment by CrystalOnScript** [comment]
Thanks for providing this @charset-and-forget ! I've opened a PR to add RebelMouse, however, the link provided:
https://www.rebelmouse.com/amp/

Did not work for me, so I replaced it with:
https://www.rebelmouse.com/amp-2644865462.html

Please let me know if this is okay, or provide me with a preferred link. Thanks :)

**Comment by charset-and-forget** [comment]
My mistake, the link was case sensitive `AMP` not `amp`

Have a great day!

**Comment by CrystalOnScript** [comment]
No problem, I have updated the link! RebelMouse will be on the site with our next deploy :)
