### ISSUE TITLE
Request to add Copernica as a tool that supports AMP for Email

### ISSUE THREAD

**Issue by sanderisbestok** [ampproject/amp.dev#3270]
## Request to add third-party tool/service/platform/vendor

**1. What's the name?**
Copernica [https://www.copernica.com](https://www.copernica.com)

**2. For which format?**
Email

**3. What type is it?**
Service provider

**4. What page should it appear on?**
[amp.dev/documentation/tools](https://amp.dev/documentation/tools)

**5. If you choose 1 in Step 4:**
[https://media.copernica.com/logos/copernica-logo.svg](https://media.copernica.com/logos/copernica-logo.svg)

Copernica is a tool to create automated email campaigns with an powerful drag & drop editor. 

And some documentation
[https://www.copernica.com/nl/documentation/amp](https://www.copernica.com/nl/documentation/amp)

**Comment by matthiasrohmer** [comment]
@fstanis, does Copernica fullfil the criteria to be listed?

**Comment by fstanis** [comment]
Approved, added in #3350

**Comment by sanderisbestok** [comment]
@fstanis could description be changed to, I made a spell error:

Copernica is a tool to create automated email campaigns with a powerful drag & drop editor.

**Comment by fstanis** [comment]
Sure, you can just send us a PR to update [tools.yaml](https://github.com/ampproject/amp.dev/blob/future/pages/shared/data/tools.yaml) and we can merge it.
