### ISSUE TITLE
[Translate_ko] Beginners Course index page

### ISSUE THREAD

**Issue by jeongsd** [ampproject/amp.dev#3289]
**Declare into which language you're translating the document.**
Korean

**Name which file you wish to translate or update.**
https://github.com/ampproject/amp.dev/blob/future/pages/content/amp-dev/documentation/courses/beginning-course/index.md

**Give a rough estimation of how much of the file you are translating.**
index.md

**Provide a general estimation of how much time it will take to complete the translation task.**
1 day

@CrystalOnScript

**Comment by CrystalOnScript** [comment]
@jeongsd that would be great!
