### ISSUE TITLE
Amp-analytics example iframe has 500 internal server error

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amp.dev#3306]
The [amp-analytics example](https://amp.dev/documentation/examples/components/amp-analytics/?format=websites) creates an iframe which is returning a 500 internal server error.

## Expected behavior/code
Looking at `examples/source/1.components/amp-analytics/embed.html` it should be showing information collected through the amp-analytics tag (user account, timestamp, etc...)

### How do we reproduce the issue?
Visit this [link](https://amp.dev/documentation/examples/components/amp-analytics/?format=websites)

Chrome
MacOs

**Comment by patrickkettner** [comment]
this has since been fixed
