### ISSUE TITLE
Irrelevant articles under AMPHTML ads documentation

### ISSUE THREAD

**Issue by lannka** [ampproject/amp.dev#3320]
Many unrelated articles under AMPHTML ads documentation, such as "validation flow", "AMP cache & CORS" etc.

<img width="402" alt="Screen Shot 2019-12-20 at 3 33 26 PM" src="https://user-images.githubusercontent.com/8496897/71298697-255cba80-233e-11ea-94d5-f9c82f1e2a3a.png">

**Comment by matthiasrohmer** [comment]
Doesn't the validation flow also apply to AMP4ADS? Anyway feel free to either compile a list of items that shouldn't appear for ads or disable them yourself by removing `ads` from the `formats` key in the document's frontmatter via a PR 🙂

**Comment by lannka** [comment]
1. Validation does apply to AMP4ADS, but the current links point to AMP page validations.
2. AMP Cache is not relevant to AMP4ADS, as they are not cached. (Like AMP4MAIL)
3. The whole Optimize & Measure section is not relevant
4. The whole Contribute section is not relevant.

I looked at the equivalent AMP4MAIL doc, seems that is more tailored to AMP4MAIL.

**Comment by CrystalOnScript** [comment]
Thanks for flagging! I've opened a PR that filters out some of the documentation you suggested with the following exceptions:

The call to action to contribute to AMP is always relevant. It also does have specific information on ads. 
<img width="302" alt="Screen Shot 2020-03-19 at 11 32 28 AM" src="https://user-images.githubusercontent.com/23297417/77102783-a166ad00-69d6-11ea-80f9-0d1fbaa4e95d.png">

The validation documentation does have ads specific information. 
<img width="1082" alt="Screen Shot 2020-03-19 at 11 38 58 AM" src="https://user-images.githubusercontent.com/23297417/77102866-c3602f80-69d6-11ea-9ea1-ad99ad72cdc3.png">

The validation error page does not show as specific ads information as email or stories - but that is a content update issue. I don't think the entire document should not be removed from the TOC. 

The optimize and measure section has a tutorial on configuring analytics in AMP. Analytics is supported in ads. I'm happy to try and filter for ads specific information if its different enough - or maybe write up a new tutorial.
