### ISSUE TITLE
Can't find links to all AMPHTML ad examples

### ISSUE THREAD

**Issue by lannka** [ampproject/amp.dev#3321]
For example, how can someone navigate to this page from amp.dev main page:

https://amp.dev/documentation/examples/visual-effects/scrollbound_animation_ad/

/cc @ampproject/wg-ads @jeffjose

**Comment by CrystalOnScript** [comment]
[This link should work](https://amp.dev/documentation/examples/?format=ads)

You can get to this by going to amp.dev > documentation > examples, then click the filtering button and selecting `ads`

<img width="909" alt="Screen Shot 2019-12-20 at 3 50 30 PM" src="https://user-images.githubusercontent.com/23297417/71299115-7c638f00-2340-11ea-95b0-84dea97f6035.png">

We're currently exploring user journeys to make the filtering more clear.

**Comment by lannka** [comment]
Thanks for the link!
