### ISSUE TITLE
📖(samples): internal samples tutorial is stale

### ISSUE THREAD

**Issue by DerekNonGeneric** [ampproject/amp.dev#3325]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be updated.**

[adding-embedded-samples-in-docs.md](https://github.com/ampproject/amp.dev/blob/master/contributing/adding-embedded-samples-in-docs.md) seems to be outdated since the [amp-by-example](https://www.npmjs.com/package/amp-by-example) package, which it uses, has been deprecated. The Preview code samples section of [Formatting guides & tutorials](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting/#preview-code-samples) may be the closest current equivalent. 

The old way allowed one to create a standalone sample that was embeddable in multiple documents using an `amp-iframe`. I think independent samples created using the stale document would currently live in [`ampproject/amp.dev/examples/static/samples/`](https://github.com/ampproject/amp.dev/tree/future/examples/static/samples). A new version of this document could also be expanded to include information about how to contribute samples to the [`ampproject/samples` repo](https://github.com/ampproject/samples).

**In which part of the site would that content live?**

Documentation » Guides & Tutorials » CONTRIBUTE » Contribute documentation

**What type of content is it?**

Tutorial.

**Optional: Propose information architecture.**

```ruby
amp.dev
└──  /documentation/
     └──  /guides-and-tutorials/
          └──  /contribute/
               └──  /contribute-documentation/
                    ├──  formatting.md                        # Existing guide.
                    └──  samples.md                           # Future tutorial?
```

/cc @CrystalOnScript

**Comment by CrystalOnScript** [comment]
Thanks for filing this! 

I completely forgot this was here. It is extremely outdated. You're correct, the Preview code samples section of [Formatting guides & tutorials](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting/?format=websites#preview-code-samples) replaced [adding-embedded-samples-in-docs.md](https://github.com/ampproject/amp.dev/blob/master/contributing/adding-embedded-samples-in-docs.md).

Example contribution [instructions are here](https://github.com/ampproject/amp.dev/blob/future/contributing/samples.md), it has been on my TODO to surface this on amp.dev.

**Comment by DerekNonGeneric** [comment]
My pleasure!

Oh wow, I can't believe I missed that, I even contributed to that document! Really looking forward to seeing that document surface.

**Comment by DerekNonGeneric** [comment]
Thank you for the clarification. I just realized why [adding-embedded-samples-in-docs.md](https://github.com/ampproject/amp.dev/blob/master/contributing/adding-embedded-samples-in-docs.md) could have so easily been forgotten about. There are some old internal guides living in the `contributing` folder on [the non-default `master`](https://github.com/ampproject/amp.dev/tree/master/contributing) branch that ceased to exist on [the default `future`](https://github.com/ampproject/amp.dev/tree/future/contributing) branch. Someone fell victim to having the old site on the `master` branch [just the other day](https://github.com/ampproject/amp.dev/pull/3308).


This may be something worth bringing up during the next wg-outreach meeting. Along with a discussion about the branching scheme, there are a few other open issues I'd be interested in participating in a discussion about. If the timing works out, I hope I can join you all on that day. :)
