### ISSUE TITLE
amp-lightbox documentation with a duplicated property

### ISSUE THREAD

**Issue by fellyph** [ampproject/amp.dev#3333]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated.**  
At the documentation page for amp-lightbox the property scrollable is appearing twice:
![Screen Shot 2019-12-29 at 10 57 43](https://user-images.githubusercontent.com/330792/71555991-75b4d600-2a2a-11ea-9c7d-c77308df0db8.png)

**In which part of the site would that content live at?**  
https://amp.dev/documentation/components/amp-lightbox/

**What type of content is it?**  
At the attribute section the scrollable property appears twice and 

**Optional: Propose information architecture.** 
I think the second property should be removed

**Comment by CrystalOnScript** [comment]
Thanks for filing @fellyph - I just caught this one in a [related PR](https://github.com/ampproject/amphtml/pull/26107/files#diff-ac192b7f3e0a63c5a463cfec689a7d4eR102) and should be resolved once it's merged :)
