### ISSUE TITLE
Request to add NodemailerApp as a tool that supports AMP for Email

### ISSUE THREAD

**Issue by andris9** [ampproject/amp.dev#3334]
## 🛠️ Request to add third-party tool/service/platform/vendor

**1. What's the name?**
NodemailerApp

**2. For which format?**
email

**3. What type is it?**
developer tool

**4. What page should it appear on?**
[amp.dev/documentation/tools](https://amp.dev/documentation/tools)

**5. If you chose 1 in Step 4:**  
https://github.com/nodemailer/nodemailer/blob/master/assets/nm_logo_1000x680.png

NodemailerApp is an email debugging app that includes a local SMTP server and renders AMP4Email emails

* https://nodemailer.com/app/
* Blog post: [Testing AMP4Email with Nodemailer](https://blog.nodemailer.com/2019/12/30/testing-amp4email-with-nodemailer/)

**Comment by CrystalOnScript** [comment]
Hi @andris9 ! I've attempted to add NodemailerApp to the tools page, but the dimensions of the logo you provided are not rendering well on the page. Could you please provide an image that is 800 x 400? 
<img width="387" alt="Screen Shot 2020-01-03 at 1 55 17 PM" src="https://user-images.githubusercontent.com/23297417/71751574-dd0ac580-2e30-11ea-82c9-e0792e3b5329.png">

**Comment by andris9** [comment]
@CrystalOnScript hey, sure, here's a 800x400 logo:

https://cldup.com/oxt6985LXt.png

**Comment by CrystalOnScript** [comment]
Awesome, thank you! I opened a [PR](https://github.com/ampproject/amp.dev/pull/3340). The image looks much better! 
<img width="321" alt="Screen Shot 2020-01-03 at 3 32 39 PM" src="https://user-images.githubusercontent.com/23297417/71755234-85735680-2e3e-11ea-87b9-492f09dc7f71.png">

**Comment by matthiasrohmer** [comment]
Resolved by #3340.
