### ISSUE TITLE
Should we remove the phrase "suck less"?

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3336]
From the bottom of [the main documentation page](https://amp.dev/documentation/):

"Check out our community section to join our mission to make the web suck less."

We could add a link there to the Community section. And I'm wondering if we should soften the last few words there.

**Comment by DerekNonGeneric** [comment]
If for no other reason, it is inaccurate.

> **Mission**
>
> Provide a user-first format for web content, supporting the long-term success of every web publisher, merchant, and advertiser.

— [Vision and Mission - amp.dev](https://amp.dev/about/mission-and-vision/)
