### ISSUE TITLE
style_pages.md: Confusing documentation/validator behavior about banned CSS classes and tag names

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amp.dev#3373]
**Please only file reports about bugs in AMP here.**

## What's the issue?

Briefly describe the bug.

> Class names, in author stylesheets, may not start with the string `-amp-`. These are reserved for internal use by the AMP runtime. It follows, that the user's stylesheet may not reference CSS selectors for `-amp-` classes and `i-amp` tags."

 https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages/#disallowed-styles

There are multiple things that seem wrong or incomplete about this documentation.

1. The documentation says that class names cannot start with the string `-amp-`, but then the AMP validator doesn't actually enforce this.
2. On the other hand, the validator does enforce that class names cannot start with `i-amphtml-`, but the `i-amphtml-` prefix isn't documented anywhere (at least I didn't find any).
3. The documentation also says that you cannot reference `i-amp`, missing a `-` at the end. This is not consistent with the previous documentation which does include a `-` at the end: `i-amp-`.
4. The documentation also says that you cannot reference `i-amp-` tag names, but this is not enforced by the validator.
5. What about class names that start with `amp-` such as `amp-element` and `amp-notbuilt`? These are also used internal by the AMP runtime, but the documentation is silent about this and the validator also doesn't ban setting class names to `amp-*`. Wouldn't that cause issues with AMP trying to apply styles to classes that have `amp-` prefix?

/cc @choumx 
/cc @caroqliu

**Comment by zhangsu** [comment]
1-4 are probably all documentation issues, but 5 could be a question for the validator/runtime. Is it okay that developers can style something like the `amp-element` class and also add `amp-element` class to elements in their pages?

**Comment by sebastianbenz** [comment]
@CrystalOnScript can you take a look?

**Comment by choumx** [comment]
> Is it okay that developers can style something like the amp-element class and also add amp-element class to elements in their pages?

For extensions, I think this depends on a case-by-case basis. E.g. important CSS properties under overridable names should be marked `!important` which many extensions do (but some don't consistently).

In runtime, I only saw `.amp-built` and `.amp-notbuilt` which appear low impact (most elements are built before the user sees them) but we can consider changing it.
