### ISSUE TITLE
Convert all animated GIFs to videos

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3392]
The animated GIF on the homepage takes  ~40% of the main thread CPU on a high-end device. It's from a blog post though.

![image](https://user-images.githubusercontent.com/380472/72594890-e142e280-3908-11ea-8061-bd2c9d23ef45.png)

@westonruter is there an easy way in WP to convert animated GIFs?
@matthiasrohmer are you aware of any animated GIFs on amp.dev?

//cc @kristoferbaxter

**Comment by westonruter** [comment]
No, WordPress does not provide transcoding of GIF to video.

Wouldn't this be helped marginally by using `amp-anim` instead of `amp-img`?

Perhaps a non-GIF should be used as the featured image and then the GIF could be transcoded to a video manually and added to the content of a post as a Video block.

**Comment by westonruter** [comment]
Related: https://github.com/WordPress/gutenberg/issues/19730 /cc @pbakaus

**Comment by kristoferbaxter** [comment]
In the interim, can we remove the existing animated gif from the homepage of `amp.dev`? It's blocking some critical performance testing work.

**Comment by sebastianbenz** [comment]
We could try using amp-anim. I'm skeptical though whether this is really
going to help.

>

**Comment by kristoferbaxter** [comment]
I too am skeptical it would improve things meaningfully. Would like to recommend not using animated video/gif until this is resolved.

**Comment by sebastianbenz** [comment]
Yup. I've just replaced the GIF with an image in WP. Triggering a new
deploy now, should be live in an hour.

>

**Comment by kristoferbaxter** [comment]
Thank you!
