### ISSUE TITLE
Wordpress Blog Posts from homepage are using originally uploaded images

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amp.dev#3395]
### Current behavior
Blog posts on the homepage of `amp.dev` are using originally uploaded image content.

![Screenshot from 2020-01-17 13 48 10](https://user-images.githubusercontent.com/61764/72648531-1d3d6e00-3930-11ea-8671-e4540f2a570f.png)

This example image is 838KB and 685/385 pixels. For this surface, the size can be significantly smaller and as a result compress much better. 

Please also provide:
- Page link: https://amp.dev

### Expected behavior/code
Wordpress automatically creates smaller preview images for content uploaded that can be used.

https://blog.amp.dev/wp-json/wp/v2/posts?per_page=3&_embed

From the json feed on posts, look for `_links['wp:featuredmedia']` for the entity. : https://blog.amp.dev/wp-json/wp/v2/media/3064

This JSON feed will return the available media to use including a viable candidate `media_details.sizes.medium`. https://blog.amp.dev/wp-content/uploads/2019/12/Screen-Shot-2020-01-17-at-21.23.56-300x169.png

Using this image cuts the size of this resource from 838KB -> 76KB.

- What browser are you using? Chrome 79
- What O/S are you using? Linux

**Comment by matthiasrohmer** [comment]
Fixed by #3486.
