### ISSUE TITLE
🚀 Give filtered categories a specific URL for easy sharing 

### ISSUE THREAD

**Issue by noodles** [ampproject/amp.dev#3400]
### Problem
The [success stories](https://amp.dev/success-stories/) and [tools](https://amp.dev/documentation/tools) pages have category buttons for filtering the articles/tools. At the moment there is no way to share a single category with someone.

For example, when sharing success stories with a publisher it would be useful to share the list of success stories that are relevant to publishers.

### Solution
Add a anchor tag or URL parameter that directly links to a selected category.

e.g. https://amp.dev/documentation/tools#stories

![Screen Shot 2020-01-21 at 10 35 10 AM](https://user-images.githubusercontent.com/183972/72764023-60eaed00-3c3a-11ea-8dca-dfdb10e84a92.png)

### Page Links

https://amp.dev/documentation/tools
https://amp.dev/success-stories/

**Comment by sebastianbenz** [comment]
It'd be good to have this. I think @matthiasrohmer and I discussed this in the past as well. 

This hits one of the current limitations of AMP. Fragments don't work due to AMP not being able to change the content on page load. However, we could do the same thing server-side, this would mean that clicking on filter reloads the page.

**Comment by matthiasrohmer** [comment]
I agree and also think we ultimately decided to drop the client-side filtering and use SSR instead. But if I remember correctly the tools page was also one of the first to get SSR which was a little rough around the edges at first and made us revert the PR multiple times (#2509, #2559, #2623) which might have caused it to never make it to production 😬 I'll look into this.
