### ISSUE TITLE
[blog] Mismatching CSP security headers

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3421]
<img width="411" alt="Screen Shot 2020-01-27 at 20 02 27" src="https://user-images.githubusercontent.com/380472/73204857-0cff6d00-4140-11ea-8b72-7d83ec1e2b85.png">

@westonruter can you take a look?

**Comment by westonruter** [comment]
@sebastianbenz Pantheon has added direct support for sending this header now and so it was conflicting with what the site was sending manually.

I've implemented the `enforce_https: full` configuration as described https://pantheon.io/docs/pantheon-yml and removed the site's manual sending of `Strict-Transport-Security: max-age=604800; preload`.

**Comment by westonruter** [comment]
@sebastianbenz Would you like to retain the `preload` flag? If I implement `enforce_https: full+subdomains` then this will be added.

**Comment by sebastianbenz** [comment]
I don't think it's critical. Your decision :-)

**Comment by westonruter** [comment]
Change applied.

```
$ curl -sI https://blog.amp.dev | grep strict-transport-security
strict-transport-security: max-age=31622400; includeSubDomains; preload
```

**Comment by sebastianbenz** [comment]
Awesome! Thanks!

>
