### ISSUE TITLE
AMP Broilerplate

### ISSUE THREAD

**Issue by okabrionz** [ampproject/amp.dev#3464]
Saat saya klik Google analytics pada fitur amp broilerplate, saya menemukan script video masuk kedalam tampilan yang seharusnya tidak ada.

**Comment by DerekNonGeneric** [comment]
Translated from Indonesian:
> When I click Google analytics on the 'amp broilerplate' feature, I find the video script entered into a view that should not be there.

**Comment by matthiasrohmer** [comment]
Did the same but couldn't reproduce it 😉 My feeling is that @okabrionz selected "Video" in the structured data section before. Once anything is selected in this section it can't be unselected. This is what might cause confusion.
