### ISSUE TITLE
Incomplete metadata for docs

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp.dev#3472]
I shared the reference docs for amp-subscription, and the title is less meaningful than it could be:
![Screenshot_20200201-090022](https://user-images.githubusercontent.com/89679/73690402-2004c680-4685-11ea-9a6d-4e84fc97aabc.png)

**Comment by matthiasrohmer** [comment]
Thanks for the report! That's sadly valid for all component docs. The frontmatter actually contains all the information. The problem is the component's name is fenced in `<` and `>` which gets stripped out by Twitter.
