### ISSUE TITLE
Shared paths of new and old version of components breaks build

### ISSUE THREAD

**Issue by DerekNonGeneric** [ampproject/amp.dev#3477]
### Current behavior
A clear and concise description of the bug you found in amp.dev.

Running `gulp develop` crashes.

```
    raise PathConflictError(path, value, self.value)
grow.routing.routes.PathConflictError
: Path already exists: /documentation/components/amp-date-display.html (<RouteInfo kind=doc meta={'locale': 'en', 'pod_path': u'/content/amp-dev/documentation/components/reference/amp-date-display-v0.1.md', 'collection_path': '/content/amp-dev/documentation/components/reference/'}> != <RouteInfo kind=doc meta={'locale': 'en', 'pod_path': u'/content/amp-dev/documentation/components/reference/amp-date-display-v0.2.md', 'collection_path': '/content/amp-dev/documentation/components/reference/'}>)
```

```
    raise PathConflictError(path, value, self.value)
grow.routing.routes.PathConflictError: Path already exists: /documentation/components/amp-next-page.html (<RouteInfo kind=doc meta={'locale': 'en', 'pod_path': u'/content/amp-dev/documentation/components/reference/amp-next-page-v0.2.md', 'collection_path': '/content/amp-dev/documentation/components/reference/'}> != <RouteInfo kind=doc meta={'locale': 'en', 'pod_path': u'/content/amp-dev/documentation/components/reference/amp-next-page-v1.0.md', 'collection_path': '/content/amp-dev/documentation/components/reference/'}>)
```

Please also provide:
- ~~Page link: <insert the URL link to the amp.dev page(s) that you found the issue on>~~
- ~~(Optional) Screenshots/videos:~~

### Expected behavior/code

`amp-date-display-v0.1.md` & `amp-date-display-v0.2.md` not use the same path.

`amp-next-page-v1.0.md` & `amp-next-page-v.0.1md` not use the same path.

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. `npm i && npx gulp bootstrap && npx gulp develop`

---

- What browser are you using? Windows Server (WSL Debian 10)
- What O/S are you using? n/a

**Comment by DerekNonGeneric** [comment]
FWIW, I solved this by removing these keys from the frontmatter of the old versions.

```
is_current: [...]
$path: [...]
$localization: [...]
```

I also added this key if it was missing.

```
versions: [...]
```

Pretty sure these get pulled in from the `amphtml` repo.

**Comment by matthiasrohmer** [comment]
@patrickkettner had similar issues 🙁 They'll be gone with #3344 which currently has other issues I am still fixing up.

The file's content indeed gets imported from ampproject/amphtml but the frontmatter is actually auto-generated during import which seems to fail at some point and creates duplicate paths.

**Comment by matthiasrohmer** [comment]
Shouldn't happen anymore with the new importer. Anyhow please reopen if you experience it again.

**Comment by DerekNonGeneric** [comment]
@matthiasrohmer, I would re-open if I could. :)

**Comment by matthiasrohmer** [comment]
Still happening for you even being on `future` and after running `gulp importAll` again?

**Comment by DerekNonGeneric** [comment]
Yes, that is correct.

**Comment by matthiasrohmer** [comment]
@DerekNonGeneric you've got some more details for me? For which components there are path conflicts?

**Comment by DerekNonGeneric** [comment]
The errors in [the CI logs](https://travis-ci.org/ampproject/amp.dev/builds/652395811) are the same exact ones I get on my machine.

**Comment by matthiasrohmer** [comment]
Ah alright 🙂 Thanks for clarifying. Those are actually unrelated to those that have been triggering this issue.

Also thanks for the reminder on your PR. Coming back to you on that today.
