### ISSUE TITLE
Remove custom loader in favor of amp-loader

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3481]
I'd vote for removing our custom loader (tiny, blinking flash) to reduce code and also because AMP's new built-in loader looks fairly decent.

Another problem with our custom one is that it isn't used consistently across the site and isn't always positioned correctly.

![Bildschirmfoto 2020-02-06 um 09 44 01](https://user-images.githubusercontent.com/12857772/73920664-233ac500-48c6-11ea-89aa-7087ded9bcba.png)

**Comment by sebastianbenz** [comment]
yes very much please
