### ISSUE TITLE
Privacy Policy seems not right

### ISSUE THREAD

**Issue by amanintech** [ampproject/amp.dev#3484]
### Problem
In a discussion with @mrjoro I got to know AMP is trying to stay Independent from Google even though it was founded by them. Now this confuses me as the privacy policy still links to Googles Page so does that means AMP shares the web PP with Google and so does the cookies and user information

### Location
Footer of AMP.dev
### Content type
Privacy Policy
https://policies.google.com/privacy?hl=en

### Information architecture (optional)
We can document the PP and host it inside AMP.dev to avoid confusion.

**Comment by matthiasrohmer** [comment]
Good point! Looping in @tobie as that's also related to the work of ampproject/wg-foundation-onboarding.

**Comment by mrjoro** [comment]
Thanks for raising this issue!  We're tracking the change here:  https://github.com/ampproject/wg-foundation-onboarding/issues/13

We're working to determine what the proper privacy policy should be as an OpenJSF project.

**Comment by mrjoro** [comment]
More broadly, we're tracking all of the OpenJSF onboarding work here:  https://github.com/orgs/ampproject/projects/4

If you see something that should be changed as we transition AMP from Google to OpenJSF that isn't tracked there, please let us know! :)

**Comment by matthiasrohmer** [comment]
... could have also quickly scanned the issues 😬 Thanks, @mrjoro!

**Comment by mrjoro** [comment]
Haha, no worries... there are a lot of issues kind of spread around a bit. :)

**Comment by amanintech** [comment]
@mrjoro will definitely do more contribution. Do you think there is a dedicated team I can be part of and contribute

**Comment by mrjoro** [comment]
Great!  Take a look at the working groups and see if there are many that match your interests; you can then reach out in the working group's Slack channel or to the working group facilitator on Slack directly.

https://github.com/ampproject/meta/tree/master/working-groups
