### ISSUE TITLE
Remove select format call out on mobile?

### ISSUE THREAD

**Issue by wassgha** [ampproject/amp.dev#3515]
### Current behavior
The select format call out makes sense on desktop but it's not idea on mobile for a few reasons:
- It's not clear what this call out is pointing at (on desktop it's clearly pointing at a drop down)
- Swiping up and down detaches the caret from the callout which makes it look broken
- The close icon is not visible
![IMG_6434](https://user-images.githubusercontent.com/591655/74273674-b2c8e500-4cc5-11ea-92cf-a9996182ae9e.GIF)

**Comment by matthiasrohmer** [comment]
@robinvanopstal, please hide the hint for small screens.
