### ISSUE TITLE
Stories tutorial returns a 404

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3519]
https://amp.dev/about/documentation/guides-and-tutorials/start/visual_story/index.md?format=stories

**Comment by matthiasrohmer** [comment]
Huh? That's a really strange link. First-level `/about/` and ending in `.md`. Do you recall from which page you got this?

**Comment by sebastianbenz** [comment]
https://amp.dev/about/stories/ => Start Developing

>
