### ISSUE TITLE
[Translate_pt_BR]  Beginners Course - Our First AMP Page

### ISSUE THREAD

**Issue by fellyph** [ampproject/amp.dev#3538]
### Synopsis
Hi @CrystalOnScript
I would like to translate the "Our First AMP Page" section from Beginners course to Brazilian Portuguese: https://amp.dev/pt_br/documentation/courses/beginning-course/our-first-amp-page/?level=beginner

### Content type

- [ ] Guide
- [ ] Tutorial
- [ ] Example
- [x] Translation
- [ ] Other (please specify)

### Process
Read the [contributing guide](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/?format=websites), then create a copy of [this template](https://docs.google.com/document/d/18i_lbQ-h-auYW2SwbWRuuu2_xhtU5XrjXlcCtj0sNeY/edit?usp=sharing) and fill in the proposal and outline sections. When you’ve finished, add the link to this issue and check the box for step one. A member of the AMP team will assign the ticket to themselves and work as your reviewer through the remaining steps. Thanks for contributing to AMP! 

- [ ] 1. Proposal created: `<link to proposal>`.
- [ ] 2. Proposal approved.
- [ ] 3. Draft complete.
- [ ] 4. Draft approved.
- [ ] 5. Pull request submitted.
- [ ] 6. Pull request approved!

**Comment by CrystalOnScript** [comment]
Thank you! This would be fantastic! 

CC @patrickkettner and @morsssss

**Comment by patrickkettner** [comment]
Closing due to time, please do reach out @fellyph if you would like to work on anything or have any questions :D

**Comment by morsssss** [comment]
Good news is that this was done by someone else a few months ago - and @fellyph kindly reviewed the work.
