### ISSUE TITLE
Wrong component script for amp-video in boilerplate generator

### ISSUE THREAD

**Issue by iaroel** [ampproject/amp.dev#3541]
https://cdn.ampproject.org/v0/amp-video-1.0.js
404. That’s an error.

The requested URL /v0/amp-video-1.0.js was not found on this server. That’s all we know.

**Comment by matthiasrohmer** [comment]
`amp-video`s only release is `0.1`. The correct URL would therefore be: `https://cdn.ampproject.org/v0/amp-video-0.1.js`.

Just a typo or where did you get this URL from? 🙂Everything on https://amp.dev/documentation/components/amp-video/?format=websites looks fine.

**Comment by iaroel** [comment]
It's generated by the boilerplate generator https://amp.dev/boilerplate/

**Comment by matthiasrohmer** [comment]
Fixed by #3551 as soon as it's merged.
