### ISSUE TITLE
Sections hidden for a certain AMP format aren't hidden in the table of content

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amp.dev#3545]
### Current behavior

One example:

https://amp.dev/documentation/components/amp-form/?format=email#redirecting-after-a-submission

The "Redirecting after a submission" section is hidden when the selected format is "Email", but it's still displayed in the table of content on the right. Clicking on it from the table of content does nothing because the section that corresponds to the anchor is missing on the page.

### Expected behavior/code

Hidden section not displayed in the table of content.

**Comment by sebastianbenz** [comment]
Thanks for reporting! Looks like the TOC is generated independently from filtering. //cc @matthiasrohmer

**Comment by matthiasrohmer** [comment]
Yep, we had a similar issue for the courses: https://github.com/ampproject/amp.dev/issues/2774#issuecomment-522505642. @tharders did you had a specific idea how to implement this?
