### ISSUE TITLE
Code samples not working in blog

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#3548]
Please see the code blocks in: https://blog.amp.dev/2018/05/03/dynamic-geo-personalization/

**Comment by matthiasrohmer** [comment]
@westonruter, as always: let us know if we can help 🙂

**Comment by westonruter** [comment]
@CrystalOnScript I'm not sure what the intended behavior is. Are these code samples supposed to be running or are they supposed to be examples that the reader should copy/paste? If the latter, you should be using the Code block in the editor and put the code samples inside each one.

**Comment by westonruter** [comment]
For example, look at the WordPress edit screen for this post: https://blog.amp.dev/2019/11/19/creating-delightful-user-experiences-using-amp-on-adobe-experience-manager/

**Comment by westonruter** [comment]
In other words, the `[code]` shortcode is obsolete in favor of the Code block.

**Comment by CrystalOnScript** [comment]
From my understanding they should just be simple code blocks. I do not think they run.

**Comment by westonruter** [comment]
Oh, I see. This is legacy content. I'll update it.

**Comment by westonruter** [comment]
Fixed.

<table><thead><tr><th>Before</th><th>After</th></tr></thead><tbody><tr valign=top><td><img src="https://user-images.githubusercontent.com/134745/74578558-53c7d200-4f4a-11ea-843f-b36f1f65ee45.png"></td><td><img src="https://user-images.githubusercontent.com/134745/74578561-5aeee000-4f4a-11ea-9b46-8cb8a6a2ce41.png"></td></tr></tbody></table>

**Comment by matthiasrohmer** [comment]
Thanks, Weston!
