### ISSUE TITLE
Make git util lazy and use sh over execSync

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3553]
Isolated from #3330.

https://github.com/ampproject/amp.dev/blob/551ee7fb30b9778cc68c3f70319ac7d876192258/platform/lib/utils/git.js#L18-L26

git.js currently does three `execSync` operations as soon as it is required. That's bad. Especially because not all of the computed values are needed for development or are even available. 

Therefore we should refactor the util to be Promise-based, cache the computed values where it makes sense and use our `sh` util instead of `execSync` directly.

**Comment by sebastianbenz** [comment]
Good find!

>

**Comment by patrickkettner** [comment]
closing in favor of #5125
