### ISSUE TITLE
Component reference: relative GitHub links are broken

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3565]
See link: `../amp-access/amp-access.md` in https://github.com/ampproject/amphtml/blob/master/extensions/amp-subscriptions/amp-subscriptions.md

Which gets resolved to: https://amp.dev/github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access.md

**Comment by matthiasrohmer** [comment]
Paul's fix (#3563) just hadn't made it to production yet. Started build [8788](https://travis-ci.org/ampproject/amp.dev/builds/652569354).

It's already fine on staging https://amp-dev-staging.appspot.com/documentation/components/amp-subscriptions/?format=websites.

**Comment by sebastianbenz** [comment]
Thanks
