### ISSUE TITLE
amp-bind doc page shows no import script

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3572]
No import script in the table:

https://amp.dev/documentation/components/amp-bind/?format=websites

**Comment by robinvanopstal** [comment]
Scripts are also missing in: 
![Bildschirmfoto 2020-02-20 um 10 09 22](https://user-images.githubusercontent.com/35134232/74918373-45097100-53c9-11ea-93f8-2e4254a201ee.png)
