### ISSUE TITLE
Remove dependency hints and dependency injection extension

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3576]
In our templates we hint for used AMP components like so:

https://github.com/ampproject/amp.dev/blob/0da7c0f3b1bba02555beb21abeb93ab9a5b1e107/pages/content/amp-dev/index.html#L53-L55

The amp-toolbox/optimizer recently started to support auto-injection of missing `<script>` tags which would allow us to get rid of those hints as well as remove the related Grow extension [amp-dependencies](https://github.com/ampproject/amp.dev/tree/future/pages/extensions/amp_dependencies).

**Comment by patrickkettner** [comment]
resolved by #4117
