### ISSUE TITLE
amp-story beginners guide incorrectly configures Facebook share icon

### ISSUE THREAD

**Issue by philkrie** [ampproject/amp.dev#3587]
### Problem
The amp-story guide "Create your first AMP Story" has a confusing section "[Creating the Bookend](https://amp.dev/documentation/guides-and-tutorials/start/visual_story/create_bookend/?format=websites)" that omits the fact that Facebook requires a config object in shareProviders. Without a Facebook App ID, the share link gets an error. Since someone might use this as a starter, it should at least be mentioned or correctly configured in the example, as described in the amp-story-bookend [documentation](https://amp.dev/documentation/components/amp-story-bookend/).

### Location
https://amp.dev/documentation/guides-and-tutorials/start/visual_story/create_bookend/?format=websites
### Content type
Tutorial

**Comment by patrickkettner** [comment]
Closing as we no longer have the documentation to be out of date 🙃
