### ISSUE TITLE
Comment form on blog posts needs styling

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3590]
### Current behavior
The comment form on blog posts seems to lack proper styling. The input fields are far too short, and the text near checkboxes lies beneath them and is so narrow that it wraps unnecessarily.

Please also provide:
- Page link: https://blog.amp.dev/2020/02/20/amp-conf-2020-return-to-nyc/

- (Optional) Screenshots/videos:

<img width="812" alt="Screen Shot 2020-02-23 at 6 54 06 PM" src="https://user-images.githubusercontent.com/29419498/75122681-2b3c8800-566e-11ea-9b56-9b48050d7701.png">

- What browser are you using?
Chrome 80

- What O/S are you using?
Mac OS

**Comment by sebastianbenz** [comment]
Good point. Wondering whether we should keep it as comments are not listed anyway. 

//cc @alexduran4

**Comment by matthiasrohmer** [comment]
@sebastianbenz, slightly related: is there any news on the plan to switch over to using WordPress headless?

**Comment by sebastianbenz** [comment]
Afaik, we're not showing the comments anywhere. Wouldn't it make sense to disable comments in that case?

**Comment by matthiasrohmer** [comment]
Definitely! But if we're switching anyway this issue (and some others related to blog styling/UX) would become obsolete or at least be in our responsibility 🙂

**Comment by patrickkettner** [comment]
@westonruter can we disable the comment form from showing up?

**Comment by westonruter** [comment]
Done!
