### ISSUE TITLE
Component table description does not render Markdown

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3591]
<img width="708" alt="Screen Shot 2020-02-24 at 10 34 53" src="https://user-images.githubusercontent.com/380472/75141505-5ae0a400-56f1-11ea-8686-e3025a3b632f.png">

https://amp.dev/documentation/components/amp-date-display/?format=websites

**Comment by robinvanopstal** [comment]
Closed as discussed in #3610
