### ISSUE TITLE
I2I: New Roadmap page 

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3594]
## Problem

The current [Roadmap](https://amp.dev/community/roadmap/) contains stale content as AMP progress is now tracked via working groups.

## Proposed Solution

Pull in status updates from the working groups ([example](https://github.com/ampproject/wg-ui-and-a11y/issues?utf8=%E2%9C%93&q=is%3Aissue++label%3A%22Type%3A+Status+Update%22+)). 

Here is a rough mock (not the actual design):

<img width="932" alt="Screen Shot 2020-02-24 at 10 47 13" src="https://user-images.githubusercontent.com/380472/75143313-148d4400-56f5-11ea-9d13-861c3eb9083f.png">

The important things are:

1. The intro paragraph should link to:
   * the yearly high-level AMP roadmap blog post
   * the list of [open intent-to-implements](https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+label%3A%22INTENT+TO+IMPLEMENT%22)
   * the list of [open feature requests](https://github.com/ampproject/amphtml/issues?q=is%3Aopen+is%3Aissue+label%3A%22Type%3A+Feature+Request%22)
1. A list of recent wg status updates 
    * (ordered by date of publish in descending order).
    * wg status updates should be filterable by working group. Note: we should find better labels for the working groups to make it easier to understand what they do.
     *  We might need to come up with a new template for wg status updates (to simplify parsing) and normalize existing updates.

@nainar please add anything I've missed.

//cc @matthiasrohmer @robinvanopstal

**Comment by nainar** [comment]
Plan LGTM

**Comment by sebastianbenz** [comment]
@matthiasrohmer should we discuss the UX in our sync next Monday?

**Comment by sebastianbenz** [comment]
Few examples links for status updates:

https://github.com/ampproject/wg-runtime/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Type%3A+Status+Update%22
https://github.com/ampproject/wg-ui-and-a11y/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Status+Update%22
