### ISSUE TITLE
Consider including ABE in site search

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp.dev#360]
A query like this one works https://www.google.com/search?q=live+list&as_sitesearch=www.ampproject.org&search=#q=live+list+(site:www.ampproject.org+OR+site:ampbyexample.com)&*

**Comment by pbakaus** [comment]
@cramforce I'm not sure how to build the query without resorting to JavaScript. Thoughts?

**Comment by pbakaus** [comment]
I still don't know how to actually do this without resorting to JS.

**Comment by sebastianbenz** [comment]
done
