### ISSUE TITLE
Update Ads and Stories CSS limits

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#3604]
In some places the CSS limit for Stories and Ads reflects the 75kb update. These formats are unaffected. 

https://amp.dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations/?format=stories

https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/?format=stories

https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/?format=ads

**Comment by patrickkettner** [comment]
@CrystalOnScript what is the limit for Ads and Stories?
