### ISSUE TITLE
amp-script demo on playground is near useless

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amp.dev#3608]
### Current behavior
Due to the [playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-script) being a single file, the samples for amp-script are inlined. [Due to the hash requirements](https://amp.dev/documentation/components/amp-script/?format=websites#security-features), it means that any time a single byte is modified, the demo breaks with no obvious reason until you dig into the console errors.

### Expected behavior/code
You should be able to edit the amp-script demo without recompiling the hash every time

**Comment by patrickkettner** [comment]
@sebastianbenz can we recompile and inject the hash somehow?

**Comment by sebastianbenz** [comment]
Yes! We should do this! We can use [toolbox-script-csp](https://github.com/ampproject/amp-toolbox/tree/master/packages/script-csp) to generate the hash. Integration could work similar to [auto-importer](https://github.com/ampproject/amp.dev/blob/future/playground/src/auto-importer/auto-importer.js) (most likely a lot easier).
