### ISSUE TITLE
Format user notification defaults to email

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3613]
🐛 Bug Report

This may relate to #3592 .

### Current behavior
If I go to a URL with no query string, I get this format notification:

![Screen Shot 2020-02-27 at 4 43 07 PM](https://user-images.githubusercontent.com/29419498/75489648-a52b8480-5980-11ea-8600-341475e1aa41.png)

If I click the "X" to dismiss it, I end up choosing "email".

![Screen Shot 2020-02-27 at 4 43 44 PM](https://user-images.githubusercontent.com/29419498/75489694-b4123700-5980-11ea-9498-7590688f8363.png)

This is on Chrome 80, Mac OS.

Please also provide:
- Page link: https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial/

### Expected behavior/code
I'd expect that no selection would be made.

**Comment by robinvanopstal** [comment]
Fixed by #3611.
Since needed for the sidebar's `format-toggle` hovering the format buttons generated an after element which enlarged its click area.
