### ISSUE TITLE
Add ExpressPigeon to AMP Email providers and editors

### ISSUE THREAD

**Issue by ipolevoy** [ampproject/amp.dev#3616]
### 1. Resource name
ExpressPigeon

### 2. Relevant format(s)

- [ ] websites
- [ ] stories
- [ ] ads
- [x ] email

### 3. Resource type

- [ x] editor
- [ x] service provider
- [ ] developer tool
- [ ] content platform
- [ ] CMS
- [ ] ads
- [ ] audio/video
- [ ] analytics vendor

### 4. Destination
1. [amp.dev/support/faq/platform-and-vendor-partners](https://amp.dev/support/faq/platform-and-vendor-partners)
2. [amp.dev/documentation/tools](https://amp.dev/documentation/tools)

#### 4.1 If you chose 1 in Step 4:
Please provide an image (min. 800x400 pixels) to appear on the [Tools](https://amp.dev/documentation/tools) page, as well as a short description (max. 100 characters).

![ep-for-amp](https://user-images.githubusercontent.com/500941/75573748-17ed3c00-5a23-11ea-926c-f0fd4a15e124.png)

Description: 
Create and send beautiful dynamic messages using Drag and Drop. 
No coding required.

#### 4.2 If you chose 2 in Step 4:
Please provide link(s) to your documentation page(s) on your domain and for ads, the configuration page in the [ads/](https://github.com/ampproject/amphtml/tree/master/ads) folder of the `amphtml` repository.

https://expresspigeon.com/amp-dynamic-email

**Comment by fstanis** [comment]
Thanks, added in #3671. Just as heads up, we're moving service providers from the tools section to the FAQ soon, so this is where the change will land.

**Comment by ipolevoy** [comment]
@fstanis thank  you for taking care of this. Do you have a plan to push this to prod?

**Comment by sebastianbenz** [comment]
It's already live: https://amp.dev/support/faq/email-support/

>

**Comment by ipolevoy** [comment]
I see, but not listed here: https://amp.dev/documentation/tools/, under Creation and Design, with description and  the logo attached. Our platform includes a full UI drag and drop email AMP composer.

**Comment by fstanis** [comment]
Is this tool part of your platform or a separate one? We no longer list ESPs in the tools section, but if your tool is platform-independent, I think we can put it in the tools section.

@sebastianbenz let me know if this is in line with how we list tools on the website in general.

**Comment by ipolevoy** [comment]
@fstanis our editor is not currently available independent of our platform.
