### ISSUE TITLE
Make component categories linkable

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3619]
I'd like to be able to link all components for a specific category, e.g.: https://amp.dev/documentation/components/ with `Dynamic content` preselected.

//cc @robinvanopstal @matthiasrohmer

**Comment by matthiasrohmer** [comment]
So same procedure as with https://github.com/ampproject/amp.dev/pull/3425? Ditch client-side filtering in favor of deep-linking?

**Comment by sebastianbenz** [comment]
Yes.

**Comment by sebastianbenz** [comment]
Some components are also listed under `none`:

<img width="1006" alt="Screen Shot 2020-03-02 at 13 56 14" src="https://user-images.githubusercontent.com/380472/75678537-28edb580-5c8e-11ea-90f7-97a6a5e247bb.png">
