### ISSUE TITLE
Update component (docs) contribution guidelines

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3623]
Per #3610 and others it's not possible to use Markdown in teaser texts for component docs. This needs to be documented somewhere. 

While searching for the documentation template in the ampproject/amphtml repository to do so (@CrystalOnScript, can you tell me where it is? 😁) I stumbled over https://github.com/ampproject/amphtml/blob/master/contributing/building-an-amp-extension.md. This for example still lists a *Summary table* as required which isn't the case anymore.

Documenting how to write docs for the components is one thing but I would actually find it quite interesting to show documents like the one above in the *Contributing* section on amp.dev as well. @CrystalOnScript, @sebastianbenz, what do you think?

**Comment by CrystalOnScript** [comment]
Thanks for flagging this! I didn't know this piece of documentation existed - it really needs an update.

The [reference documentation template is here!](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/extension-generator/extension-doc.template.md). The table is pulled out of it, but it doesn't specify that markdown cannot be used in frontmatter...  I've opened [an issue](https://github.com/ampproject/amphtml/pull/27056)

I am all for surfacing this type of documentation on amp.dev! But this one will need some serious updating before we can do so.
