### ISSUE TITLE
Improve filter block matching

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3658]
Every once in a while a corrupt `[filter]` statement in one of the imported docs breaks the build. Cases that I remember when this happened:

- `[filter formats="websites]`: missing quote
- `[filter formats='websites"]`: non-matching quotes
- Unclosed `[filter]` block

Those should all be handled gracefully instead of breaking the build. Could be fixed with #3657.

**Comment by patrickkettner** [comment]
closing as it is [outdated](https://github.com/ampproject/amp.dev/pull/3733#issuecomment-757328420
), and taken care of by grow v1
