### ISSUE TITLE
Component page: amp-lightbox, does not work in translation

### ISSUE THREAD

**Issue by alexandr-kazakov** [ampproject/amp.dev#3659]
## What's the issue?

If you go to the page: https://amp.dev/documentation/components/amp-lightbox/?format=websites and switch the language in the site header, then the page will stop working. I tested it in Russian.

## How do we reproduce the issue?

I have seen this bug many times, on different days, it is 100% there. I recorded a short video of what it looks like for me: http://bit.ly/2It6nbU To the browser console shows that the entire page is covered by amp-lightbox :smile: that's why you can't click anywhere on the page.

If you don't see this bug, try the following:

1. Go to the main page and switch to English in the site header.
2. In the site header, go to the components page. Next, in the sidebar on the left, select amp-lightbox.
3. Switch to Russian in the site header. Switch to Russian in the site header. In this case, I have 100% stops working.

## What browsers are affected?

Tested in different browsers from the computer, at different times. 

## Which AMP version is affected?

Version 2002251816300

**Comment by CrystalOnScript** [comment]
Just tested it on my machine, that is a weird bug - 100% there. Thanks for filing @alexandr-kazakov!
