### ISSUE TITLE
AMP Copy button Playground error

### ISSUE THREAD

**Issue by photocoder** [ampproject/amp.dev#3660]
## What's the issue?

I'm trying to use "copy button", but even example code doesn't work and **AMP Validator** show errors.

## How do we reproduce the issue?

1. Visit https://amp.dev/documentation/examples/interactivity-dynamic-content/copy_button/?format=websites#asd and go to **Open in Playground**.
And even there I see **3 errors** message on the top
2. Copy code from left panel to my website: https://dimasfrolov.com/test/2/

And what I see? 
1. It included my page in iframe
2. copy button doesn't work
3. amp validator shows https://validator.ampproject.org/#url=https%3A%2F%2Fdimasfrolov.com%2Ftest%2F2%2F

## What browsers are affected?

Version 80.0.3987.132 (Official Build) (64-bit)

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 2002251816300

**Comment by photocoder** [comment]
Powered by AMP ⚡ HTML – Version 2003031842100 
And the error is still there....  
Check it out: [https://dimasfrolov.com/test/2/]( https://dimasfrolov.com/test/2/)

**Comment by qwerqian** [comment]
<amp-iframe sandbox="allow-scripts" width="50" height="42" frameborder="0" src="https://www.xxx.com/copy.html#texttext">
                            <button class="copy-button" placeholder disabled>Copy</button>
                        </amp-iframe>
https://www.xxx.com/copy.html   Must be an accessible html page with copy capability

**Comment by qwerqian** [comment]
```
 <amp-iframe sandbox="allow-scripts" width="50" height="42" frameborder="0" src="https://www.xxx.com/copy.html#texttext">
                            <button class="copy-button" placeholder disabled>Copy</button>
                        </amp-iframe>
```
https://www.xxx.com/copy.html   Must be an accessible html page with copy capability
Example
`<!DOCTYPE html>

<html>

<head>
    <style>
        /* so button can go to edge */
        
        body {
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Roboto", "Segoe UI", "Oxygen-Sans", "Ubuntu", "Cantarell", "Helvetica Neue", sans-serif;
        }
        /* common styles for button */
        
        button#copy {
            box-sizing: border-box;
            font: inherit;
            font-size: 14px;
            font-weight: 500;
            line-height: 1.2;
            background: #333;
            cursor: pointer;
            border: 2px solid transparent;
            padding: 0;
            text-align: center;
            color: #fff;
            display: block;
        }
        /* cursor/size for within iframe */
        
        button#copy {
            cursor: copy;
            width: 100vw;
            height: 55vh;
        }
        /* custom focus effect (outline would be cropped) */
        
        button#copy:active,
        button#copy:focus {
            outline: 0;
            border-color: yellow;
        }
        
        #copy svg {
            width: 18px;
            height: 18px;
            vertical-align: middle
        }
        
        #copy svg path {
            fill: #fff
        }
    </style>
</head>

<body>
    <button id="copy">Copy</button>
    <input type="text" id="_i" hidden />
    <script>
        /*
          When the copy button is pressed, we:
          * decode the text from the hash, as that's how the text is passed to us
          * place it in our hidden text element,
          * show and focus the input, so the browser lets us copy it
          * call `execCommand('copy')`, to perform the actual copy
          * before hiding it again.
          See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
         */
        copy.onclick = function() {
            _i.value = window.decodeURIComponent(window.location.hash.substr(1));
            _i.hidden = false;
            _i.select();
            _i.focus();
            document.execCommand('copy');
            _i.hidden = true;
            _i.value = '';
        };
    </script>
</body>`

**Comment by qwerqian** [comment]
`<amp-iframe sandbox="allow-scripts" width="50" height="42" frameborder="0" src="https://www.xxx.com/copy.html#texttext">
                            <button class="copy-button" placeholder disabled>Copy</button>
                        </amp-iframe>`
https://www.xxx.com/copy.html Must be an accessible html page with copy capability
Example
https://wholesale.hchairbeauty.com/copy.html
