### ISSUE TITLE
Document resolving in ComponentReferenceImporter fails for amp-next-page

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3675]
via @CrystalOnScript:

>Hey ya'll, got another weird issue I think is related to the table autogeneration

>The content for amp-next-page has a script tag for v 1.0: https://amp.dev/documentation/components/amp-next-page/?format=websites

>But shows the content from 0.1: https://github.com/ampproject/amphtml/blob/master/extensions/amp-next-page/0.1/amp-next-page.md

**Comment by robinvanopstal** [comment]
This will be solved with ampproject/amphtml#26841 since we're only importing stable versions.

Another related question would be if experimental versions should be selected as default ... or should we stay with the latest stable version here?

**Comment by sebastianbenz** [comment]
Experimental versions should not be the default.

**Comment by CrystalOnScript** [comment]
Thanks for filing @matthiasrohmer !
