### ISSUE TITLE
AMP playground is marking font-display with red background 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#3686]
The playground renders use of `font-display` with a red background, but gives no validation errors. I think this might be related to how we're importing CSS specifiers here:

https://github.com/ampproject/amp.dev/blob/future/playground/src/editor/editor.js

Which appears to come from here:
https://github.com/codemirror/CodeMirror/blob/master/mode/css/css.js

A quick search reveals that `font-display` is not listed. 

This will be problematic as we advise developers to use `font-display` instead of `amp-font`. 

cc// @caroqliu 

<img width="1477" alt="Screen Shot 2020-03-13 at 11 58 20 AM" src="https://user-images.githubusercontent.com/23297417/76651602-15f6a300-6522-11ea-9148-6ae748a4ad65.png">

**Comment by patrickkettner** [comment]
created a [PR](https://github.com/codemirror/CodeMirror/pull/6177) to add this upstream

**Comment by patrickkettner** [comment]
that PR has been merged, I assume that renovate bot will give us the update once its published, right @CrystalOnScript @sebastianbenz ?

**Comment by matthiasrohmer** [comment]
Thanks for fixing upstream @patrickkettner! 🙂 Indeed Renovate will create a PR as soon the update is out.

**Comment by matthiasrohmer** [comment]
Fixed by #3822.
