### ISSUE TITLE
amp-mustache component main description displays escaped markdown link

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amp.dev#3687]
### Current behavior

The main description of the `amp-mustache` component displays escaped Markdown links literally:

```
Allows rendering of [Mustache.js](https://github.com/janl/mustache.js/) templates.
```

Please also provide:
- Page link: https://amp.dev/documentation/components/amp-mustache/

### Expected behavior/code
The description display a link instead of the Markdown source.

**Comment by matthiasrohmer** [comment]
Huh, this should actually be fixed by https://github.com/ampproject/amp.dev/pull/3610. Thanks for reporting, we'll take another look.

**Comment by matthiasrohmer** [comment]
@robinvanopstal, this seems to appear for multiple: see [`amp-youtube`](https://amp.dev/documentation/components/amp-youtube/). Can you have another look over all of them?

#3610 did only fix it for automatically extracted teaser text. An alternative approach could also be to run the same sanitizer function over all manually maintained texts.
