### ISSUE TITLE
Component amp-nested-menu only requires script for amp-sidebar not amp-nested-menu

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#3699]
### Current behavior

The [docs for `amp-nested-menu`](https://amp.dev/documentation/components/amp-nested-menu/) indicate that two component scripts are needed, one for `amp-nested-menu` and another for `amp-sidebar`:

![image](https://user-images.githubusercontent.com/134745/76795802-50ad4500-6787-11ea-83c5-0f72dbce648b.png)

However, opening the example in the playground, there is only a script for `amp-sidebar` and no validation error is reported. In fact, if I try to add the script for `amp-nested-menu` I then get a validation error:

![image](https://user-images.githubusercontent.com/134745/76795858-72a6c780-6787-11ea-8a7f-10e139b8a2e0.png)

There is no mention of `amp-nested-menu` among the `requires_etension` rules in the protoascii: https://github.com/ampproject/amphtml/blob/master/extensions/amp-nested-menu/validator-amp-nested-menu.protoascii

### Expected behavior/code

The `amp-nested-menu` script should be removed from the Required Scripts section.

### Reproduction procedure

View [`amp-nested-menu` in playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fcomponents%2Famp-nested-menu.example.1.html%3Fformat%3Dwebsites&format=websites&_gl=1*1jfc6au*_ga*YW1wLTkyNW81TVZ3MmZjS0F6aVZfV2pfOHc.) and try adding the `amp-nested-menu` script:

```html
<script async custom-element="amp-nested-menu" src="https://cdn.ampproject.org/v0/amp-nested-menu-0.1.js"></script>
```

Notice the validation error.

**Comment by matthiasrohmer** [comment]
Thanks for reporting, @westonruter! Indeed `amp-nested-menu` seems to get automatically injected by `amp-sidebar` as soon as `amp-nested-menu` is used.

The docs importer does something wrong here when resolving dependencies. I'll have a look.
