### ISSUE TITLE
Update amp-consent to new configuration scheme

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3701]
Doesn't seem as if immediate action is required, just stumbled over it while using `amp-consent` for another project. `promptIfUnknown*` seems to be the [legacy way](https://amp.dev/documentation/components/amp-consent/#response) of configuring `amp-consent`. `consentRequired` and (in our case) `geoOverride` should be used instead.

/cc @sebastianbenz for triage

**Comment by sebastianbenz** [comment]
Is this in the example?

**Comment by matthiasrohmer** [comment]
Have been thinking of amp.dev itself, the [user consent](https://amp.dev/documentation/examples/?category=user-consent&format=websites) examples are actually up-to-date 😄
