### ISSUE TITLE
amp-inputmask sample contains invalid JavaScript

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3708]
### Current behavior
[The sample for &lt;amp-inputmask&gt;](https://amp.dev/documentation/examples/components/amp-inputmask/) contains custom JavaScript, causing it to fail validation. Looks like this was added to make a toggle to turn on an experiment.

Is this still needed?

```HTML
<script>const experiments = ["amp-inputmask"]</script>
```

etc.

**Comment by matthiasrohmer** [comment]
No it's not, but added automatically via the example's frontmatter: https://github.com/ampproject/amp.dev/blob/5f3c42d6fa0358660a6949ef39f0315e56cc5f96/examples/source/1.components/amp-inputmask.html#L3-L4. Thanks for reporting, @morsssss!

@robinvanopstal, while you're at the examples anyway with #3567 could you please remove the experiments from the frontmatter?
