### ISSUE TITLE
Add dedicated tracking for how users are navigating to and from documentation detail pages

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#3723]
TBD in detail. Generally: are they coming from teasers on the overview pages? Are they using the sidebar? Is the sidebar discoverable enough...?

**Comment by sebastianbenz** [comment]
Add custom tracking events for: 

* Click on table of content for examples, guides, components
* Click on sidebar toggle for examples, guides, components

**Comment by sebastianbenz** [comment]
//cc @CrystalOnScript for more input

**Comment by matthiasrohmer** [comment]
Input from Ferdi:

>- How often is the sidebar used to navigate to specific components. (Desktop / Tablet / Mobile)
>- How often is the component overview page used to get to specific components. (Desktop / Tablet / Mobile)
>- How often is the "Table of content" used in relation to simple scrolling to jump to a specific content on a component page. (Desktop / Tablet / Mobile)
>- How often does the user minimize or maximize the sidebar via toggle? (Tablet)
>- How many different component detail pages are displayed per visit?
>- How far does the user scroll on the component detail pages per visit?
>- How exactly does the user get to the component detail pages (user flow)? (Desktop / Tablet / Mobile)
>- How often is the breadcrumb on the component detail pages used by users?
>- Which sections within the "Table of Content" are used the most?
