### ISSUE TITLE
Page layout changes in the bottom.

### ISSUE THREAD

**Issue by VasudevHarshal-123** [ampproject/amp.dev#3728]
### Current behavior
The component page displaying [amp-analytics](https://amp.dev/documentation/components/amp-analytics/?format=websites#timer-trigger) changes the layout after the topic scroll-trigger ends.
Which I guess is due to the reason that the content after scroll-trigger is not wrapped inside the `section` having class `-t`.

**Comment by matthiasrohmer** [comment]
Just stumbled over this myself. Thanks for reporting! In cases like this a screenshot helps a lot 🙂 This is how it looks:

![Bildschirmfoto 2020-03-24 um 18 14 57](https://user-images.githubusercontent.com/12857772/77456392-74adfd80-6dfb-11ea-9308-2952603b4fcb.png)

**Comment by VasudevHarshal-123** [comment]
@matthiasrohmer will do from next time.
