### ISSUE TITLE
Github importer misses attributes if defined in a table

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3732]
Attributes are defined here: 

https://github.com/ampproject/amphtml/blob/0acc235afdf63cf83a1e2fea653773a5a7b608e3/extensions/amp-position-observer/amp-position-observer.md

but are missing here:

https://amp.dev/documentation/components/amp-position-observer/#attributes

//cc @matthiasrohmer

**Comment by CrystalOnScript** [comment]
I'm updating this to critical, as its effecting ALL components with attributes in a table. 

https://amp.dev/documentation/components/amp-ad/?format=websites#attributes
https://amp.dev/documentation/components/amp-inline-gallery/?format=websites#attributes

ect
