### ISSUE TITLE
🐛The "unsupported for current selected format" warning seems wrong for non-component pages

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amp.dev#3742]
### Current behavior
amp.dev says `Important: this component does not support your currently selected format websites!` even though the current page is not about a single component.

Please also provide:
- Page link: https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_emails/?format=websites

### Expected behavior/code
Since it's not a component documentation, it should probably say something like `Important: this **page** is not applicable to your currently selected format websites!`.

**Comment by sebastianbenz** [comment]
Good point! //cc @matthiasrohmer
