### ISSUE TITLE
Remove amp-analytics as supported child of amp-story-grid-layer

### ISSUE THREAD

**Issue by shishirm** [ampproject/amp.dev#3782]
amp-analytics is incorrectly listed as a child of amp-story-grid-layer when instead it is only allowed as a direct child of amp-story.

https://amp.dev/documentation/components/amp-story-grid-layer/#

**Comment by gmajoulet** [comment]
Thanks for filing this! Why do you think this is incorrect? @Enriqe looked at our validation rules and we think this is supposed to work.
Thanks!

**Comment by shishirm** [comment]
Apologies for the confusion. What I had intended was to adjust the amp-story documentation to indicate that amp-analytics was an allowed child.

At the moment the documentation says, "The <amp-story> component contains one or more <amp-story-page> components, containing each of the individual screens of the story".

https://amp.dev/documentation/components/amp-story/?format=stories#children-(of-amp-story)

I just tested and it appears that amp-analytics is even allowed as a direct child of body. If this was left intentionally vague, please feel free to close out this bug. Alternatively, adding a supported child elements section to the amp-story documentation  (similar to the amp-story-grid-layer documentation) would be ideal.

**Comment by gmajoulet** [comment]
Thanks for the additional details :)
@Enriqe is looking into this
