### ISSUE TITLE
amp-carousel not listed under supported components for AMP for Email

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#3784]
In the [AMP Component Catalogue](https://amp.dev/documentation/components/?format=email) and the sidebar:

![image](https://user-images.githubusercontent.com/250887/78025713-65c2d000-7352-11ea-80d5-976a5b9bcfe4.png)

Likely related to the fact email doesn't support 0.2 but supports 0.1.

**Comment by matthiasrohmer** [comment]
`amp-carousel` not appearing at all will be fixed with #3828. But there is a UX problem now: the component sidebar links to the latest version by default.

I'll try to shove in more logic into the template to work around this but I'm skeptical...
