### ISSUE TITLE
 possible error: community/working-groups/access-subscriptions

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amp.dev#3816]
On https://amp.dev/community/working-groups/access-subscriptions/
see:
The GitHub Team also includes { name } WG members.

**Comment by matthiasrohmer** [comment]
@robinvanopstal, can you please look into this? In the template there's:

```html
<p>{{ _('<a href={{ doc.html_url }} target="_blank" rel="noopener">The GitHub Team</a> also includes { name } WG members.',  name=doc.full_name) }}</p>
```

The importer also sets `full_name` but I can't quite make sense of it...
