### ISSUE TITLE
The extension 'amp-wistia-player' was found on this page, but is unused. Please remove this extension

### ISSUE THREAD

**Issue by gerardorm** [ampproject/amp.dev#3839]
Recently I added this extension in order to use the wistia player. After adding all my pages that don't have a wistia element are getting that error message, and the page is not validated successfully.

Is this the desired behavior? or is it an AMP known issue?.

![2spVH](https://user-images.githubusercontent.com/14027305/79593265-11c52480-8090-11ea-9de3-ed5e92052f50.png)

**Comment by sebastianbenz** [comment]
This is the desired behavior to avoid AMP pages downloading too much JS.
