### ISSUE TITLE
Please update the AMP Cache URL Format doc

### ISSUE THREAD

**Issue by Gregable** [ampproject/amp.dev#3851]
### Problem
The AMP Cache Origin algorithm is changing. The changes have largely been implemented, so it seems safe to go ahead and change the wording of the documentation.

Background [here](https://github.com/ampproject/amphtml/issues/26205).

### Location
https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls/

### Content type
Guides & Tutorials

### Information architecture (optional)

Modify the "Basic Algorithm" section to add a new step 4 between current steps 3 and 4:

<ol start=4>
  <li>
   If the output of step 3 has a "-" (hyphen) at both positions 3 and 4, then to the output of step 3, add a prefix of "0-" and add a suffix of "-0". See [#26205](https://github.com/ampproject/amphtml/issues/26205) for background.
  </li>
</ol>

Modify the last example in the the "basic algorithm" examples to have a domain prefix column value of `0-en--us-example-com-0`.

Replace the section "The reasons for a domain prefix not being a valid DNS label include:", including the list below that section with the sentence.

"A domain prefix is not a valid DNS label if it is longer than 63 characters".

Modify the "Amp Cache Origin to Publisher Domain" section to add a new step 2 to the ordered list algorithm between current steps 1 and 2:

<ol start=2>
  <li>
    If the domain prefix starts with "0-" and ends with "-0", strip both the "0-" prefix and the "-0" suffix.
  </li>
</ol>

Change the new steps 3 and 4 (previously 2 and 3) to correctly reference the previous steps. In other words replace: "output by Step 1" with "output by Step 2" and "result of Step 2" with "result of Step 3". Same for the sentence below the algorithm.

**Comment by Gregable** [comment]
@CrystalOnScript let me know if you need any clarifications. Thanks!

**Comment by CrystalOnScript** [comment]
Thanks for taking the time to write this out @Gregable! I've sent up a PR with the requested fixes, let me know if it looks good!
