### ISSUE TITLE
Serve webp based on accept headers instead of fallback

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3854]
We currently serve webp versions of our images via `amp-img fallback` which results in the image being downloaded twice on Safari (see also https://github.com/ampproject/amphtml/issues/21912#issuecomment-617995565). Instead we should serve these based on accept headers.

**Comment by sebastianbenz** [comment]
//cc @patrickkettner

**Comment by matthiasrohmer** [comment]
As discussed in a call: if `Accept: image/webp` is present the backend does a lookup for the requested image with the `.webp` extension and delivers that one if it exists and falls back to the original path otherwise.

**Comment by matthiasrohmer** [comment]
Fixed by introducing Thumbor.
