### ISSUE TITLE
AMP-FX-COLLECTION for background images

### ISSUE THREAD

**Issue by gtamborero** [ampproject/amp.dev#3862]
Is it possible to apply amp-fx to background images? Any example? Thanks!

**Comment by matthiasrohmer** [comment]
Can you provide a code example of what you tried so far?

So long I'm assuming you are embedding your background image via CSS. If that's the case I'd recommend using `amp-img` instead. This would allow AMP to take care of loading the image only when it's needed. You could then simulate `background-size: cover|contain` via `object-fit`. See the example [here](https://amp.dev/documentation/examples/style-layout/how_to_support_images_with_unknown_dimensions.email/?format=websites#object-fit-to-the-rescue). On the `amp-img` element you could then also use `amp-fx` 🙂

**Comment by sebastianbenz** [comment]
amp-fx-collection is not specific to AMP element, you can use it on arbitrary HTML elements. This means it works with CSS background images as well.

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
  <script async custom-element="amp-fx-collection" src="https://cdn.ampproject.org/v0/amp-fx-collection-0.1.js"></script>
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
    header {
      background-image:  url("https://mdn.mozillademos.org/files/11991/startransparent.gif"), 
                     url("https://mdn.mozillademos.org/files/7693/catfront.png");
 	  background-color: transparent;
    }
  </style>
</head>
<body>
  <header amp-fx="fade-in">
    <h1>Hello AMPHTML World!</h1>
  </header>
</body>
</html>
```

**Comment by gtamborero** [comment]
Thank you @matthiasrohmer I think i'll try to create a background without background-image attribute. Thank you  @sebastianbenz  . Fade-in effect works perfect because the effect applies to the full layer but it doesn't work the parallax effect.

**Comment by matthiasrohmer** [comment]
Let us know if you need any further assistance with this 🙂 Closing for so long.
