### ISSUE TITLE
Why does amp.dev uses grow.io?

### ISSUE THREAD

**Issue by amandeeepsingh** [ampproject/amp.dev#3866]
This is just a question, why does amp.dev uses grow.io?
Do you recommend grow.io for large scale static websites?

Thanks

**Comment by jaygray0919** [comment]
https://docs.google.com/document/d/1RNkKhXjJeHCOKB1cSxEzzEzCxBLA3jxltMRo-rVZ-i4/edit#

**Comment by amandeeepsingh** [comment]
Thanks! @jaygray0919
