### ISSUE TITLE
The CSS "transition" property is listed as supported by AMP for Email, but is not supported by Gmail

### ISSUE THREAD

**Issue by sharkcrayon** [ampproject/amp.dev#3878]
### Current behavior
According to the AMP for Email [docs](https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css/?format=email#additional-restrictions) the css property `transition` is supported by AMP for Email (with restrictions). However, `transition` does not work in Gmail (desktop or mobile) according to my own testing. It does work within the AMP for Email playground.

- Page link: https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css/?format=email#additional-restrictions

### Expected behavior/code
I expected the css property `transition` to work within an AMP email within the Gmail web client and mobile Gmail app because the AMP for Email docs said it would, and because it works within the AMP for Email playground.

I'd much prefer a solution to this where it starts working in Gmail, rather than the docs being updated ;)

### Reproduction procedure

1. View the code below in the AMP for Email playground. Observe that a transition occurs when the "Toggle Class" button is clicked.
2. Send it to yourself in Gmail. Inspect the CSS and observe that the `transition` property is missing.

(I also tried this with slightly different CSS and an `opacity` transition, and the same behavior occurred.)

- I'm using the Chrome browser on macOS Catalina.

```
<!doctype html>
<html ⚡4email>
<head>
  <meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>

  <style amp4email-boilerplate>body{visibility:hidden}</style>
  <style amp-custom>

    .Example {
      padding: 20px;
      width: 240px;
      background-color: red;
      position: fixed;
      top: 0;
      right: 0;
      bottom: 0;
      z-index: 2;
      transform: translate(300px,0);
      transition: transform .3s ease;
    }
    .Example.open {
      transform: translate(0, 0);
    }

  </style>
</head>

<body>

  <div id="example" class="Example">My example div.</div>
  <button class="Toggle"
    role
    tabIndex
    on="tap:example.toggleClass(class='open')">
    Toggle Class
  </button>

</body>
```

**Comment by fstanis** [comment]
Seems this is a bug in Gmail where fractional duration is not allowed in `transition`. As a workaround, you can use milliseconds until it's fixed: `transition: transform 300ms ease` which should work.

(BTW you can file Gmail AMP bugs [using the process outlined here](https://developers.google.com/gmail/ampemail/support#issues_with_amp_specific_to_gmail))

CC @zhangsu

**Comment by sharkcrayon** [comment]
Oh that's awesome, thanks! I gave that a try and it's working with `transform 300ms ease`.
