### ISSUE TITLE
"Toggle Sidebar" prevents clicking content

### ISSUE THREAD

**Issue by hogashi** [ampproject/amp.dev#3885]
### Problem

Related with the issue #1604 . "Toggle Sidebar" button is still annoying sometime when I use the documents.

It seems that b078b6cac0bc5f5dc8df4b3cabaac5eef4110bc8 added `opacity: 0` for this. However, this element is clickable while it is not visible. It prevents clicking links.

![image](https://user-images.githubusercontent.com/12870472/80669602-c6733300-8adf-11ea-848a-5e2b37aa71d2.png)

### Solution

I think it rather be `display: none` or something to make "Toggle Sidebar" invisible and not clickable.

### Alternatives

It would be better if not invisible completely because the users can understand that there is a button: e.g. `opacity: 0.2` , or `border: 1px solid color('blue-ribbon')` on the parent `<label>` tag.

### Additional information (optional)

When this issue is solved, the content of the document is still readable and links nearby the "Toggle Sidebar" button will be clickable.

**Comment by matthiasrohmer** [comment]
Thanks a lot for your feedback! The sidebars and their toggling behavior is also something we are currently looking into to improve UX.

For now, giving it `display: none;` instead of `opacity: 0;` sounds good to me for a quick fix. @robinvanopstal, can you please take care of this?

**Comment by hogashi** [comment]
Thank you for your fix ⭐  I'm looking forward to the further improvements!
