### ISSUE TITLE
<amp-script> Playground page not working 

### ISSUE THREAD

**Issue by Svenmay** [ampproject/amp.dev#3886]
### Current behavior
The examples for "amp-script" on the playground do not work. Clicking on any of the buttons do not trigger any reaction, instead a lot of JS errors are thrown on the console.

Specific error message in console. **[amp-script] Script hash not found. amp-script[script="hello-world"].js must have "sha384-a93VCeQbvTG7y-NYFU4XSZnhfxIjDIhqdCVXo1agLB4rIO42b2uApwLDJTbpp8Lf" in meta[name="amp-script-src"].**

- Page link: https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-script&format=websites
- (Optional) Screenshots/videos:

![Screenshot 2020-04-30 at 10 28 17](https://user-images.githubusercontent.com/39521568/80689285-64113700-8acd-11ea-9969-e48d088ba7b4.png)

### Expected behavior/code
Examples on playground should work

### Reproduction procedure
1. Open the page above
2. Open DevTools
3. See lot of errors
4. Click on any of the buttons (in the example)
5. No reaction

- What browser are you using? Current Chrome stable
- What O/S are you using? ChromeOS

**Comment by sebastianbenz** [comment]
Yes, this is annoying. The playground should auto-generate the script hash using the [script-csp package](https://github.com/ampproject/amp-toolbox/tree/master/packages/script-csp).

**Comment by matthiasrohmer** [comment]
This is tracked here: https://github.com/ampproject/amp.dev/issues/3608. I almost have this ready and try to land the PR this week.
