### ISSUE TITLE
Broken links on content_encryption page

### ISSUE THREAD

**Issue by jeffochoa** [ampproject/amp.dev#3891]
### Broken links on content_encryption page

The GitHub links in the `Related resources`  are broken.

### Content outdated

The `go` script seems to be broken https://github.com/subscriptions-project/encryption/tree/master/golang/cmd/gcp_key_gen

Is there an alternative that you can recommend? 

### Location
https://amp.dev/documentation/guides-and-tutorials/develop/monetization/content_encryption/

**Comment by CrystalOnScript** [comment]
Thanks for flagging @jeffochoa ! There's been a fix for the links [here](https://github.com/ampproject/amp.dev/pull/3874) - it's been merged and will be live with the next update. 

I've filed an issue on the scubscriptions-project GitHub repo and cc'd you [here](https://github.com/subscriptions-project/encryption/issues/11).
