### ISSUE TITLE
blog.amp.dev: schema.org metadata suggests WordPress is the publisher

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp.dev#3914]
The blog post <https://blog.amp.dev/2020/05/06/amp-web-vitals-a-better-web-together/> has schema.org metadata of:

```json
{
    "@context": "http://schema.org",
    "@type": "BlogPosting",
    "author": {
        "@type": "Person",
        "name": "Alex Dur\u00e1n"
    },
    "dateModified": "2020-05-06T17:04:34-07:00",
    "datePublished": "2020-05-06T16:42:47-07:00",
    "headline": "AMP + Web Vitals &#8211; a better web, together",
    "image": "https://blog.amp.dev/wp-content/uploads/2019/11/AMP_Blog_Square.jpg",
    "mainEntityOfPage": "https://blog.amp.dev/2020/05/06/amp-web-vitals-a-better-web-together/",
    "publisher": {
        "@type": "Organization",
        "logo": "https://blog.amp.dev/wp-content/plugins/amp/assets/images/amp-page-fallback-wordpress-publisher-logo.png",
        "name": "The AMP Blog"
    }
}
```

`publisher.logo` is <https://blog.amp.dev/wp-content/plugins/amp/assets/images/amp-page-fallback-wordpress-publisher-logo.png>, which is the WordPress logo.

This causes (I assume) the WordPress logo appearing in "Discover" (and probably other places), which is confusing:

![IMG_7669](https://user-images.githubusercontent.com/51244/81227059-b7124f00-8fe3-11ea-8195-5c2e6d393d73.png)

The AMP logo should probably appear there instead, as it does for most of the amp.dev content.

/cc @westonruter

**Comment by westonruter** [comment]
Good point. Will this image URL suffice? https://amp.dev/static/img/icons/icon-512x512.png

**Comment by ithinkihaveacat** [comment]
I'd guess so (that's what amp.dev uses, and seems to be a definite improvement) but not my decision!

**Comment by westonruter** [comment]
Who makes the decision?

**Comment by sebastianbenz** [comment]
I can make that decision. I think that icon is fine. Thanks for reporting
Michael! I've also noticed that the author is wrong as it should be Patrick
in this case.

>

**Comment by westonruter** [comment]
The author is incorrect because Alex published post and Patrick doesn't have a user account. the quick fix this simply for Alex to create an additional user account for Patrick and then change the author to him.

**Comment by westonruter** [comment]
I've corrected the logo in the Schema.org metadata.

**Comment by matthiasrohmer** [comment]
Thanks, @westonruter!

**Comment by westonruter** [comment]
I've fixed the post authorship to be @patrickkettner:

```html
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "BlogPosting",
    "author": {
        "@type": "Person",
        "name": "Patrick Kettner"
    },
    "dateModified": "2020-05-12T02:59:46-07:00",
    "datePublished": "2020-05-06T16:42:47-07:00",
    "headline": "AMP + Web Vitals &#8211; a better web, together",
    "image": "https://blog.amp.dev/wp-content/uploads/2019/11/AMP_Blog_Square.jpg",
    "mainEntityOfPage": "https://blog.amp.dev/2020/05/06/amp-web-vitals-a-better-web-together/",
    "publisher": {
        "@type": "Organization",
        "logo": "https://blog.amp.dev/wp-content/uploads/2020/05/amp-logo-icon-512x512-1.png",
        "name": "The AMP Blog"
    }
}
</script>
```

And @alexduran4 is going to update the other posts to ensure they have the right authorship asigned.

**Comment by sebastianbenz** [comment]
Thanks @westonruter !
