### ISSUE TITLE
Portuguese (Portugal) language

### ISSUE THREAD

**Issue by mansil** [ampproject/amp.dev#3939]
Hi,

I would like to contribute and help with the translation for Portuguese (Portugal) language.

I already "forked" amp.dev and I and my husband will help both.

Thank you for your time.

Sincerely,

Manuela Silva

**Comment by matthiasrohmer** [comment]
Thanks a lot for your interest in contributing to AMP 🙂 @patrickkettner and @CrystalOnScript conduct all efforts around localization for the AMP Project and can provide some more guidance.

**Comment by mansil** [comment]
Thank you @matthiasrohmer
