### ISSUE TITLE
typo in amp-img example. <img> tag not properly terminated

### ISSUE THREAD

**Issue by cjimmy** [ampproject/amp.dev#3948]
In the amp-img [example](https://amp.dev/documentation/examples/components/amp-img/?format=websites), under the example, the `<img>`  has a typo.

Currently reads
```
<amp-img src="/static/samples/img/amp.jpg"
  alt="AMP"
  width="475"
  height="268"
  layout="responsive">
  <noscript>
    <img src="/static/samples/img/amp.jpg" width="475" height="268" alt="AMP">
  </noscript>
</amp-img>
It should end in a />.
```
 <img> should end with a `/>`

**Comment by matthiasrohmer** [comment]
With HTML5 a slash in front of the closing tag bracket is optional for void tags 🙂
