### ISSUE TITLE
Remove bookend from Create your first Web Story

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#3957]
### Problem
Bookend is being deprecated. It needs to be removed from the tutorial and the [starter/finished code](https://github.com/ampproject/amp.dev/tree/master/tutorial_source/amp-pets-story).

### Location
[Creating the bookend](https://amp.dev/documentation/guides-and-tutorials/start/visual_story/create_bookend/?format=stories)

**Comment by patrickkettner** [comment]
@newmuis what should be the path on this? Outright removal? tagged deprecation?

**Comment by newmuis** [comment]
I don't know what "tagged deprecation" in this context means, but yes I think it should be just removed from this guide.

**Comment by patrickkettner** [comment]
Sorry, I just made up the term -  some things (like [amp-font](https://amp.dev/documentation/components/amp-font/) have a badge that says "deprecated"

![image](https://user-images.githubusercontent.com/465414/108912957-56e2ad00-75f7-11eb-889b-bb1a7a009050.png)


Thank you for the clarification

**Comment by newmuis** [comment]
Got it.  I think we can mark https://amp.dev/documentation/components/amp-story-bookend/ with that tag, but remove this step from the guide: https://amp.dev/documentation/guides-and-tutorials/start/visual_story/create_bookend/?format=stories
