### ISSUE TITLE
New release timetable design

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#3969]
More closely align the release schedule with the overall design of amp.dev. 

1.  [Mock 1](#-mock-1): traditional calendar view
2. [Mock 2](#-mock-2): horizontal time  (favorite, once readability has been improved)

## Mock 1

<img width="1440" alt="Screen Shot 2020-05-18 at 12 34 10" src="https://user-images.githubusercontent.com/380472/82203851-2a7d6000-9904-11ea-9509-661a48b29d30.png">
<img width="1090" alt="Screen Shot 2020-05-18 at 12 34 28" src="https://user-images.githubusercontent.com/380472/82203854-2c472380-9904-11ea-8b3f-2ea1356c61c5.png">
<img width="1086" alt="Screen Shot 2020-05-18 at 12 34 42" src="https://user-images.githubusercontent.com/380472/82203858-2ea97d80-9904-11ea-9d92-8bd427c56348.png">

## Mock 2

<img width="721" alt="Screen Shot 2020-05-18 at 12 35 06" src="https://user-images.githubusercontent.com/380472/82203861-30734100-9904-11ea-8088-fe753a69a1e6.png">

**Comment by sebastianbenz** [comment]
@nainar @danielrozenberg wdyt?

**Comment by danielrozenberg** [comment]
I like both, slightly leaning towards Mock 1. My main issue with Mock 2 is that you have to scroll sideways (which is only ever comfortable on mobile/MacBooks, but not on Linux/Windows) _and_ you don't get to see all the information without scrolling, so context can get lost

**Comment by patrickkettner** [comment]
@sebastianbenz is this redeisgn going to happen? or is. this stale?

**Comment by sebastianbenz** [comment]
Thanks for resurfacing this Patrick! @matthiasrohmer @lluerich would be great if you could take a look if you have spare cycles.
