### ISSUE TITLE
Time period buttons on roadmap page don't always change color correctly

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#3985]
## 🐛 Bug Report
This pertains to https://amp.dev/community/roadmap/ .

### Current behavior
If you're on a certain time period, and you click on a time period button that's higher up than your current time period, the time period button *beneath* the one you've chosen turns black - not the time period button corresponding to the one you've chosen.

For example, if I'm on Q3 2019, and then I click the "Q1 2020" button, "Q4 2019" turns black. If I'm on Q2 2019 and I click the "Q4 2019" button, "Q3 2019" turns black.

But if I go in the reverse direction, all works as expected. So, if I'm on Q3 2019, and I click "Q2 2019", "Q2 2019" turns black.

All in all, it's a pretty cool animation though!

**Comment by sebastianbenz** [comment]
Noticed this as well. Looks like there's some more position observer fine-tuning needed. //cc @robinvanopstal

**Comment by matthiasrohmer** [comment]
Fixed with #3994
