### ISSUE TITLE
AMP.DEV not reachable when using NORDVPN

### ISSUE THREAD

**Issue by jaccos** [ampproject/amp.dev#3992]
### Current behavior
A clear and concise description of the bug you found in amp.dev.

Please also provide:
- Page link: <insert the URL link to the amp.dev page(s) that you found the issue on>
- (Optional) Screenshots/videos:

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. Step 1 to reproduce
2. Step 2 to reproduce
3. …

- What browser are you using?
- What O/S are you using?

**Comment by patrickkettner** [comment]
@jaccos would you be able to share a screenshot of the error? It sounds like DNS issue (the domain name isn't being resolved). 

However the default DNS servers for NordVPN are both resolving correctly

![image](https://user-images.githubusercontent.com/465414/83140610-55ae3f00-a0bc-11ea-81d4-890755cee377.png)

Do you know what your DNS server is set to on the device you are using?

**Comment by patrickkettner** [comment]
@jaboc83 ping

**Comment by jaboc83** [comment]
> @jaboc83 ping

??? I think you pinged the wrong person.

**Comment by patrickkettner** [comment]
terribly sorry !

**Comment by patrickkettner** [comment]
@jaccos ping

**Comment by patrickkettner** [comment]
closing due to lack of response, feel free to give a shout if you are still having a problem
