### ISSUE TITLE
amp-img documentation advises antipattern of using fallbacks for WebP

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#4024]
### Problem

The docs for `amp-img` have an example for how to specify a fallback image when the browser doesn't support WebP. The problem is that this is an antipattern, as browsers which don't support WebP will be forced to download two images: the WebP and then the JPG.

### Location

https://amp.dev/documentation/components/amp-img/#example:-specifying-a-fallback-image

### Content type

Example

**Comment by sebastianbenz** [comment]
Duplicate of https://github.com/ampproject/amphtml/issues/21912#issuecomment-617995565
