### ISSUE TITLE
Playground isn't surfacing warnings

### ISSUE THREAD

**Issue by fstanis** [ampproject/amp.dev#4035]
### Current behavior

[playground.amp.dev](https://playground.amp.dev/) doesn't currently surface validator warnings.

### Expected behavior/code

Warnings surfaced the same way errors are.

These are important to notify users of deprecations and changes to the spec they may otherwise miss.

### Reproduction procedure

1. Go to [playground.amp.dev](https://playground.amp.dev/).
2. Paste this code into the body: `<noscript><video muted></video></noscript>`
3. Observe no warning.
4. Try the same in [validator.ampproject.org](https://validator.ampproject.org/).
5. Observe warning appears: `The attribute 'muted' in tag 'video' is deprecated - use 'autoplay' instead. Learn more.`

**Comment by matthiasrohmer** [comment]
Will be fixed by #4044.
