### ISSUE TITLE
Show or hide div using amp list in email

### ISSUE THREAD

**Issue by chronustdd** [ampproject/amp.dev#4058]
What I need to do:
       I need to show or hide the div using remote endpoint response.
Amp  email doesn't provide the option for setting state using source via remote end point. Is there any way in which I can use list or any other element to toggle div using remote end point.

**Comment by matthiasrohmer** [comment]
Not an AMP4Email export but [`amp-list`](https://amp.dev/documentation/components/amp-list/?format=email) seems to be supported and would offer the possibility to show dynamic content. Does that serve your use-case?

**Comment by matthiasrohmer** [comment]
Let us know if you need further support with this.
