### ISSUE TITLE
Stories Documentation page has a validation issue

### ISSUE THREAD

**Issue by amanintech** [ampproject/amp.dev#4108]
Validation issue on the URL https://amp.dev/documentation/examples/multimedia-animations/supported_media_types_in_amp_stories/?format=stories

![image](https://user-images.githubusercontent.com/28403318/85198576-4b701100-b307-11ea-9de5-be9e5122b662.png)

**Comment by matthiasrohmer** [comment]
Thanks for the report, but that's actually known and intended as the example uses experimental features with `amp-google-vr-view-image`.
