### ISSUE TITLE
Visual Stories

### ISSUE THREAD

**Issue by visualstories** [ampproject/amp.dev#4109]
### Story creation resource name

Visual Stories

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [x] Platform
- [ ] Other

### URL

[https://visualstories.com](https://visualstories.com/)

### Image

![visualstories](https://user-images.githubusercontent.com/64431239/85206637-0ec10b80-b341-11ea-92c5-6d597317192c.png)

### Description

Multi-site, multi-author blogging tools and WYSIWYG editor to create Web Stories on your own domain.

### List of Stories

- [Story 1](https://travel.visualstories.com/8top-things-to-do-in-salta-argentina)
- [Story 2](https://parenting.visualstories.com/quotes-about-parents-that-will-warm-your-heart)
- [Story 3](https://healthyliving.visualstories.com/calming-sleep-affirmations-to-help-you-fall-asleep)
- [Story 4](https://selfimprovement.visualstories.com/is-the-law-of-attraction-real)
- [Story 5](https://inspihub.com/how-to-overcome-laziness-and-become-proactive)
- [Story 6](https://literature.visualstories.com/brilliant-life-lessons-from-the-fountainhead)
- [Story 7](https://animals.visualstories.com/10remarkable-benefits-of-bird-watching)
- [Story 8](https://adventure.visualstories.com/best-places-for-hiking-in-scotland)
- [Story 9](https://beauty.visualstories.com/how-to-stay-looking-young-naturally)
- [Story 10](https://food.visualstories.com/baking-a-marble-sponge-cake-recipe)

**Comment by sebastianbenz** [comment]
@shishirm PTAL

**Comment by shishirm** [comment]
Hello,

We're currently reviewing your submission and hope to complete the process before the end of the week. We'll add comments here if there is anything additional that is needed. Thanks for your patience!

**Comment by visualstories** [comment]
Thank you. If you like we can arrange a demo of our tool at your convenient time.
