### ISSUE TITLE
Link anchors don't jump to the right heading

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amp.dev#4167]
Helloooooo!

Just found this bug:

1. Open this link: https://amp.dev/documentation/components/amp-story/#live-story
2. Note how it does not jump to the "Live Story" heading.

That's it :)

**Comment by manisaiprasad** [comment]
Hey @pbakaus 

I just found that there is also a #live-story id at this tr tag.

<img width="341" alt="Screen Shot 2020-07-11 at 4 05 30 AM" src="https://user-images.githubusercontent.com/18515609/87208285-cf785000-c32b-11ea-99a6-54e87d6104bd.png">

<img width="1221" alt="Screen Shot 2020-07-11 at 4 07 09 AM" src="https://user-images.githubusercontent.com/18515609/87208360-0f3f3780-c32c-11ea-9b27-ea61ce41d7b1.png">

can I fix it with #live-story-optional ?

<img width="270" alt="Screen Shot 2020-07-11 at 4 14 49 AM" src="https://user-images.githubusercontent.com/18515609/87208701-16b31080-c32d-11ea-8851-b45301a87c8e.png">

**Comment by pbakaus** [comment]
ah interesting! Hopefully pretty straight forward fix then.

**Comment by manisaiprasad** [comment]
Yeah 

can I fix it with #live-story-optional ?

**Comment by matthiasrohmer** [comment]
@manisaiprasad, this should fix it. You can easily use GitHub's UI to edit the file [in the browser](https://github.com/ampproject/amphtml/edit/master/extensions/amp-story/amp-story.md). Looking forward to your PR 🙂

**Comment by manisaiprasad** [comment]
Thanks @matthiasrohmer the PR is submitted 😇

**Comment by gmajoulet** [comment]
Closed by https://github.com/ampproject/amphtml/pull/29242

Thank you @manisaiprasad!
