### ISSUE TITLE
typo correction to the repo urls

### ISSUE THREAD

**Issue by mnjit20** [ampproject/amp.dev#4171]
### Problem
Below mentioned 2  documents have urls of worker-dom repo which are pointing to wrong branch url and due to that its getting redirected to 404 page.

### reference 1: 
https://github.com/ampproject/amp.dev/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
#### expired link : 
https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md

### reference 2:
https://github.com/ampproject/amp.dev/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
#### expired link: 
https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md

### Location
Section of the site where the content lives (or should).
https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md

###correct urls will be
https://github.com/ampproject/worker-dom/blob/main/web_compat_table.md

**Comment by mnjit20** [comment]
A PR is created for this; waiting for it to be reviewed and merged.

**Comment by matthiasrohmer** [comment]
Fixed by #4172, thanks Manjeet!
