### ISSUE TITLE
Star Rating and Gmail inbox

### ISSUE THREAD

**Issue by gpalz** [ampproject/amp.dev#4192]
### Current behavior
Star Rating passed validation in Amp for Email Playground but when sent to my Gmail.com inbox account, hover effect does not work and Star size is much smaller

Please also provide:
Gmail:

![gmail](https://user-images.githubusercontent.com/22349338/87723514-ebdf1700-c787-11ea-8c1f-c9ae31e1aee1.jpg)

Amp for Email Playground:

![playground](https://user-images.githubusercontent.com/22349338/87723526-eeda0780-c787-11ea-9a3e-54a3aec52d6d.jpg)

### Expected behavior/code
Expected Hover Yellow color to appear. Unable to tell if star rating is selecting when clicked. Expected star size to match that in Amp for Email Playground. 

### Reproduction procedure
Please provide the steps to reproduce the problem:

- Chrome
- Windows 10

Is Star Rating out of scope for Amp for Email?

**Comment by matthiasrohmer** [comment]
That sounds like a provider-specific issue but to make sure can you provide a EML file of your mail to reproduce?

**Comment by patrickkettner** [comment]
closing as @gpalz hasn't replied. @gpalz if you can share the source, we'd be happy to look into this with you
