### ISSUE TITLE
Ukrainian language (uk or uk_ua)

### ISSUE THREAD

**Issue by sibmius** [ampproject/amp.dev#4197]
Hi,

I would like to contribute and help with the translation for Ukrainian language language.

I already forked amp.dev.

Thank you for your time.

Andi

@CrystalOnScript

**Comment by matthiasrohmer** [comment]
Thank you for your interest in contributing to the AMP project! @CrystalOnScript is coordinating all of our internationalization efforts and may provide some guidance on this 🙂
