### ISSUE TITLE
amp.dev is throwing errors with sample code 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#4223]
One of the examples under [Customized load-more elements in amp-list](https://github.com/ampproject/amphtml/blob/master/extensions/amp-list/amp-list.md#customizing-load-more-elements) contains a `#` - amp.dev is throwing an error although it is correctly wrapped in backticks. 

```
<amp-list
  load-more="auto"
  width="100"
  height="500"
  src="https://www.load.more.example.com/"
>
  ...
  <amp-list-load-more load-more-button>
    <template type="amp-mustache">
      Showing {{#count}} out of {{#total}} items
      <button>Click here to see more!</button>
    </template>
  </amp-list-load-more>
</amp-list>
```

**Comment by patrickkettner** [comment]
@CrystalOnScript is this still true? I am not sure what you mean by throwing an error (like in what way/what process the error is being thrown)
