### ISSUE TITLE
AMP Blog: provide an overview page listing all blog posts

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#4225]
Currently, the blog shows the last X articles. There are several problems with this approach:

* The reading experience is very bad as it's hard to see where one article stops and the next starts.
* It's impossible to discover previous articles.

Suggestions:

* Redesign the blog landing page to highlight the last X blog posts (where X <=3). These shouldn't not be shown in full. Show a list of all blog posts below (headlines only).
* use amp-next-page to load next articles when reading a blog post

//cc @amedina @westonruter

**Comment by westonruter** [comment]
For a quick fix, how about using the title with image and excerpt and a read more link:

> ![image](https://user-images.githubusercontent.com/134745/88585820-66215e00-d008-11ea-9c86-8c7a837d014f.png)

cc @patrickkettner

**Comment by westonruter** [comment]
@sebastianbenz I've deployed this change to the dev environment. Please take a look: https://dev-amphtml-blog.pantheonsite.io/

If good, I'll deploy that to the live environment.

**Comment by sebastianbenz** [comment]
Much better! Thanks!

>

**Comment by westonruter** [comment]
This is now deployed to blog.amp.dev
