### ISSUE TITLE
I suggest we add the lang attribute to html and set it to "en-US", otherwise assistive technologies could have problems with interpreting the page

### ISSUE THREAD

**Issue by BogdanCerovac** [ampproject/amp.dev#4237]
https://github.com/ampproject/amp.dev/blob/6fde29bd6a6d6cee066a17a8e67f939b9ee0d9bb/tutorial_source/amp-pets-story/pets-completed.html#L2

Probably not an issue for real as this is being generated etc., but if somebody wants to copy from here the language must be set.

**Comment by patrickkettner** [comment]
fixed by #4972, @BogdanCerovac let me know if there is anything still missing and we can reopen
