### ISSUE TITLE
when i test my site show me not an amp page

### ISSUE THREAD

**Issue by homsii** [ampproject/amp.dev#4238]
hello,

when I test my website on google console amp test it shows me this message https://ibb.co/XJNcqdV

I install and active web story plugins

**Comment by patrickkettner** [comment]
hello!
what is the url?

**Comment by homsii** [comment]
> hello!
> what is the url?

https://tasueq.com/

**Comment by patrickkettner** [comment]
that url does not appear to have any amp code in it, which would explain the error you are seeing.
