### ISSUE TITLE
Cutnut Story Editor

### ISSUE THREAD

**Issue by Cutnut** [ampproject/amp.dev#4242]
### Story creation resource name

Cutnut

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [ ] Platform
- [ ] Other

### URL

https://cutnut.net/

### Image

![Bildschirmfoto 2020-07-29 um 11 29 43](https://user-images.githubusercontent.com/46722483/88790502-8f70f400-d198-11ea-8742-0126d22e354e.png)

### Description

Easily create visually-rich and engaging stories across the web and social media. Fully customizable and CI conform.

### List of Stories

https://stories-cutnut-tv.cdn.ampproject.org/c/s/stories.cutnut.tv/amp/ec0db31f-fb37-4672-b11e-f755e4b24e46.html
https://stories-cutnut-tv.cdn.ampproject.org/c/s/stories.cutnut.tv/amp/024ee540-6fed-4bfb-8890-24a5cebae4eb.html
https://stories-storypepper-com.cdn.ampproject.org/c/s/stories.storypepper.com/amp/d3951e3c-2831-4dc6-a860-42a535b47c6f.html
https://stories-cutnut-tv.cdn.ampproject.org/c/s/stories.cutnut.tv/amp/5459c205-3c09-403e-b89b-beb7b725e536.html
https://stories-cutnut-tv.cdn.ampproject.org/c/s/stories.cutnut.tv/amp/f8687fe3-ba3e-4c21-8944-e467f74f24e9.html
https://stories-storypepper-com.cdn.ampproject.org/c/s/stories.storypepper.com/amp/7f81f0fb-8a7a-4490-a5c0-daaf5ede7e57.html
https://stories-cutnut-tv.cdn.ampproject.org/c/s/stories.cutnut.tv/amp/9d4fcd0a-ef6f-4c46-beea-4a621b12d9a1.html
https://stories-cutnut-tv.cdn.ampproject.org/c/s/stories.cutnut.tv/amp/0876916a-b8b5-4e97-b60f-7a295df98b9b.html
https://stories-cutnut-tv.cdn.ampproject.org/c/s/stories.cutnut.tv/amp/5b8a9179-7a0b-4a68-bd11-cb827ab2ebdc.html
https://stories-storypepper-com.cdn.ampproject.org/c/s/stories.storypepper.com/amp/71186b03-f835-4596-bc74-57d9fe45113b.html

**Comment by shishirm** [comment]
Hello @Cutnut , thank you so much for filing this. We've reviewed the various Stories and before we list on amp.dev, some fixes are requested,

**Must-Fix**

- The Stories are currently not self-canonical i.e. the link rel canonical tag currently points to the AMP cache URL. For example, https://stories.cutnut.tv/amp/ec0db31f-fb37-4672-b11e-f755e4b24e46.html points to https://stories-cutnut-tv.cdn.ampproject.org/c/s/stories.cutnut.tv/amp/ec0db31f-fb37-4672-b11e-f755e4b24e46.html as canonical but should instead point to https://stories.cutnut.tv/amp/ec0db31f-fb37-4672-b11e-f755e4b24e46.html. Could you kindly update all Stories with this fix. We suggest providing this feature within the tool itself.
- poster-portrait-src is not set to an image. Once set, it should be the recommended dimensions and aspect ratio.
- publisher-logo-src is not set to an image. Once set, it should be the recommended dimensions and aspect ratio.

**Nice-To-Haves**

These are NOT required to list on amp.dev but we'd like to pass along these recommendations to incorporate in the tool based on reviewing the submitted Stories,

- Avoid using heavy text in Stories. The [recommendation](https://developers.google.com/search/docs/guides/enable-web-stories) is to use 200 characters or less per page.
- Certain pages in Stories have text overlapping/overflowing on different viewports/device sizes.
- Some pages in Stories have text blending in with backgrounds i.e. incorrect contrast.
- We suggest adding descriptive alt attributes for every image. At the moment these are generic image names.
- We suggest providing subtitles for videos via track elements as part of the tool.
- In lieu of track elements for subtitles, for videos with text burned in, we suggest providing alt text attributes on videos.
- It is suggested to provide the ability to add OGP data to Stories from within the tool.
- It is suggested to preload the AMP Runtime.

Once your must-fix issues are in place, I'll go ahead and create a PR to add Cutnut to amp.dev. Please feel free to update this issue when ready.

Thank you!

**Comment by patrickkettner** [comment]
closing as @cutnut hasn't replied - please let us know if you would like it to be reopened
