### ISSUE TITLE
Validator UI: improve responsiveness

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#4243]
https://playground.amp.dev/validator.html?url=https%3A%2F%2Famp.dev

Two small things we should fix with the new validator UI:

Background makes text hard to read:

<img width="75" alt="Screen Shot 2020-07-29 at 13 38 40" src="https://user-images.githubusercontent.com/380472/88795877-04e0c280-d1a1-11ea-9259-add7836e0d13.png">

The input/result page should have a max width on large displays.

<img width="1793" alt="Screen Shot 2020-07-29 at 13 38 53" src="https://user-images.githubusercontent.com/380472/88795880-0611ef80-d1a1-11ea-94c8-25bc02f04249.png">

**Comment by matthiasrohmer** [comment]
Fixed by https://github.com/ampproject/amp.dev/pull/4276
