### ISSUE TITLE
Sidebar missing on example pages

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#4250]
### Current behavior
The Live Blog example page is missing the sidebar and the image is missing
https://amp.dev/documentation/examples/news-publishing/live_blog/?format=websites

**Comment by patrickkettner** [comment]
@CrystalOnScript is it still broken? The images appear to be working to me

**Comment by CrystalOnScript** [comment]
The images are back for me too! But it's still missing the amp.dev sidebar 
<img width="1389" alt="Screen Shot 2021-04-05 at 11 19 58 AM" src="https://user-images.githubusercontent.com/23297417/113609697-fafd4200-9600-11eb-9dc9-6a775c780f31.png">

**Comment by sebastianbenz** [comment]
@lluerich can you please take a look. All example pages are missing the sidebar.

**Comment by lluerich** [comment]
I will look into this.

**Comment by lluerich** [comment]
@patrickkettner any reason why [this](https://github.com/ampproject/amp.dev/blob/b4b8d78366d0512883f31613ce1631ade37601ab/frontend/templates/views/examples/documentation.j2#L12) has to be outside the ```{% block main %}``` as it is in [this](https://github.com/ampproject/amp.dev/blob/b8db02d3f66f4db44cb5dfc4a1a6ef9d0e44949e/frontend/templates/views/detail/component-detail.j2#L20) file?

**Comment by patrickkettner** [comment]
[nope!](https://github.com/ampproject/amp.dev/pull/5653)

**Comment by lluerich** [comment]
Some background on this issue:
- components/amp-analytics
- components/amp-live-list
- interactivity-dynamic-content/SeatMap
- interactivity-dynamic-content/SeatMap_Multiple_Selection
- news-publishing/Live_Blog (this ticket)

use the ```SampleRenderer```-API and return the rendered template directly. Therefore they are not piped through the AMP-Optimizer via ```growPages```, that is why they have duplicate elements, no components injected. etc. resulting in lots and lots of amp error.

**Comment by sebastianbenz** [comment]
Ah ok. Can we enable AMP Optimizer for them?

**Comment by lluerich** [comment]
@matthiasrohmer suggested, that we modify the handler inside the ```SampleRenderer``` and optimise there. It would then also be handy to extract the AMP-Optimizer part from ```growPages``` as a utility to be used both inside the ```SampleRenderer``` and ```growPages```.
