### ISSUE TITLE
Problem with consecutive lists

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4264]
## 🐛 Bug Report

I hit this issue while updating [the documentation for `<amp-script>`](https://amp.dev/documentation/components/amp-script/):

If you put two numbered or bulleted lists in a row, they get mushed into a single list, even if one of them is indented, with the intention of making it into a sublist.

So, let's say you do this:

\- item 1
\- item 2

\1. new list item 1
\1. new list item 2

What's output is a bulleted list of 4 items.

As far as I can tell, this happens whether I include whitespace or not, whether I prefix each element in the last list with "1." or whether I number them consecutively, and whether or not the last list is indented.

**Comment by matthiasrohmer** [comment]
Indenting with four spaces does the trick for me:

```md
- First first-level list item
- Second first-level list item
    - Indented list item
    - A second identented list item
- Third first-level list item

***

1. First first-level list item
1. Second first-level list item
    1. Indented list item
    1. A second identented list item
1. Third first-level list item
```

results in

![Bildschirmfoto 2020-08-04 um 15 39 12](https://user-images.githubusercontent.com/12857772/89300617-c8153f80-d668-11ea-95eb-8ecb3e00a69c.png)

Can you do me a favor and try this? 🙂  Feel free to reopen if this doesn't work for you.

**Comment by morsssss** [comment]
Four spaces does work! Ha. I never thought to try that. Thanks :)

Can we fix this so that two spaces is sufficient? That's usually enough in markdown - and I'm sure someone else will hit this issue later on.

Also, the other issue still remains: two lists in a row, even separated by a newline, even if one is unordered and one is ordered, still get combined into a single list.

**Comment by matthiasrohmer** [comment]
My pleasure! The only chance to enable 2-spaces nested lists would be to add another monkey patch to amp.dev. Something Sebastian and I now strongly try to avoid as everything related to page building adds to our Python codebase which we would like to keep as small as possible. The upstream markdown implementation Grow is using (python-markdown) has been refraining to add support in https://github.com/Python-Markdown/markdown/issues/3

Similar for consecutive lists. The python-markdown project claims it is following standards in https://github.com/Python-Markdown/markdown/issues/636 - I am going to create a PR that enables the `sane_lists` extension for amp.dev though.

**Comment by morsssss** [comment]
Thanks!

I know it's not great to make this project even more complex. Alternately we could just document this in the contributors' guide... but of course most people won't notice that 🙄
