### ISSUE TITLE
amp-base-carousel snap-by looks broken

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amp.dev#4270]
![image](https://user-images.githubusercontent.com/726049/89228637-da25ae00-d594-11ea-8e5c-770269c9a3e8.png)

Seems like something should be there after ". This ..."

**Comment by caroqliu** [comment]
From https://github.com/ampproject/amphtml/issues/20595:
> For example, snap-align="2" means that the carousel will snap on every other slide. This is primarily useful when used with the `visible-count` attribute.
