### ISSUE TITLE
Pixi: Metric values don't correspond to position on plot

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4345]
![Screen Shot 2020-08-20 at 10 45 37 AM](https://user-images.githubusercontent.com/7919520/90807124-dbfcaa80-e2d2-11ea-9c2c-457b298a1ca1.png)
In the above screenshot you can see that while LCP is 2.141 seconds it is being plotted as >2.5s

**Comment by matthiasrohmer** [comment]
Thanks for reporting, that's something I am currently on 🙂
