### ISSUE TITLE
Pixi: amp-script in Pixi fails on relative URLs

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4347]
Pixi fails to run on amp.dev but does on https://amp.dev

amp-script shows the following error:
![Screen Shot 2020-08-20 at 11 37 09 AM](https://user-images.githubusercontent.com/7919520/90811457-7fe95480-e2d9-11ea-92b6-06a0faa6ffe5.png)

**Comment by nainar** [comment]
Note that PSI redirects amp.dev to https://amp,dev

**Comment by caroqliu** [comment]
> Note that PSI redirects amp.dev to https://amp,dev

So does validator.amp.dev.

**Comment by caroqliu** [comment]
This is fixed
