### ISSUE TITLE
Pixi: Finalize progress bars for Core Web Vitals

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#4358]
via @caroqliu. https://github.com/ampproject/amp.dev/pull/4354#issuecomment-678298594.

@nainar, @sebastianbenz: what do you think about visualizing the proportions?

**Comment by sebastianbenz** [comment]
> visualizing the proportions

Can you explain?

**Comment by matthiasrohmer** [comment]
Sure! I think what @caroqliu meant is that Page Speed Insights shows fast, average, slow as proportions like so:

![Bildschirmfoto 2020-08-24 um 10 06 59](https://user-images.githubusercontent.com/12857772/91019620-90f3d780-e5f1-11ea-8110-3445168d1027.png)

I adapted this behaviour for the Pixi scales:

![Bildschirmfoto 2020-08-24 um 10 13 10](https://user-images.githubusercontent.com/12857772/91020199-74a46a80-e5f2-11ea-97de-929c0ad68fef.png)

 In Ferdi's layout each speed category took up equal parts though:

![Bildschirmfoto 2020-08-24 um 10 05 27](https://user-images.githubusercontent.com/12857772/91019765-cf899200-e5f1-11ea-8c5c-e2dd026483b0.png)

The question is in which direction we want to go. In my opinion the scales are really hard to understand. Adding tooltips like PSI does will already help:

![Bildschirmfoto 2020-08-24 um 10 14 48](https://user-images.githubusercontent.com/12857772/91020440-b8976f80-e5f2-11ea-9fde-6356a1cb139a.png)

But additionally I think we should stick to proportions as only then a good page has a big green chunk.

**Comment by sebastianbenz** [comment]
I like the scales and percentages from PSI, having only a visual indicator as in our mocks is less clear. However, marking the actual value on the same scale is a bit confusing. 

One note: what I don't like about PSI is that it uses three colors (orange, green, yellow) to encode a binary result (fail / pass). What does orange mean?

**Comment by matthiasrohmer** [comment]
>However, marking the actual value on the same scale is a bit confusing.

Right! That's what I am stumbling over.

Is the PSI result really binary? Actually it puts each vital in a category of "slow", "average" and "fast" - these categories are also what the three colors map to.

**Comment by caroqliu** [comment]
One option could be to remove the separation markers and thresholds — i.e. 2.5s, 4s for LCP — that are plotted so there is not as much clutter. We still want to make this information available, possibly in the `?` icon next to the test title. 

To @sebastianbenz's point, if we want to shift to a pass/fail model we could also calculate based on [this information](https://web.dev/vitals/):

> For each of the above metrics, to ensure you're hitting the recommended target for most of your users, a good threshold to measure is the 75th percentile of page loads, segmented across mobile and desktop devices.
> 
> Tools that assess Core Web Vitals compliance should consider a page passing if it meets the recommended targets at the 75th percentile for all of the above three metrics.

**Comment by caroqliu** [comment]
This is fixed by #4434
