### ISSUE TITLE
Pixi: Lab data isn't laid our properly

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4369]
Issues: 
Scales are off
Numbers aren't showing up on the scales correctly

![Screen Shot 2020-08-24 at 12 43 28 PM](https://user-images.githubusercontent.com/7919520/91096812-7e8a9580-e613-11ea-937a-70f27cee32c0.png)

**Comment by caroqliu** [comment]
Dedup with #4450 which has an updated screenshot
