### ISSUE TITLE
[pixi] Make sure input bar is visible in first viewport on most common screen sizes

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#4378]
The input bar is the most important part of the page, it should be instantly visible. Currently it looks like this:

<img width="520" alt="Screen Shot 2020-08-25 at 19 24 57" src="https://user-images.githubusercontent.com/380472/91207269-c63f1900-e708-11ea-9fe3-2b3d576101a8.png">

**Comment by robinvanopstal** [comment]
Handed this over to Ferdi - will be solved in a separate PR. :)

**Comment by caroqliu** [comment]
This is fixed
