### ISSUE TITLE
[Pixi] Internationalization: Support right to left languages

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4379]
UI: Add support for RTL languages
Page layout: Add support for RTL languages.

**Comment by matthiasrohmer** [comment]
via @patrickkettner: especially consider this for the PSI scales.

**Comment by patrickkettner** [comment]
After checking with some speakers, Arabic would be RTL for numbers, Hebrew should be LTR

**Comment by caroqliu** [comment]
#4702 fixes the orientation of the scales for RTL. 

Also need to do:

- [ ] Field and lab data tabs should be right-aligned on the CWV container
- [ ] Recommendation items and filter should be right-aligned, with "Next advice" available on the left side (dir="rtl" shoulddo most of the automatically)


Open question:
- Should the visual itself be RTL in addition to be oriented left of the text? i.e. Should the green page loads bar be right-aligned over the grey bar? Should the lab data visual start with the green region on the right, yellow region in the middle, and red region on the left?

**Comment by caroqliu** [comment]
Now that #4750 and #4757 are merged this issue is fixed.
