### ISSUE TITLE
Pixi: Teaser page should link to Page experience as well

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4383]
The current Pixi teaser page only directs to Web Vitals. 
It should also direct to page experience. 
Link to be used: https://developers.google.com/search/docs/guides/page-experience

**Comment by nainar** [comment]
@caroqliu can we make this change so that it lands by Aug 31?

**Comment by caroqliu** [comment]
To clarify you want both links? If so, both as buttons or one inline with text?
