### ISSUE TITLE
Update use of "Dev Channel" to "Beta Channel" 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#4390]
### Problem
Several pieces of documentation, such as [Enable experimental features](https://amp.dev/documentation/guides-and-tutorials/learn/experimental/) and [Geolocation-based consent flow](https://amp.dev/documentation/examples/user-consent/geolocation-based_consent_flow/?format=websites) say `dev-channel`/`Dev Channel`. But it is not an option at [https://cdn.ampproject.org/experiments.html](https://cdn.ampproject.org/experiments.html). Instead they should be enabling the `beta-channel`.

**Comment by souvik-03-07-2001** [comment]
can I take this?
