### ISSUE TITLE
Pixi: graph values rendering incorrectly in edge cases

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amp.dev#4417]
small screen values overlapping
![image](https://user-images.githubusercontent.com/465414/91882309-c4b5a980-ec50-11ea-8c19-024a0b15f664.png)

long value being clipped 
![image](https://user-images.githubusercontent.com/465414/91882428-ef9ffd80-ec50-11ea-9b3a-8314a8534ac9.png)

**Comment by caroqliu** [comment]
Related to #4358
