### ISSUE TITLE
Pixi: Recommendation loading UI is missing

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amp.dev#4420]
Expected:
![Screen Shot 2020-09-01 at 3 44 30 PM](https://user-images.githubusercontent.com/10456171/91898659-0c94fa80-ec6a-11ea-809a-21b04e6bcb4e.png)

Actual:
![Screen Shot 2020-09-01 at 3 44 26 PM](https://user-images.githubusercontent.com/10456171/91898668-10288180-ec6a-11ea-9bde-6b559a07fced.png)

I recall seeing this at one point last week, what happened? cc @robinvanopstal @matthiasrohmer

**Comment by caroqliu** [comment]
Also @nainar Is the loading copy in the mock finalized?

**Comment by nainar** [comment]
It should be "Improve your AMP page"

Let's remove `Wait a moment` from that copy

**Comment by caroqliu** [comment]
Related: Loading UI does not reset between multiple "Analyze". 
Actual:
![2e366f2d-54ac-4456-aae8-df4cfcb28073](https://user-images.githubusercontent.com/10456171/91900481-c0978500-ec6c-11ea-87c0-2023b2671967.gif)

Note the duplicated recommendations on the 2nd run:
![Screen Shot 2020-09-01 at 4 03 52 PM](https://user-images.githubusercontent.com/10456171/91900493-c4c3a280-ec6c-11ea-8151-4685b6ed02a0.png)

Expected:
- Performance colors should be reset to grey for "Analyzing..."
- Boolean test values should be reset to grey with "Analyzing..." instead of the old status.
- Preexisting recommendations should be cleared before each run.

**Comment by caroqliu** [comment]
The recommendations are being reset correctly between runs of the same instance now. All that remains is the need to reset text coloring, which is somewhat buried in this issue. Closing this issue in favor #4478.
