### ISSUE TITLE
Pixi: Intro copy should be one chunk, not three

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#4445]
<img width="476" alt="Bildschirmfoto 2020-09-07 um 17 17 19" src="https://user-images.githubusercontent.com/12857772/92401501-187f3180-f12e-11ea-8ee0-f1847cc7eca3.png">

**Comment by matthiasrohmer** [comment]
The texts are now vertical paragraphs, hence closing.

**Comment by caroqliu** [comment]
Reopening due to #4532

**Comment by caroqliu** [comment]
Updated issue name to resolve both the original issue (scrollbar) and a related issue (need to update intro text layout)

**Comment by matthiasrohmer** [comment]
Resolved by #4654.
