### ISSUE TITLE
Pixi: Tablet view too narrow

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amp.dev#4470]
![image](https://user-images.githubusercontent.com/10456171/92653593-96714300-f2bc-11ea-9d05-5fc245b23ab4.png)

**Comment by nainar** [comment]
Can we make the URL bar smaller on tablet?

**Comment by caroqliu** [comment]
> Can we make the URL bar smaller on tablet?

@nainar Do you mean smaller in width?

**Comment by nainar** [comment]
yes
