### ISSUE TITLE
Pixi: how should API failures be handled?

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amp.dev#4473]
as of right now, SafeBrowsing is failing due to quota exhaustion. I have applied for an increase in quota, but I am not aware of a discussion about how to handle this scenario

**Comment by caroqliu** [comment]
They result in `Analysis Failed` with overall status "Oops! Looks like something went wrong. We weren't able to get reliable results for all required criteria. Please rerun the test."

This should surface now with #4471

**Comment by patrickkettner** [comment]
do we want to encourage people to reuse the API when we know it will fail? it isn't currently clear that it is an understood issue (rather than a ghost in the machine or problem with their site)

**Comment by caroqliu** [comment]
For SafeBrowsing, Mobile-friendliness, and CWV we can surface unique recommendations saying "Please go to <link> to rerun the test." I'm torn on what the overall status should say. It's true that we are not able to get results for all required criteria. It could be frustrating to encourage users to rerun the test without assurance it will work on subsequent times.

A good post-launch feature could be to render buttons like this on individual test blocks to re-run them in isolation.
![image](https://user-images.githubusercontent.com/10456171/92734338-74bc9e00-f346-11ea-8b18-c564d190caec.png)

**Comment by caroqliu** [comment]
> do you mean link to a different scanner? Like this if mobile friendliness is failing, etc

Yeah it's not ideal to be linking away from the tool but at least it will bring them to the source of truth?

**Comment by nainar** [comment]
Per @caroqliu point - we don't have the space in the `additional check` to show this message. And just showing Error is not sufficient of a CTA.

**Comment by caroqliu** [comment]
Update:
- Overall status banner should be updated to describe which test has failed, as well as anchor jump to that section.
- Failed test should link to relevant dashboard to run the API directly -- can we put this in the info tip?

**Comment by caroqliu** [comment]
Reopening as we do not have an interface in place for when PSI fails. Note "Analyzing" state goes on indefinitely while console shows `undefined` errors:
![image](https://user-images.githubusercontent.com/10456171/94286333-dd00a780-ff22-11ea-955d-29ee378336d7.png)
![image](https://user-images.githubusercontent.com/10456171/94286343-e12cc500-ff22-11ea-9624-4202e873181a.png)

@matthiasrohmer Maybe you and Ferdi can settle on a good simple degradation on Monday?
