### ISSUE TITLE
Add Product Stories as story creation tool

### ISSUE THREAD

**Issue by g00dv1n** [ampproject/amp.dev#4474]
### Story creation resource name

Product Stories

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [x] CMS
- [ ] Platform
- [ ] Other

### URL

https://productstories.pro/

### Image
![image](https://user-images.githubusercontent.com/4170706/92724194-e1e62880-f372-11ea-9906-cf3b78d103f2.png)

### Description

eCommerce tool for the automatic generation of Web Stories from the product information.

### List of Stories

https://productstories.pro/s/5f57746fccc97c057e6fac99/grain-free-recipe-drydog-food

https://productstories.pro/s/5f5798e2ccc97c057e6fac9b/the-ultimate-sports-watch-series-3

https://productstories.pro/s/5f589d21ccc97c057e6fac9c/cairo-sneaker-mesh-leather-look

https://productstories.pro/s/5f58a427ccc97c057e6faca0/blooming-colors-lips-collection

https://productstories.pro/s/5f58b638ccc97c057e6facaa/easy-portable-steamer-comfort-life

https://productstories.pro/s/5f58c728ccc97c057e6facb9/if-it-makes-you-happy

https://productstories.pro/s/5f58d1b6ccc97c057e6facc4/black-lace-babydoll-dress

https://productstories.pro/s/5f58d8f1ccc97c057e6faccc/rotating-round-office-chair

https://productstories.pro/s/5f58dfa8ccc97c057e6facd6/toys-talking-farmenes

https://productstories.pro/s/5f58ebf8ccc97c057e6face3/tasty-healthy-andamp-simple-meal-kit

**Comment by matthiasrohmer** [comment]
@shishirm, could you please review this?

**Comment by shishirm** [comment]
Thank you for filing this. We will start the review process and provide any feedback by the end of the week.

**Comment by g00dv1n** [comment]
@shishirm 
Any updates?

**Comment by shishirm** [comment]
Hello. We're still working on this. Will get back to you with feedback hopefully in a couple of days, if not earlier.

**Comment by shishirm** [comment]
Hello @g00dv1n , thank you so much for filing this. We've reviewed the various Stories and before we list on amp.dev, some fixes are requested.

**Diverse Story Types**

All the stories submitted fit into 3 templated formats. Would you happen to have some more / diverse templates to share? If not, while we will still be able to list the tool, we will not mark it with "WYSIWYG" but will instead create a new category i.e. "Templatized Editor".

**Must-Fix**

- The poster-portrait-src dimensions are not set to the right aspect ratio and the right dimensions. Kindly follow the guidance [here](https://amp.dev/documentation/components/amp-story/#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src)).

**Nice-To-Haves**

These are NOT required to list on amp.dev but we'd like to pass along these recommendations to incorporate in the tool based on reviewing the submitted Stories. Some of the rationale to include can also be found [here](https://blog.amp.dev/2020/02/12/seo-for-amp-stories/).

- Some of the videos are not optimized and their load is janky and slow. Please follow video recommendations [here](https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/#video).
- The publisher-logo-src specified does not meet the recommended design guidelines. We suggest following them [here](https://amp.dev/documentation/components/amp-story/#publisher-logo-src-guidelines), with sufficient padding (8px) all around.
- All the poster-portrait-src images have burned in text. This is highly discouraged as various representations of Stories will overlay text on top of the poster and this will make the text unreadable. Additionally, the poster should be representative of the entire story and should encourage users to click into the Story.
- Some pages in Stories have text blending in with backgrounds i.e. incorrect contrast.
- We suggest providing the ability to add descriptive alt attributes for every image.
- We suggest providing the ability to add subtitles for videos via track elements as part of the tool.
- In lieu of track elements for subtitles, for videos with text burned in, we suggest providing the ability to add alt text attributes on videos.
- It is suggested to provide the ability to add OGP data to Stories from within the tool.
- We recommend providing the ability to add structured data onto the page.
- Avoid the repetitive use of the same animations on pages.

Once your must-fix issues are in place, I'll go ahead and create a PR to add Product Stories to amp.dev. Please feel free to update this issue when ready.

Thank you!

**Comment by g00dv1n** [comment]
@shishirm 
Thanks for your feedback. We appreciated it.

We fixed poster-portrait-src dimensions and publisher-logo-src. Other points we added to our backlog.

About diverse story types:
Now we have 10 different templates (we going to add more according to different product categories), but you understand us correctly. We are not "WYSIWYG" editor. So, a new category will be even better.

Waiting for your PR to add Product Stories to amp.dev.
Thanks.

**Comment by shishirm** [comment]
Hello @g00dv1n ,

Hope you're doing well! We wanted to reach out and let you know of the new [Web Story Developer Preview Group](https://groups.google.com/a/amp.dev/g/web-stories-devpreview). We'll be using this forum to disseminate early previews of testable / working code for new and upcoming features in Web Stories.

Would you be interested in signing-up for the same? We're expecting about 1-2 emails a month and the information will also be available on Github.

Thanks a lot.

**Comment by g00dv1n** [comment]
@shishirm 
Hello
We will be happy to join.

Thanks for the updates.
