### ISSUE TITLE
Menu button misaligned on mobile devices

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4483]
The menu is about 30px below the rest of the header on mobile devices. I see this on my Pixel 2, and I see it in Chrome's emulator:

![amp dev_(iPhone 6_7_8)](https://user-images.githubusercontent.com/29419498/92791169-743dfa80-f37a-11ea-902c-522a8c71e2ee.png)

I don't know this CSS that well, but I do wonder why the `31px` is in this rule:

```
.has-banner+.ap-o-burger-menu-label {
    top: calc(49px + 31px);
}
```

**Comment by patrickkettner** [comment]
thats probably from hiding the banner yesterday. ill dig into it

**Comment by morsssss** [comment]
This is an excellent theory... thanks!
