### ISSUE TITLE
Pixi: The loading checks status bar will non deterministically not go away

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4540]
See screenshot here: 
![Screen Shot 2020-09-15 at 10 08 57 AM](https://user-images.githubusercontent.com/7919520/93242365-93060d80-f73b-11ea-9887-54b6e788c086.png)

Most commonly happens on WaPo templates. 
Test URL: https://www.washingtonpost.com/sports/2020/08/07/derrius-guice-arrested/?outputType=amp

Experienced by Malte and me

**Comment by caroqliu** [comment]
Dedup with #4458
