### ISSUE TITLE
Pixi: Clarify Field test and Lab test more

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4543]
- [x] Information tips for Field and Lab data - See here: https://docs.google.com/document/d/15KTgFoQnmPEDhHyfANe-Ln5_qG20rTK1QOe4F6IfejQ/edit
- [ ] Field data should have a info banner inline explaining that this is 28 days aggregated data hence data will lag.

**Comment by caroqliu** [comment]
@nainar Is there copy available for the second point above? Can this go in the info tip?

**Comment by nainar** [comment]
@patrickkettner did you want this in the info tip or on the screen. 

`This data updated daily for the trailing 28-day period.`

**Comment by patrickkettner** [comment]
more prominent the better,imo
