### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#4550]
Travis will close down the travis-ci.org domain by 31st of December. Fore more context see [this support article](https://docs.travis-ci.com/user/migrate/open-source-repository-migration).

**Comment by matthiasrohmer** [comment]
Tentatively assigning to you, @patrickkettner. I guess this also impacts other @ampproject repositories.

**Comment by patrickkettner** [comment]
this is being handled by the ampproject org as a whole, closing this off as a result
