### ISSUE TITLE
Playground: <amp-bind> not autoimported

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4565]
It's pretty awesome that the AMP playground auto-imports the scripts needed to run AMP components!

But as far as I can tell it doesn't do so for `<amp-bind>`. You can see this, for example, in [this `<amp-script>` example](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-script%2F20&format=websites&_gl=1*7i9rvn*_ga*YW1wLW5JWnZlT09hRlFLaGx0Yl8wRmNReXc.).

Click on the "Surprise me" button, and you'll see the error in the Console.

**Comment by matthiasrohmer** [comment]
I know, that's a shame: https://github.com/ampproject/amp.dev/issues/3911 ... 😅
