### ISSUE TITLE
Staging server not up to date

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4570]
I got this while trying to run tests on camp.samples.amp.dev. This worked the last time I did it - so I'm not sure why it failed this time!

However, I do see two errors in the console:

![image](https://user-images.githubusercontent.com/29419498/93393580-c3839f80-f840-11ea-8c0e-08b51129e886.png)

Sadly the JS there is minified. Here's what it looks like to me:

![image](https://user-images.githubusercontent.com/29419498/93393666-f168e400-f840-11ea-8c7f-a59cf5b07183.png)

**Comment by patrickkettner** [comment]
you may be hitting after [this change](https://github.com/ampproject/amp.dev/pull/4563). Are you up to date on the repo and node modules?

**Comment by morsssss** [comment]
That was a quick response!

I'm using the staging link, so, probably not :)

**Comment by patrickkettner** [comment]
> I'm using the staging link, so, probably not :)

how do you mean?

**Comment by morsssss** [comment]
I mean, I didn't build this on my machine. I'm accessing Pixi here:

https://amp-dev-staging.appspot.com/page-experience/

**Comment by patrickkettner** [comment]
ah! looks like deploys were broken, ill check it out

**Comment by patrickkettner** [comment]
fixed! closing
