### ISSUE TITLE
Pixi: unsightly blue border around accordion headers

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4571]
This should be an easy fix, at least!

I see this on Chrome on my Mac.

![image](https://user-images.githubusercontent.com/29419498/93393887-49074f80-f841-11ea-8670-8c3b27ec01da.png)

**Comment by patrickkettner** [comment]
@PeterSaathoff-Harshfield is this ok to hide?

**Comment by PeterSaathoff-Harshfield** [comment]
No, the keyboard focus ring is essential for keyboard-only use and every keyboard-focusable control must have a visible focus ring or style. If you want, you can design a custom focus style that looks different, as long as it's clearly visible.
I've heard there is some way to hide it when the mouse clicks on the control (and thus moves keyboard focus there), but I don't know how that's accomplished.

**Comment by morsssss** [comment]
Got it! I thought it was an example of a common bug, where someone doesn't disable the browser's natural inclination to place a border around a focused element. It makes sense to me that we need this for accessibility.

In that case, I'm no designer - but right now it looks to me like it's a bug. I think it would be best to at least provide some padding so the box didn't touch text in the container or the caret that expands/contracts the accordion. Also, right now when the accordion expands, it looks even more like a bug.

I do like the design, for example, of the border around the textarea where I'm typing right now in github...

![image](https://user-images.githubusercontent.com/29419498/93531083-a5837100-f90c-11ea-8524-d606d9b23078.png)

**Comment by PeterSaathoff-Harshfield** [comment]
Unfortunately I think this is  a common misconception that focus rings should be hidden, so it's important to understand why they exist..
The ideas around adjusting the padding are good, just beware that different browsers draw the ring in slightly different ways.

**Comment by patrickkettner** [comment]
@matthiasrohmer does ferdi have a design for focus rings? I don't see it in Zeplin, and therefore am not sure if this is working as intended or needs a different design implemented?

**Comment by caroqliu** [comment]
Looks like there has been more padding added recently
![image](https://user-images.githubusercontent.com/10456171/93789586-0ad2ad00-fc00-11ea-9ae6-bd169883d70c.png)

**Comment by matthiasrohmer** [comment]
@patrickkettner, sorry didn't see this. No there is no dedicated design but I think we agreed to stick with browser defaults. Robin added some more padding though to make it look more decent as Caroline correctly pointed out 🙂
