### ISSUE TITLE
Pixi: when returning to page, "Analyze" button is disabled

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4574]
Steps to reproduce:

1. Use Pixi to analyze a URL. Yay!
1. Get excited about a recommendation and click on a link therein. Browser navigates to new page.
1. Use browser's "back" button to return to Pixi to see more recommendations.
1. You have to analyze the page all over again, unfortunately. But, worse still, the "Analyze" button is disabled even though there's a valid URL in the input. The input isn't checked on page load; this requires a keypress. So you need to backspace over part of your URL and retype it.

**Comment by caroqliu** [comment]
This should be fixed by #4560 which no longer allows disabling the button

**Comment by caroqliu** [comment]
> But nevertheless I think it would be good to add target="_blank" to the links in the recommendations 🤔

True true, though that's mentioned in #4573

**Comment by morsssss** [comment]
This is true!

I'm gratified by your prompt attention to the issues I raised just yesterday. If it's useful, I'll do another QA pass tomorrow :)
