### ISSUE TITLE
Pixi: Polish for values in Lab test

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4616]
![Screen Shot 2020-09-21 at 1 02 05 PM](https://user-images.githubusercontent.com/7919520/93815854-84bc6380-fc0b-11ea-925e-3532c9f1a7c4.png)

This needs the following fixes: 
- Values to the far right are falling outside the CWV container
- The arrows point down instead of the right
- The CLS value 0.00 is coloured orange instead of green

Page tested: https://www.bonappetit.com/story/food-businesses-covid-19/amp

**Comment by caroqliu** [comment]
Steps to reproduce the `6.5s` beyond the max:
- Analyze https://amp-dev-staging.appspot.com/page-experience/?url=https://amp.dev
- Wait until lab results come in for the given URL
- In the same page instance, change the input URL to https://www.bonappetit.com/story/food-businesses-covid-19/amp and run "Analyze"
- Observe numbers may be on the wrong side of their indicators.
