### ISSUE TITLE
Pixi: Failing AMP validation

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4620]
Make sure that Pixi passes AMP validation. The loading page and the results page both fail validation currently

**Comment by caroqliu** [comment]
After #4648 these are the remaining validator issues via the Chrome extension on the local server version of the page:
![image](https://user-images.githubusercontent.com/10456171/93931078-56628500-fcec-11ea-915c-063e5226ad4e.png)

However I am not seeing the same issues on validator.amp.dev for the staging URL, so will take another look once the first PR is in.

**Comment by caroqliu** [comment]
Verified this is OK in staging now by both @nainar and myself
