### ISSUE TITLE
Pixi: Shouldn't show Fixit now for non AMP URLs

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4621]
See: https://www.nytimes.com/2020/09/21/us/politics/trump-supreme-court.html

![Screen Shot 2020-09-21 at 6 28 18 PM](https://user-images.githubusercontent.com/7919520/93836662-5739df00-fc38-11ea-909f-64d5dc897f28.png)

**Comment by caroqliu** [comment]
Fixed by #4613
