### ISSUE TITLE
Pixi: turn autocomplete on input bar off?

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4641]
https://screenshot.googleplex.com/8W3RC5Zn2ahGxzq

**Comment by caroqliu** [comment]
@nainar What browser is this? This should be fixed by adding `autocomplete="off"` onto the input element.

**Comment by zewenliang** [comment]
That was my screenshot. If it helps I am using Chrome with version 85.0.4183.102. 

Yes turning off the autocomplete can be an immediate workaround. But I think it is also helpful if the autocomplete dropdown can remember the recent ones I put here before. It was just that the URLs showed in my screenshot has nothing to do with my recent activity - i don't know where those 3 URLs were coming from.
