### ISSUE TITLE
Repeated CSS on amp.dev

### ISSUE THREAD

**Issue by kevinkimball** [ampproject/amp.dev#4650]
### Current behavior

The custom style tag for amp includes this snippet repeated nearly 100 times: 

```
@keyframes rotate {
                to {
                    transform: rotate(360deg)
                }
            }
```

Please also provide:
- Page link: amp.dev
- (Optional) Screenshots/videos:
<img width="671" alt="Screen Shot 2020-09-22 at 3 00 07 PM" src="https://user-images.githubusercontent.com/6886483/93941977-59f20e00-fce4-11ea-81c4-35c177696566.png">

### Expected behavior/code
This should only be included once 

### Reproduction procedure
Please provide the steps to reproduce the problem:
Visit the site and inspect the source 

- What browser are you using?
Chrome 87
- What O/S are you using?
OSX

**Comment by matthiasrohmer** [comment]
Thanks for the report, @kevinkimball! Fixed this in #4652. The loading indicator is actually only used in the playground and SASS seems to have done weird stuff with unused `@extends` when compiling amp.dev's CSS.
