### ISSUE TITLE
Pixi: GH template on amphtml repo isn't filled in properly

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4651]
Let's make sure that the GH issue that we file from Pixi is filled in with the values for all the metrics properly.

**Comment by caroqliu** [comment]
@nainar Is this supposed to be closed?

**Comment by matthiasrohmer** [comment]
I guess it's a duplicate of https://github.com/ampproject/amp.dev/issues/4633. 🙂

**Comment by nainar** [comment]
Yup what Matthias said.
