### ISSUE TITLE
Pixi: Analyze button doesn't work after you hit a cached page. 

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4669]
Once you hit a cached page - you get this banner: 
<img width="701" alt="Screen Shot 2020-09-23 at 7 19 39" src="https://user-images.githubusercontent.com/7919520/94047944-a04c7900-fd87-11ea-9d16-da89b44c1fb7.png">

However, when you enter a new URL in the bar and try to hit `Analyze` the button doesn't work. 

There is nothing in the Console.

**Comment by caroqliu** [comment]
Does this behavior also occur when giving an invalid AMP page? If so it is likely related to the button being disabled so as to disallow spamming "Enter" when results are actually loading. We should be sure not to run other tests when the linter returns with these cases.

**Comment by nainar** [comment]
@caroqliu yes it happens on invalid and non AMP pages as well.
