### ISSUE TITLE
Homepage news carousel should use amp-carousel

### ISSUE THREAD

**Issue by kevinkimball** [ampproject/amp.dev#4670]
### Current behavior
The news carousel on the amp.dev homepage does not use amp-carousel (it uses CSS)

Please also provide:
- Page link: amp.dev
- (Optional) Screenshots/videos:
<img width="431" alt="Screen Shot 2020-09-23 at 10 39 54 AM" src="https://user-images.githubusercontent.com/6886483/94049057-46e54980-fd89-11ea-9043-7cc614c39ed9.png">

### Expected behavior/code
We should use amp-carousel, since it will prevent the carousel from being laid out when it is outside the viewport. This should improve LCP and FID 

### Reproduction procedure
Please provide the steps to reproduce the problem:

Inspect HTML source 

- What browser are you using?
Chrome
- What O/S are you using?
OSX

**Comment by jaygray0919** [comment]
Agree!

**Comment by patrickkettner** [comment]
@CrystalOnScript is the homepage getting a redesign as well, or just docs pages?

**Comment by matthiasrohmer** [comment]
That has been fixed in the meantime.
