### ISSUE TITLE
Missing documentation on data-ampdevmode

### ISSUE THREAD

**Issue by Gregable** [ampproject/amp.dev#4671]
### Problem
We should document somewhere the behavior of `data-ampdevmode`.

### Location
I don't have a strong opinion. Mostly this would be critical for search requests.

### Content type
Reference probably.

### Information architecture (optional)
Here's where the attribute was introduced:
https://github.com/ampproject/amphtml/issues/20974

It was originally used only as an internal thing for the Wordpress plugin, but it appears that interest is growing. Weston wrote some additional docs [here](https://weston.ruter.net/2019/09/24/integrating-with-amp-dev-mode-in-wordpress/). 

There is a concise summary in [this comment](https://github.com/ampproject/amphtml/issues/29457#issuecomment-696351959). The "first meaning" is what should be documented for now as the "second meaning" part is still under development.

I can also answer any questions if the behavior is unclear.

**Comment by matthiasrohmer** [comment]
After Ben's recent rewrite of the amp-script docs theres actually a tip at the end of the [Calculating the script hash](https://amp.dev/documentation/components/amp-script/#calculating-the-script-hash) section but maybe we can have it somewhere more prominent...

/cc @morsssss

**Comment by morsssss** [comment]
Agreed! This attribute isn't documented at all. I made an issue for this a little while ago: https://github.com/ampproject/amp.dev/issues/4215

Closing this as a duplicate.
