### ISSUE TITLE
Pixi: Give scroll to top prompt a margin

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4698]
It is currently suck to the right which makes it hard to notice. 

Also can we increase the background shadow slightly?

**Comment by caroqliu** [comment]
This is a question for Ferdi, the current is exactly the button provided in the mocks. Also why isn't this considered polish?

**Comment by Ferdinand-Weinrother** [comment]
I agree with a slightly stronger shadow. But I like the position. Otherwise the element has no stability on the page. Besides, it is just an additional assistant and should not distract too much from the actually important elements.
