### ISSUE TITLE
Pixi: Submit issues to wg-performance instead of amphtml repo 

### ISSUE THREAD

**Issue by kevinkimball** [ampproject/amp.dev#4711]
### Problem
Kris is concerned this will generate too many issues and be harder to triage in amphtml repo 

### Solution
Submit Pixi issues to wg-performance repo 

### Alternatives
We could create a new repo, but this would require a lot of approvals so we don't think it is worth the effort 

cc @nainar

**Comment by nainar** [comment]
Can do!

In that case can someone on Perf WG approve this: https://github.com/ampproject/wg-performance/pull/47

cc @caroqliu

**Comment by nainar** [comment]
@caroqliu isn't this fixed?

**Comment by caroqliu** [comment]
Yep, here's an [example link that we show for amp.dev](https://github.com/ampproject/wg-performance/issues/new?assignees=&labels=Type%3A+Page+experience&title=Pixi:+Poor+page+experience&body=URL%0A---%0Ahttp%3A%2F%2Famp.dev%0A%0ADetails%0A---%0A%0A%7C%20Metric%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Field%20data%20%7C%20Lab%20data%20%7C%0A%7C-----------------%7C------------%7C---------%7C%0A%7C%20LCP%20%7C%203.3%20s%20%7C%203.8%20s%20%7C%0A%7C%20FID%20%20%7C%20289%20ms%20%7C%20425%20ms%20%7C%0A%7C%20CLS%20%20%7C%200.05%20%20%7C%200.17%20%20%7C%0A%7C%20HTTPS%20%20%7C%20pass%20%7C%20---%20%7C%0A%7C%20Safe%20browsing%20%20%7C%20pass%20%7C%20---%20%7C%0A%7C%20Mobile-friendliness%20%20%7C%20n%2Fa%20%7C%20---%20%7C%0A%7C%20Intrusive%20Interstitials%20%7C%20%3Cpass%2Ffail%3E%20%7C%20---%20%7C%0A%0ANotes%0A---%0A%0AComponents%20in%20use%3A%20amp-install-serviceworker%2C%20amp-consent%2C%20amp-geo%2C%20amp-analytics%2C%20amp-animation%2C%20amp-mustache%2C%20amp-list%2C%20amp-autocomplete%2C%20amp-form%2C%20amp-lightbox%2C%20amp-bind%2C%20amp-user-notification%2C%20amp-iframe%0A%0A%0A%3C!--%0A%3CAdditional%20notes%3E%0A--%3E%0A%0A%2Fcc%20%40ampproject%2Fwg-performance) (lab data CLS needs improvement without recommendations)
