### ISSUE TITLE
[Accessibility] Expandable sections aren't expandable/collapsible with enter/space

### ISSUE THREAD

**Issue by PeterSaathoff-Harshfield** [ampproject/amp.dev#4712]
Environment:
Any OS/browser

Steps to reproduce:
1. Open https://amp-dev-staging.appspot.com/page-experience/
2. Enter a valid URL and press Analyze
3. Press tab to move keyboard focus to the expandable sections below the "Take action. Improve your AMP site" heading
4. When a section has focus, press enter and space

Expected:
These buttons should accept both enter and space to expand/collapse them

Actual:
Enter has no effect and space pages down

![image](https://user-images.githubusercontent.com/30604285/94316502-4f7c8200-ff39-11ea-8df1-f82a83ea66d6.png)

**Comment by robinvanopstal** [comment]
Hi @PeterSaathoff-Harshfield, this will only work on press `enter` since `e.preventDefault()` is not allowed in `amp-script`.
