### ISSUE TITLE
Emojis break build

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amp.dev#4735]
When attempting to add `🎉` to `pages/content/pixi/index.md`: 
```
✖  error     500: /page-experience.html - Error parsing /content/pixi/index.md: unacceptable character #xd83c: special characters are not allowed
```
![image](https://user-images.githubusercontent.com/10456171/94475657-66bba980-019d-11eb-884b-8d22bbdd24f7.png)

Once this is fixed let's add `🎉` to `No action needed!`

**Comment by matthiasrohmer** [comment]
There sadly is not much we can do about this: pyYAML doesn't like emojis. We stumbled over this for other features as well already, see https://github.com/ampproject/amp.dev/issues/4002

For the roadmap we fixed it by switching from YAML to JSON but that is not really practical for translation files. Another option would be to add the emoji via JS....
