### ISSUE TITLE
Debug and fix ampproject.org CI build

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#4822]
Per https://github.com/ampproject/amp.dev/pull/4226#issuecomment-705509180

**Comment by patrickkettner** [comment]
@sebastianbenz if you happen to have any leads here, i'd love to get this sorted so #4226 could get merged

**Comment by patrickkettner** [comment]
@matthiasrohmer did you have any thoughts on what may be causing the issue here?

**Comment by sebastianbenz** [comment]
@matthiasrohmer ping

**Comment by patrickkettner** [comment]
I fixed it!

**Comment by sebastianbenz** [comment]
Awesome!
