### ISSUE TITLE
amp-accordion documentation does not install amp-bind

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amp.dev#4828]
https://amp.dev/documentation/components/amp-accordion/#[data-expand]

![image](https://user-images.githubusercontent.com/10456171/95502747-48f9fb80-0978-11eb-9df5-5e7217b57f96.png)

**Comment by morsssss** [comment]
I think this is another instance of https://github.com/ampproject/amp.dev/issues/3911 .

**Comment by matthiasrohmer** [comment]
`amp-bind` is on the documentation page itself but is lacking for the iframe at https://preview.amp.dev/documentation/components/amp-accordion.example.4.html#amp=1

**Comment by morsssss** [comment]
Thanks for raising the priority, @matthiasrohmer  - it would be great to see this fixed!

**Comment by patrickkettner** [comment]
closing as a dupe of #3911
