### ISSUE TITLE
Request to add Join Stories as a Story Creation Tool on amp.dev

### ISSUE THREAD

**Issue by nggood** [ampproject/amp.dev#4848]
### Story creation resource name

Join Stories

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [ ] Platform
- [ ] Other

### URL

https://www.join-stories.com/

### Image

![Join_AMP DEV](https://user-images.githubusercontent.com/13469356/95723674-aee6cb80-0c75-11eb-9811-356e1fc4f033.jpg)

### Description

Long Story Short, Join Stories is the fastest and easiest Story creation tool.

### List of Stories

- https://showcase.join-stories.com/tesla-cars-timeline-hh9WH1Xnc/
- https://showcase.join-stories.com/spacex-key-events-EUpHmjrzo/
- https://showcase.join-stories.com/gaming-zD-u4sprX/
- https://showcase.join-stories.com/zidane-1998-zVGu_lG62/
- https://showcase.join-stories.com/porsche-museum-W6zMjN0M5/
- https://showcase.join-stories.com/sciences-appliques-la-physique-derriere-une-plaque-a-induction-fq0fMQ5-L/
- https://showcase.join-stories.com/primer-epidemic-MzNPytfjB/
- https://showcase.join-stories.com/la-pompe-Ooqbwzcxz/
- https://showcase.join-stories.com/7-lois-wtf-MWQxtDK16/
- https://showcase.join-stories.com/guide-dentretien-du-t-shirt-CDRSZNuq9/

**Comment by sdenaro** [comment]
@nggood expect the PR to be ready before end of week.

**Comment by nggood** [comment]
@sdenaro Thanks for the update !

**Comment by sdenaro** [comment]
@nggood Can you confirm this is OK with the thumbnail? 

https://join-stories.com/static/31f2c30a58381d1ffeadb6e6a470b593/e56b8/1-fs8.png

If you'd rather have the join logo, please let me know and provide me with an image URL and I will use that one.

Thanks

**Comment by sdenaro** [comment]
@nggood  see https://github.com/ampproject/amp.dev/pull/4892

**Comment by nggood** [comment]
@sdenaro I just received an email from you about our tool thumbnail. You can use the one attached within the issue (800x400px) 👍

**Comment by sdenaro** [comment]
@nggood I updated it to use the attached image

thankis

**Comment by matthiasrohmer** [comment]
Closed by https://github.com/ampproject/amp.dev/pull/4899
