### ISSUE TITLE
mailmodo.com

### ISSUE THREAD

**Issue by ApurvGpt** [ampproject/amp.dev#4852]
### 1. Resource name
mailmodo.com

### 2. Relevant format(s)

- [ ] websites
- [ ] stories
- [ ] ads
- [x] email

### 3. Resource type

- [x] editor
- [ ] service provider
- [ ] developer tool
- [ ] content platform
- [ ] CMS
- [ ] ads
- [ ] audio/video
- [ ] analytics vendor

### 4. Destination
 [amp.dev/documentation/tools](https://amp.dev/documentation/tools)

#### 4.1 If you chose 1 in Step 4:

Create AMP emails with inline forms so that your users can take actions right inside the email. Just like an app!
![mailmodo-logo-full](https://user-images.githubusercontent.com/3850706/95875744-fd888880-0d8f-11eb-981d-e2e80d647e85.png)

**Comment by ApurvGpt** [comment]
Hey @CrystalOnScript, would it be possible to get an update on it? When can I expect it to get merged?

**Comment by matthiasrohmer** [comment]
@sebastianbenz, this one is another AMP4Email tool waiting for approval.

**Comment by ApurvGpt** [comment]
Hi @sebastianbenz , the name of Mailmodo is misspelled in this commit. Could you please fix that.
The actual name is Mailmodo but it's mentioned as Mailmondo. TIA

**Comment by sebastianbenz** [comment]
Fixed in
https://github.com/ampproject/amp.dev/commit/b7f8e0a491e9982c845e2f128df09970a684c82d

>
