### ISSUE TITLE
Pixi: Testing redirected page not provided page. 

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4871]
Because https://www.nytimes.com/live/2020/10/16/us/trump-biden-town-halls.amp.html redirects to https://www.nytimes.com/live/2020/10/16/us/trump-biden-town-halls, that's the one we are running through Pixi and treating as non AMP.

This means https://www.nytimes.com/live/2020/10/16/us/trump-biden-town-halls.amp.html  ends up being recognized as a non AMP page.

**Comment by nainar** [comment]
@matthiasrohmer @tharders

**Comment by nainar** [comment]
@caroqliu

**Comment by nainar** [comment]
The best way to solve this:

1. Instead of showing a banner that says this isn't an AMP page, we should tell the user that while the submitted page is an AMP page, the page the user is experiencing is a redirect to a non AMP page. And advise that they test the cached page.

2. Add support for testing the cached AMP page

**Comment by sebastianbenz** [comment]
Closing as we can't fix it.
