### ISSUE TITLE
Remove `Your AMP page needs improvement` recommendation if no field data is available

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4877]
Swap the `Your AMP page needs improvement`recommendation to instead advertise that there is no field data available.

**Comment by patrickkettner** [comment]
@robinvanopstal was there any blockers for this?

**Comment by patrickkettner** [comment]
cc @matthiasrohmer

**Comment by bezoerb** [comment]
Do we have a test page available for this? Any URL to reproduce the error message?

**Comment by patrickkettner** [comment]
a valid amp document that has low/no traffic should trigger it
