### ISSUE TITLE
Pixi doesn't work and says "This URL is invalid." for a valid AMP page

### ISSUE THREAD

**Issue by sisidovski** [ampproject/amp.dev#4887]
### Current behavior

- Page link: https://amp.dev/page-experience/
- (Optional) Screenshots/videos:
![Screen Shot 2020-10-22 at 19 57 34](https://user-images.githubusercontent.com/1642255/96877853-20fcb300-14b5-11eb-91b0-c0826ae70271.png)

Tested this URL. https://news.yahoo.co.jp/amp/pickup/6374389

Given URL is a valid AMP page, but the page audit doesn't run and shows "This URL is invalid." on AMP Page Experience Guide page. It's difficult to understand what's going on and how to fix it from this error message.

I looked into the network and noticed the lint API only returns `{"status": "error"}` without any other messages.
https://amp.dev/page-experience/api/lint?url=https%3A%2F%2Fnews.yahoo.co.jp%2Famp%2Fpickup%2F6374389

I checked the API code and realized this happens because the given AMP page doesn't have 'Content-Type' header in the response, and API doesn't care if the header exists or not, and makes type error. This is one problem I think.

```
[22:41:38] [Pixi API] › ✖  error     Unable to lint https://news.yahoo.co.jp/amp/pickup/6374389 TypeError: Cannot read property 'includes' of null
    at RateLimitedFetch.fetchHtmlResponse (/Users/sisidovski/Projects/amp.dev/platform/lib/utils/rateLimitedFetch.js:120:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async execChecks (/Users/sisidovski/Projects/amp.dev/pixi/backend/api.js:58:15)
    at async /Users/sisidovski/Projects/amp.dev/pixi/backend/api.js:100:25
```

Another problem that I think more important is, there is no way to let users know what the cause is. If above lint API is fixed, then the API response for the given URL would be like this.

```
{
  "status": "error",
  "errorId": "UNSUPPORTED_CONTENT_TYPE",
  "message": "https://news.yahoo.co.jp/amp/pickup/6374389 is no HTML document."
}
```

This is good if users can see those error messages as it is at the pixi frontend, they can understand the problem and fix their pages. However, the error messages from the lint API are thrown away and treated as very general "invalid-url" status id finally.

https://github.com/ampproject/amp.dev/blob/90b488a8271ce07edec6abda234131814889300c/pixi/src/checks/AmpLinterCheck.js#L50-L56

https://github.com/ampproject/amp.dev/blob/90b488a8271ce07edec6abda234131814889300c/pixi/src/utils/checkAggregation/statusBanner.js#L23-L25

https://github.com/ampproject/amp.dev/blob/90b488a8271ce07edec6abda234131814889300c/pages/content/pixi/status-banners/invalid-url.md#L1-L6

### Expected behavior/code

1. The lint API should consider if the `Content-Type` header exists in a response
1. Show more detailed error message to users. In this case, "This URL is unsupported content type" or something.

### Reproduction procedure

1. Go to https://amp.dev/page-experience/
2. Type https://news.yahoo.co.jp/amp/pickup/6374389 to the form
3. Submit

- What browser are you using?
Chrome
- What O/S are you using?
Mac OS

**Comment by sisidovski** [comment]
I fixed the API issue at the moment, but still curious to hear how the frontend could show better error messages to notify pixi users. Any thoughts?

**Comment by nainar** [comment]
@matthiasrohmer could you or @tharders look into this please?

**Comment by matthiasrohmer** [comment]
I tried to address this with https://github.com/ampproject/amp.dev/pull/4959. This at least surfaces this specific underlying API error to the end user. Not too sure about the others.

https://news.yahoo.co.jp/amp/pickup/6374389 meanwhile shows a 404 with the correct `content-type` header set. I synthetically tested with 

```js
api.get('/no-content-type', (request, response, next) => {
  response.removeHeader('content-type');
  response.end('<html amp></html>');
});
```

If there's another real-world sample of this issue you could provide that'd be great! I tried finding one on news.yahoo.co.jp but wasn't too lucky 😁 

Thanks for the detailed report by the way!

**Comment by sisidovski** [comment]
@matthiasrohmer 
news.yahoo.co.jp fixed their bug and now their AMP pages have correct `Content-Type`, so we don't have another real-world example unfortunately. But I think your test is enough to cover the case. Thank you for addressing the issue!
