### ISSUE TITLE
amp-script error on guide 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#4906]
### Current behavior
The [Interactivity in AMP introduction page](https://amp.dev/documentation/guides-and-tutorials/develop/interactivity_guide/?format=websites&_gl=1*eh0rul*_ga*MzU1NzgzMDgzLjE1NTM2MjE0NzI) is reporting a `The extension 'amp-script' was found on this page, but is unused. Please remove this extension.` issue. Not sure if this is from the [amp-script example](https://amp.dev/documentation/guides-and-tutorials/develop/interactivity_guide/?format=websites&_gl=1*eh0rul*_ga*MzU1NzgzMDgzLjE1NTM2MjE0NzI#building-personalized-interactive-experiences)? 

cc @taytus

**Comment by morsssss** [comment]
`amp-script` is indeed used in the example you mention - but that example is in an iframe. So the script doesn't need to be included in the main page.

I wonder if the script autoincluder knows to ignore components that are inside an iframe...
