### ISSUE TITLE
External user consent example is broken

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4909]
## 🐛 Bug Report
The [External User Consent Flow example](https://amp.dev/documentation/examples/user-consent/external_user_consent_flow/?format=websites) doesn't work. Loading it up [in the playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fuser-consent%2Fexternal_user_consent_flow&format=websites), the webpage preview simply reads:

`Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.`

Turns out the reason is this:

`<amp-iframe layout="fill" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox" src="https://amp-by-example-api.appspot.com/iframe/external-consent-iframe.html">`

Yes, the `<amp-iframe>` is looking for a page hosted at `amp-by-example-api.appspot.com`.

I see this in the code:

`src="<% hosts.api %>/iframe/external-consent-iframe.html">`

I could go and fix `hosts.api`, but I don't see `external-consent-iframe.html` anywhere in the repo. Did this get migrated from the old ampbyexample?

Grepping around the repo, I do see examples where `https://amp-by-example-api.appspot.com` is hardcoded into the HTML. These instances concern me too!

**Comment by morsssss** [comment]
Also, it looks like [`promptIfUnknown` may be deprecated](https://amp.dev/documentation/components/amp-consent/).

**Comment by zhouyx** [comment]
Oh yes! `promptIfUnknown` is migrated to `consentRequired `. We need to also update legacy examples. 
@micajuine-ho

**Comment by micajuine-ho** [comment]
@zhouyx Great point! I can take care of this.

**Comment by morsssss** [comment]
@micajuine-ho , I don't see it anywhere else.

**Comment by morsssss** [comment]
@matthiasrohmer , thanks for kindly offering to look for the missing HTML file referenced above.

If it helps, I can also make another issue to fix other references to `amp-by-example-api.appspot.com`.
