### ISSUE TITLE
Pixi: Recommendations not always shown for image size, srcset, next gen formats

### ISSUE THREAD

**Issue by kevinkimball** [ampproject/amp.dev#4955]
### Current behavior
Recommendations is not always shown for image size, use srcset, and next gen formats even when the page could have savings with smaller images, doesn't use srcset, or doesn't use next gen formats. 

I believe this is because PSI reports the page as "passing" even though the page is not adopting the recommendations.

### Expected behavior/code
If the page could have smaller image sizes, expect to see a recommendation.
If the page is not using srcset, expect to see a recommendation to use srcset. 
If the page is not using webp, expect a recommendation for webp. 

### Reproduction procedure
Visit the tool and put in a page url. For example [here](https://www.eleconomista.com.mx/amp/mercados/Peso-mexicano-se-aprecia-tras-triunfo-de-Biden-dolar-cierra-en-20.34-unidades-20201109-0078.html)

Observe there are no recommendations re: srcset, webp, smaller image size. 

Visit the [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights) tool for the same URL and observe reservations (that are still marked green/passing). 

- What browser are you using? Chrome 87
- What O/S are you using? OSX

cc @nainar  @caroqliu

**Comment by kevinkimball** [comment]
Is this resolved by https://github.com/ampproject/amp.dev/issues/4666?

**Comment by matthiasrohmer** [comment]
Nope, #4666 was really just introducing the image recommendations including their details in the first place. It's exactly as you assumed 😉
