### ISSUE TITLE
📖 Minor: nested lists not showing as nested in live docs

### ISSUE THREAD

**Issue by TetraLogicalHelpdesk** [ampproject/amp.dev#4973]
This may be because the live documentation is older than the one in the repository, but: comparing the repository version of https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/0.1/amp-sidebar.md against the live version https://amp.dev/documentation/components/amp-sidebar/#usage it appears that the nested list is not actually rendering as nested?

> ![screenshot of what should be a nested list, showing as a flat list](https://user-images.githubusercontent.com/54933393/99407906-86429900-28e7-11eb-9d81-be82dc12054d.png)

**Comment by patrickkettner** [comment]
@matthiasrohmer given [your comment](https://github.com/ampproject/amp.dev/issues/4264#issuecomment-668746298), would we add something like [truly_sane_lists](https://github.com/radude/mdx_truly_sane_lists), or are we just not going to consider patching and instead focus on linting?
