### ISSUE TITLE
Some text in courses landing page is stuck in English

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4982]
### Current behavior
On the [courses landing page](https://amp.dev/es/documentation/courses/), most of the text has been translated into other languages. But other text is stuck in English, yielding the following strange result:

![image](https://user-images.githubusercontent.com/29419498/99737329-18889f80-2a96-11eb-8537-6b5bcfffe1a1.png)

This happens because we pull the content of these three teaser areas from the `description` field of `.md` files:

```
      {% for teaser_doc in [
        g.doc('/content/amp-dev/documentation/courses/beginning-course/index.md', locale=doc.locale),
        g.doc('/content/amp-dev/documentation/courses/intermediate-course/index.md', locale=doc.locale),
        g.doc('/content/amp-dev/documentation/courses/advanced-course/index.md', locale=doc.locale),
        ] %}
      {% include '/views/partials/teaser.j2' %}
      {% endfor %}
```

I imagine the right solution is to instead store this text in `index.html` with the usual curly brackets and underscores, so they can be translated.

@matthiasrohmer , wdyt?

/cc @gelopfalcon and @isayas who are kindly helping us translate the courses into Spanish!

**Comment by gelopfalcon** [comment]
Yeah, I can do it!

**Comment by morsssss** [comment]
If you like, sure!

Let me know if you want guidance on how this should be done. (Part of the
key is to put the translated text
in pages/translations/es/LC_MESSAGES/messages.po)

**Comment by matthiasrohmer** [comment]
I think everything is actually as it should be: texts coming from the translated source appear translated on the rendered page. My guess is the pages the cards are linking to are not yet translated and by this are in their original language.

See the Portuguese landing page for example: https://amp-dev-staging.appspot.com/pt_br/documentation/courses/. Here the teaser cards are translated as the description text has also been translated in their frontmatter:

https://github.com/ampproject/amp.dev/blame/future/pages/content/amp-dev/documentation/courses/beginning-course/index%40es.md#L1-L10

So as soon as there are fully translated `beginning-course/index@es.md`, `intermediate-course/index@es.md`, `advanced-course/index@es.md` docs the Spanish courses landing page should also appear fully translated.

Does that make sense? Feel free to ping me if not. I know the amount of different translation methods inside amp.dev is confusing, but sadly there is not much we can do about it. But in my personal opinion the .po files should actually only hold reused UI copy. Everything else should reside in a specific document.

**Comment by morsssss** [comment]
@matthiasrohmer , thanks for stepping in here to explain how this works. That does make sense - the build is smart enough to pull the `description` from the translated version of each file.

In fact, we do already have the translated `beginning-course/index@es.md` file. (It's what you linked to in your comment.) I still don't see this translated on amp.dev. But I do see it on staging [here](https://amp-dev-staging.appspot.com/es/documentation/courses/). So I imagine we'll see it in production soon as well!

Closing this.
