### ISSUE TITLE
How to load custom premium font in AMP?

### ISSUE THREAD

**Issue by tpkahlon** [ampproject/amp.dev#4995]
# Bug

On this [page](https://www.drugdiscoverynews.com/it-s-electric-can-trigeminal-nerve-stimulation-help-with-adhd-14755/amp), custom premium font is broken. The font is hosted on the server but is not readable publicly.

# Cause

According to [documentation](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts/), Fonts included via @font-face must be fetched via the HTTP or HTTPS scheme. Hence, font appears broken because HTTP call cannot be performed due to restricted read access.

# Solution

- Please suggest a workaround for this.

**Comment by patrickkettner** [comment]
hi @tpkahlon 
As mentioned in the docs, you need to reference the docs with their fully qualified domain name (.e.g `https://www.drugdiscoverynews.com/fonts/BentonSans/BentonSans-Bold.woff`), rather than a relative URL that is currently being used.
