### ISSUE TITLE
Content proposal - Update Screenshot for makestories.io

### ISSUE THREAD

**Issue by ghelapratik** [ampproject/amp.dev#5032]
We have recently updated the software for MakeStories and so we will like to update the screenshot on the listing page at https://amp.dev/documentation/tools/?format=stories. Please find the attached file for the same. 

Thanks!

@shishirm

![MakeStories-amp-dev](https://user-images.githubusercontent.com/22929187/101283526-f1a1cb80-3800-11eb-9b3a-d7997fd4ba9d.png)

**Comment by matthiasrohmer** [comment]
Thanks for your inquiry, @ghelapratik! Would you be comfortable doing this change on your own? The file that needs to be replaced is located here: https://github.com/ampproject/amp.dev/blob/future/pages/static/img/tools/makestories.jpg

**Comment by ghelapratik** [comment]
Hey @matthiasrohmer, Chintan has made a pull request for the same at https://github.com/ampproject/amp.dev/pull/5068

Thanks!

- Pratik G.
