### ISSUE TITLE
localization PR's should trigger a CI build for that locale

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amp.dev#5038]
when .po files are modified, that locale should be triggered for build. some bugs have crept since PRs only seem to be testing english

**Comment by matthiasrohmer** [comment]
I don't want to unnecessarily bloat the scope of this, but actually, there is a feature we have been aiming for for a while: build the subset of pages that have been altered in the specific PR and somehow serve them for review/preview.

This would not only be beneficial for localization but also for new features that need approval from colleagues who are not comfortable setting up amp.dev on their own machine. If we face situations like this currently we usually make screenshots and use those for approval.

Let me know if I can help with any of this.
