### ISSUE TITLE
PX guide JS error: Cannot read property 'origin_fallback' of undefined

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#5040]
### Current behavior

I'm getting a PX guide JS error: 

> Could not perform page experience check TypeError: Cannot read property 'origin_fallback' of undefined:

Please also provide:
- Page link: https://amp.dev/page-experience/

![image](https://user-images.githubusercontent.com/134745/101411311-9bcb3300-3895-11eb-9d15-105f0f894ad3.png)

### Expected behavior/code

No JS error.

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. Provide the URL to an AMP page. (You may need to provide a URL that has not been checked recently.)
2. Check it.

- What browser are you using? Chrome
- What O/S are you using? Mac

**Comment by matthiasrohmer** [comment]
@bezoerb, as discussed offline: tentatively assigning this to you to get a first glimpse of Pixi. LMK if you need further support with this though I am fairly confident you'll figure this out ☺️
