### ISSUE TITLE
<amp-brightcove> and docking into a slot, I can't make it work

### ISSUE THREAD

**Issue by DrLightman** [ampproject/amp.dev#5075]
Hello,

please see the attached example, I'm sorry you have to upload somewhere and load it into a browser.

[test-amp-brightcove-dock.zip](https://github.com/ampproject/amp.dev/files/5682374/test-amp-brightcove-dock.zip)

Enter dev tools mobile testing on your browser (not required) then click play on the video and scroll down to activate the docking.

The issue is that I want the <amp-brightcove> video to dock into the #bcslot element, but no matter what it always docks in the top right corner at some arount top 20px and right 20px;

ref docs:
https://amp.dev/documentation/components/amp-video-docking/
https://amp.dev/documentation/examples/multimedia-animations/advanced_video_docking/

I'm incoluding the amp html source below.

Thank you.

```html
<!doctype html>
<html amp lang="it-IT">
<head>
<meta charset="utf-8">
<link rel="dns-prefetch" href="//cdn.ampproject.org">
<link rel="canonical" href="http://example.org">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=2,user-scalable=yes">
<title>Test AMP dock slot</title>
<link rel="preload" as="script" href="https://cdn.ampproject.org/v0.js">
<script custom-element="amp-brightcove" src="https://cdn.ampproject.org/v0/amp-brightcove-latest.js" async></script>
<script custom-element="amp-video-docking" src="https://cdn.ampproject.org/v0/amp-video-docking-latest.js" async></script>
<script src="https://cdn.ampproject.org/v0.js" async></script>
<style amp-boilerplate>body {-webkit-animation:-amp-start 8s steps(1, end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1, end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1, end) 0s 1 normal both;animation:-amp-start 8s steps(1, end) 0s 1 normal both}
@-webkit-keyframes -amp-start {
	from {visibility:hidden}
	to {visibility:visible}
}
@-moz-keyframes -amp-start {
	from {visibility:hidden}
	to {visibility:visible}
}
@-ms-keyframes -amp-start {
	from {visibility:hidden}
	to {visibility:visible}
}
@-o-keyframes -amp-start {
	from {visibility:hidden}
	to {visibility:visible}
}
@keyframes -amp-start {
	from {visibility:hidden}
	to {visibility:visible}
}</style>
<noscript>
	<style amp-boilerplate>body {-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style>
</noscript>
<style amp-custom>
	#bcslot { position:fixed; top:25px; left:25px; }
	.content { width:500px; max-width:100%; margin:0 auto; }
	.content .box { width:100%; height:200px; background-color:#2e86c1; margin-bottom:20px; }
</style>
</head>
<body data-amp-auto-lightbox-disable>
<amp-layout
	id="bcslot"
	layout="responsive"
	width="16"
	height="9"
	on="dock: slideDown.start; undock: slideUp.start"
></amp-layout>
<div class="content">
	<div class="box"></div>
	<div class="box"></div>
	<amp-brightcove
		data-account="1752604059001"
		data-video-id="5715315990001"
		data-player="H1xW7NWcz"
		layout="responsive"
		width="16"
		height="9"
		dock="#bcslot"
	></amp-brightcove>
	<div class="box"></div>
	<div class="box"></div>
	<div class="box"></div>
	<div class="box"></div>
	<div class="box"></div>
</div>
</body>
</html>
```

**Comment by patrickkettner** [comment]
Hi @DrLightman!

The issue you are hitting is because your slot has no dimension. It works if you set a `height` and/or `width` style. [Here](https://happy-flax-dolphin.glitch.me/) is an example. 

Separately, a couple things.
    - I _highly_ recommend using glitch for any code samples - its a great place to both host stuff, and share issues.
    - This repo is meant for issues/development of the website amp.dev. For these sorts of problems in the future, it would be best to either submit a question to [stackoverflow](https://stackoverflow.com/), or the [amp slack channel](https://bit.ly/amp-slack-signup)


best  of luck!
