### ISSUE TITLE
Render Bento label in component reference docs

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#5094]
Once `bento` has been add to the supported formats in bento component readme files (see https://github.com/ampproject/amphtml/issues/31609), we should add a bento label to the respective component doc pages. 

* For the design we should re-use the `experimental` label design (color `#f15a5a`).  
* The label should link to the Bento intro guide (to be written).

Mockup: 

<img width="361" alt="Screen Shot 2020-12-15 at 19 27 27" src="https://user-images.githubusercontent.com/380472/102256950-5b5e5b80-3f0c-11eb-833a-702c305d0489.png">

**Comment by sebastianbenz** [comment]
//cc @nainar @caroqliu @dvoytenko

**Comment by CrystalOnScript** [comment]
Will we change the color of the label when Bento moves out of experimental?

**Comment by matthiasrohmer** [comment]
Good question. I thought it's pink to resemble salmon and by that a bento box 😅  but I guess for you the redish tone indicated a warning/error state? Is this where you are coming from?
