### ISSUE TITLE
Request to add Webstoryz to amp.dev tools

### ISSUE THREAD

**Issue by Vint7r** [ampproject/amp.dev#5103]
### Story creation resource name

Webstoryz

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [x] CMS
- [ ] Platform
- [ ] Other

### URL

https://webstoryz.com/

### Image

https://drive.google.com/file/d/1K_fZ4Dn9Bf1FOA6gZLYF8OyVjX3Qgyg9/view?usp=sharing

### Description

Increase engagement on your website using Webstoryz widget

### List of Stories

1. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=237209e9-a66f-493f-a960-59b8db8fd40f
2. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=a826053f-1211-4886-93ff-26e8ba98defc
3. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=0efe8617-b6bd-47df-82a2-a1d0ccb47a99
4. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=4ddd43f3-83ce-449d-a3a1-62f3c4865be8
5. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=911257c4-4216-42f3-bd6f-7ddab70100f2
6. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=45384224-6be9-45dc-b312-80613b7d8580
7. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=3ba985ed-6393-4f53-ac88-0df9f92c56b8
8. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=e7e7a927-a33a-4bcb-b237-0e310fc1cb5c
9. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=7d3933fc-5882-444f-87f2-11dae0fe32c4
10. https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=73cca137-fa4d-406b-99eb-a98f69d6a284

**Comment by sdenaro** [comment]
@Vint7r  I should be able to review this on Monday.

**Comment by shishirm** [comment]
@Vint7r, also wanted to let you know of the new [Web Story Developer Preview Group](https://groups.google.com/a/amp.dev/g/web-stories-devpreview). We'll be using this forum to disseminate early previews of testable / working code for new and upcoming features in Web Stories, surveys, etc. It should be open to sign up. Please let me know if you run into any issues.

**Comment by Vint7r** [comment]
> @Vint7r I should be able to review this on Monday.

Hello everyone! We have a global widget update coming soon. At the moment there is no need to conduct a review, we will definitely write to you!

**Comment by sdenaro** [comment]
@Vint7r 

Please give me a heads up when I can restart the review.

Thanks

**Comment by sdenaro** [comment]
@Vint7r just checking in. Any new word?

**Comment by Vint7r** [comment]
@sdenaro Hello! Sorry for the delay. You can start checking Web Stories, thanks

**Comment by Vint7r** [comment]
@sdenaro Hello, are there any updates?

**Comment by sdenaro** [comment]
@Vint7r I will have time this week, expect an update by mid-week. thanks.

**Comment by sdenaro** [comment]
@Vint7r 

I am seeing the same failures for all stories:

As an example:

https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=237209e9-a66f-493f-a960-59b8db8fd40f

FAIL Story is self-canonical
> actual: https://apiapp.webstoryz.com/1.0/widget-story/webstoryz.com, expected: https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=237209e9-a66f-493f-a960-59b8db8fd40f

FAIL AMP Story preview metadata is correct size and aspect ratio
> [publisher-logo-src] (https://apiapp.webstoryz.com/1.0/widget-story/@) 404 file not found

FAIL AMP Story preview metadata is correct size and aspect ratio
> [poster-portrait-src] (https://apiapp.webstoryz.com/1.0/widget-story/@) 404 file not found

FAIL AMP Story preview metadata is correct size and aspect ratio
> [poster-square-src] (https://apiapp.webstoryz.com/1.0/widget-story/@) 404 file not found

FAIL AMP Story preview metadata is correct size and aspect ratio
> [poster-landscape-src] (https://apiapp.webstoryz.com/1.0/widget-story/@) 404 file not found


You can duplicate these errors via the amp-linter, assuming you have a current version of node installed

npx @ampproject/toolbox-cli lint "https://apiapp.webstoryz.com/1.0/widget-story/get-content?apiKey=n8eJRj06PSt6lGc5Pvc2pboP7qR7Lsavgh4DRNCeNFOkfLzjIlCcw1WNeYFYE30ztlcGkd51zjXujAYyHVHvcN6E8t7UkBHuEQwjH60UziJa2ZyVejgMlJTmWB9mdPcz&storyId=237209e9-a66f-493f-a960-59b8db8fd40f"

Can you confirm you are see this was well?

**Comment by Vint7r** [comment]
@sdenaro 
Thanks! Getting started on the fix

**Comment by sdenaro** [comment]
@Vint7r  Just checking in. Is this still in progress?

**Comment by Vint7r** [comment]
@sdenaro At the moment we are working on a new version of the builder, along with the release all bugs will be fixed

**Comment by sdenaro** [comment]
@Vint7r just checking in. 

Is there anything you need from my end?

thanks.

**Comment by Vint7r** [comment]
@sdenaro Hi! We have globally updated the constructor, now our stories must meet all the requirements. Sorry for the delay, we have done a lot of work.

Updated storie- https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=c6be3604-d4e1-46ad-be34-4f2f45f23cc8

**Comment by sdenaro** [comment]
@Vint7r 

Thanks, I will check on availability and have the stories reviewed again.

**Comment by Vint7r** [comment]
@sdenaro 
Hi, when approximately can you check the story?

**Comment by sdenaro** [comment]
I have time this week, thanks

**Comment by sdenaro** [comment]
There is an issue with the publisher logo, but the canonical link is correct.

storymetadatathumbnailsareok (FAIL)

  [publisher-logo-src = {"url":"https://cdn.webstoryz.com/webstoryz/logo-small.svg","width":31,"height":33,"mime":"image/svg+xml"}] failed [isRaster, isSquare, isAtLeast96x96]

Unfortunately, none of the older stories got this fix after I changed the URL from /1.0/ to /2.0/ 

Can you have those stories updated and resolve the logo issue?

Thanks.

**Comment by Vint7r** [comment]
@sdenaro Ok, we will fix the logo and update previous stories
Thanks!

**Comment by Vint7r** [comment]
@sdenaro Hi! Here are updated stories:

1. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=a4e0a7dc-8dd7-46c9-a6e1-bbbbcb8cbb3d
2. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=b1af861d-b455-443e-9152-c69017f2b558
3. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=eab15028-b3cb-4469-aa71-a89b58dfb54c
4. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=9d352085-c175-4dcf-af87-593cc1e00ad5
5. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=0789ba7d-8d88-4c5e-b7e0-59b55e1c917e
6. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=5354b410-2d70-492f-8fe7-7eb2b1e6b06a
7. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=274f6f0b-6a9f-4bd2-bec5-55bd297578a1
8. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=ef2c8c4d-61f0-4a32-b308-0df307e7bd14
9. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=739c0292-b287-4364-aadb-319967fb8959
10. https://apiwidget.webstoryz.com/2.0/widget-story/get-content?storyId=e822df11-14c0-4b6c-8a85-aa82a57fd801

**Comment by sdenaro** [comment]
@Vint7r ,

If you can fix this issue in the CDN I can get this approved.  The image should be at least 96*96 and square.  

Thanks

  [publisher-logo-src = {"url":"https://cdn.webstoryz.com/webstoryz/logo-small.png","width":31,"height":33,"mime":"image/png"}] failed [isSquare, isAtLeast96x96]

**Comment by Vint7r** [comment]
@sdenaro
Hi! We fixed it, thanks for feedback

**Comment by Vint7r** [comment]
@sdenaro Hello! Can you please check the image update?

**Comment by Vint7r** [comment]
@sdenaro Hi! Can you approve our service please?

**Comment by sdenaro** [comment]
@Vint7r  I will getting a PR together today, it should be merged by early next week, thanks

**Comment by sdenaro** [comment]
@matthiasrohmer is the amp.dev build currently broken? I am unable to test.

**Comment by sdenaro** [comment]
@Vint7r there is a PR to update. thanks

**Comment by Vint7r** [comment]
@sdenaro thanks. Can we update description and image?

**Comment by patrickkettner** [comment]
@Vint7r feel free to PR any change you would like to see

**Comment by sdenaro** [comment]
@Vint7r @patrickkettner 

if you can attach the image you would like to this ticket with the new description I can update it.

Thanks

**Comment by Vint7r** [comment]
@patrickkettner Hi! We want to update information.
Text: "Increase engagement and conversion rates on your website and mobile app using Webstoryz widget!"
Image: https://drive.google.com/file/d/1KH1zge2QjTHZbOCEzcFfN9AIIHTy0iZ-/view?usp=sharing

@sdenaro Thanks for support!

**Comment by Vint7r** [comment]
Hi @patrickhlauke ! Can you please update description to "Increase engagement and conversion rates on your website and mobile app using Webstoryz widget!" ?

**Comment by patrickhlauke** [comment]
assume the above is for my evil twin @patrickkettner :)

**Comment by IzmaylovN28** [comment]
@Vint7r @patrickkettner 

Hi! Can you please update our old link "https://webstoryz.com/" to new link: https://webstoryz.com/?utm_source=google_listing ?

I am writing here for the first time, if something is wrong, I apologize in advance :)

**Comment by sdenaro** [comment]
I think I will have time to do this.
