### ISSUE TITLE
Upgrade to Grow 1

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#5110]
I'll just keep this here for 2021 😅 

Grow released 1.0.0 which also marks the long overdue switch from the deprecated Python 2.7 to 3. We should definitely upgrade to stop forcing contributors to install Python 2.7 which for example `brew` already heavily tries to prevent.

**Comment by jaygray0919** [comment]
Is the Grow upgrade in plan or a "nice to have" when time permits? Now see the P1: High flag.

**Comment by jaygray0919** [comment]
@mathiasbynens we want to be a "fast follower" as you migrate to Grow support for Py3. Can you forecast when the upgrade will be implemented (e.g. 1Q21, 2Q21)? Can we help you test the upgrade?

**Comment by patrickkettner** [comment]
@matthiasrohmer, rather than @mathiasbynens (hi @mathiasbynens!!!). I would imagine this should land in later Q1 to mid Q2

**Comment by jaygray0919** [comment]
@patrickkettner @matthiasrohmer Thanks for update. We're willing to help if needed/useful.

**Comment by matthiasrohmer** [comment]
@lluerich will start with this one and see what it takes to update. 🙂

**Comment by jaygray0919** [comment]
@matthiasrohmer @lluerich we're available to help if/where we can. Our gulp-like substitution/build process depends on an updated Grow capability.
