### ISSUE TITLE
Broken Link (line 114 in https://github.com/ampproject/docs/blob/future/examples/source/personalization/Geolocation_with_amp-list.html)

### ISSUE THREAD

**Issue by nicolasfaurereboot** [ampproject/amp.dev#5190]
### Current behavior
the 'location results' url (src="https://caramel-wolf.glitch.me//location-specific-results.json") is broken.
line 114 in https://github.com/ampproject/docs/blob/future/examples/source/personalization/Geolocation_with_amp-list.html

Please also provide:
- Page link: <amp.dev/examples/source/personalization/Geolocation_with_amp-list.html>

**Comment by patrickkettner** [comment]
thanks @nicolasfaurereboot!

@CrystalOnScript any idea who owned this demo?

**Comment by CrystalOnScript** [comment]
Ooh, yikes. I see the example was contributed by @jamesshannon - do you own this Glitch project James?

**Comment by patrickkettner** [comment]
this has been fixed
