### ISSUE TITLE
Page experience (#2)

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amp.dev#5210]
Page experience

https://amp.dev/about/page-experience/

is different in at least two ways from other pages

1. uses different CSS for search
2. ordering of search and language (EN) is reversed

CSS for page-experience seems to be a different release than other pages

**Comment by jaygray0919** [comment]
Whoa! Only one menu structure, not two! Very nice. No wonder there are differences.

**Comment by matthiasrohmer** [comment]
That's intended. The Page Experience Guide uses the first components of a more streamlined frontend implementation for amp.dev to improve on Core Web Vitals.

**Comment by jaygray0919** [comment]
Do you plan to update all other pages using the streamlined frontend implementation?
