### ISSUE TITLE
Missing Templates for AMP for Email Components in AMP Playground

### ISSUE THREAD

**Issue by paulnahal** [ampproject/amp.dev#5227]
## What's the issue?

It looks like the templates for AMP for Email components have disappeared from the AMP Playground.

## How do we reproduce the issue?

https://playground.amp.dev/?runtime=amp4email

1. Open the AMP Playground
2. Choose AMP for Email
3. Click untitled in the top/middle of the page to open the Select Template modal. 

Only `amp-autocomplete-email`, and `amp-bind-macro` components are shown.

Previously you would see `amp-form`, `amp-list`, etc.

## What browsers are affected?

Chrome, Firefox, possibly all.

## Which AMP version is affected?

This is a new issue, as templates would always show beforehand. 

## Screenshot
![amp components](https://i.imgur.com/HTITOuC.png)

**Comment by sebastianbenz** [comment]
This is most likely a side effect of #5053. The more stricter validation makes many of the samples (which are auto transformed from the website samples) invalid. For example, we often use CSS variables in samples which are now invalid. We might have to extend the format transformer to also rewrite these.

//cc @patrickkettner

**Comment by patrickkettner** [comment]
@sebastianbenz what is the request? To get the templates working, or update the format transformer? Happy to do either, not sure where to begin on the later

**Comment by sebastianbenz** [comment]
The ideal solution would be updating the format transformer to auto expand all CSS variables. This would need to happen [here](https://github.com/ampproject/amp.dev/blob/future/platform/lib/format-transform/formats/amp4email.js).
