### ISSUE TITLE
The "advanced server request" example in playground is broken

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amp.dev#5232]
### Current behavior
The "advanced server request" example in playground for the email format is broken. The amp-list XHR to https://amp.dev/documentation/examples/api/echo?__amp_source_origin=https%3A%2F%2Fplayground.amp.dev fails with HTTP 400:

```
Requests must set content-type=application/json
```

Please also provide:
- Page link: https://playground.amp.dev/?runtime=amp4email&url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Finteractivity-dynamic-content%2Fadvanced_server_request

/to @sebastianbenz

**Comment by lluerich** [comment]
Also mentioned [here](https://github.com/ampproject/amp.dev/pull/3694#issuecomment-601890517).

**Comment by lluerich** [comment]
Please add the corresponding CORS headers as discussed. Thanks :)

**Comment by sebastianbenz** [comment]
cc @patrickkettner

**Comment by patrickkettner** [comment]
@lluerich [here](https://amp.dev/documentation/guides-and-tutorials/learn/cors-in-email/) are the docs I mentioned, with the relevant section [here](https://amp.dev/documentation/guides-and-tutorials/learn/cors-in-email/?format=email#implementing-cors). In short, we can check for a `__amp_source_origin` querystring.  I created a PR [here](https://github.com/ampproject/amp.dev/pull/5244) if you want to review it

**Comment by lluerich** [comment]
The main problem here is that ```amp-list``` is fetching the initial data via GET. Could we use a workaround via ```amp-script``` to use POST instead? Something like [this](https://amp.dev/documentation/components/amp-list/#using-amp-script-as-a-data-source), @sebastianbenz?
Or we just get rid of the initial data in the ```amp-list``` and just set it to something static.

**Comment by sebastianbenz** [comment]
@lluerich This is for email, which don't support amp-script. Afaik, the main problem is that we check for the JSON content header, but it's not set by the email initiated request. Disabling the check for emails (based on the headers would be the right way to go). We can also simply remove it.

The amp-list is a different problem. It's not used at all in this sample. The echo endpoint does not return anything that can be rendered in the amp-list. I think the best thing is to remove the amp-list (please the mention in the sample comment) as it doesn't add anything.

**Comment by lluerich** [comment]
@sebastianbenz For now, we could simply switch to a POST request on the ```/echo```-endpoint, as it does not have the check for the JSON content header.
We can also remove the ```amp-list``` but the whole example is kind of based on the premise that the ```amp-list``` and ```amp-form``` can be used together for an enhanced user experience. We could just switch the source to a static file as seen [here](https://amp.dev/documentation/components/amp-list/?format=email#displaying-a-dynamic-list).

**Comment by sebastianbenz** [comment]
Sounds good. Switching to a static file would be perfect!

>
