### ISSUE TITLE
ZMOOZ is a Web Stories Platform with a Mobile App, a Visual Desktop Editor and a Tool to Turn Articles into Web Stories Automatically 

### ISSUE THREAD

**Issue by Zmooz** [ampproject/amp.dev#5235]
< ZMOOZ STORIES>

### Type

- [ x] Story Creation Tool
- [x ] CMS
- [ x] Platform
- [ x] Other

### URL

< www.zmooz.com>

### Image

https://user-images.githubusercontent.com/57263373/104914003-c1685380-598e-11eb-9a74-9e90a49586e8.png

>

### Description

< Turn automatically articles into templated web stories. WYSIVYG Studio and Apps to edit and share. >

### List of Stories

< https://amp.zmooz.com/stories/The-seven-most-remarkable-fashion-shows-of-the-decade-4A3x
https://amp.zmooz.com/stories/Les-differents-styles-de-yoga-:-le-Vinyasa-owBW

https://amp.zmooz.com/stories/Supreme-x-Nike-:-un-duo-fait-pour-perdurer!-w3Ew

https://amp.zmooz.com/stories/Top-10-des-chiens-les-plus-droles-du-web-6A3k

https://amp.zmooz.com/stories/La-rentree-en-5-expositions-mode-LaWq

https://amp.zmooz.com/stories/Visitez-lArc-de-Triomphe-avec-moi-PXgg

https://amp.zmooz.com/stories/Friends-les-looks-de-Rachel-Green-quon-reve-de-porter-yEMR

https://amp.zmooz.com/stories/Les-plus-beaux-jardins-parisiens-pour-se-ressourcer-d6EL

https://amp.zmooz.com/stories/5-boissons-chaudes-pour-se-rechauffer!-BA3x

https://amp.zmooz.com/stories/Lionel-Messi-xdE5

>

**Comment by patrickkettner** [comment]
cc @shishirm

**Comment by Zmooz** [comment]
@shishirm Hello :)

**Comment by sdenaro** [comment]
I will be starting this soon and will update before the end of the week.

**Comment by sdenaro** [comment]
@Zmooz 

None of the linked stories are valid Web Stories AMP. You can confirm this by adding "#development=1" to the end of the URL as in [this link](https://amp.zmooz.com/stories/La-rentree-en-5-expositions-mode-LaWq#development=1) and seeing the errors in the Debug tab. 

For more information, please take a look at the amp linter which is part of the [AMP Toolbox project](https://github.com/ampproject/amp-toolbox)

You can run it via `npx amp-toolbox-linter`

Thanks.

**Comment by Zmooz** [comment]
Hello @sdenaro We have fixed the issue...  Let us know if you see anything else
Thanks

**Comment by sdenaro** [comment]
I am blocking off time on Wed the 17th to update my review. Thanks

**Comment by Zmooz** [comment]
thanks @sdenaro

**Comment by Zmooz** [comment]
Hi @sdenaro  any news ? Thanks

**Comment by sdenaro** [comment]
Just re-checked everything and there are stiff some issues.


If you check 

https://amp.zmooz.com/stories/The-seven-most-remarkable-fashion-shows-of-the-decade-4A3x#development=1

You'll see there is still an AMP issue

There are also issues that come up in the amp linter.  Please take a look at the amp linter which is part of the AMP Toolbox project

You can run it via npx amp-toolbox-linter

You'll see that multiple stories have issues with images, either the ratios are are correct (some are 0.56 rather than 0.65) and a number of the stories have video that exceeds 4mb. 

https://amp.zmooz.com/stories/Supreme-x-Nike-:-un-duo-fait-pour-perdurer!-w3Ew

Has this video,  https://storage.googleapis.com/zmooz-estoryc-images/asset/media-e021369d-b4e3-4478-be0d-3b3302e56e6a/001.mp4,https://storage.googleapis.com/zmooz-estoryc-images/asset/media-054edb78-9ae1-4fa2-86bb-ca3c002d9246/001.mp4 which is too large for the web stories platform.

Please let me know if you are able to install the linter to verify the structure. 

Thanks

**Comment by Zmooz** [comment]
Thank you for the reply, 
We will check for the last issue on the story https://amp.zmooz.com/stories/The-seven-most-remarkable-fashion-shows-of-the-decade-4A3x

We've also been able to install and use the linter, we'll go through the logs and update the stories accordingly.
However, is it normal that some requirements are different on the AMP website (minimum size for poster-square-src = 640x640) and the linter ( 928x928 ) ?

Thank you

**Comment by sdenaro** [comment]
More information on poster image sizes and image rations can be found here:

https://amp.dev/documentation/guides-and-tutorials/learn/webstory_technical_details/?format=websites

https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/

A general best practices guide in PDF format is here:

https://services.google.com/fh/files/misc/web_stories_best_practices.pdf

Thanks

**Comment by sdenaro** [comment]
tagging @Dbrown910

**Comment by sdenaro** [comment]
@Zmooz 

Thanks, I will check on availability and give you an ETA to revaluate

**Comment by Zmooz** [comment]
thanks @sdenaro 
Looking forward your feed backs

**Comment by Zmooz** [comment]
Hi @sdenaro @patrickkettner I hop you are doing well :)

We have reviewed everything and have made sure , everything is fixed.
Except the book end warning, but the bookend warning is present on all the stories from the other tools that were validated by Google.
   
We would be thankful to have your feedback.
Thanks

**Comment by sdenaro** [comment]
I will have time this week, thanks

**Comment by sdenaro** [comment]
Looks good, not issue with the stories, I will branch and stage to have this added to amp.dev. Will update with the PR by EOD

**Comment by Zmooz** [comment]
Hi Thanks @sdenaro

**Comment by Zmooz** [comment]
@sdenaro @patrickkettner , I hope you are well !
 Quick question, are we also going to appear here :
https://stories.google/tools/

Best,

**Comment by sdenaro** [comment]
Let me double check the PR.

**Comment by sdenaro** [comment]
Looks like a merge conflict, let me fix this tomorrow and update you.

**Comment by matthiasrohmer** [comment]
Zmooz will be listed on amp.dev by at least tomorrow with https://github.com/ampproject/amp.dev/pull/5906.

**Comment by sdenaro** [comment]
@matthiasrohmer Does't look like zmooz was added. Was there an issue?

**Comment by sdenaro** [comment]
@Zmooz I will check on https://stories.google/tools/ next week

**Comment by matthiasrohmer** [comment]
Thanks for the ping, @sdenaro. We are actually facing deployment issues with amp.dev - as soon as they are resolved, Zmooz will appear on amp.dev. I'll work on this tomorrow (Monday).

**Comment by Zmooz** [comment]
Hello,
Did you manage to fix the deployment issues? We look forward to appearing in the list of tools :)

**Comment by Zmooz** [comment]
@matthiasrohmer @sdenaro  ...
