### ISSUE TITLE
amp.dev sample images are not shown

### ISSUE THREAD

**Issue by ka2jun8** [ampproject/amp.dev#5242]
## What's the issue?

amp.dev sample images are not shown.

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-carousel&format=websites

Console:

```
GET https://amp.dev/static/samples/img/image1.jpg 500
GET https://amp.dev/static/samples/img/image2.jpg 500
GET https://amp.dev/static/samples/img/image3.jpg 500
```

## How do we reproduce the issue?

1. Go to the page (https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-carousel&format=websites)
2. Images are not shown

## What browsers are affected?

All browsers

## Which AMP version is affected?

does not matter

**Comment by patrickkettner** [comment]
thumbor was locked up again, I kicked the process and the URLs are resolving again

**Comment by patrickkettner** [comment]
cc @matthiasrohmer @sebastianbenz

**Comment by sebastianbenz** [comment]
Thanks Patrick! @matthiasrohmer I thought we solved the log overflow issue?
