### ISSUE TITLE
Make AMP validator also validate structured data

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#5252]
https://github.com/ampproject/amp.dev/pull/5251 made me aware of this discussion: https://github.com/ampproject/ampbench/issues/126#issuecomment-573708719

Making the [updated validator](https://playground.amp.dev/validator) also checking structured data could be a feature worth adding. WDYT @sebastianbenz?

**Comment by sebastianbenz** [comment]
Thanks for flagging Matthias! Structured data is not required by AMP, hence it's not in the scope for the AMP validator.
