### ISSUE TITLE
Many pages have broken layout on mobile

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amp.dev#5283]
### Current behavior
Many pages have broken layout on mobile, with the right side of the mobile screen incorrectly taken by blank space of varying widths. This only happens to some pages but not all.

- https://amp.dev/about/email/
- https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders/?format=email
- https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/?format=email
- https://amp.dev/documentation/guides-and-tutorials/learn/amp-email-actions-and-events/?format=email

![Screen Shot 2021-01-31 at 3 53 00 PM](https://user-images.githubusercontent.com/743034/106397661-8cbbb980-63dc-11eb-8297-4b9a00665da9.png)
![Screen Shot 2021-01-31 at 3 53 07 PM](https://user-images.githubusercontent.com/743034/106397662-8d545000-63dc-11eb-80db-40bc798adab4.png)
![Screen Shot 2021-01-31 at 3 53 14 PM](https://user-images.githubusercontent.com/743034/106397663-8d545000-63dc-11eb-8d48-076e2f6ad3be.png)
![Screen Shot 2021-01-31 at 3 53 22 PM](https://user-images.githubusercontent.com/743034/106397665-8dece680-63dc-11eb-8f0e-7bc694c98a7e.png)

**Comment by westonruter** [comment]
Per https://github.com/ampproject/amp.dev/issues/5188#issuecomment-763349850, the following CSS fixes the issue, but it naturally should have better selectors and not use `!important`:

```css
code, a {
    word-break: break-all !important;
}
```
