### ISSUE TITLE
Categories of post not work

### ISSUE THREAD

**Issue by dikeii** [ampproject/amp.dev#5290]
Good morning, the categories of the posts have amp support? since I have tried to visualize them but I do not get it in any way, it just redirects me to the page no amp, thanks. Greetings.

**Comment by patrickkettner** [comment]
Good morning! 

I am not entirely sure what you are referring to, though - would you be able to elaborate?

**Comment by dikeii** [comment]
Good morning, of course, my question was if the categories had amp support, for example the following url:

http: //xxx.xx/category/my-category/

same for tags

http: //xxx.xx/tag/my-tag/

since I can't see them in amp mode, is there a way to support it with code?

thanks

**Comment by patrickkettner** [comment]
Categories of what? I am not sure what posts you are referring to?

**Comment by dikeii** [comment]
Good morning, this is embarrassing, sorry I made the wrong repository, thanks for your attention. Greetings.
