### ISSUE TITLE
Field Data cannot be seen in AMP Page Experience Guide

### ISSUE THREAD

**Issue by genki-koba** [ampproject/amp.dev#5295]
In the page of AMP Page Experience Guide, I have tried some AMP URLs that its original web page have over 300,000 views for the past 2months.
The articles from the site I have tried can be seen in Top Stories everyday(even every hour) in SEARPs(the site is well-known in general and also in top stories as well) and that means the AMP URLs should have enough views with a great margin to be able to investigate the CWV scores from the Field Data.
Nonetheless, how come can I not see the Field Data in this page?(https://amp.dev/page-experience/)

**Comment by patrickkettner** [comment]
@genki-koba what url?

**Comment by patrickkettner** [comment]
closing for lack of response - please do let us know if you have an update!
