### ISSUE TITLE
Add a Story Creation Platform: GliaStory

### ISSUE THREAD

**Issue by lucemia** [ampproject/amp.dev#5317]
### Story creation resource name

GliaStory

### Type

Use [x] to mark a selection:

- [ ] Story Creation Tool
- [ ] CMS
- [x] Platform
- [ ] Other

### URL

https://www.gliastory.com/

### Image

![截圖 2021-02-08 下午5 44 14](https://user-images.githubusercontent.com/432851/107202577-51049d80-6a35-11eb-9acf-f9e5d59b9798.png)

### Description

GliaStory uses AI to generate Web Stories from news, e-commerce and even podcast content in minutes!

### List of Stories

- https://player.gliacloud.com/@www.gliacloud.com/demo/jpmedia-fanfunfukuoka.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/skywatchers.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/jpmedia-kingsoft-starthome.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/twmedia-ifoodie.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/media-marieclaire.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/distinct-education.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/gliacloud.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/ecommerce-vacanza-acc.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/ecommerce-pet-products.html
- https://player.gliacloud.com/@www.gliacloud.com/demo/artgallery.html

* Minimum of 7 pages
* At least 4 images
* At least 2 videos
* At least four pages with some text >

**Comment by lucemia** [comment]
@sebastianbenz @shishirm 

Any updates? Any Information missing?

**Comment by sdenaro** [comment]
I will be starting this soon and will update before the end of the week.

**Comment by lucemia** [comment]
@shishirm Any updates?

**Comment by sdenaro** [comment]
Thanks for checking in. There are a lot of issues that need to be resolved

If you open the URLs with "#development=1" padded to the end you'll see that stories like this 

https://player.gliacloud.com/@amp.distinct-education.com/#development=1

There are AMP issues with the stories that show up in the debug section

https://player.gliacloud.com/@amp.distinct-education.com/#development=1&tab=debug

In addition, there are other issues with the stories,  they fall into the three basic problems


1.  The canonical URL is not correct
2. Some videos are larger than 4mb
3. Some story thumbnails are too small 
4. WHile not an error, it would be nice to have  "rel=preload" to the amp cdn import  `<link href=https://cdn.ampproject.org/v0.js rel=preload> `


### Story breakdown:


1.  https://player.gliacloud.com/@www.gliacloud.com/demo/jpmedia-fanfunfukuoka.html

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/jpmedia-fanfunfukuoka.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/jpmedia-fanfunfukuoka.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static-gchannel.glianetwork.com/published/a012ac405e92b384991998dcf5a67bc7bb04f44f.png","width":165,"height":165,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

1.   https://player.gliacloud.com/@www.gliacloud.com/demo/ecommerce-pet-products.html

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/ecommerce-pet-products.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/ecommerce-pet-products.html

runtimeispreloaded (WARN)

  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static-gchannel.gliacloud.com/published/4a3d7894baba74d8eaeecccf30f00b0081b3d82d.jpg","width":412,"height":495,"mime":"image/jpeg"}] failed [isPortrait, isAtLeast696x928]

3.  https://player.gliacloud.com/@www.gliacloud.com/demo/ecommerce-vacanza-acc.html

ampvideoissmall (FAIL)

  videos over 4MB: [https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2021/02/vacanza.mp4]

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/ecommerce-vacanza-acc.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/ecommerce-vacanza-acc.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static-gchannel.glianetwork.com/published/a012ac405e92b384991998dcf5a67bc7bb04f44f.png","width":165,"height":165,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

4.  https://player.gliacloud.com/@www.gliacloud.com/demo/skywatchers.html

ampvideoissmall (FAIL)

  videos over 4MB: [https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2021/02/699d35851486ac2883ce261d0be0ce6138b3d72d.mp4]

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/skywatchers.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/skywatchers.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static-gstudio.gliacloud.com/amp-story/1594957548-99d421cd4df3d3e1248ed771f4f412ab.jpg","width":540,"height":360,"mime":"image/jpeg"}] failed [isPortrait, isAtLeast696x928]

5.  https://player.gliacloud.com/@www.gliacloud.com/demo/gliacloud.html

ampvideoissmall (FAIL)

  videos over 4MB: [https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2020/10/hero-image.3340a91c0138d64da1e046c68e1d5779-online-video-cutter.com_.mp4,https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2020/11/a4d4c12cbe57e0e07feb6c73abce4580b396a762.mp4,https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2020/10/2.mp4,https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2020/10/c2191fc5451581b98a65b78cb0aff6f5e15a0347.mp4]

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/gliacloud.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/gliacloud.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://gchannel.gliacloud.com/published/597c9ccab90b1ba564dbe9f97cdf92fbf90e7f05.jpg","width":76,"height":75,"mime":"image/jpeg"}] failed [isPortrait, isAtLeast696x928]

6.  https://player.gliacloud.com/@www.gliacloud.com/demo/media-marieclaire.html

ampvideoissmall (FAIL)

  videos over 4MB: [https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2021/02/marie-clare-1.mp4,https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2021/02/marie-claire-2.mp4]

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/media-marieclaire.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/media-marieclaire.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static-gchannel.glianetwork.com/published/a012ac405e92b384991998dcf5a67bc7bb04f44f.png","width":165,"height":165,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

7.  https://player.gliacloud.com/@www.gliacloud.com/demo/twmedia-ifoodie.html

ampvideoissmall (FAIL)

  videos over 4MB: [https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2021/02/ifoodie-clip1.mp4,https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2021/02/ifoodie-clip-2.mp4]

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/twmedia-ifoodie.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/twmedia-ifoodie.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static-gchannel.gliacloud.com/published/aab1035255e185edfc4a341ea9795584e68653a4.jpg","width":1200,"height":800,"mime":"image/jpeg"}] failed [isPortrait, isAtLeast696x928]

8.  https://player.gliacloud.com/@www.gliacloud.com/demo/jpmedia-kingsoft-starthome.html

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/jpmedia-kingsoft-starthome.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/jpmedia-kingsoft-starthome.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://gchannel.gliacloud.com/published/1ce9796945fe08476702a12d8fee00c73a19a978.jpg","width":500,"height":333,"mime":"image/jpeg"}] failed [isPortrait, isAtLeast696x928]

9.  https://player.gliacloud.com/@www.gliacloud.com/demo/jpmedia-fanfunfukuoka.html

linkrelcanonicalisok (FAIL)

  actual: https://www.gliacloud.com/demo/jpmedia-fanfunfukuoka.html, expected: https://player.gliacloud.com/@www.gliacloud.com/demo/jpmedia-fanfunfukuoka.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static-gchannel.glianetwork.com/published/a012ac405e92b384991998dcf5a67bc7bb04f44f.png","width":165,"height":165,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

10.  https://player.gliacloud.com/@amp.distinct-education.com/

linkrelcanonicalisok (FAIL)

  actual: https://amp.distinct-education.com/index.html, expected: https://player.gliacloud.com/@amp.distinct-education.com/

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"https://static-gstudio.gliavideo.com/d311e847dd65d586822278d2d875d90b153ee839.jpg","width":3890,"height":4862,"mime":"image/jpeg"}] failed [isPortrait]

**Comment by lucemia** [comment]
@sdenaro 
Thanks your comments, I have fixed the system and updated all story.

![截圖 2021-03-26 下午12 39 32（2）](https://user-images.githubusercontent.com/432851/112577952-588ad500-8e30-11eb-8b24-e1367f54396b.png)

**Comment by sdenaro** [comment]
Thanks, I take a second look at the end of this week.

**Comment by sdenaro** [comment]
taggin @Dbrown910

**Comment by sdenaro** [comment]
@sebastianbenz  can you assign @dbrown910 ?

**Comment by sdenaro** [comment]
@lucemia We are having @DBrown910 complete this, he has a bit more bandwidth than I have right now.

**Comment by Dbrown910** [comment]
Hey @lucemia. Only one issue popped up this time. Just a video that needs compression:

6. https://player.gliacloud.com/@www.gliacloud.com/demo/media-marieclaire.html
ampimgamppixelpreferred (PASS)

ampimgheightwidthisok (PASS)

ampvideoissmall (FAIL)

  videos over 4MB: [https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2021/02/marie-claire-2.mp4]

ampvideoisspecifiedbyattribute (PASS)

bookendexists (WARN)

  <amp-story-bookend> not found

endpointsareaccessiblefromcache (PASS)

endpointsareaccessiblefromorigin (PASS)

linkrelcanonicalisok (PASS)

metacharsetisfirst (PASS)

runtimeispreloaded (PASS)

schemametadataisnews (PASS)

storyismostlytext (PASS)

storymetadataisv1 (PASS)

storymetadatathumbnailsareok (PASS)

storyruntimeisv1 (PASS)

The others are all good!

**Comment by lucemia** [comment]
> Hey @lucemia. Only one issue popped up this time. Just a video that needs compression. The others are all good!
> 
> 1. https://player.gliacloud.com/@www.gliacloud.com/demo/media-marieclaire.html
> 
> ampimgamppixelpreferred (PASS)
> 
> ampimgheightwidthisok (PASS)
> 
> ampvideoissmall (FAIL)
> 
> ```
> videos over 4MB: [https://wordpress.gliaoffice.com/wordpress/wp-content/uploads/2021/02/marie-claire-2.mp4]
> ```
> 
> ampvideoisspecifiedbyattribute (PASS)
> 
> endpointsareaccessiblefromcache (PASS)
> 
> endpointsareaccessiblefromorigin (PASS)
> 
> linkrelcanonicalisok (PASS)
> 
> metacharsetisfirst (PASS)
> 
> runtimeispreloaded (PASS)
> 
> schemametadataisnews (PASS)
> 
> storyismostlytext (PASS)
> 
> storymetadataisv1 (PASS)
> 
> storymetadatathumbnailsareok (PASS)
> 
> storyruntimeisv1 (PASS)

@Dbrown910 
 I have compressed the video files. Please confirm.

Thanks!

**Comment by Dbrown910** [comment]
Double checked and everything looks good. Opening a pull request.

**Comment by sdenaro** [comment]
This should be closed

**Comment by lucemia** [comment]
Thanks all your help @Dbrown910 @sdenaro
