### ISSUE TITLE
Broken script copy icon

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#5342]
e.g. here: https://amp.dev/documentation/components/amp-accordion-v1.0/?format=websites

<img width="289" alt="Screenshot 2021-02-10 at 16 39 33" src="https://user-images.githubusercontent.com/380472/107582706-32033880-6bfa-11eb-96c1-8a8e29f104d2.png">

**Comment by lluerich** [comment]
https://amp.dev/shared/copy-script/ is a 404. Was there an error during deployment?
