### ISSUE TITLE
Roadmap shows Q11 2020

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#5344]
2020 felt long, but it wasn't that long 

![image](https://user-images.githubusercontent.com/380472/107667333-c7044100-6c8f-11eb-8177-a22be13ae6ae.png)

**Comment by matthiasrohmer** [comment]
Feels valid to me, hence closing.

**Comment by lluerich** [comment]
@gmajoulet Please change the title of the status update (ampproject/wg-stories#45) to match the pattern YYYY-MM-DD, as it is currently YYYY-DD-MM, which causes it to show up in Q11 on amp.dev.

**Comment by gmajoulet** [comment]
@lluerich done, sorry about that
