### ISSUE TITLE
The FAQ page is visually broken

### ISSUE THREAD

**Issue by jono-alderson** [ampproject/amp.dev#5369]
### Current behavior
The page at https://amp.dev/support/faq/ has display issues; it looks like the image should maybe be positioned and scaled as background to the tiles?

![image](https://user-images.githubusercontent.com/11629607/107970121-9c282e80-6fa8-11eb-8fcb-232e0dc76ab7.png)

Running Chrome 88.0.4324.150 on Windows, at varying tested resolutions.

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. Visit https://amp.dev/support/faq/
2. Note that the page appears to display incorrectly

- Chrome 88.0.4324.150
- Windows

**Comment by sebastianbenz** [comment]
Was my fault...
