### ISSUE TITLE
AMP Page Experience Disable Tap Delay Warning

### ISSUE THREAD

**Issue by milindmore22** [ampproject/amp.dev#5396]
### Current behavior
The AMP page experience now shows **Disable Tap Delay** warning even if the page has a viewport meta with property `width=device-width`.

I think it's not parsing value correctly if there are multiple properties  like `initial-scale=1`

No Issues : `<meta name="viewport" content="width=device-width">`
Displays tap delay Warnning : `<meta name="viewport" content="width=device-width,initial-scale=1">`

PS: I temporarily removed `initial-scale` property from my [website](https://wpindia.co.in/2021/01/07/well-my-phones-battery-stuck-at-50-for-some-reason/?amp) to confirm, it shows [no tap delay error](https://amp.dev/page-experience/?url=https://wpindia.co.in/2021/01/07/well-my-phones-battery-stuck-at-50-for-some-reason/?amp).

Please also provide:
- Page link: https://amp.dev/page-experience/?url=https://amp-wp.org/success-on-the-web-with-amp-and-google-site-kit/
- (Optional) Screenshots/videos:
![image](https://user-images.githubusercontent.com/1132541/108407824-41adfd00-724a-11eb-82c1-3bc7f1cce8fa.png)

### Expected behavior/code
It should allow multiple properties for the viewport ie initial-scale, minimum-scale, maximum-scale, and user-scalable. 
eg: `<meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=5.0, minimum-scale=0.86">`

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. Step 1 Visit https://amp.dev/page-experience/
2. Step 2 Enter this URL to Analyze https://amp-wp.org/success-on-the-web-with-amp-and-google-site-kit/
3. Step 3 Wait for results and you will see Disable Tap Delay Message. (not sure if this is broken but 
notice `<code><span class="err">`it's also in screenshot )

- What browser are you using? Chrome Version 88.0.4324.150 (Official Build) (x86_64)
- What O/S are you using? Mac OS Catalina 10.15.7

**Comment by milindmore22** [comment]
Closing this ref: https://github.com/ampproject/amp.dev/pull/5063

**Comment by schlessera** [comment]
Related fix in `amp-wp`: https://github.com/ampproject/amp-wp/issues/5894
