### ISSUE TITLE
📖 Question: do AMP Stories support `<amp-anim>` ?

### ISSUE THREAD

**Issue by TetraLogicalHelpdesk** [ampproject/amp.dev#5398]
### Problem
The components documentation for AMP Stories https://amp.dev/documentation/components/?format=stories currently doesn't list `<amp-anim>`. However, https://amp.dev/documentation/guides-and-tutorials/learn/common_attributes/?format=stories#fallback gives an example using `<amp-anim>`. Should the example be changed/generalised to apply to stories as well?

### Location
https://amp.dev/documentation/guides-and-tutorials/learn/common_attributes/?format=stories#fallback

### Content type
Updated paragraph

**Comment by patrickkettner** [comment]
@CrystalOnScript would this be on your plate? Or does someone on the dev team need to confirm anything?
