### ISSUE TITLE
APESTER as a Story Creation Platform for AMP 

### ISSUE THREAD

**Issue by roeyharari1** [ampproject/amp.dev#5405]
### Story creation resource name

<Apester>

### Type

Use [x] to mark a selection:

- [X] Story Creation Tool
- [ ] CMS
- [X] Platform
- [ ] Other

### URL

<https://www.apester.com>

### Image

< Please provide a screenshot of your resource’s editor window (min. 800x400 pixels) to appear on the [Tools](https://amp.dev/documentation/tools) page. JPEG, PNG or SVG images are acceptable >

### Description

< Please provide a short description (max. 100 characters) to appear on the [Tools](https://amp.dev/documentation/tools) page. >
<img width="1437" alt="Screen Shot 2021-02-20 at 18 23 42" src="https://user-images.githubusercontent.com/20553204/108611067-cf9ffa00-73a8-11eb-8155-40f904892438.png">

### List of Stories

< Please list 10 Web Stories across a diverse set of topics/treatments that each meet the following criteria

* Minimum of 7 pages
* At least 4 images
* At least 2 videos
* At least four pages with some text >
* https://renderer.apester.com/v2/5e5b7710b26035724d9d2c43?preview=true&iframe_preview=true
* https://renderer.apester.com/v2/5e0a0739606383908f14849c?preview=true&iframe_preview=true
* https://renderer.apester.com/v2/5dc59d35daa233fe5327bb3d?preview=true&iframe_preview=true
* https://renderer.apester.com/v2/5dd163c54e71a768b800e9ef?preview=true&iframe_preview=true
* https://renderer.apester.com/v2/5dcd332150088b6fbbae01fb?preview=true&iframe_preview=true
* https://renderer.apester.com/v2/5ee3ab8df66451384925ef4c?preview=true&iframe_preview=true
* https://renderer.apester.com/v2/5dd2a4a950088b42a8ae0526?preview=true&iframe_preview=true&_ga=2.164961087.1412886258.1613811391-2022989737.1557634659
* https://renderer.apester.com/v2/5dbe8444923548b36a17547b?preview=true&iframe_preview=true&_ga=2.164961087.1412886258.1613811391-2022989737.1557634659
* https://renderer.apester.com/v2/5e15db1e1003e5699af85863?preview=true&iframe_preview=true&_ga=2.68444049.1412886258.1613811391-2022989737.1557634659
* https://renderer.apester.com/v2/5e15f4d422b40152c3b406b7?preview=true&iframe_preview=true&_ga=2.68444049.1412886258.1613811391-2022989737.1557634659

**Comment by patrickkettner** [comment]
@sdenaro would this be something you could look at?

**Comment by Dbrown910** [comment]
Hey @roeyharari1

I just reviewed the links. Content and quality wise they look great, but these don't comply with the AMP format. In order to proceed the first thing we need are AMP valid Web Stories. Here is [the documentation](https://amp.dev/documentation/guides-and-tutorials/start/visual_story/?format=stories) to help you get started.

**Comment by Dbrown910** [comment]
Hi @roeyharari1 

Just wanted to touch base? Any update on this?

**Comment by roeyharari1** [comment]
Hi Damani,
Sorry for the radio silence on my end.

I'm checking with my dev team what is the effort to comply with the AMP
format and get back to you.

I wondered if you had some time this week to meet with my VP R&D to chat
about the compliance and the work needs to be done on our end so we can
estimate it more accurately.

Best,

**Comment by roeyharari1** [comment]
Hi Damani,
following up on my last email,
My tech team would like to start working on it but we need to better
understand what is the MVP needed here.

I'll appreciate your feedback and if we can set up a kick off meeting so
you can elaborate more about the complies requierments

Best,

**Comment by Dbrown910** [comment]
Hi @roeyharari1 ,

What's your email? I'll set up some time for us to connect!

**Comment by roeyharari1** [comment]
***@***.***

Tnx,
Roey

**Comment by Dbrown910** [comment]
@roeyharari1 
Oh whoops. Github actually masked your email address. Can you try again in a comment? Or you can just reach out to me, damanibrown @ google

**Comment by roeyharari1** [comment]
just sent you an email, any case this is mine
roey.harari @ apester.  com

**Comment by sdenaro** [comment]
Was this ticket completed?

**Comment by powerivq** [comment]
Closing old issues.
