### ISSUE TITLE
Pixi: Disable tap delay has code formatting problem

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#5417]
## 🐛 Bug Report

The Disable tap delay advice has a problem with the code formatting:

![image](https://user-images.githubusercontent.com/134745/108760518-9d0a1480-7502-11eb-96d8-978ff83b49b8.png)

### Current behavior

The `<code>` tags are rendered out, apparently being HTML-escaped.

### Expected behavior/code

Instead of:

```
<code><span class="err"><meta name="viewport" content="width=device-width"></span>
</code>
```

It should display:

```
<meta name="viewport" content="width=device-width">
```

**Comment by matthiasrohmer** [comment]
@kristoferbaxter, I think this is a worker-dom bug. I can build a test case if needed but it boils down to Pixi trying to set `<p>Set viewport width to match the device width to disable touch delay, which 
can increase FID. To remove this 300-350ms tap delay, change the viewport 
declaration in the <code>&lt;head&gt;</code> of your page to:</p>
<div class="ap-m-code-snippet"><pre><code><span class="err">&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;</span>
</code></pre></div>` as `innerHTML` for a node.

Doing this renders the malformed result Weston reported, doing it via the DOM API directly at runtime (i.e. `$0.innerHTML = ...) with the same string works fine.

**Comment by kristoferbaxter** [comment]
Oh, interesting!

Let's create a simplified example case and file something on WorkerDOM.

I'm happy to take a look.

**Comment by sebastianbenz** [comment]
@matthiasrohmer have you already filed a bug for worker-dom?
