### ISSUE TITLE
Page experience issue

### ISSUE THREAD

**Issue by VishalSrivastav** [ampproject/amp.dev#5439]
Hi,

I am an SEO Professional, working with Homeonline.com. We are using AMP Site for the last 2 Years. Now I am trying to analyze our AMP Pages for Page Experience but the tool is showing an error that the URL is Invalid, however, the AMP Validator Tool is showing Valid and the same URLs are being crawled and indexed in Google SERPs. Could you please help us to get the exact reason why the page experience tool is showing pages as Invalid?

Please find below the AMP URLs of My Site:

- https://www.homeonline.com/amp/property-for-sale-bhopal
- https://www.homeonline.com/amp/property-for-sale-indore
- https://www.homeonline.com/amp/property-for-sale-raipur

Please Help! 
Regards,
Vishal

**Comment by sebastianbenz** [comment]
Is it possible that the site is geoblocking certain regions.

<img width="1489" alt="Screenshot 2021-02-24 at 16 21 37" src="https://user-images.githubusercontent.com/380472/109022746-6aa41700-76bc-11eb-88df-f6d609ca8590.png">

**Comment by VishalSrivastav** [comment]
Yes, We have blocked access from the European Region. Unblocking these regions will work?

**Comment by sebastianbenz** [comment]
We run Pixi on servers in different regions. Depending on which instance
you get, your content might be blocked. I don't see a good way around this.

>

**Comment by patrickkettner** [comment]
@VishalSrivastav assuming you want to continue blocking EU, would it be possible to allow access the [IP ranges Google Cloud](https://cloud.google.com/vpc/docs/configure-private-google-access) uses in that area?

**Comment by sebastianbenz** [comment]
Closing as not related to amp.dev.
