### ISSUE TITLE
Avoid CLS for format switcher hint

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#5476]
Would be great if we could come up with a better way. Maybe make the bar smaller and leave the space empty.

**Comment by sebastianbenz** [comment]
![cls (1)](https://user-images.githubusercontent.com/380472/110024101-3d93dc00-7d2e-11eb-9894-62080dae6af4.gif)

**Comment by lluerich** [comment]
Maybe make it as small as the toggle in the sidebar? I see if I can think of anything. Maybe Ferdi has an idea as well.

**Comment by matthiasrohmer** [comment]
@lluerich, result from Tuesday's call: we'll condense the design in height and reserve the place it might need to avoid CLS issues. Ferdi will take this on.
