### ISSUE TITLE
Overlapping words on amp.dev homepage on mobile 

### ISSUE THREAD

**Issue by nathanpuls** [ampproject/amp.dev#5506]
Video of the issue. 
3 seconds in it starts. 

https://streamable.com/3c84up

**Comment by kristoferbaxter** [comment]
Transferred this to amp.dev since it appears unrelated to the AMP Framework.

**Comment by patrickkettner** [comment]
thanks @kristoferbaxter 

@nathanpuls what device was this? I am not able to replicate it

**Comment by nathanpuls** [comment]
iphone 12

**Comment by powerivq** [comment]
Closing old issues.
