### ISSUE TITLE
Non-experimental components listed in "Enable experimental features" guide

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#5507]
## 🐛 Bug Report

On https://amp.dev/documentation/guides-and-tutorials/learn/experimental, lots of components are listed as being in experimental status. This is caused by the Bento developer preview.

Currently, it says this:

The following is a list of components that are currently in experimental status and are ready to be tested by developers for first user feedback:

- amp-accordion
- amp-action-macro
- amp-base-carousel
- amp-base-carousel
- amp-date-countdown
- amp-fit-text
- amp-inline-gallery
- amp-instagram
- amp-lightbox
- amp-mega-menu
- amp-next-page
- amp-selector
- amp-social-share
- amp-timeago
- amp-truncate-text
- amp-video
- amp-youtube

**Comment by sebastianbenz** [comment]
My suggestion would be to add the component version to list (e.. amp-accordion-v0.1 is not experimental, but amp-accordion-v1.0 is). Also these components should link to the version specific docs.
