### ISSUE TITLE
amp-analytics example page broken

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#5538]
The [amp-analytics example](https://amp.dev/documentation/examples/components/amp-analytics/?referrer=ampbyexample.com) has a lot of AMP errors
<img width="1395" alt="Screen Shot 2021-03-18 at 3 21 02 PM" src="https://user-images.githubusercontent.com/23297417/111705311-b8182d80-87fd-11eb-873d-24963e45a3af.png">
 is missing the TOC.

**Comment by patrickkettner** [comment]
dupe of #4250
