### ISSUE TITLE
[amp-carousel] Playground examples use 0.1 instead of 0.2

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amp.dev#5586]
On https://amp.dev/documentation/components/amp-carousel, the documentation is for 0.2 (based off of the drop down at the top).

However, opening the playground snippets on that page, in the code snippet I see that we have script tags for 0.1, which is a little confusing since the documentation I was just on was for 0.2.

![image](https://user-images.githubusercontent.com/30711678/112632679-a8987600-8df5-11eb-9483-f187de7c5176.png)

**Comment by lluerich** [comment]
I stumbled over something similar the other day and I found out that the version gets overwritten at build time when the latest components are being fetched. ```amp-carousel``` has two separate entries, one for websites and one for amp4email.
https://github.com/ampproject/amp.dev/blob/a26709c1a0deaf268fe919acf0500749f93811a8/gulpfile.js/build.js#L184 is where it happens. I will create a PR for this.

**Comment by lluerich** [comment]
Fixed by #5588.
