### ISSUE TITLE
amp-image-lightbox menu duplication

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amp.dev#5598]
### Problem
amp-image-lightbox label appears 2x in menu
![image](https://user-images.githubusercontent.com/11330577/112748619-84b66b00-8f82-11eb-980f-5ca53997e3a8.png)

### Location
https://amp.dev/documentation/examples/components/amp-image-lightbox.email/?format=websites

**Comment by lluerich** [comment]
This is actually correct, since one sample is the default sample for websites and the other one is format specific (in this case it's the sample for amp4email).

**Comment by sebastianbenz** [comment]
Hm. But the email specific sample should not be listed for websites.

**Comment by jaygray0919** [comment]
@sebastianbenz that's what i "meant to say ..."

**Comment by sebastianbenz** [comment]
@lluerich can you please take a look. Looks like all components with format specific samples are listed multiple times.
