### ISSUE TITLE
Pixi analysis fails due undefined API key

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#5604]
## 🐛 Bug Report

When attempting to run Pixi, the result is a failure:

> ![image](https://user-images.githubusercontent.com/134745/112908421-5a5cce80-90a4-11eb-88ea-9afa5fcc6fcc.png)

In looking at the network log, the key is undefined in the requests to Google APIs:

> ![image](https://user-images.githubusercontent.com/134745/112908418-57fa7480-90a4-11eb-80ce-9394dd019d58.png)

Console:

> ![image](https://user-images.githubusercontent.com/134745/112908539-8d06c700-90a4-11eb-8ab9-5f04d40b8b00.png)

May relate to https://github.com/ampproject/amphtml/issues/33405#issuecomment-805478248.

**Comment by patrickkettner** [comment]
Looks like the changes added [here](https://github.com/ampproject/amp.dev/pull/5553) would be where this came from - @sebastianbenz How is the API key being defined in a github action world?

**Comment by sebastianbenz** [comment]
I've triggered a rollback to the latest travis build.

**Comment by patrickkettner** [comment]
@sebastianbenz sorry, didn't mean that the CLI is the cause - rather it would have been an issue since that commit, as it appeared to be what introduced the key mapping in `AMP_DEV_PIXI_APIS_KEY`, where it hadn't been an issue previous to the actions build

**Comment by sebastianbenz** [comment]
Running `gulp buildPixi` locally results in the API keys correctly being added to the bundles.

**Comment by matthiasrohmer** [comment]
Will quickly setup a isolated workflow just building Pixi and storing it as an artifact for debugging.

**Comment by matthiasrohmer** [comment]
I'm terribly sorry! It struck me in the moment I was suggesting so setup a dedicated testing workflow... could had have a more thorough look last time. https://github.com/ampproject/amp.dev/pull/5605 should fix it.
