### ISSUE TITLE
Inline code previews not working/flashing

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#5624]
### Current behavior
A lot of the inline code examples are doing a weird flashing/refreshing something. It makes the samples impossible to view and interact with. 

Examples include:

https://amp.dev/documentation/guides-and-tutorials/integrate/embed-stories/ 
https://amp.dev/documentation/guides-and-tutorials/integrate/embed-stories-nonamp/?format=websites
https://amp.dev/documentation/components/amp-accordion/?format=websites
https://amp.dev/documentation/components/amp-mega-menu/?format=websites

**Comment by patrickkettner** [comment]
Checked with the AMP release team as it was noticed shortly after a release, however after review it seems to be an issue with our code, rather than AMP's.
This constant reloading is isolated to examples with `playground="true"` and `preview="top-frame"`, digging into that presently
