### ISSUE TITLE
Bento guide: amp-accordion example loads repeatedly

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#5626]
### Current behavior
Go to [the Bento guide](https://amp.dev/documentation/guides-and-tutorials/start/bento_guide/?format=websites). Scroll down to the `amp-accordion` example.

This example keeps loading again and again and again, several times per second.

### Expected behavior/code
It would only load once 😎

https://user-images.githubusercontent.com/29419498/113238297-7fa13680-9276-11eb-8209-3e84c0dff173.mov

**Comment by patrickkettner** [comment]
thanks! being tracked in #5624
