### ISSUE TITLE
node-sass deprecated, should be replaced

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amp.dev#5632]
I've been having a lot of issues locally, a number of them seem to be stemming from node-sass not building correctly. It was actually [deprecated last year](https://sass-lang.com/blog/libsass-is-deprecated).
On a related note, `gulp-sass` has received few updates for some time, and [appears to be unresponsive](https://github.com/dlmanning/gulp-sass/pull/786) to requests to migrate to the project to the replacement, [`sass`](https://www.npmjs.com/package/sass)

Anyone against replacing them both with updated deps?

**Comment by sebastianbenz** [comment]
No. SGTM

>
