### ISSUE TITLE
AMP Optimizer

### ISSUE THREAD

**Issue by fri-mue** [ampproject/amp.dev#5638]
Hi, 
would it be possible for you to provide an AMP Optimizer on your website that can be used to optimize static AMP websites.
This is available, for example, at https://toolbox-optimizer.glitch.me/, but the optimizer no longer works.

With best regards

Tom

**Comment by kristoferbaxter** [comment]
Transferring to `amp.dev`, sounds like a good recommendation to live here.

**Comment by patrickkettner** [comment]
thank @kristoferbaxter!

Hi @fri-mue! - that site is actually ran by this team, I think the fact that it isn't currently working was an oversite. 

@sebastianbenz, the underlying response sends back `{"body": <!doctype html><html amp .....`, as a json response, which ends up returning true on [`isAmp`](https://github.com/ampproject/amp-toolbox/blob/master/packages/core/lib/IsAmp.js). As a result, our optimizer middleware is rewriting the response. Not sure how you want to handle this (I doubt many people are embedding an AMP doc inside of a JSON response using a express server with our middleware...), so I though the simplest fix is something like

```diff
diff --git a/views/index.html b/views/index.html
index ebe321e..8d4f534 100644
--- a/views/index.html
+++ b/views/index.html
@@ -109,6 +109,9 @@
         const response = await fetch("/optimize", {
           method: "POST",
           body: JSON.stringify(optimizeRequest),
+          headers: {
+            "Accept": "application/json"
+          }
         });
         if (response.ok) {
           const transformed = await response.json();
@@ -142,3 +145,4 @@
     </script>
   </body>
 </html>
+

```

Setting this makes the `Accepts` header more strict (its currently `*/*`), thereby getting past [`isResourceRequest_`](https://github.com/ampproject/amp-toolbox/blob/84cb3057e5f6c54d64369ddd285db1cb36237ee8/packages/optimizer-express/lib/AmpOptimizeMiddleware.js#L114).

**Comment by patrickkettner** [comment]
@sebastianbenz I requested edit on the Glitch, assuming you are good with the fix I suggested?

**Comment by sebastianbenz** [comment]
I didn't receive a request Patrick. I went ahead it applied your fix.
Thanks for looking into this!

>

**Comment by patrickkettner** [comment]
no worries, I have no idea how glitch requests actually work, I just hit the "request" button.

@fri-mue thanks for the report! closing as this should be solved now
