### ISSUE TITLE
search and autosuggest

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amp.dev#5654]
When searching for `position`,  autosuggest returns this term: `amp-position-observer`

but does not return the page link, i.e.

https://amp.dev/documentation/components/amp-position-observer/?format=websites

**Comment by matthiasrohmer** [comment]
Indeed... thanks for the report!
![image](https://user-images.githubusercontent.com/12857772/114066697-4aab6a00-989c-11eb-8bd7-f84ddc2e13bf.png)

**Comment by jaygray0919** [comment]
This issue is actually widespread. Try different patterns. Autosuggest part 1 properly returns a target string. But autosuggest part 2 does not return a link that matches part 1. Part 2 does return links, but most are not relevant to part 1.

**Comment by jaygray0919** [comment]
looks like this has been fixed (i missed where the fix was applied, but it seems to have worked)
