### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp.dev#5657]
I recognize this is non-trivial given the accompanying infrastructure changes that are needed. For `amphtml`, we've been following [this migration plan](https://docs.google.com/document/d/1BN8CkM3b2nydENRI2X1tE6nCxcaeVliUIaC2e-mXZbg/edit#), which seems to have worked quite nicely so far. See https://github.com/ampproject/amphtml/issues/32195 for more details.

/cc @tobie @kristoferbaxter

**Comment by sebastianbenz** [comment]
We've migrated away from master a long time ago. Our current default branch is `future`.

**Comment by matthiasrohmer** [comment]
@sebastianbenz, there's still a `master` branch though that holds the old ampproject.org code. That is probably fine to delete though as there's no matching CI in place anymore and there's `legacy-production` in pair with it.

**Comment by sebastianbenz** [comment]
Good point. Deleted `master`.

>
