### ISSUE TITLE
[Pixi] Pixi should highlight that the CLS metric is evolving

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#5692]
See https://web.dev/evolving-cls/ for reference

We should show a "Did you know?" section while the results are loading that point to the above link and call out that the way CLS is measured has change. 

Copy: `The Chrome Speed Metrics Team has changed the way CLS is measured to be more fair to pages that are open for a long time. See https://web.dev/evolving-cls/ for more details`

**Comment by sebastianbenz** [comment]
What are other links we could show while waiting for the result? //cc @patrickkettner

**Comment by patrickkettner** [comment]
any idea what you want it to look like? Something like this?

![image](https://user-images.githubusercontent.com/465414/114732059-3938e680-9d10-11eb-83f2-ab218cac27a8.png)

**Comment by nainar** [comment]
<img width="1064" alt="Screen Shot 2021-04-14 at 10 59 53 AM" src="https://user-images.githubusercontent.com/7919520/114732515-93d24280-9d10-11eb-89c0-be1643f77a7f.png">
The suggestion was here ^

**Comment by patrickkettner** [comment]
ah! missed that part of your comment. Thank you
