### ISSUE TITLE
Pixi: Unexpected format for font-display recommendation

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#5698]
## 🐛 Bug Report

Given this recommendation in Pixi:

> ![image](https://user-images.githubusercontent.com/134745/115064670-0b83a700-9ea2-11eb-9cd5-57e0641562c5.png)

1. The heading shows backticks when it should be a `code` tag.
2. In the suggestion for Open Sans, the `$display=swap` is unexpected, as is `&display: optional`. The font is getting loaded via `https://fonts.googleapis.com/css?family=Open+Sans%3A400%2C400i%2C700%2C700i%2C300%2C300i&display=swap` so shouldn't it say to just replace `display=swap` with `display=optional`?
3. There is a dangling apostrophe and comma at the end of that suggestion as well.

**Comment by sebastianbenz** [comment]
Good points! We also should not recommend optional for icon fonts (cc @lluerich).

**Comment by lluerich** [comment]
Good catch! Could you attach the tested URL?

**Comment by westonruter** [comment]
The tested URL can be seen in a screenshot on https://github.com/ampproject/amp-wp/issues/6073.

**Comment by lluerich** [comment]
@sebastianbenz regarding the recommendation for the icon font: should we check for icon font usage at this point? I feel like those are two different pairs of shoes. Regarding the recommendation that the font should use ```display: optional``` is correct if only checking the ```font-display``` settings, isn't it?

**Comment by sebastianbenz** [comment]
@leo We need to make sure to ignore icon fonts when recommending font-display optional.
