### ISSUE TITLE
Update AMP Optimizer documentation to include Cloudflare workers

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#5702]
https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/

^ Update to include Cloudflare workers as well

**Comment by sebastianbenz** [comment]
It's already listed under hosting provider integrations, would you like it to be more prominent?

**Comment by patrickkettner** [comment]
ping @nainar

**Comment by nainar** [comment]
Ignore me - I didn't see it when I searched Cloudflare when I created that issue.
