### ISSUE TITLE
RocketMail AMP platform

### ISSUE THREAD

**Issue by rocketmaileu** [ampproject/amp.dev#5719]
### 1. Resource name
RocketMail

https://www.rocketmail.lu/

### 2. Relevant format(s)

- [ ] websites
- [ ] stories
- [ ] ads
- [ x] email

### 3. Resource type

- [ x] editor
- [ ] service provider
- [ ] developer tool
- [ ] content platform
- [ ] CMS
- [ ] ads
- [ ] audio/video
- [ ] analytics vendor

### 4. Destination
 [amp.dev/documentation/tools](https://amp.dev/documentation/tools)

#### 4.1 If you chose 1 in Step 4:
Please provide an image (min. 800x400 pixels) to appear on the [Tools](https://amp.dev/documentation/tools) page, as well as a short description (max. 100 characters).

http://www.rocketmail.lu/wp-content/uploads/2021/04/RocketMail-AMP-dev.jpg

from creation to delivery and interaction analysis. RocketMail offers a full solution for AMP emails

**Comment by rocketmaileu** [comment]
Do you think this open issue is going to be taken care of ??? i don't have any feedback

**Comment by powerivq** [comment]
The platform does not seem to be supporting AMP4EMAIL. Closing.
