### ISSUE TITLE
AMP Based instagram like story platform - focused on News Contents

### ISSUE THREAD

**Issue by azmathr** [ampproject/amp.dev#5720]
Hi,
We are developing a story platform, which is solely focused on AMP stories. We are partnering with major news publishers to have their contents in our iOS and web platform, and each stories will be neatly categories into various sections.

Our expectation on developing such platform using AMP is to possibly attract SEO advantage in future. We have created over 2000 in-house news stories, and we would like to push it via AMP through our upcoming website.

Please let us know if we could collaborate with Google.

**Comment by patrickkettner** [comment]
Hi @azmathr!

The AMP project is separate from Google, but we can review the service to be listed on the official amp.dev site if that is of use?
