### ISSUE TITLE
Broken link to amp-pets-story.zip

### ISSUE THREAD

**Issue by matthiasq** [ampproject/amp.dev#5724]
The link to https://github.com/ampproject/docs/raw/master/tutorial_source/amp-pets-story.zip on https://amp.dev/documentation/guides-and-tutorials/start/visual_story/setting_up/?format=stories seems broken.

**Comment by processprocess** [comment]
cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
Hey @sebastianbenz @CrystalOnScript, we recently changed the branch name on the `amphtml` repo to `main`, and [rewrote all URLs](https://github.com/ampproject/amphtml/pull/33570) to reflect the change. For amp.dev, I think all the related docs pulled automatically from GH should be updated, but there might be some that still need to be updated on the amp.dev repo. Could you please take a look?

**Comment by processprocess** [comment]
@matthiasq A fix for this has been merged and the changes will be reflected within the next week. Thanks again for filing this!

**Comment by sebastianbenz** [comment]
Fix is already live :-)

>

**Comment by sebastianbenz** [comment]
Yup, amp.dev pulls in docs based on amp releases. The master / main change hasn't made it into the released version of the story docs yet. Added an exception here: https://github.com/ampproject/amp.dev/pull/5728
