### ISSUE TITLE
PAGE NOT FOUND

### ISSUE THREAD

**Issue by himanshu007-creator** [ampproject/amp.dev#5786]
### Current behavior
when a user go through the <code>Create your first AMP page</code> module, there is a broken link in final step.

Please also provide:
- Page link: https://amp.dev/documentation/guides-and-tutorials/start/create/publish/?format=websites
- (Optional) Screenshots/videos:
![2021-05-07](https://user-images.githubusercontent.com/65963997/117398542-30f15700-af1c-11eb-8596-5128bcd3abed.png)

### Expected behavior/code
The link should open a new page

### Reproduction procedure
Please provide the steps to reproduce the problem:
1)_ navigate to <code>Documentation>Guides & Tutorials>Create your first AMP Page</code>
2) click on link<code> Getting Started With Your Development Workflow.</code>
- Chrome  90.0.4430.93 (Official Build) (64-bit)
- OS:- Windows 10

**Comment by sebastianbenz** [comment]
This should be fixed with #5756
