### ISSUE TITLE
Clicking any link in the sidebar removes filter

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amp.dev#5842]
### Current behavior
If you have filtered amp.dev to e.g. `stories` clicking any links in the sidebar will take you back to `website` mode. 

Please also provide:
- Page link: https://amp.dev/documentation/examples/advertising-analytics/publisher_served_amp_story_ads/
- (Optional) Screenshots/videos:
![image](https://user-images.githubusercontent.com/16087874/118156199-efeebc00-b3cd-11eb-9321-5050b38e7829.png)

### Expected behavior/code
Ideally the filter would persist

### Reproduction procedure

1. Select `story` filter.
2. Click on any link in the sidebar

- What browser are you using? Chrome 90
- What O/S are you using? MacOS

**Comment by calebcordry** [comment]
cc/ @raovs

**Comment by patrickkettner** [comment]
Thanks!

**Comment by matthiasrohmer** [comment]
This one is tricky. I tried to fix that specific case for the examples with #5855. But what happens is that you are visiting the page without a `format` query arg. The server doesn't know what format the pages default to and assumes `websites` which of course breaks for the `story` formats.
