### ISSUE TITLE
Enable offline access to docs site

### ISSUE THREAD

**Issue by DerekNonGeneric** [ampproject/amp.dev#589]
## Description of the issue:

- Page link: [ampproject.org](https://www.ampproject.org/)
- Description of the documentation issue: The service worker only caches static assets, not pages, causing the site to be unusable while offline.

## How do we reproduce the issue?

1. Visit [ampproject.org](https://www.ampproject.org/)
1. Disconnect from the internet
1. Refresh
1. See offline dino

What browser are you using? Google Chrome Version 61.0.3143.0 (Official Build) canary (64-bit)
What O/S are you using? macOS Sierra Version 10.12.6 Beta (16G18a)

![amp-docs-sw-bug](https://user-images.githubusercontent.com/17770407/27703385-28513d24-5cd5-11e7-821b-743e8ba481ad.png)

**Comment by amedina** [comment]
There may be an issue with Lighthouse; when loading ampproject.org locally I can see proper Web Manifest and Service Worker running smoothly; I am also able to load the site on repeat visit and fully offline.

**Comment by amedina** [comment]
![screen shot 2017-07-03 at 12 44 09 pm](https://user-images.githubusercontent.com/506089/27806100-7bbfe666-5fed-11e7-985b-c85fc03c8a32.png)
![screen shot 2017-07-03 at 12 43 58 pm](https://user-images.githubusercontent.com/506089/27806106-7fc572ee-5fed-11e7-87a7-1d73a86d960f.png)

**Comment by amedina** [comment]
Talked to @pbakaus offline; currently the SW is not providing offline support because caching all pages is ineffective; it will a good enhancement to support offline capability, at least for the docs section. Setting this as an enhancement and we will get to it.

**Comment by johnw123** [comment]
If you’re looking for <a href="https://www.etech7.com/managed-it-services-in-nyc">Managed IT Services in NYC</a>, Etech7 is the right place for you. I’m a dummy in IT sphere, so all the time I need a good company to solve my IT problems. Finally I’ve found Etech7 and  when I need <a href="https://www.etech7.com/it-consulting">IT Consulting</a>, I’ll definitely call them.
