### ISSUE TITLE
Playground: snackbar style broken 

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#5894]
See screenshot

<img width="630" alt="Screenshot 2021-05-21 at 16 34 50" src="https://user-images.githubusercontent.com/380472/119154525-88caaa80-ba52-11eb-9c88-c1f69bc5a35b.png">

**Comment by lluerich** [comment]
@sebastianbenz could you elaborate on this?

**Comment by sebastianbenz** [comment]
Open: https://playground.amp.dev/?mode=Pixel+2&url=notfound

You'll see an error message in the header which should be in a snackbar.
