### ISSUE TITLE
Bento docs for `amp-date-display` links to missing stylesheet

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#5901]
### Current behavior

On the [docs for `amp-date-display` v1.0](https://amp.dev/documentation/components/amp-date-display/?format=websites), the Bento option shows this HTML to copy:

```html
<script async custom-element="amp-date-display" src="https://cdn.ampproject.org/v0/amp-date-display-1.0.js"></script>
<link rel="stylesheet" href="https://cdn.ampproject.org/v0/amp-date-display-1.0.css">
```

Problem: https://cdn.ampproject.org/v0/amp-date-display-1.0.css is a 404.

This is not a problem for [`amp-base-carousel` v1.0](https://amp.dev/documentation/components/amp-base-carousel/) where it shows:

```html
<script async custom-element="amp-base-carousel" src="https://cdn.ampproject.org/v0/amp-base-carousel-1.0.js"></script>
<link rel="stylesheet" href="https://cdn.ampproject.org/v0/amp-base-carousel-1.0.css">
```

And the stylesheet URL is OK: https://cdn.ampproject.org/v0/amp-base-carousel-1.0.css

### Expected behavior/code

Bento stylesheet link should not 404.

**Comment by sebastianbenz** [comment]
@caroqliu do you know why amp-date-display hasn't got a CSS file?

**Comment by caroqliu** [comment]
> @caroqliu do you know why amp-date-display hasn't got a CSS file?

No good reason, I'll add now. It also appears to be missing for `amp-date-countdown` and `amp-timeago`.
