### ISSUE TITLE
Built in components are not listed (amp-img, amp-layout)

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amp.dev#5991]
`amp-img` and `amp-layout` are not listed in the component library sidebar: 
![image](https://user-images.githubusercontent.com/10456171/122071087-73803c00-cdc4-11eb-9e13-4e7508abe097.png)

In addition, the typical component pages appear to be 404ing, ex:
- https://amp.dev/documentation/components/amp-layout/ is 404 
- should this link to https://amp.dev/documentation/components/amp-layout-v0.1/?format=websites instead?

**Comment by sebastianbenz** [comment]
Fix is live in prod

**Comment by caroqliu** [comment]
Thanks for the quick work here!
