### ISSUE TITLE
Add AOL mail support to amp.dev

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#5997]
AOL web mail now supports AMP for Email format.  This was launched this at the end of March.

Let's add this to the support matrix for Email clients
![yahoo-mail](https://user-images.githubusercontent.com/7919520/122254448-1f945680-ce9b-11eb-875b-071861ec16bc.png)
![aol-mail](https://user-images.githubusercontent.com/7919520/122254450-202ced00-ce9b-11eb-851c-a8f89353167b.png)

**Comment by nainar** [comment]
@kaewka as FYI

**Comment by patrickkettner** [comment]
@nainar do you have a landing page URL for them ([like this](https://developer.verizonmedia.com/mail/amp-for-email)? Also, do they have a privacy policy for [here](https://amp.dev/documentation/guides-and-tutorials/start/email_sender_distribution#follow-privacy-policies)?

**Comment by kaewka** [comment]
@patrickkettner That is correct.  Both Yahoo Mail and AOL Mail are using the same landing page and privacy policy page https://developer.verizonmedia.com/mail/amp/
and
https://www.verizonmedia.com/policies/us/en/verizonmedia/privacy/index.html

**Comment by patrickkettner** [comment]
Thanks @kaewka! For text, is there a prefrerred style for the two brands? (e.g. `AOL/Yahoo Mail`) or do you prefer they are wholly separate entries?

**Comment by kaewka** [comment]
@patrickkettner Two separate entries.  Thanks!
