### ISSUE TITLE
The side bar button doesn't work on mobile version of amp.dev

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amp.dev#6000]
### Description

The side bar button doesn't work on mobile version of amp.dev.  This bug appears only on real devices. In mobile view on desktop OS it works as expected. 

### Reproduction Steps

1) launch any browser on your mobile device
2) go to https://amp.dev/
3) tap on the hamburger button 
4) observe result

Actual result: Side menu doesn't appear after tapping on hamburger button.
Expected result: Side menu should appear on the screen.

https://user-images.githubusercontent.com/37351864/122447466-a1968500-cf58-11eb-88cc-af105b878752.MP4

### OS(s) Affected

all mobile OS

### AMP Version Affected

all versions

**Comment by sebastianbenz** [comment]
Looks like the new frontend does not include the template for the burger-menu.

**Comment by patrickkettner** [comment]
looks like it _is_ there, its just at the bottom of the page - scoping issue? checking it out

![image](https://user-images.githubusercontent.com/465414/122454504-77a18a80-cf79-11eb-8cac-b6c0291b5d55.png)

**Comment by sebastianbenz** [comment]
Fix is live

**Comment by patrickkettner** [comment]
WFM!

Side question, does tapping the section header not supposed to toggle the
section? It only opens presently and I don’t remember what the design doc
was
-- 
patrick

**Comment by Ichigo3d** [comment]
Confirm fix is applied. Thank you all.

**Comment by sebastianbenz** [comment]
@patrickkettner yeah, I think it should toggle
