### ISSUE TITLE
Bento amp-lightbox (v1.0) example broken

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#6071]
## 🐛 Bug Report

The Bento `amp-lightbox` example is broken at https://amp.dev/documentation/components/amp-lightbox-v1.0/?format=websites

Clicking the button to open the lightbox does nothing. There are errors in the console:

![image](https://user-images.githubusercontent.com/134745/127064416-0d17c046-f279-4e83-b74f-15f2e2fd2d78.png)

From https://preview.amp.dev/documentation/components/amp-lightbox-v1.0.example.1.html

**Comment by lluerich** [comment]
```layout="nodisplay"``` on ```amp-lightbox``` is missing in the example.
