### ISSUE TITLE
Strenuous Blog

### ISSUE THREAD

**Issue by Strenuouchima** [ampproject/amp.dev#6111]
### Problem
A precised amp for google blogger missing

### Location
Amp should be added to Blogger users like strenuousblog.com.

### Content type
A comphrensive video tutorials, documents and more.

### Information architecture (optional)
You know better!

**Comment by patrickkettner** [comment]
hi @Strenuouchima - thanks for reaching out!
I do not understand the request, however. Can you explain it in more detail?

**Comment by powerivq** [comment]
Closing old issues.
