### ISSUE TITLE
Add WebStories.Today Story Creation Tool/CMS/Platform

### ISSUE THREAD

**Issue by Web-Stories-Today** [ampproject/amp.dev#6213]
### Story creation resource name

WebStories.Today

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [x] Platform
- [ ] Other

### URL

https://webstories.today

### Image

https://webstories.today/images/webstories-platform-builder.jpg

### Description

We make sure Your Stories are discovered everywhere. Web, Discover, Slack, FB Messenger, LINE, Telegram,.....

### List of Stories

https://webstories.today/st/banksy
https://webstories.today/s/robb-report-the-best-steakhouses-in-america-right-now
https://webstories.today/s/most-impressive-wall-art-in-cities
https://webstories.today/s/guide-to-potty-training-within-7-days
https://webstories.today/s/robb-report-the-8-greatest-steaks-served-in-new-york-city
https://webstories.today/s/robb-report-10-new-luxe-hotels-opening-in-the-us-this-fall
https://webstories.today/s/The-importance-of-Story-telling-in-Sales
https://webstories.today/s/The-importance-of-Story-telling-in-Sales
https://webstories.today/s/contemporary-artists
https://webstories.today/s/moda-anos-70-e-a-identidade-brasileira-na-moda

**Comment by powerivq** [comment]
Cannot visit the platform. Closing.
