### ISSUE TITLE
Add Mailmodo to supported ESPs (AMP Email)

### ISSUE THREAD

**Issue by ApurvGpt** [ampproject/amp.dev#6214]
### 1. Resource name
Mailmodo
[mailmodo.com](https://www.mailmodo.com/)

### 2. Relevant format(s)

- [ ] websites
- [ ] stories
- [ ] ads
- [x] email

### 3. Resource type

- [ ] editor
- [x] service provider
- [ ] developer tool
- [ ] content platform
- [ ] CMS
- [ ] ads
- [ ] audio/video
- [ ] analytics vendor

### 4. Destination
https://amp.dev/support/faq/email-support/

**Comment by patrickkettner** [comment]
This is now live
