### ISSUE TITLE
Zazu

### ISSUE THREAD

**Issue by Zazuapp** [ampproject/amp.dev#6237]
### Story creation resource name

Zazu

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [ ] Platform
- [ ] Other

### URL

https://zazuapp.co/

### Image

http://zazuapp.co/wp-content/uploads/2021/11/Zazu-Slides-RedDot-05.png

### Description

Design award-winning Web Story builder. Rely on the most intuitive editor to build Stories with your team or automate the entire process.

### List of Stories

- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/cfee6bbe-1cbc-4264-a3ff-294621527924/Amp/56abeadb-ec65-48d0-954d-67974da9f728.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/84910072-e9bb-4cfb-8da7-03233380a7ca/Amp/2ef867b3-35db-445d-bcce-4da27e18f04c.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/b1ce3a64-3fcd-4f0e-a558-f959f8b26ddf/Amp/d76af626-93c5-4196-a21d-0724b3cf48c0.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/3bc0a049-d305-43aa-870f-e5bc6412c03b/Amp/8e29d6fc-316f-4450-a38d-5d20285ef0bc.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/16da2220-5925-4ff4-a3c4-dd869ac2b46e/Amp/75a671f3-ddab-4ac3-95c4-f5be4c1e667f.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/61aea12d-c79a-4fe5-ab6e-cc44d5a1c856/Amp/3dea61a7-b391-45ed-98c2-4e9c31204082.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/783e2513-ffd5-4d7f-afd7-c181460bcf68/Amp/e8abc703-c674-4bae-b93b-63bfff70b40b.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/34248313-0d91-4b64-a12f-ebfb566b6ab2/Amp/7d1957ae-45a4-4a56-8923-e3b3203af6b6.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/0b7ae7cc-9943-40b7-b01c-ba035e51fb63/Amp/d6bc8483-298c-4527-8bc9-458d72c9a4c3.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/480cb5b6-2cb5-4730-82f4-31e7c732f371/Amp/b3c5bb41-9f20-4547-9725-0ba19282d05f.html

**Comment by sdenaro** [comment]
Confirming I am taking this one.

**Comment by sdenaro** [comment]
There are five major issues and a few minor ones.

1) Many stories are reporting an issue with the canonical links but the links seem to be correct but the URLs are slightliy off, as an example:

linkrelcanonicalisok (FAIL)
actual: 

https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/**619b9946bebb3800136ecd2d**/Stories/12b531b5-2519-4b03-b3e8-6df3d96211cd/Amp/b344a396-680c-49bf-bf1f-5099e8fb7eb8.html

expected: 

https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/**619b998abebb3800136ecd34**/Stories/12b531b5-2519-4b03-b3e8-6df3d96211cd/Amp/b344a396-680c-49bf-bf1f-5099e8fb7eb8.html

I made the difference bold.

This MUST be fixed. 

2) The images listed as portrait are actually square. Please look at the poster-square-src tag,

  [poster-portrait-src = {"url":"https://zazuapp.co/wp-content/uploads/2021/09/logo_orange-1.png","width":4167,"height":4167,"mime":"image/png"}] failed [isPortrait]


3) Some images have the incorrect aspect ratio

As example in this story:

https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/201290e9-5121-4211-879f-b5e327fd31e9/Amp/b6438e54-d218-4ae4-8b3b-811a57b1290e.html

This image

https://media.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Media/a3d72aa7-0e25-4f99-b5db-e3ed8b83aac5.octet-stream 

Has an aspect ratio of 480/202 = 2.37 that does not match the specified ratio of  61/26 = 2.34

4) Some videos are above 4mb

As an example 

https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/66c48d2c-317c-470c-90d7-b49ce973ccfb/Amp/0a4d37ef-6e6f-4b5d-b4db-d81fdd9d33dd.html

Has this video that is over 4MB https://media.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Media/a3392c17-5482-4f5e-98de-17d3e66dcdfc.mp4


5) For the minor issues 

a)  I recommend adding   <link href=https://cdn.ampproject.org/v0.js **rel=preload**> when loading AMP.  In many cases this will provide a performance boost. 

schemametadataisnews (WARN)

b) I strongly recommend adding [Structured](https://amp.dev/documentation/guides-and-tutorials/start/converting/discoverable/#:~:text=is%20no%20ambiguity!-,Add%20structured%20data,-Valid%20AMP%20pages) data. 

  @type is not 'Article' or 'NewsArticle' or 'ReportageNewsArticle'

I will be back at my desk in Jan to work on this.

Thanks

**Comment by Zazuapp** [comment]
Hello @sdenaro 

We worked on the issues mentioned above and fixed the important ones, feel free to check the Stories URLs again: 

- Canonical URLs are now correct
- Poster-portrait are now in the right dimensions and orientation
- Images have now the correct specified ratios
- We added the AMP CDN script to all our Stories

On top of that, we are implementing structured data, it should hit production very soon. 

Regarding keeping the videos below 4mb, we are working on some ideas, however we saw on other Story Creation Tools listed on Google page that they don't always keep the videos 4mb as well, depending on the original size, so we guessed that this point is slightly less priority to appear on the list. 

Looking forward to hearing your feedback, hopefully now the requirements are met. 

Thanks

**Comment by sdenaro** [comment]
I will have time to work on this on Friday. I will give you an update after, thanks.

**Comment by sdenaro** [comment]
Story work was pushed back a bit, I will block off time to finish this in by the end of next week.

**Comment by sdenaro** [comment]
I re-ran on this list

- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/12b531b5-2519-4b03-b3e8-6df3d96211cd/Amp/b344a396-680c-49bf-bf1f-5099e8fb7eb8.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/839d9e7f-e614-4b73-abfb-c82a71697f3a/Amp/c936b6e2-d64e-4ccb-a9b2-7c5e91084fc4.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/201290e9-5121-4211-879f-b5e327fd31e9/Amp/b6438e54-d218-4ae4-8b3b-811a57b1290e.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/9c13b054-26fe-4326-a380-8c33373539f7/Amp/26af597f-893e-4367-9ad3-fdf07ecf82da.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/6b66386d-0cb0-4e21-adcc-023ec28ab6a7/Amp/9497c4ea-afe9-4cd8-99e2-e8769872021e.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/f2f189b9-5268-494f-832f-cce6dac78241/Amp/afc92f65-967b-4d97-b2df-8cfb48f61d1a.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/66c48d2c-317c-470c-90d7-b49ce973ccfb/Amp/0a4d37ef-6e6f-4b5d-b4db-d81fdd9d33dd.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/33ae0a1d-504d-48e5-a951-76d5958601a7/Amp/e250c91d-9583-4f99-8f15-a8eca21b697a.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/a9e698d9-5ee8-4e13-bc97-c1272199208f/Amp/5c3f3bb2-6e5a-43fe-884f-96bc6ac31e7e.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/3f06e5c6-8226-4380-9af7-6957d92e46b7/Amp/ae81e474-4f0e-47fd-81c9-61dc1183c125.html

And I am still seeing some issues.

1.  Canonical links do not always match. 

For: https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/9c13b054-26fe-4326-a380-8c33373539f7/Amp/26af597f-893e-4367-9ad3-fdf07ecf82da.html

  actual: https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b9946bebb3800136ecd2d/Stories/9c13b054-26fe-4326-a380-8c33373539f7/Amp/26af597f-893e-4367-9ad3-fdf07ecf82da.html, 

expected: https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/9c13b054-26fe-4326-a380-8c33373539f7/Amp/26af597f-893e-4367-9ad3-fdf07ecf82da.html

2. The portrait ratio should be 3/4 (0.75), the links are using 720/1280 which is .5625. 960/1280 would be 3/4. 

3. For the video issue, can you see if this guidance works for you?

https://blog.amp.dev/2021/08/24/better-video-performance-in-web-stories/

Thanks

**Comment by Zazuapp** [comment]
Hi @sdenaro 

Some of the Stories in the list were not updated with last changes, I just updated the list with new Stories (content is same but they are brand new Stories containing the fixes you pointed out). 

- Ratios are correct for poster images 
- Canonical links are matching
- We added the Google cache for videos 

Looking forward for the feedback!

**Comment by sdenaro** [comment]
I think I have time next week. Great to hear you're using cache for the video content. 

Thanks

**Comment by Zazuapp** [comment]
Hey @sdenaro 
When can we expect some feedback on this side? 

Thanks

**Comment by sdenaro** [comment]
I am back in the office and can loop back now.

**Comment by sdenaro** [comment]
Were the poster images updated? It looks like they are still 720/1280 which isn't the correct ratio.

I also found this in the dev tools console:

```
https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b998abebb3800136ecd34/Stories/3f06e5c6-8226-4380-9af7-6957d92e46b7/Amp/ae81e474-4f0e-47fd-81c9-61dc1183c125.html:3:4516 

The text inside tag 'style amp-custom' contains 'CSS i-amphtml- name prefix', which is disallowed. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#stylesheets)
```

**Comment by Zazuapp** [comment]
Hey @sdenaro 

It seems that the list of Stories that you checked yesterday is still the old one from your comment. Those Stories are broken, we will delete them.
The updated list is the one in the original comment, I updated all the links last time. 
For the sake of clarity, here is the updated list again: 

- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/cfee6bbe-1cbc-4264-a3ff-294621527924/Amp/56abeadb-ec65-48d0-954d-67974da9f728.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/84910072-e9bb-4cfb-8da7-03233380a7ca/Amp/2ef867b3-35db-445d-bcce-4da27e18f04c.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/b1ce3a64-3fcd-4f0e-a558-f959f8b26ddf/Amp/d76af626-93c5-4196-a21d-0724b3cf48c0.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/3bc0a049-d305-43aa-870f-e5bc6412c03b/Amp/8e29d6fc-316f-4450-a38d-5d20285ef0bc.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/16da2220-5925-4ff4-a3c4-dd869ac2b46e/Amp/75a671f3-ddab-4ac3-95c4-f5be4c1e667f.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/61aea12d-c79a-4fe5-ab6e-cc44d5a1c856/Amp/3dea61a7-b391-45ed-98c2-4e9c31204082.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/783e2513-ffd5-4d7f-afd7-c181460bcf68/Amp/e8abc703-c674-4bae-b93b-63bfff70b40b.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/34248313-0d91-4b64-a12f-ebfb566b6ab2/Amp/7d1957ae-45a4-4a56-8923-e3b3203af6b6.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/0b7ae7cc-9943-40b7-b01c-ba035e51fb63/Amp/d6bc8483-298c-4527-8bc9-458d72c9a4c3.html
- https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/480cb5b6-2cb5-4730-82f4-31e7c732f371/Amp/b3c5bb41-9f20-4547-9725-0ba19282d05f.html

Looking forward to your feedback

**Comment by sdenaro** [comment]
I'll have time this week

**Comment by sdenaro** [comment]
I am see this same issue here, which is what I was expecting. I am going to move this along in parallel with getting the issue resolved  https://github.com/ampproject/amp-toolbox/issues/1311

**Comment by sdenaro** [comment]
I need you to update this story so the thumbnails meet the published minimums. 

```
Portrait: 640px x 853px
Landscape: 853px x 640px
Square: 640px x 640px

```

This story:

https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/480cb5b6-2cb5-4730-82f4-31e7c732f371/Amp/b3c5bb41-9f20-4547-9725-0ba19282d05f.html

Has 300px by 400px, 400px by 300px and 400px by 400px.

The tooling should have some kind of warning about this. You don't want your users publishing stories that have blurry images in discovery or in search results. 

Thanks

**Comment by Zazuapp** [comment]
@sdenaro We just updated the thumbnail for the mentioned Story. Make sure to delete cache when you check so you have the updated version of the Story. 

We will think of adding a warning on our tool, that's a good point, thanks!

Is there anything else we can do to resolve this ticket?

Thanks

**Comment by Zazuapp** [comment]
Hi @sdenaro 

Thanks for the feedback. We are really looking forward to appearing on the Google tools list! 

We saw the list of tools in the stories.google page is not listed alphabetically nor by the time of joining, so we would like to know how we can have our software listed in a higher position among the others? We work with big clients in the European ecosystem and put the user experience and the software interface front and center of every decision we make - which is also why we won the prestigious Red Dot Design Award in 2021 for best User Interface - and we are convinced that we are one of the most user-friendly web story tools out there. 

Best

**Comment by sdenaro** [comment]
I closed https://github.com/ampproject/amp-toolbox/issues/1311 and looped back to re-run with clean environment 

Using these stories:

1. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/cfee6bbe-1cbc-4264-a3ff-294621527924/Amp/56abeadb-ec65-48d0-954d-67974da9f728.html
2. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/84910072-e9bb-4cfb-8da7-03233380a7ca/Amp/2ef867b3-35db-445d-bcce-4da27e18f04c.html
3. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/b1ce3a64-3fcd-4f0e-a558-f959f8b26ddf/Amp/d76af626-93c5-4196-a21d-0724b3cf48c0.html
4. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/3bc0a049-d305-43aa-870f-e5bc6412c03b/Amp/8e29d6fc-316f-4450-a38d-5d20285ef0bc.html
5. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/16da2220-5925-4ff4-a3c4-dd869ac2b46e/Amp/75a671f3-ddab-4ac3-95c4-f5be4c1e667f.html
6. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/61aea12d-c79a-4fe5-ab6e-cc44d5a1c856/Amp/3dea61a7-b391-45ed-98c2-4e9c31204082.html
7. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/783e2513-ffd5-4d7f-afd7-c181460bcf68/Amp/e8abc703-c674-4bae-b93b-63bfff70b40b.html
8. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/34248313-0d91-4b64-a12f-ebfb566b6ab2/Amp/7d1957ae-45a4-4a56-8923-e3b3203af6b6.html
9. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/0b7ae7cc-9943-40b7-b01c-ba035e51fb63/Amp/d6bc8483-298c-4527-8bc9-458d72c9a4c3.html
10. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/480cb5b6-2cb5-4730-82f4-31e7c732f371/Amp/b3c5bb41-9f20-4547-9725-0ba19282d05f.html

I am still seeing the issue with images that are not sized correctly and/or do not have the correct image rations

1. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/cfee6bbe-1cbc-4264-a3ff-294621527924/Amp/56abeadb-ec65-48d0-954d-67974da9f728.html

The poster-portrait-src should be 640x853px or larger

This image https://media.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/cfee6bbe-1cbc-4264-a3ff-294621527924/SEO/db42ad86-8b5c-49d5-b908-03e5e6a65df8.webp

is 500 × 667 which is too small. 

1. https://stories.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/b1ce3a64-3fcd-4f0e-a558-f959f8b26ddf/Amp/d76af626-93c5-4196-a21d-0724b3cf48c0.html

The poster-landscape-src that should be 853x640px or larger

This image https://media.zazuapp.co/0f84a40d-ed07-492e-a32a-d8dafee676bf/Users/619b999dbebb3800136ecd3b/Stories/b1ce3a64-3fcd-4f0e-a558-f959f8b26ddf/SEO/4a647911-b56e-4a76-83b1-8c862e2a23ba.webp 

is 720 × 540 which is too small.

This repeats in a few other stories.

I would suggest you add checks from the UI to prevent users from using images that are too small. 

Thanks

**Comment by Zazuapp** [comment]
Hello @sdenaro 

Thank you for the feedback. Our UI checks for poster images are being released soon as you suggested. 

In the meantime the Stories are updated with correct image sizes and ratios. Indeed some Stories were still containing smaller images than recommended minimum size. Feel free to run the tests on the same list. 

Thanks

**Comment by Zazuapp** [comment]
Hi, @sdenaro 

Did you have time to check the list again? Is there anything we can do to speed up the process, as it's been 4 months already that this issue is opened?

Looking forward to hear from you,

Gaetan from Zazu

**Comment by sdenaro** [comment]
Gaetan,

I will be able to loop back to this next week. 

I do need to provide 10 stories that meet the requirements when I put in the submission and create the pull request. Can you make sure you have ten urls with the correct image sizes?

Thanks

**Comment by Zazuapp** [comment]
@sdenaro 

The latest URLs have the correct poster images size ratios and minimum sizes. 
Looking forward to your feedback!

Gaetan

**Comment by sdenaro** [comment]
I am confirming the image issues have been resolved. There should not be any other issues. I can create a PR after I update everything internally.

**Comment by powerivq** [comment]
Completed.
