### ISSUE TITLE
Pendular.io

### ISSUE THREAD

**Issue by jjccc** [ampproject/amp.dev#6243]
### Story creation resource name

Pendular

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [x] CMS
- [x] Platform
- [ ] Other

### URL

https://pendular.io/

### Image

![pendular_amp](https://user-images.githubusercontent.com/4615820/144458080-c3a1c71e-8f09-4e5b-829f-96ddd6a67d7f.png)

### Description

Allows publishers to automate the creation of high-quality stories focused on sports content.

### List of Stories

https://engine.pendular.io/uploads/amp/415/cad-atl-1638446823.html
https://engine.pendular.io/uploads/amp/403/rmb-bet-1638449254.html
https://engine.pendular.io/uploads/amp/415/petground-1638454826.html
https://engine.pendular.io/uploads/amp/415/bagles-1638457354.html
https://engine.pendular.io/uploads/amp/415/monedero-1638459550.html
https://engine.pendular.io/uploads/amp/415/peinado-de-los-90-1638446664.html
https://engine.pendular.io/uploads/amp/415/press-conference-1638448569.html
https://engine.pendular.io/uploads/amp/415/horoscopo-1638450221.html
https://engine.pendular.io/uploads/amp/415/cheesecake-1638456127.html
https://engine.pendular.io/uploads/amp/415/atp-finals-1638458988.html

**Comment by sdenaro** [comment]
Confirming I am taking this one.

**Comment by sdenaro** [comment]
There are some issues

1)  Thumbnails:

	Thumbnails are either the wrong size or have the wrong dimensions. As examples:

a) In this one, the image ratio is broken. It should be 3/4 or 4/3 for portrait or landscape, 1/1 for square. This ratio is about .56  

	https://engine.pendular.io/uploads/amp/415/cad-atl-1638446823.html

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"/uploads/plugin_slot/preroll/61715/mini_magick20211202-861-vpg6kz.jpg","width":1125,"height":2000,"mime":"image/jpeg"}] failed [isPortrait]

b) https://engine.pendular.io/uploads/amp/403/rmb-bet-1638449254.html

This image is too small

storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"/uploads/plugin_slot/preroll/60059/mini_magick20211202-16412-1vpm93h.png","width":255,"height":452,"mime":"image/png"}] failed [isPortrait, isAtLeast696x928]

c) https://engine.pendular.io/uploads/amp/415/peinado-de-los-90-1638446664.html

This ratio is also off, and too small.
	
storymetadatathumbnailsareok (FAIL)

  [poster-portrait-src = {"url":"/uploads/plugin_slot/preroll/61717/screenshot_154643_1638445361.jpg","width":405,"height":720,"mime":"image/jpeg"}] failed [isPortrait, isAtLeast696x928]

2) Other images are not in the correct ratios. See:

  [https://engine.pendular.io/uploads/tmp/skins/08e004c97171cee9.png]: actual ratio [800/300 = 2.66] does not match specified [801/261 = 3.06]

3) There are stories with videos that are too large. Videos need to be under 4mb.

	https://engine.pendular.io/uploads/amp/415/petground-1638454826.html

  videos over 4MB: [https://engine.pendular.io/uploads/card_image_box/image/123371/axed_173819_000.mp4,https://engine.pendular.io/uploads/card_image_box/image/123369/axed_173819_000.mp4,https://engine.pendular.io/uploads/card_image_box/image/123370/axed_173819_000.mp4,https://engine.pendular.io/uploads/card_image_box/image/123374/axed_173818_000.mp4,https://engine.pendular.io/uploads/card_image_box/image/123372/axed_173818_000.mp4,https://engine.pendular.io/uploads/card_image_box/image/123373/axed_173818_000.mp4,https://engine.pendular.io/uploads/card_image_box/image/123386/axed_173817_000.mp4,https://engine.pendular.io/uploads/card_image_box/image/123384/axed_173817_000.mp4,https://engine.pendular.io/uploads/card_image_box/image/123385/axed_173817_000.mp4]

4) And some minor issues""

a)  <link href=https://cdn.ampproject.org/v0.js rel=preload> is missing

This can improve performance. It's a warning, not an error. I would change this to use preload. 

5) Structured data:

	 @type is not 'Article' or 'NewsArticle' or 'ReportageNewsArticle'

This can help with surfacing the right articles to the right users.

https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data

6) The canonical URLs should be correct. When this isn't working, you'll get errors in the search console.

linkrelcanonicalisok (FAIL)

  actual:
https://engine.pendular.io/uploads/amp/415/horoscopo-1638450220.html, expected: https://engine.pendular.io/uploads/amp/415/horoscopo-1638450221.html

**Comment by jjccc** [comment]
We have fixed the issues and  we have the next doubts: 
- structured data are mandatory or it is only a recommendation?
- poster have been generated following the minimum sizes that appears in AMP documentation:
     Portrait: 640px x 853px
     Landscape: 853px x 640px
     Square: 640px x 640px
Are these sizes right?

These are the new amp stories pages. URLs have changed because we use timestamps during the generation and it was the cause of bug 6 with the canonical URLs.

https://engine.pendular.io/uploads/amp/329/monedero-1638458361.html
https://engine.pendular.io/uploads/amp/329/atp-finals-1638457907.html
https://engine.pendular.io/uploads/amp/329/bagles-1638456637.html
https://engine.pendular.io/uploads/amp/329/cheesecake-1638454666.html
https://engine.pendular.io/uploads/amp/329/petground-1638449839.html
https://engine.pendular.io/uploads/amp/329/horoscopo-1638449597.html
https://engine.pendular.io/uploads/amp/329/press-conference-1638447321.html
https://engine.pendular.io/uploads/amp/422/peinado-de-los-90-1638445341.html
https://engine.pendular.io/uploads/amp/415/cad-atl-1638444982.html
https://engine.pendular.io/uploads/amp/403/rmb-bet-1637779695.html

**Comment by sdenaro** [comment]
Structured data is a strong recommendation.

I will confirm the changes when I am back in Jan.

Thanks

**Comment by jjccc** [comment]
Thanks.
When you make the revision, please, change the last URL story of the previous list

https://engine.pendular.io/uploads/amp/403/rmb-bet-1637779695.html

by this one:

https://engine.pendular.io/uploads/amp/329/rmb-bet-1637779695.html

Thanks.

**Comment by sdenaro** [comment]
I will have time to confirm the changes this week and will update you. Thanks.

**Comment by sdenaro** [comment]
Story work was pushed back, I need to block off time to complete this by the end of next week. Sorry about the delay.

**Comment by sdenaro** [comment]
Looks like another issue. Our tooling and the documentation disagree on min image sizes. I'm going to investigate and see why this is.

storymetadatathumbnailsareok (FAIL)

failed [isAtLeast696x928]

storymetadatathumbnailsareok (FAIL)

failed [isAtLeast928x928]

storymetadatathumbnailsareok (FAIL)

 failed [isAtLeast928x696]

Thanks for waiting patiently as we sort this out.

**Comment by jjccc** [comment]
Hi, any updates on this issue? Thank!

**Comment by sdenaro** [comment]
I am back in the office and following up.

**Comment by sdenaro** [comment]
I'm going to file a bug against the linter. Everything else looks good to go.

**Comment by jjccc** [comment]
Thanks! We will impatiently wait for the fix.

**Comment by sdenaro** [comment]
I'm going to move forward with listing this while I wait for word on a fix.

**Comment by sdenaro** [comment]
@jjccc  I'll escalate internally and see what the hold up is.

**Comment by jjccc** [comment]
Can the category and the screenshot of our product be updated after it is listed in amp.dev tools page?

Thanks!

**Comment by sdenaro** [comment]
update the issue with the new image and product information. Unless there is some issue with changing it, I can put in another PR some time next week when I have time to work on open source again. 

thanks.

**Comment by powerivq** [comment]
Already completed.
