### ISSUE TITLE
Google GitHub actions need to be updated

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#6302]
See: https://github.com/ampproject/amp.dev/runs/4678421175?check_suite_focus=true#step:6:19

Authentication is now handled by a separate action. This blocks build.

**Comment by sebastianbenz** [comment]
Afaik, this isn't blocking the build yet (but the service keys expired).

**Comment by sebastianbenz** [comment]
(and thanks for investigationg :-) )

**Comment by matthiasrohmer** [comment]
You're welcome! I can also take care of updating the other things tomorrow now the keys are valid again 🙂
