### ISSUE TITLE
Google Cloud secrets need to be updated

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#6303]
The key for staging seems to be no longer valid: https://github.com/ampproject/amp.dev/runs/4615877272?check_suite_focus=true#step:10:11 This blocks staging builds.

It could be that auth tokens need to be refreshed at all: https://github.com/ampproject/amp.dev/runs/5048813806?check_suite_focus=true#step:6:14 This affects production builds.

**Comment by sebastianbenz** [comment]
@patrickkettner has updated the keys. They should work again.
