### ISSUE TITLE
CSP Errors when loading Page Experience

### ISSUE THREAD

**Issue by samouri** [ampproject/amp.dev#6317]
**summary**

I am getting a CSP error when loading the Page Experience report tool
Nothing seems to be broken though.

```
[Report Only] Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src blob: 'unsafe-inline' https://cdn.ampproject.org/v0.js https://cdn.ampproject.org/v0.mjs https://cdn.ampproject.org/v0/ https://cdn.ampproject.org/sw/ https://cdn.ampproject.org/viewer/ https://cdn.ampproject.org/rtv/ https://www.googletagmanager.com/gtag/js https://playground.amp.dev/ https://preview.amp.dev/ https://go.amp.dev/ https://log.amp.dev/".
```
![Screen Shot 2022-02-22 at 1 24 56 PM](https://user-images.githubusercontent.com/4656974/155195277-288cacd7-3c5c-4d6a-a1ca-64aeeab30045.png)

**reproduction steps**
1. Go to: https://amp.dev/page-experience/
2. Open up Dev Console

**Comment by patrickkettner** [comment]
Thanks for reporting!

These are Report-Only, so this is working as intended. Not sure if we are
prioritizing ratcheting down the strictness
-- 
patrick
