### ISSUE TITLE
WebStoriesBuilder

### ISSUE THREAD

**Issue by webstoriesbuilder** [ampproject/amp.dev#6363]
### Story creation resource name

Web Stories Builder

### Type

Use [x] to mark a selection:

- [ x] Story Creation Tool
- [ x] CMS
- [ x] Platform
- [ ] Other

### URL

https://webstoriesbuilder.com/

### Image

![WebStoriesBuilderBanner](https://user-images.githubusercontent.com/104660857/166084834-0008453c-9526-47cc-b37c-087795a71712.png)

### Description

We helps publishers, marketers & designers to build, distribute & monetize visual, engaging Web Stories, faster. Without coding.

### List of Stories

https://app.webstoriesbuilder.com/margot-robbie-starring-barbie-taking-on-christopher-nolan-oppenheimer
https://app.webstoriesbuilder.com/conversations-with-friends-season-1-is-releasing-in-may
https://app.webstoriesbuilder.com/the-batman-2-announced-at-cinemacon
https://app.webstoriesbuilder.com/megan-fox-and-fiance-machine-gun-kelly
https://app.webstoriesbuilder.com/ginny-and-georgia-season-2
https://theubj.com/stories/boys-season-3-trailer-reveal-jensen-ackles-as-soldier-boy
https://theubj.com/stories/tesla-shares-were-sold-for-about-4-billion-by-elon-musk
https://theubj.com/stories/james-cordon-set-to-leave-the-late-late-show
https://theubj.com/stories/last-moon-knight-episode-to-be-shortest
https://theubj.com/stories/anndrew-garfield-pause-his-movie-career

**Comment by sebastianbenz** [comment]
@shishirm what's the status of this?

**Comment by powerivq** [comment]
Not accessible. Closing for now.
