### ISSUE TITLE
Enable option to users upload your stories

### ISSUE THREAD

**Issue by Felipemauah** [ampproject/amp.dev#6364]
Hello! Thanks for the amazing job inthis plugin (WP Stories).

My request is about a new feature: Enable option from the users upload yours stories like instagram, behance or facebook.

In my business (content community+ marketplace), my goal is supply a tools to my cliente sell your product and publish your content.

This option is a very important, not only to me, but for the many and many users. I know that feature is not simple to develop, but if this feature made it into your roadmap it would be fantastic, as we would know that there would soon be a possibility for us to provide this feature to our customers.

Thank you so much again for the beautiful work.

**Comment by powerivq** [comment]
Hi @Felipemauah 

We understand that it would be great to have that. There are a lot of platforms that can help you create an AMP story and host it on their platform. AMP is an open standard and does not plan on hosting them on AMP like a social media platform.

Thanks!
