### ISSUE TITLE
[AMP-pages] add instructions on how to make your own AMP component

### ISSUE THREAD

**Issue by alexandr-kazakov** [ampproject/amp.dev#6367]
Previously, the site had a step-by-step AMP instruction about how to create your own component. Screenshots:

<img width="1126" alt="chrome_bdnX90T5w4" src="https://user-images.githubusercontent.com/20513262/166974038-817d58c8-54cc-4d80-a4fd-dfb849724f2d.png">
<img width="1353" alt="Upwork_2p9JdKOEpm" src="https://user-images.githubusercontent.com/20513262/166974146-c1073827-99c6-472c-9ba0-e88a187e9767.png">
But now I noticed that these pages are no longer available.             

I have a project related to a chat for which I would like to make an AMP component like this: https://amp.dev/documentation/components/amp-playbuzz/?format=websites but I don't find any relevant information on this. 

Maybe return the old instruction or add a new one?

**Comment by sebastianbenz** [comment]
This code lab was never hosted on amp.dev. You can find it here: https://kiosk-dot-codelabs-site.appspot.com/codelabs/creating-your-first-amp-component/index.html?index=..%2F..index#0
