### ISSUE TITLE
Pixi : Unable to scan any website 

### ISSUE THREAD

**Issue by milindmore22** [ampproject/amp.dev#6368]
## 🐛 Bug Report
The Page Experience is not able to check/scan any website 

### Current behavior
It shows an error saying the **URL is invalid.**

When I checked the browser console the response for `https://amp.dev/page-experience/api/lint?url=https%3A%2F%2Famp-wp.org%2F` is `error` 
```
This URL is invalid.
We were unable to load the page you requested. Make sure you are testing the correct URL and that the server is responding properly.
```

![image](https://user-images.githubusercontent.com/1132541/167132148-d2b5222b-63fd-4441-b72d-c771e19af24b.png)

Please also provide:
- Page link: https://amp.dev/page-experience/

https://user-images.githubusercontent.com/1132541/167133024-5c201051-525e-499c-bd2d-08395e4a644a.mov

### Expected behavior/code
It should analyze the site.

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. Step 1 Visit https://amp.dev/page-experience/
2. Step 2 enter any AMP URL : https://amp-wp.org/
3. Step 3 See error

- What browser are you using? Chrome
- What O/S are you using? Mac OS Catalina

**Comment by sebastianbenz** [comment]
Thanks for reporting. I've updated dependencies and re-deployed our cloud functions. Seems to work now.

**Comment by milindmore22** [comment]
Awesome, thank you for the quick response and the fix 👏🏼

**Comment by milindmore22** [comment]
@sebastianbenz Sorry to bother you, but the issue seems to be back again, can you please check.
