### ISSUE TITLE
New Story creation tool Request = snackeet.com

### ISSUE THREAD

**Issue by cikguvanda** [ampproject/amp.dev#6395]
### Story creation resource name

< SNACKEET >

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [ ] Platform
- [ ] Other

### URL

< https://www.snackeet.com/ >

### Image

< ![Editor___Snackeet](https://user-images.githubusercontent.com/108184359/175858916-9b2e61fa-0375-4e1b-b6c4-d68f577b2ad0.png)>
![Editor___Snackeet](https://user-images.githubusercontent.com/108184359/175858916-9b2e61fa-0375-4e1b-b6c4-d68f577b2ad0.png)

### Description

< Snackeet is a web story builder that lets you design interactive landing pages to engage your audience, collect leads, and launch surveys.>

### List of Stories

< Please list 10 Web Stories across a diverse set of topics/treatments that each meet the following criteria

* Minimum of 7 pages
* At least 4 images
* At least 2 videos
* At least four pages with some text 

quizzes and surveys
https://snkt.io/627d0f87ad9776e63b5887ab
https://snkt.io/627d11a4ad9776e63b588b3f
https://snkt.io/personalityquiz2
https://snkt.io/justaquiz

dynamic digital experience
https://go.snackeet.com/60b8eab7dbaf323f64abb20c
https://snkt.io/62b933778e7260f0fb776346

Lead-Gen
https://snkt.io/627d2651ad9776e63b58f284
https://snkt.io/savemoney1

Customer Feedback
https://snkt.io/FEEDBACK

Engagement
https://snkt.io/engagement

end>

**Comment by Milka974** [comment]
This request is not valid and the stories examples here are not AMP. This request should be closed. 

Snackeet's Team has submitted a new valid request.
