### ISSUE TITLE
 Request to Add an Email-Platform Sendsay

### ISSUE THREAD

**Issue by KatyaKyaro** [ampproject/amp.dev#6470]
### 1. Resource name
Sendsay

### 2. Relevant format(s)

- [ ] websites
- [ ] stories
- [ ] ads
- [x] email

### 3. Resource type

- [ ] editor
- [x] service provider
- [ ] developer tool
- [ ] content platform
- [ ] CMS
- [ ] ads
- [ ] audio/video
- [ ] analytics vendor

### 4. Destination
1. [amp.dev/support/faq/platform-and-vendor-partners](https://amp.dev/support/faq/platform-and-vendor-partners)
2. [amp.dev/documentation/tools](https://amp.dev/documentation/tools)
3. [x] [amp.dev/support/faq/email-support] (https://amp.dev/support/faq/email-support)

#### 4.1 If you chose 1 in Step 4:
Please provide an image (min. 800x400 pixels) to appear on the [Tools](https://amp.dev/documentation/tools) page, as well as a short description (max. 100 characters).

Images https://drive.google.com/drive/folders/1wxEWHTEjmtlNrxhNHk0xz14YC15tlJc0?usp=sharing 
Sendsay is a complex solution for marketing automation. Automate communication with customers and watch sales grow!

#### 4.2 If you chose 2 in Step 4:
Please provide link(s) to your documentation page(s) on your domain and for ads, the configuration page in the [ads/](https://github.com/ampproject/amphtml/tree/main/ads) folder of the `amphtml` repository.

**Comment by KatyaKyaro** [comment]
Hello! When will my application be reviewed?

**Comment by sebastianbenz** [comment]
@patrickkettner

**Comment by KatyaKyaro** [comment]
Hello! When will my application be reviewed?

**Comment by patrickkettner** [comment]
Hi @KatyaKyaro! What is the link you want `Sendsay` to point to?

**Comment by KatyaKyaro** [comment]
> Hi @KatyaKyaro! What is the link you want `Sendsay` to point to?

Hi! To our website https://sendsay.com/

**Comment by KatyaKyaro** [comment]
Hello! When will my application be reviewed?

**Comment by patrickkettner** [comment]
hello!
The site is currently going  through a backend migration. Your contact will be added once it has been completed.

**Comment by KatyaKyaro** [comment]
Okay

**Comment by patrickkettner** [comment]
[this is now live](https://amp.dev/documentation/tools/email/)

**Comment by KatyaKyaro** [comment]
Hello! Thank you very much for posting us! But can, please, you put the link with our English version in ? https://sendsay.com/

**Comment by patrickkettner** [comment]
this has been done
