### ISSUE TITLE
Add Snackeet.com as Story Creation Tool 

### ISSUE THREAD

**Issue by Milka974** [ampproject/amp.dev#6477]
### Story creation resource name

Snackeet - Webstories

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [ ] CMS
- [ ] Platform
- [ ] Other

### URL

Website : https://www.snackeet.com/?utm_source=google_listing
Platform : https://app.snackeet.com/

### Image

https://user-images.githubusercontent.com/115029368/195884726-5855ad8d-712b-45e4-a2b4-96ec9a57eb18.png

### Description

Snackeet is the only tool you will ever need to build outstanding Webstories and INTERACTIVE DIGITAL EXPERIENCES. 

### List of Stories

 - https://snkt.io/63495a3d9fa0a4c6a0a97dee
 - https://snkt.io/63492966bf70b86d23f8eed8
 - https://snkt.io/63491ffdbf70b86d23f8cd89
 - https://snkt.io/6344237e97944cae16517211
 - https://snkt.io/6341e80197944cae164ea95d
 - https://snkt.io/6341df2697944cae164ea0c8
 - https://snkt.io/634164ff97944cae164df701
 - https://snkt.io/6341447d97944cae164dc77c
 - https://snkt.io/6340519a97944cae164cbda2
 - https://snkt.io/recrutement-startup

**Comment by Milka974** [comment]
Hey Guys, 

Any update on this 

Thanks

**Comment by Milka974** [comment]
Hey 👋
When will our application be reviewed please?
Is there anything missing?
@sebastianbenz  @patrickkettner  @shishirm  @sdenaro  @matthiasrohmer  @newmuis 
Thanks

**Comment by patrickkettner** [comment]
The site is going through an infrastructure change, your information will
be added once that has completed --
patrick

**Comment by Milka974** [comment]
@patrickkettner Great, thanks for your answer 🙏

**Comment by patrickkettner** [comment]
this is now live

**Comment by Milka974** [comment]
Hey @patrickkettner this is great thanks. However I noticed that we are not under the right section. 
We currently are under **"Developer Tools"** but we belong to **"Creation & Design"**
Would you be able to modify it ? 
Thanks 🙏

**Comment by patrickkettner** [comment]
will do

**Comment by patrickkettner** [comment]
this has been done
