### ISSUE TITLE
Request for update in FAQ section

### ISSUE THREAD

**Issue by sudha-CM** [ampproject/amp.dev#6539]
### Problem
Please update [Pepipost](https://pepipost.com/) to 'Netcore Cloud' in the following doc. Pepipost was a subsidiary, it has been merged into the parent company - Netcore Cloud. 

### Location
https://amp.dev/support/faq/email-support (Under Supported Email Service Providers section)

### Content type
FAQ

### Information architecture (optional)
N/A

**Comment by patrickkettner** [comment]
[this is now live](https://amp.dev/support/faq/email-support)
