### ISSUE TITLE
Content Found on accident... Please help with some sort of clarity

### ISSUE THREAD

**Issue by AwesomeFaith20** [ampproject/amp.dev#6551]
### Synopsis
A clear and concise description of the content you will be contributing.

### Content type

- [ ] Guide
- [ ] Tutorial
- [x] Example
- [x] Translation
- [x] Other (please specify)

### Process
Read the [contributing guide](https://amp.dev/documentation/guides-and-tutorials/contribute/contribute-documentation/?format=websites), then create a copy of [this template](https://docs.google.com/document/d/18i_lbQ-h-auYW2SwbWRuuu2_xhtU5XrjXlcCtj0sNeY/edit?usp=sharing) and fill in the proposal and outline sections. When you’ve finished, add the link to this issue and check the box for step one. A member of the AMP team will assign the ticket to themselves and work as your reviewer through the remaining steps. Thanks for contributing to AMP! 

- [ ] 1. Proposal created: `<link to proposal>`.
- [ ] 2. Proposal approved.
- [ ] 3. Draft complete.
- [ ] 4. Draft approved.
- [ ] 5. Pull request submitted.
- [ ] 6. Pull request approved!

**Comment by AwesomeFaith20** [comment]
Delivered-To: leeanncoleman72@gmail.com
Received: by 2002:a59:994f:0:b0:323:b7b0:4378 with SMTP id k15csp862912vqr;
        Thu, 3 Nov 2022 13:04:45 -0700 (PDT)
X-Received: by 2002:a05:622a:5d0:b0:3a5:3979:6292 with SMTP id d16-20020a05622a05d000b003a539796292mr13310531qtb.108.1667505885055;
        Thu, 03 Nov 2022 13:04:45 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1667505885; cv=none;
        d=google.com; s=arc-20160816;b=N+GUAYDaiwj0SQcc1wbx4TyII9BBq/irNGHvltLED4jh+SqkylIFwYRqgmJZ4JtEF8
         TqMe6OZzfj+y9Sv3a7G6fVz5RKLXzCUmaFI3YEE4UfqPUo4U7uUkzdQzE8/edlO6dnVh
         0GNyt51j+iiYGU0UHqETSUOPUvloZaHrQmh3lu28vjwx2EnfzbHZuhaK0TxFwQCp6q67
         +zS6QmGZnvGL3ZJavJOv/vSaxEFsk+N4Ndz6TGJHfpuCXI7sUf+vW74zy/pVB1x0gxhR
         m8iJUjJCqODipwp4UaYpNi3PbCgKt0i+pWi8P02khQxZBmu4aeDLvOFrQeODjHgoXb3W
         NR+A==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=to:from:subject:message-id:list-id:feedback-id:list-unsubscribe
         :precedence:reply-to:date:mime-version:dkim-signature;
        bh=9nC6qfgf8288U+JzV2C6prmITMYEAr/HD3TYhW8zN3Y=;
        b=ffqvRYuRMZnrdP6W2kiYbCmh3Fd3abOwiQwV5xmawZmfUkvqv/bUgYKG6+WVxEcCkQ
         EFcqXExFFXuJDhunl80ZI7Zl7a7EjgFXI7HirQWEk8lk6jCk6WKGfgfpDoTcqoB4VR0s
         Z8RO1hCpbG1nlsMC3CetPK83uq+IxycDQtvE9Ga4gAZsklli9lE40Sb7eNKlfDb3lnVR
         PygVEHnGiU1edA2gw+5m8MBQw7a3zf9gCf5M/rOClxtxSZgZNIh7QsQwIeZ31vgtZihD
         eHkbQ1aevsNxe2vJzb343BUGHgBP26tNxo+V53QS4VNWZZznWN4JT8paMioI9mCcYmuw
         hXnQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@google.com header.s=20210112 header.b=CnSPJIbI;
       spf=pass (google.com: domain of 33b5kyw4kd8sx55x2v-458v62fx55x2v.t532vvr44t52v3r4ojx3rz2.t53@scoutcamp.bounces.google.com designates 209.85.220.69 as permitted sender) smtp.mailfrom=33B5kYw4KD8sx55x2v-458v62Fx55x2v.t532vvr44t52v3r4OJx3rz2.t53@scoutcamp.bounces.google.com;
       dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=google.com
Return-Path: <33B5kYw4KD8sx55x2v-458v62Fx55x2v.t532vvr44t52v3r4OJx3rz2.t53@scoutcamp.bounces.google.com>
Received: from mail-sor-f69.google.com (mail-sor-f69.google.com. [209.85.220.69])
        by mx.google.com with SMTPS id 144-20020a370a96000000b006fa11f651b5sor624287qkk.173.2022.11.03.13.04.45
        for <leeanncoleman72@gmail.com>
        (Google Transport Security);
        Thu, 03 Nov 2022 13:04:45 -0700 (PDT)
Received-SPF: pass (google.com: domain of 33b5kyw4kd8sx55x2v-458v62fx55x2v.t532vvr44t52v3r4ojx3rz2.t53@scoutcamp.bounces.google.com designates 209.85.220.69 as permitted sender) client-ip=209.85.220.69;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@google.com header.s=20210112 header.b=CnSPJIbI;
       spf=pass (google.com: domain of 33b5kyw4kd8sx55x2v-458v62fx55x2v.t532vvr44t52v3r4ojx3rz2.t53@scoutcamp.bounces.google.com designates 209.85.220.69 as permitted sender) smtp.mailfrom=33B5kYw4KD8sx55x2v-458v62Fx55x2v.t532vvr44t52v3r4OJx3rz2.t53@scoutcamp.bounces.google.com;
       dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=google.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=google.com; s=20210112;
        h=to:from:subject:message-id:list-id:feedback-id:list-unsubscribe
         :precedence:reply-to:date:mime-version:from:to:cc:subject:date
         :message-id:reply-to;
        bh=9nC6qfgf8288U+JzV2C6prmITMYEAr/HD3TYhW8zN3Y=;
        b=CnSPJIbImuofbkrABh9mz9+i3lWP/AHR4x9r7LbVGS2WZWCKAoJaZB7xtHpdHXb9+1
         2fQSlhg9s19OCHIrfKI2WwdP6UhohoNT2FeRGnfjNmwv6pimeT5fv54AV4FaAeH7fXVh
         BRzSpMbvpFjui5ci+e2hopfQfB9DEqhqucZpQR7TERMo1+zW5jk1/CpSB3H+0q2ey8s4
         xAUyTTf1fw/tpuY8HG7H7ar5MIyRgSpRmGwGO+SW/aJHvg13+v7CwFuCK/9s7xl2B8Dc
         /RWrWP3WkSQzjyu8p7/C434PNITVgtzT5gzY0LJE2p4eaSAY7EU0I3hSJSDhRrobz1HZ
         H7sw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112;
        h=to:from:subject:message-id:list-id:feedback-id:list-unsubscribe
         :precedence:reply-to:date:mime-version:x-gm-message-state:from:to:cc
         :subject:date:message-id:reply-to;
        bh=9nC6qfgf8288U+JzV2C6prmITMYEAr/HD3TYhW8zN3Y=;
        b=uzdB8wPvngDgroX9h/VzrRnqST2jGlzaRBNTKC0rCpQy9tcx4KrKhn5MgmMoYmGAqU
         VtfaflvWsKlB

**Comment by AwesomeFaith20** [comment]
Please tell me since i have been hacked for a while am i actually communicating with the outside world at all.... Or is this some experiment or project?? Please help thanks in advance

**Comment by patrickkettner** [comment]
Hi @AwesomeFaith20 
I don't understand the question. This is a forum for posting questions about the website amp.dev - best of luck in whatever the problem is!
