### ISSUE TITLE
 Listing PubLive as one of the AMP website building CMS platforms in the tools page

### ISSUE THREAD

**Issue by harmeetpublive** [ampproject/amp.dev#6560]
### 1. Resource name
PubLive

### 2. Relevant format(s)

- [x] websites
- [ ] stories
- [ ] ads
- [ ] email

### 3. Resource type

- [ ] editor
- [ ] service provider
- [ ] developer tool
- [ ] content platform
- [x] CMS
- [ ] ads
- [ ] audio/video
- [ ] analytics vendor

### 4. Destination
1. [amp.dev/support/faq/platform-and-vendor-partners](https://amp.dev/support/faq/platform-and-vendor-partners)
2. [amp.dev/documentation/tools](https://amp.dev/documentation/tools)

#### 4.1 If you chose 1 in Step 4:
Please provide an image (min. 800x400 pixels) to appear on the [Tools](https://amp.dev/documentation/tools) page, as well as a short description (max. 100 characters).
Image: 
![1](https://user-images.githubusercontent.com/113248937/213277375-9ad7456d-61e3-489e-896a-da02cd4d209e.jpg)
Short Description: CMS for Content Creators & Publishers which creates AMP websites with automated SEO capabilites.

#### 4.2 If you chose 2 in Step 4:
Please provide link(s) to your documentation page(s) on your domain and for ads, the configuration page in the [ads/](https://github.com/ampproject/amphtml/tree/main/ads) folder of the `amphtml` repository.
Link: https://thepublive.com/

**Comment by harmeetpublive** [comment]
Hi Team,

Any updates on this?

**Comment by harmeetpublive** [comment]
Hi Team, checking in on this.

**Comment by harmeetpublive** [comment]
Hi team, thanks for the update. 
@patrickkettner @sebastianbenz I can see PubLive here [amp.dev/support/faq/platform-and-vendor-partners](https://amp.dev/support/faq/platform-and-vendor-partners) but not in the tools page as listing: [amp.dev/documentation/tools](https://amp.dev/documentation/tools).

Am I missing anything here?

**Comment by patrickkettner** [comment]
Sorry about that, that has been fixed
