### ISSUE TITLE
Amp.dev does not work on Brave browser. 

### ISSUE THREAD

**Issue by silicahd** [ampproject/amp.dev#6572]
Well the titles explains it all. When you try to go to amp.dev it will just spin and freeze up.

**Comment by patrickkettner** [comment]
Hmm. I am not sure that the title captures all the information - the site loads in Brave for me. Can you please provide more information, such as

- operating system
- mobile? desktop?
- installed extensions?
- is it happening on the homepage directly? Does it happen every page? ([here is one to try](https://amp.dev/documentation/guides-and-tutorials/start/create/) if you want a fairly simple page)

**Comment by silicahd** [comment]
This was a conflict with brave and last pass. So odd.
