### ISSUE TITLE
having troubles with integrating amp-dev into Nextjs

### ISSUE THREAD

**Issue by dhavalveera** [ampproject/amp.dev#6575]
### Current behavior
- I am trying to use the `amp.dev` in my Nextjs project, but I'm facing some difficulties to integrate such as I've Navbar for Desktop & Mobile which getting rendered based on a condition, which is not happening in Nextjs + MUI Code.
- also, I am unable to use `amp-img` tag, it's rendering in the browser but Image isn't shown on the UI
- unable to identify how to use PWA Feature of amp-dev in the Nextjs.

Please also provide:
[Codesandboxx](https://codesandbox.io/p/sandbox/frosty-cherry-duktwc?file=%2FREADME.md)

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. Step 1 to reproduce
2. Step 2 to reproduce
3. …

- What browser are you using?
- I'm using Chrome & the version is `Version 110.0.5481.177`
- What O/S are you using?
- Windows 11

**Comment by dhavalveera** [comment]
and I've created this issue because, on the Google or Internet, I am not able to find the proper documentation or anything which shows how to use the amp features in Next js, including PWA Features and many more.

**Comment by powerivq** [comment]
Hi,

This repo is for amp.dev website itself and using it for other purposes is at your own risk.
