### ISSUE TITLE
Issue: Trying to work with inline JS script in AMP email not working properly?

### ISSUE THREAD

**Issue by abhilash0694** [ampproject/amp.dev#6576]
### Current behavior
I am trying to add an amp-script tag in the body and want to call with an inline js script as mentioned below in the body. Anyone can solve help me with this? As given below code if you I had added an amp-script tag with some wrap dynamic content. Wants to translate the code below while calling below script tags.
Anyone help me how to use amp-script in amp mails design.

**Comment by patrickkettner** [comment]
Hi @abhilash0694!
Unfortunately, `amp-script` [is not supported in amp emails](https://amp.dev/documentation/components/email/amp-script)

best of luck
