### ISSUE TITLE
View demo of all templates leads to 404

### ISSUE THREAD

**Issue by vaclavHala** [ampproject/amp.dev#6625]
### Current behavior
When browsing https://amp.dev/documentation/templates/ there is option to `View Demo` in detail page of each template (e.g. https://amp.dev/documentation/templates/simple_blog -[View Demo]-> https://amp.dev/documentation/templates/preview/websites/blog/templates/blog.amp.html)
this seems to lead to a generic 404 not found page for all of the templates

Please also provide:
- Page link: https://amp.dev/documentation/templates/preview/websites/blog/templates/blog.amp.html

### Expected behavior/code
I expect to see some demo page using the template

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. Go to https://amp.dev/documentation/templates/
2. pick any template and click it to go to its details page
3. click `View Demo` link

- browser: chrome
- OS: linux

**Comment by patrickkettner** [comment]
thanks! this has been fixed
