### ISSUE TITLE
Blaash Content Led Engagement Platform

### ISSUE THREAD

**Issue by santhoshkadamat** [ampproject/amp.dev#6629]
### Story creation resource name

Blaash Content Led Engagement Platform

### Type

Use [x] to mark a selection:

- [x] Story Creation Tool
- [x] CMS
- [x] Platform
- [ ] Other

### URL

https://blaash.io

### Image

![Wide Range of Templates](https://github.com/ampproject/amp.dev/assets/134306138/a22e47d3-73a2-4072-a0ca-1119b3f5396d)

### Description

Blaash provides automated & templatized content generation for web stories, be it images or videos in a seamless & easy way. Make interactive, shoppable & engagement-led stories that convert.

### List of Stories

< Please list 10 Web Stories across a diverse set of topics/treatments that each meet the following criteria

* Minimum of 5 pages
* At least 2 images
* At least 2 videos
* At least four pages with some text >

**Comment by powerivq** [comment]
@santhoshkadamat Do you support AMP story as an output? I do not see any references so I am not sure.
