### ISSUE TITLE
Filter formats regressed and broke amp.dev output

### ISSUE THREAD

**Issue by dgilman** [ampproject/amp.dev#6650]
### Current behavior
[Take a look at amp-img](https://amp.dev/documentation/components/websites/amp-img) for websites. The header "Set multiple source files for different screen resolutions" is present but there is no content under it.

If you take a look [at the source in ampproject/amphtml](https://github.com/ampproject/amphtml/blob/main/src/builtins/amp-img/amp-img.md) you can see this section is wrapped in a `[filter formats=` directive. The code that parses the filter appears to have regressed and you aren't getting any output on any of the different format pages.

### Expected behavior/code
Content from the md is shown in the browser

### Reproduction procedure
Browse to the page

**Comment by powerivq** [comment]
Looked at the page. This is a known issue.
