### ISSUE TITLE
Is Amp webstories dying ? we are not seing significant improvements for 2 years.

### ISSUE THREAD

**Issue by Milka974** [ampproject/amp.dev#6777]
### Current behavior

It is an important question because we need to know if we must continue to invest in it for our clients. 
- Some critical bugs are still present 
- We still do not see webstories in Google search in Europe, 
- There are no new components. 
Please advise 
Thanks

**Comment by powerivq** [comment]
Hello, this repo is intended for amp.dev website bugs. Issues not relevant to the topic will be closed. Plz consult with ampproject/amphtml
