### ISSUE TITLE
amp-youtube and additional play pause buttons

### ISSUE THREAD

**Issue by ttodorov1987** [ampproject/amp.dev#6821]
### About the bug:

The amp-youtube module play and pause functionality are not working.

- Page link: https://tatkraft.wp-staging.net/?amp=1
- Screenshots: [![image](https://2create.s3.eu-west-1.amazonaws.com/uploads/a5377088e9ece6347c33dee2b37d24fb/1720102960771.png)](https://2create.s3.eu-west-1.amazonaws.com/uploads/a5377088e9ece6347c33dee2b37d24fb/1720102960771.png)

### Expected behavior/code
```
tap:amp-video-button-testimonial-1.hide, amp-video-media-testimonial-1.play
```

### Reproduction procedure:

1. Step 1 click on the Play button.
2. Step 2 the poster image close.
3. Step 3 the YouTube video is visible
4. Step 4. The video needs to play with functions:
```
amp-video-media-testimonial-1.play
```
But notheing happend.

> What browser are you using?
- Chrome.

> What O/S are you using?
- Mac Ios

**Comment by powerivq** [comment]
I tested your page on iOS Chrome and Mac Chrome. Youtube video is playing fine.

Btw, this repo is for amp.dev website issue, not for AMP itself. In the future, please go to https://github.com/ampproject/amphtml/issues to report these issues.
