### ISSUE TITLE
AMP Validator Errors Docs Improvement

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amp.dev#755]
Requested by: @Gregable 
*Leftover from Oct 2017 fixit*

## Description
Most of the AMP Validator errors link to the spec for the specific AMP component. For example:

```
The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'? 
(see https://www.ampproject.org/docs/reference/components/amp-img)
```
However, not all errors have to do with a specific AMP component, and we don’t have URLs for these errors, or the URLs we do use are not very specific. For example:

```
Tag or text which is only allowed inside the body section found outside of the body section.
```

Let’s make a section of ampproject.org that contains docs specific to error messages output by the AMP Validator. This section doesn’t need to be well-linked from the AMP documentation as we expect users to primarily find it via the validator error messages.

## Possible resolution

There are 5 documents we should add, which can improve the following errors:

### Errors missing URLs
- Body Section document:
  - Tag or text which is only allowed inside the body section found outside of the body section.
  - The tag 'BODY' appears more than once in the document.
- Meta tag document:
  - The attribute 'name' in tag 'meta name= and content=' is set to the invalid value 'X'.
  - The attribute 'http-equiv' may not appear in tag 'meta name= and content='.
- Missing extensions document:
  - The extension 'amp-X' was found on this page, but is unused. Please remove this extension.

### Errors that could use better URLs
- Custom javascript document:
  - Only AMP runtime 'script' tags are allowed, and only in the document head. Currently links to: https://www.ampproject.org/docs/reference/spec#html-tags 
  - The attribute 'onclick' may not appear in tag 'a'. Currently links to: https://www.ampproject.org/docs/reference/spec#links 
- Layouts document:
  - The implied layout 'CONTAINER' is not supported by tag 'amp-img'. Currently links to:  https://www.ampproject.org/docs/reference/components/amp-img

**Comment by matthiasrohmer** [comment]
Improvement of the validation messages is an ongoing effort over at ampproject/amphtml. Additionally, the implementation of the logging service (log.amp.dev) would be an entry point to improve documentation of those messages.
