### ISSUE TITLE
AMP Login tutorial clean up

### ISSUE THREAD

**Issue by sohanirao** [ampproject/amp.dev#841]
AMP Login tutorial needs to be cleaned up. There's no reference to a page to launch that the user can walk through. It refers to the comment section in ampbyexample, however, that page has its own explanation. Reference to any dependent technologies like AMP CORs must be mentioned too.

Specific issues:
-  https://www.ampproject.org/docs/tutorials/login_requiring/login
- found this text referring to the use of a returnURL. "Notice the usage of returnURL hidden input type" . I don't see it.

Please provide the steps to reproduce the issue: Just open the link

What browser are you using? Chrome
What O/S are you using? MAC

**Comment by bpaduch** [comment]
It's referring to the `returnURL` on the login page. So when you click **login**, the HTML on that page has the hidden input.  Sample code here: https://github.com/ampproject/amp-by-example/blob/master/static/login.html#L35

Also, reference to returnURL is here https://www.ampproject.org/docs/reference/components/amp-access#login-page.

Agree, that page needs some love.

**Comment by kul3r4** [comment]
I added a link to the page. Unfortunately adding a link to the Login page will not work as the return Url will not be present if not navigating from the comment sample.
@sohanirao feel free to send a PR with suggested improvements.
