### ISSUE TITLE
ampproject.org mixed content warning

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp.dev#858]
The AMP logo in this[ blog post](https://www.ampproject.org/latest/blog/the-total-economic-impact-of-amp-across-publishers-and-e-commerce/) is not `https` causing mixed content warning.

**Comment by bpaduch** [comment]
Happens to all [blogs](https://www.ampproject.org/latest/blog/ads-and-amp/) that use that icon.

Warning message:

```
Mixed Content: The page at 'https://www.ampproject.org/latest/blog/ads-and-amp/' 
was loaded over HTTPS, but requested an insecure image 'http://1.gravatar.com/avatar/42ecb1ea497ca9d0ffe1e406cae70e27?s=96&d=identicon&r=G'. 
This content should also be served over HTTPS.
```
