### ISSUE TITLE
ServiceWorker fails to initialize on www.ampproject.org.

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amp.dev#906]
When visiting www.ampproject.org I get this in the Chrome developer console:

workbox.js:20 Uncaught bad-revisioned-cache-list: The 'precache()' method expectsan array of revisioned urls like so: ['/example/hello.1234.txt', {path: 'hello.txt', revision: '1234'}]
createError @ workbox.js:20
precache @ workbox.js:149
(anonymous) @ service-worker.js?v2:8
log.js:162 ServiceWorker registration failed: TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed

Build I'm running is "64.0.3282.167 (Official Build) (64-bit)" on my Linux laptop (Google corp Linux).

**Comment by bpaduch** [comment]
@pbakaus - Can you look at ?

**Comment by bpaduch** [comment]
@morsssss - care to investigate?

**Comment by bpaduch** [comment]
@pbakaus or @morsssss - Any comments or progress?

**Comment by pbakaus** [comment]
haven't gotten around to look at this yet.
