### ISSUE TITLE
Add a sans-serif fallback font on amphtml.wordpress.com

### ISSUE THREAD

**Issue by niutech** [ampproject/amp.dev#934]
For now, the font on the offcial blog https://amphtml.wordpress.com is defined as `font-family: Roboto;` without any fallback font, which renders the blog in ugly default font Times New Roman whenever Roboto is not available for any reason. Instead, provide a sans-serif font fallback by defining: `font-family: Roboto, sans-serif;`

**Comment by bpaduch** [comment]
cc: @amedina

**Comment by patrickkettner** [comment]
For blog.amp.dev, this is no longer the case

![image](https://user-images.githubusercontent.com/465414/75313714-97181f80-582b-11ea-9e6a-e679d75c98ee.png)
