### ISSUE TITLE
Improve presentation of attributes for amp component docs

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amp.dev#964]
AMP component docs are stored and written in the AMPHTML repo (e.g., [amp-story](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md
) and imported and rendered in ampproject.org (e.g., [amp-story component](https://www.ampproject.org/docs/reference/components/amp-story))

Want the ability to standardize look and presentation of attributes so they are scannable.

Common aspects of attributes:
-  name
- description
- type
- required vs optional
- default value
- possible values
- code sample/snippet
- more detailed description

**Comment by matthiasrohmer** [comment]
This is an ongoing effort of @CrystalOnScript.
