### ISSUE TITLE
Improve process for including images in GH component docs

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amp.dev#965]
Developers write component docs in the AMPHTML repo, and often include images, which are also stored in the AMPHTML repo (e.g., [amp-story](https://github.com/ampproject/amphtml/tree/master/extensions/amp-story
),[ amp-date-picker](https://github.com/ampproject/amphtml/tree/master/extensions/amp-date-picker)). Want: Developers to easily document components with the ability to:

1.  Use relative URLs to images (e.g., ./img/amp-story-blah.png). Right now, relative URLs are 404s because the browser is looking for the image in the ampproject.org site. Need to somehow convert the relative URLs to fixed URLs.
2. Convert markdown image syntax so that it's valid AMP syntax for inclusion in ampproject, like this:

from 

```md
![Bookend heading component](/img/amp-story-bookend-component-heading.png)
```
to 
```html
<amp-img alt="Bookend heading component"
    layout="fixed"
    width="386" height="123" 
    src="https://github.com/ampproject/amphtml/raw/master/extensions/amp-story/img/amp-story-bookend-component-heading.png" >
  <noscript>
    <img alt="Bookend heading component" src="img/amp-story-bookend-component-heading.png" />
  </noscript>
</amp-img>
```

Note: Would have to know image dimensions.

**Comment by sebastianbenz** [comment]
Fixed on amp.dev
