### ISSUE TITLE
500 value error:  service-worker.js error - expected only letters

### ISSUE THREAD

**Issue by ghost** [ampproject/amp.dev#973]
When running "grow run", I get the following error in the Terminal window while browsing the local instance:

`500: / service-worker.js - expected only letters, got 'service-worker'`

![service-worker-error](https://user-images.githubusercontent.com/1012254/40726614-16675734-63f4-11e8-94ca-267d1118481d.png)

O/S: Mac OS + Linux
Grow version: 5.0

**Comment by bpaduch** [comment]
Does not occur with Grow 4.5.

**Comment by bpaduch** [comment]
@Zoramite - Do you have any insight as to why this is occuring for Grow 5.0?

**Comment by Zoramite** [comment]
Hi @bpaduch 

This is something specific to how we are currently handling routing with the `grow run`. I've opened [an issue](https://github.com/grow/grow/issues/777) to get it fixed.

Basically the routing is having trouble deciding between `/{locale}/*` and the static serving at `/*` and defaults to thinking it is a locale instead of something from the static configuration.

**Comment by bpaduch** [comment]
@Zoramite - thanks!

**Comment by Zoramite** [comment]
This should be fixed with the latest `0.5.1` version of grow.

**Comment by bpaduch** [comment]
Hi @Zoramite - I'm getting different errors now with Grow 0.5.1 for a translated file.

Steps:

1. Fetch and test translation file in this [PR](https://github.com/ampproject/docs/pull/989)  -- `git fetch origin pull/989/head:trans-pt`.
2. `git checkout trans-pt`
3. `grow run`
4. In Browser, navigate to the file -> Docs > Fundamentals > "How AMP pages are cached".  
5. Switch language to portuguese (pt_br).
6.  Browser displays: "Something went wrong while building this page.  Either no file exists at "/pwa/pt_br/docs/fundamentals/how_cached.html" or the "static_dirs" setting was not configured for this path in the podspec.yaml.
7. Console displays 

![screenshot from 2018-06-11 09-28-20](https://user-images.githubusercontent.com/1012254/41234366-f5a35c40-6d59-11e8-8554-a46c9dca7fc4.png)

**Comment by bpaduch** [comment]
Actually I don't think it has anything to do with the new file, if I work off Master, run `grow run`, open the browser to the docs, switch to Portuguese, it fails.

**Comment by Zoramite** [comment]
Is that the right URL? I see `/pt_br/docs/fundamentals/how_cached.html` in the routes, but nothing for `/pwa/pt_br/docs/fundamentals/how_cached.html`

I'm running it off of master and followed your steps and get to this page when switching languages: http://localhost:8080/pt_br/docs/fundamentals/how_cached.html

**Comment by Zoramite** [comment]
Alright, I think that I found the issue, it is being case sensitive with the matching of the locale:

Doesn't work: http://localhost:8080/pt_br/docs/fundamentals/how_cached.html
Works: http://localhost:8080/pt_BR/docs/fundamentals/how_cached.html

I'll get that fixed for the next version of grow.

**Comment by bpaduch** [comment]
That's the correct route, but not the right content - it should display [this](https://github.com/ampproject/docs/blob/master/content/docs/fundamentals/how_cached%40pt_BR.md).

**Comment by bpaduch** [comment]
Ah okay.
