### ISSUE TITLE
Provide AMP specific-CORS implementation examples for PHP

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amp.dev#981]
For the [CORS guide](https://www.ampproject.org/docs/fundamentals/amp-cors-requests#testing-cors-in-amp) (related to this [issue](https://github.com/ampproject/amphtml/issues/12089))

From @pbakaus: I think it would add a lot of value is a guide for how to do this in practice for Apache (and maybe Nginx).

According to @sebastianbenz - 95% of all CORS related questions I've seen came from PHP users. Having a dedicated sample for this would be good. My theory is that someone who manages their own Apache or Nginx instance has usually no problems implementing AMP CORS.

Also mentions wanting PHP example in this [issue](https://github.com/ampproject/amphtml/issues/12513).

**Comment by matthiasrohmer** [comment]
@sebastianbenz, what do you think? Is this still relevant? As far as I know AMP CORS deprecated due to https://github.com/ampproject/amphtml/issues/22136 - this would by the way also imply to actually deprecate amp-toolbox/cors as some of the documents on amp.dev that describe AMP CORS behavior.

**Comment by sebastianbenz** [comment]
This is no longer relevant.

>

**Comment by matthiasrohmer** [comment]
Great, thanks for the quick reply! Created #3873 for further tracking.
